--BloqueElectivos_Curso_yyyymmdd.csv
WITH REQUISITOS AS (
	SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
        , LISTAGG(TRIM(COALESCE(CASE SCRRTST_CONNECTOR WHEN 'A' THEN 'AND' WHEN 'O' THEN 'OR' ELSE SCRRTST_CONNECTOR END,'')
        		||' '|| COALESCE(SCRRTST_LPAREN,'') || COALESCE(SCRRTST_TESC_CODE,'') || COALESCE(SCRRTST_TEST_SCORE,'')
        		|| COALESCE(SCRRTST_SUBJ_CODE_PREQ,'') || COALESCE(SCRRTST_CRSE_NUMB_PREQ,'') || COALESCE(SCRRTST_RPAREN,'')),' ')
            WITHIN GROUP (ORDER BY SCRRTST_SEQNO) AS REQUISITOS
    FROM ODSMGR.LOE_SCRRTST
    GROUP BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
)
SELECT DISTINCT A.PROGRAM||'.'||A.TERM_CODE_EFF||'.'||SMRARUL_KEY_RULE AS "id_bloque"
	, SMRARUL_SUBJ_CODE||SMRARUL_CRSE_NUMB_LOW AS "id_curso"
	, R.REQUISITOS AS "prerrequisitos_curso"
	, NULL AS "correquisitos_curso"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.TERM_CODE_EFF = B.TERM_CODE_EFF AND A.AREA = B.AREA_COURSE
		INNER JOIN ODSMGR.LOE_SMRARUL ON B.TERM_CODE_EFF = SMRARUL_TERM_CODE_EFF AND B.AREA_COURSE = SMRARUL_AREA AND B.AREA_RULE = SMRARUL_KEY_RULE --AND SMRARUL_KEY_RULE LIKE '%ELECTIVO%'		
		LEFT JOIN REQUISITOS R ON SMRARUL_SUBJ_CODE = R.SCRRTST_SUBJ_CODE AND SMRARUL_CRSE_NUMB_LOW = R.SCRRTST_CRSE_NUMB
									AND R.SCRRTST_TERM_CODE_EFF = (SELECT MAX(R1.SCRRTST_TERM_CODE_EFF) FROM REQUISITOS R1
																	WHERE R1.SCRRTST_SUBJ_CODE = SMRARUL_SUBJ_CODE AND R1.SCRRTST_CRSE_NUMB = SMRARUL_CRSE_NUMB_LOW
																		AND R1.SCRRTST_TERM_CODE_EFF <= SMRARUL_TERM_CODE_EFF)
WHERE SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA') AND SMRARUL_SUBJ_CODE||SMRARUL_CRSE_NUMB_LOW IS NOT NULL
;