--Convalidaciones_yyyymmdd.csv
SELECT DISTINCT SHRTCKN_PIDM AS "id_estudiante"
	, MAX(COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE)) AS "id_campus"
	, SHRTCKN_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, SHRTCKN_SUBJ_CODE || SHRTCKN_CRSE_NUMB AS "id_curso_convalidado"
FROM ODSMGR.SHRTCKN
		INNER JOIN ODSMGR.COURSE_CATALOG ON SHRTCKN_SUBJ_CODE = SUBJECT AND SHRTCKN_CRSE_NUMB = COURSE_NUMBER AND COLLEGE <> 'GR'
											AND ((STATUS = 'A' AND ACADEMIC_PERIOD = '999999') OR STATUS = 'I')
		LEFT JOIN ODSMGR.SHRTCKG G ON SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
										AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG G1
																WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
																	AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SHRTCKN_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SHRTCKN_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR C ON SHRTCKN_PIDM = C.SOVLCUR_PIDM AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND C.SOVLCUR_LEVL_CODE = 'CR'
										AND SHRTCKN_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR A ON SHRTCKN_PIDM = A.SOVLCUR_PIDM AND A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_CURRENT_IND = 'Y'
WHERE SUBSTR(SHRTCKG_GRDE_CODE_FINAL,1,1) = 'C' AND COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE) IS NOT NULL
GROUP BY SHRTCKN_PIDM, SHRTCKN_TERM_CODE, 'JORNADA UNICA', SHRTCKN_SUBJ_CODE || SHRTCKN_CRSE_NUMB
UNION
SELECT DISTINCT SHRTRCE_PIDM AS "id_estudiante"
	, MAX(COALESCE(U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE)) AS "id_campus"
	, SHRTRCE_TERM_CODE_EFF AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, SHRTRCE_SUBJ_CODE || SHRTRCE_CRSE_NUMB AS "id_curso_convalidado"
FROM ODSMGR.SHRTRCE
		INNER JOIN ODSMGR.COURSE_CATALOG ON SHRTRCE_SUBJ_CODE = SUBJECT AND SHRTRCE_CRSE_NUMB = COURSE_NUMBER AND COLLEGE <> 'GR'
											AND ((STATUS = 'A' AND ACADEMIC_PERIOD = '999999') OR STATUS = 'I')
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SHRTRCE_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SHRTRCE_TERM_CODE_EFF BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR C ON SHRTRCE_PIDM = C.SOVLCUR_PIDM AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND C.SOVLCUR_LEVL_CODE = 'CR'
										AND SHRTRCE_TERM_CODE_EFF BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR A ON SHRTRCE_PIDM = A.SOVLCUR_PIDM AND A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_CURRENT_IND = 'Y'
WHERE COALESCE(U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE) IS NOT NULL
GROUP BY SHRTRCE_PIDM, SHRTRCE_TERM_CODE_EFF, 'JORNADA UNICA', SHRTRCE_SUBJ_CODE || SHRTRCE_CRSE_NUMB
;