--CursosEquivalentes_yyyymmdd.csv
SELECT DISTINCT A.PROGRAM||'.'||A.TERM_CODE_EFF AS "id_plan_estudio"
	, CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE||B.CRSE_NUMB_LOW ELSE SMRARUL_SUBJ_CODE||SMRARUL_CRSE_NUMB_LOW END AS "id_curso_plan"
	, E.SUBJECT_CODE_EQUIV||E.COURSE_NUMBER_EQUIV AS "id_curso_equivalente"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.TERM_CODE_EFF = B.TERM_CODE_EFF AND A.AREA = B.AREA_COURSE
		LEFT JOIN ODSMGR.LOE_SMRARUL ON B.TERM_CODE_EFF = SMRARUL_TERM_CODE_EFF AND B.AREA_COURSE = SMRARUL_AREA AND B.AREA_RULE = SMRARUL_KEY_RULE
		LEFT JOIN ODSMGR.LOE_EQUIV_COURSE_REPEATING E ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = E.SUBJECT
														AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = E.COURSE_NUMBER
														AND E.EFF_TERM = (SELECT MAX(E1.EFF_TERM) FROM ODSMGR.LOE_EQUIV_COURSE_REPEATING E1
																			WHERE E1.SUBJECT = CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
																				AND E1.COURSE_NUMBER = CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END
																				AND E1.EFF_TERM <= B.TERM_CODE_EFF)
WHERE CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE||B.CRSE_NUMB_LOW ELSE SMRARUL_SUBJ_CODE||SMRARUL_CRSE_NUMB_LOW END IS NOT NULL
	AND E.SUBJECT_CODE_EQUIV||E.COURSE_NUMBER_EQUIV IS NOT NULL AND SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA')
;