--DatosInscripciones_yyyymmdd.csv
SELECT SHRTCKN_PIDM AS "id_estudiante"
	, MAX(COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE)) AS "id_campus"
	, SHRTCKN_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, SHRTCKN_SUBJ_CODE || SHRTCKN_CRSE_NUMB AS "id_curso_inscrito"
	, CASE 
		WHEN SHRGRDE_PASSED_IND = 'Y' THEN 'A'
		WHEN SHRGRDE_PASSED_IND = 'N' THEN 'D'
		WHEN SUBSTR(SHRTCKG_GRDE_CODE_FINAL,1,1) = 'R' THEN 'R'
		ELSE 'D' END AS "id_estado_inscripcion"
	, SHRTCKG_GRDE_CODE_FINAL AS "nota_final"
	, SHRGRDE_QUALITY_POINTS*100/20 AS "nota_final_porcentual"
FROM ODSMGR.SHRTCKN
		INNER JOIN ODSMGR.COURSE_CATALOG ON SHRTCKN_SUBJ_CODE = SUBJECT AND SHRTCKN_CRSE_NUMB = COURSE_NUMBER AND COLLEGE <> 'GR'
											AND ((STATUS = 'A' AND ACADEMIC_PERIOD = '999999') OR STATUS = 'I')
		INNER JOIN ODSMGR.LOE_STVTERM ON SHRTCKN_TERM_CODE = STVTERM_CODE AND ((STVTERM_CODE < 215400 AND SUBSTR(STVTERM_DESC,5,1) = '-')
												OR (STVTERM_CODE > 215400 AND SUBSTR(STVTERM_CODE,4,1) IN ('3','4','5') AND SUBSTR(STVTERM_CODE,5,2) < '46' AND STVTERM_DESC NOT LIKE '%Int%Dob%Tit%'))
											AND STVTERM_CODE NOT IN ('201641','201642','201643','200400','200300','200200','200100','200000','199900','199800','199700','199600')
		LEFT JOIN ODSMGR.SHRTCKG G ON SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
										AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG G1
																WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
																	AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
		LEFT JOIN ODSMGR.SHRTCKL ON SHRTCKN_PIDM = SHRTCKL_PIDM AND SHRTCKN_TERM_CODE = SHRTCKL_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKL_TCKN_SEQ_NO
		LEFT JOIN ODSMGR.SHRGRDE ON SHRTCKG_GRDE_CODE_FINAL = SHRGRDE_CODE AND SHRTCKL_LEVL_CODE = SHRGRDE_LEVL_CODE
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SHRTCKN_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SHRTCKN_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR C ON SHRTCKN_PIDM = C.SOVLCUR_PIDM AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND C.SOVLCUR_LEVL_CODE = 'CR'
										AND SHRTCKN_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR A ON SHRTCKN_PIDM = A.SOVLCUR_PIDM AND A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_CURRENT_IND = 'Y'
WHERE COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE) IS NOT NULL
GROUP BY SHRTCKN_PIDM, SHRTCKN_TERM_CODE, 'JORNADA UNICA', SHRTCKN_SUBJ_CODE || SHRTCKN_CRSE_NUMB
	, CASE 
		WHEN SHRGRDE_PASSED_IND = 'Y' THEN 'A'
		WHEN SHRGRDE_PASSED_IND = 'N' THEN 'D'
		WHEN SUBSTR(SHRTCKG_GRDE_CODE_FINAL,1,1) = 'R' THEN 'R'
		ELSE 'D' END
	, SHRTCKG_GRDE_CODE_FINAL, SHRGRDE_QUALITY_POINTS*100/20
UNION 
SELECT SFRSTCR_PIDM AS "id_estudiante"
	, MAX(COALESCE(SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE)) AS "id_campus"
	, SFRSTCR_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, SSBSECT_SUBJ_CODE || SSBSECT_CRSE_NUMB AS "id_curso_inscrito"
	, CASE 
		WHEN SFRSTCR_RSTS_CODE IN ('RW','RE','RA') THEN 'C'
		WHEN SFRSTCR_RSTS_CODE IN ('WC','RF') THEN 'R'
		ELSE 'D' END AS "id_estado_inscripcion"
	, NULL AS "nota_final"
	, NULL AS "nota_final_porcentual"
FROM ODSMGR.SFRSTCR
		INNER JOIN ODSMGR.LOE_SSBSECT ON SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
		INNER JOIN ODSMGR.COURSE_CATALOG ON SSBSECT_SUBJ_CODE = SUBJECT AND SSBSECT_CRSE_NUMB = COURSE_NUMBER AND COLLEGE <> 'GR'
											AND ((STATUS = 'A' AND ACADEMIC_PERIOD = '999999') OR STATUS = 'I')
		INNER JOIN ODSMGR.LOE_STVTERM ON SFRSTCR_TERM_CODE = STVTERM_CODE AND ((STVTERM_CODE < 215400 AND SUBSTR(STVTERM_DESC,5,1) = '-')
												OR (STVTERM_CODE > 215400 AND SUBSTR(STVTERM_CODE,4,1) IN ('3','4','5') AND SUBSTR(STVTERM_CODE,5,2) < '46' AND STVTERM_DESC NOT LIKE '%Int%Dob%Tit%'))
											AND STVTERM_CODE NOT IN ('201641','201642','201643','200400','200300','200200','200100','200000','199900','199800','199700','199600')
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SFRSTCR_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SFRSTCR_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR C ON SFRSTCR_PIDM = C.SOVLCUR_PIDM AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND C.SOVLCUR_LEVL_CODE = 'CR'
										AND SFRSTCR_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR A ON SFRSTCR_PIDM = A.SOVLCUR_PIDM AND A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_CURRENT_IND = 'Y'
WHERE SFRSTCR_GRDE_DATE IS NULL AND COALESCE(SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,C.SOVLCUR_CAMP_CODE,A.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND SFRSTCR_RSTS_CODE NOT IN ('DW','DD') AND TO_DATE(STVTERM_END_DATE) +14 > CURRENT_DATE
GROUP BY SFRSTCR_PIDM, SFRSTCR_TERM_CODE, SSBSECT_SUBJ_CODE || SSBSECT_CRSE_NUMB
	, CASE 
		WHEN SFRSTCR_RSTS_CODE IN ('RW','RE','RA') THEN 'C'
		WHEN SFRSTCR_RSTS_CODE IN ('WC','RF') THEN 'R'
		ELSE 'D' END
	, NULL, NULL
;