--EstadoHistoricoEstudiantes_yyyymmdd.csv
SELECT DISTINCT SHRTCKN_PIDM AS "id_estudiante"
	, MAX(COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE)) OVER(PARTITION BY SHRTCKN_PIDM,SHRTCKN_TERM_CODE) AS "id_campus"
	, SHRTCKN_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,C.SOVLCUR_TERM_CODE_CTLG*/) AS "id_plan_estudio"
	, NULL AS "id_especialidad"
	, COALESCE(CASE 
				WHEN SHRTCKN_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'EGRESADO' THEN 'E'
				WHEN SHRTCKN_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'TITULADO' THEN 'T'
				WHEN H.HOLD IN ('BA','SD') THEN 'RD'
				END
			, MAX(CASE WHEN SHRGRDE_PASSED_IND = 'Y' THEN 'F' END) OVER(PARTITION BY SHRTCKN_PIDM,SHRTCKN_TERM_CODE)
			, MAX(CASE WHEN SUBSTR(SHRTCKG_GRDE_CODE_FINAL,1,1) = 'R' THEN 'RT' END) OVER(PARTITION BY SHRTCKN_PIDM,SHRTCKN_TERM_CODE)
			, 'D') AS "id_estado"
FROM ODSMGR.SHRTCKN
		INNER JOIN ODSMGR.LOE_SOVLCUR C ON SHRTCKN_PIDM = C.SOVLCUR_PIDM AND SHRTCKN_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
											AND SUBSTR(C.SOVLCUR_PROGRAM,4) IN ('-UG','-WA') AND SOVLCUR_PROGRAM NOT IN ('PDN-UG','PDN-WA')
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY A ON C.SOVLCUR_PROGRAM = A.PROGRAM
														AND A.TERM_CODE_EFF = (SELECT MAX(A1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A1
																				WHERE A1.PROGRAM = C.SOVLCUR_PROGRAM AND A1.TERM_CODE_EFF <= C.SOVLCUR_TERM_CODE_CTLG)
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY B ON C.SOVLCUR_PROGRAM = B.PROGRAM
														AND B.TERM_CODE_EFF = (SELECT MIN(B1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY B1
																				WHERE B1.PROGRAM = C.SOVLCUR_PROGRAM)
		LEFT JOIN ODSMGR.SHRTCKG G ON SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
										AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG G1
																WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
																	AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
		LEFT JOIN ODSMGR.SHRGRDE ON SHRTCKG_GRDE_CODE_FINAL = SHRGRDE_CODE AND SHRGRDE_LEVL_CODE = 'UG'
		LEFT JOIN ( SELECT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM, MAX(ACADEMIC_PERIOD) AS ACADEMIC_PERIOD
					FROM ODSMGR.FIELD_OF_STUDY
					WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON IN ('EGRESADO','TITULADO') AND STUDENT_LEVEL = 'UG'
					GROUP BY PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM
					) E ON C.SOVLCUR_PIDM = E.PERSON_UID AND C.SOVLCUR_PROGRAM = E.PROGRAM
		LEFT JOIN ODSMGR.HOLD H ON SHRTCKN_PIDM = H.PERSON_UID AND H.HOLD IN ('BA','SD') AND H.ACTIVE_HOLD_IND = 'Y'
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SHRTCKN_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SHRTCKN_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR CR ON SHRTCKN_PIDM = CR.SOVLCUR_PIDM AND CR.SOVLCUR_LMOD_CODE = 'LEARNER' AND CR.SOVLCUR_CACT_CODE = 'ACTIVE' AND CR.SOVLCUR_LEVL_CODE = 'CR'
										AND SHRTCKN_TERM_CODE BETWEEN CR.SOVLCUR_TERM_CODE AND COALESCE(CR.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR AC ON SHRTCKN_PIDM = AC.SOVLCUR_PIDM AND AC.SOVLCUR_LMOD_CODE = 'LEARNER' AND AC.SOVLCUR_CACT_CODE = 'ACTIVE' AND AC.SOVLCUR_CURRENT_IND = 'Y'
WHERE COALESCE(SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,C.SOVLCUR_TERM_CODE_CTLG*/) IS NOT NULL
UNION
SELECT DISTINCT SFRSTCR_PIDM AS "id_estudiante"
	, MAX(COALESCE(SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE)) OVER(PARTITION BY SFRSTCR_PIDM,SFRSTCR_TERM_CODE) AS "id_campus"
	, SFRSTCR_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,C.SOVLCUR_TERM_CODE_CTLG*/) AS "id_plan_estudio"
	, NULL AS "id_especialidad"
	, COALESCE(CASE 
				WHEN SFRSTCR_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'EGRESADO' THEN 'E'
				WHEN SFRSTCR_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'TITULADO' THEN 'T'
				WHEN H.HOLD IN ('BA','SD') THEN 'RD'
				END
			, MAX(CASE WHEN SFRSTCR_RSTS_CODE IN ('RW','RE','RA') THEN 'F' END) OVER(PARTITION BY SFRSTCR_PIDM,SFRSTCR_TERM_CODE)
			, MAX(CASE WHEN SFRSTCR_RSTS_CODE IN ('DW','DD','WC','RF') THEN 'RT' END) OVER(PARTITION BY SFRSTCR_PIDM,SFRSTCR_TERM_CODE)
			, 'D') AS "id_estado"
FROM ODSMGR.SFRSTCR
		INNER JOIN ODSMGR.LOE_SOVLCUR C ON SFRSTCR_PIDM = C.SOVLCUR_PIDM AND SFRSTCR_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END,'999996')
											AND SUBSTR(C.SOVLCUR_PROGRAM,4) IN ('-UG','-WA') AND SOVLCUR_PROGRAM NOT IN ('PDN-UG','PDN-WA')
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY A ON C.SOVLCUR_PROGRAM = A.PROGRAM
														AND A.TERM_CODE_EFF = (SELECT MAX(A1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A1
																				WHERE A1.PROGRAM = C.SOVLCUR_PROGRAM AND A1.TERM_CODE_EFF <= C.SOVLCUR_TERM_CODE_CTLG)
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY B ON C.SOVLCUR_PROGRAM = B.PROGRAM
														AND B.TERM_CODE_EFF = (SELECT MIN(B1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY B1
																				WHERE B1.PROGRAM = C.SOVLCUR_PROGRAM)
		LEFT JOIN ( SELECT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM, MAX(ACADEMIC_PERIOD) AS ACADEMIC_PERIOD
					FROM ODSMGR.FIELD_OF_STUDY
					WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON IN ('EGRESADO','TITULADO') AND STUDENT_LEVEL = 'UG'
					GROUP BY PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM
					) E ON C.SOVLCUR_PIDM = E.PERSON_UID AND C.SOVLCUR_PROGRAM = E.PROGRAM
		LEFT JOIN ODSMGR.HOLD H ON SFRSTCR_PIDM = H.PERSON_UID AND H.HOLD IN ('BA','SD') AND H.ACTIVE_HOLD_IND = 'Y'
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON SFRSTCR_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND SFRSTCR_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR CR ON SFRSTCR_PIDM = CR.SOVLCUR_PIDM AND CR.SOVLCUR_LMOD_CODE = 'LEARNER' AND CR.SOVLCUR_CACT_CODE = 'ACTIVE' AND CR.SOVLCUR_LEVL_CODE = 'CR'
										AND SFRSTCR_TERM_CODE BETWEEN CR.SOVLCUR_TERM_CODE AND COALESCE(CR.SOVLCUR_TERM_CODE_END,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR AC ON SFRSTCR_PIDM = AC.SOVLCUR_PIDM AND AC.SOVLCUR_LMOD_CODE = 'LEARNER' AND AC.SOVLCUR_CACT_CODE = 'ACTIVE' AND AC.SOVLCUR_CURRENT_IND = 'Y'
WHERE SFRSTCR_GRDE_DATE IS NULL AND COALESCE(SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,C.SOVLCUR_TERM_CODE_CTLG*/) IS NOT NULL
;