--EstadoHistoricoEstudiantes_yyyymmdd.csv
SELECT DISTINCT HST.SHRTCKN_PIDM AS "id_estudiante"
	--, MAX(COALESCE(HST.SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE)) OVER(PARTITION BY HST.SHRTCKN_PIDM,HST.SHRTCKN_TERM_CODE) AS "id_campus"
	, MAX(COALESCE(U.SOVLCUR_CAMP_CODE,CASE WHEN HST.SHRTCKN_CAMP_CODE NOT IN ('VIR','REM') THEN HST.SHRTCKN_CAMP_CODE END,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE))
			OVER(PARTITION BY HST.SHRTCKN_PIDM,HST.SHRTCKN_TERM_CODE) AS "id_campus"
	, HST.SHRTCKN_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,HST.SOVLCUR_TERM_CODE_CTLG*/) AS "id_plan_estudio"
	, NULL AS "id_especialidad"
	, COALESCE(CASE 
				WHEN HST.SHRTCKN_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'EGRESADO' THEN 'E'
				WHEN HST.SHRTCKN_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'TITULADO' THEN 'T'
				WHEN H.HOLD IN ('BA','SD') THEN 'RD'
				END
			, MAX(CASE WHEN HST.SHRGRDE_PASSED_IND = 'Y' THEN 'F' END) OVER(PARTITION BY HST.SHRTCKN_PIDM,HST.SHRTCKN_TERM_CODE)
			, MAX(CASE WHEN HST.SHRTCKG_GRDE_1 = 'R' THEN 'RT' END) OVER(PARTITION BY HST.SHRTCKN_PIDM,HST.SHRTCKN_TERM_CODE)
			, 'D') AS "id_estado"
FROM ( SELECT DISTINCT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_CAMP_CODE, SUBSTR(SHRTCKG_GRDE_CODE_FINAL,1,1) AS SHRTCKG_GRDE_1, SHRGRDE_PASSED_IND, C.SOVLCUR_PROGRAM, C.SOVLCUR_TERM_CODE_CTLG
		FROM ODSMGR.SHRTCKN
				INNER JOIN ODSMGR.LOE_SOVLCUR C ON SHRTCKN_PIDM = C.SOVLCUR_PIDM AND SHRTCKN_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END-1,'999996')
													AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND SUBSTR(C.SOVLCUR_PROGRAM,4) IN ('-UG','-WA')
													AND SOVLCUR_PROGRAM NOT IN ('PDN-UG','PDN-WA')
				INNER JOIN ODSMGR.LOE_STVTERM ON SHRTCKN_TERM_CODE = STVTERM_CODE AND ((STVTERM_CODE < 215400 AND SUBSTR(STVTERM_DESC,5,1) = '-')
														OR (STVTERM_CODE > 215400 AND SUBSTR(STVTERM_CODE,4,1) IN ('3','4','5') AND SUBSTR(STVTERM_CODE,5,2) < '46' AND STVTERM_DESC NOT LIKE '%Int%Dob%Tit%'))
													AND STVTERM_CODE NOT IN ('201641','201642','201643','200400','200300','200200','200100','200000','199900','199800','199700','199600')
				INNER JOIN ODSMGR.SHRTCKG G ON SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
												AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG G1
																		WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
																			AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
				INNER JOIN ODSMGR.SHRGRDE ON SHRTCKG_GRDE_CODE_FINAL = SHRGRDE_CODE AND SHRGRDE_LEVL_CODE = 'UG'
		) HST
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY A ON HST.SOVLCUR_PROGRAM = A.PROGRAM
														AND A.TERM_CODE_EFF = (SELECT MAX(A1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A1
																				WHERE A1.PROGRAM = HST.SOVLCUR_PROGRAM AND A1.TERM_CODE_EFF <= HST.SOVLCUR_TERM_CODE_CTLG)
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY B ON HST.SOVLCUR_PROGRAM = B.PROGRAM
														AND B.TERM_CODE_EFF = (SELECT MIN(B1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY B1
																				WHERE B1.PROGRAM = HST.SOVLCUR_PROGRAM)
		LEFT JOIN ( SELECT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM, MAX(ACADEMIC_PERIOD) AS ACADEMIC_PERIOD
					FROM ODSMGR.FIELD_OF_STUDY
					WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON IN ('EGRESADO','TITULADO') AND STUDENT_LEVEL = 'UG'
					GROUP BY PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM
					) E ON HST.SHRTCKN_PIDM = E.PERSON_UID AND HST.SOVLCUR_PROGRAM = E.PROGRAM
		LEFT JOIN ODSMGR.HOLD H ON HST.SHRTCKN_PIDM = H.PERSON_UID AND H.HOLD IN ('BA','SD') AND H.ACTIVE_HOLD_IND = 'Y'
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON HST.SHRTCKN_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND HST.SHRTCKN_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END-1,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR CR ON HST.SHRTCKN_PIDM = CR.SOVLCUR_PIDM AND CR.SOVLCUR_LMOD_CODE = 'LEARNER' AND CR.SOVLCUR_CACT_CODE = 'ACTIVE' AND CR.SOVLCUR_LEVL_CODE = 'CR'
										AND HST.SHRTCKN_TERM_CODE BETWEEN CR.SOVLCUR_TERM_CODE AND COALESCE(CR.SOVLCUR_TERM_CODE_END-1,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR AC ON HST.SHRTCKN_PIDM = AC.SOVLCUR_PIDM AND AC.SOVLCUR_LMOD_CODE = 'LEARNER' AND AC.SOVLCUR_CACT_CODE = 'ACTIVE' AND AC.SOVLCUR_CURRENT_IND = 'Y'
WHERE --COALESCE(HST.SHRTCKN_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	COALESCE(U.SOVLCUR_CAMP_CODE,CASE WHEN HST.SHRTCKN_CAMP_CODE NOT IN ('VIR','REM') THEN HST.SHRTCKN_CAMP_CODE END,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,HST.SOVLCUR_TERM_CODE_CTLG*/) IS NOT NULL
UNION
SELECT DISTINCT REG.SFRSTCR_PIDM AS "id_estudiante"
	--, MAX(COALESCE(REG.SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE)) OVER(PARTITION BY REG.SFRSTCR_PIDM,REG.SFRSTCR_TERM_CODE) AS "id_campus"
	, MAX(COALESCE(U.SOVLCUR_CAMP_CODE,CASE WHEN REG.SFRSTCR_CAMP_CODE NOT IN ('VIR','REM') THEN REG.SFRSTCR_CAMP_CODE END,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE))
			OVER(PARTITION BY REG.SFRSTCR_PIDM,REG.SFRSTCR_TERM_CODE) AS "id_campus"
	, REG.SFRSTCR_TERM_CODE AS "id_periodo_academico"
	, 'JORNADA UNICA' AS "id_jornada"
	, COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,REG.SOVLCUR_TERM_CODE_CTLG*/) AS "id_plan_estudio"
	, NULL AS "id_especialidad"
	, COALESCE(CASE 
				WHEN REG.SFRSTCR_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'EGRESADO' THEN 'E'
				WHEN REG.SFRSTCR_TERM_CODE = E.ACADEMIC_PERIOD AND E.CURRICULUM_CHANGE_REASON = 'TITULADO' THEN 'T'
				WHEN H.HOLD IN ('BA','SD') THEN 'RD'
				END
			, MAX(CASE WHEN REG.SFRSTCR_RSTS_CODE IN ('RW','RE','RA') THEN 'C' END) OVER(PARTITION BY REG.SFRSTCR_PIDM,REG.SFRSTCR_TERM_CODE)
			, MAX(CASE WHEN REG.SFRSTCR_RSTS_CODE IN ('WC','RF') THEN 'RT' END) OVER(PARTITION BY REG.SFRSTCR_PIDM,REG.SFRSTCR_TERM_CODE)
			, 'D') AS "id_estado"
FROM ( SELECT DISTINCT SFRSTCR_PIDM, SFRSTCR_TERM_CODE, SFRSTCR_CAMP_CODE, SFRSTCR_RSTS_CODE, SFRSTCR_GRDE_DATE, C.SOVLCUR_PROGRAM, C.SOVLCUR_TERM_CODE_CTLG
		FROM ODSMGR.SFRSTCR
				INNER JOIN ODSMGR.LOE_SOVLCUR C ON SFRSTCR_PIDM = C.SOVLCUR_PIDM AND SFRSTCR_TERM_CODE BETWEEN C.SOVLCUR_TERM_CODE AND COALESCE(C.SOVLCUR_TERM_CODE_END-1,'999996')
													AND C.SOVLCUR_LMOD_CODE = 'LEARNER' AND C.SOVLCUR_CACT_CODE = 'ACTIVE' AND SUBSTR(C.SOVLCUR_PROGRAM,4) IN ('-UG','-WA')
													AND SOVLCUR_PROGRAM NOT IN ('PDN-UG','PDN-WA')
				INNER JOIN ODSMGR.LOE_STVTERM ON SFRSTCR_TERM_CODE = STVTERM_CODE AND ((STVTERM_CODE < 215400 AND SUBSTR(STVTERM_DESC,5,1) = '-')
														OR (STVTERM_CODE > 215400 AND SUBSTR(STVTERM_CODE,4,1) IN ('3','4','5') AND SUBSTR(STVTERM_CODE,5,2) < '46' AND STVTERM_DESC NOT LIKE '%Int%Dob%Tit%'))
													AND STVTERM_CODE NOT IN ('201641','201642','201643','200400','200300','200200','200100','200000','199900','199800','199700','199600')
		WHERE SFRSTCR_RSTS_CODE NOT IN ('DW','DD') AND TO_DATE(STVTERM_END_DATE) +14 > CURRENT_DATE
		) REG
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY A ON REG.SOVLCUR_PROGRAM = A.PROGRAM
														AND A.TERM_CODE_EFF = (SELECT MAX(A1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A1
																				WHERE A1.PROGRAM = REG.SOVLCUR_PROGRAM AND A1.TERM_CODE_EFF <= REG.SOVLCUR_TERM_CODE_CTLG)
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY B ON REG.SOVLCUR_PROGRAM = B.PROGRAM
														AND B.TERM_CODE_EFF = (SELECT MIN(B1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY B1
																				WHERE B1.PROGRAM = REG.SOVLCUR_PROGRAM)
		LEFT JOIN ( SELECT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM, MAX(ACADEMIC_PERIOD) AS ACADEMIC_PERIOD
					FROM ODSMGR.FIELD_OF_STUDY
					WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON IN ('EGRESADO','TITULADO') AND STUDENT_LEVEL = 'UG'
					GROUP BY PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON, PROGRAM
					) E ON REG.SFRSTCR_PIDM = E.PERSON_UID AND REG.SOVLCUR_PROGRAM = E.PROGRAM
		LEFT JOIN ODSMGR.HOLD H ON REG.SFRSTCR_PIDM = H.PERSON_UID AND H.HOLD IN ('BA','SD') AND H.ACTIVE_HOLD_IND = 'Y'
		LEFT JOIN ODSMGR.LOE_SOVLCUR U ON REG.SFRSTCR_PIDM = U.SOVLCUR_PIDM AND U.SOVLCUR_LMOD_CODE = 'LEARNER' AND U.SOVLCUR_CACT_CODE = 'ACTIVE' AND U.SOVLCUR_LEVL_CODE = 'UG'
										AND REG.SFRSTCR_TERM_CODE BETWEEN U.SOVLCUR_TERM_CODE AND COALESCE(U.SOVLCUR_TERM_CODE_END-1,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR CR ON REG.SFRSTCR_PIDM = CR.SOVLCUR_PIDM AND CR.SOVLCUR_LMOD_CODE = 'LEARNER' AND CR.SOVLCUR_CACT_CODE = 'ACTIVE' AND CR.SOVLCUR_LEVL_CODE = 'CR'
										AND REG.SFRSTCR_TERM_CODE BETWEEN CR.SOVLCUR_TERM_CODE AND COALESCE(CR.SOVLCUR_TERM_CODE_END-1,'999996')
		LEFT JOIN ODSMGR.LOE_SOVLCUR AC ON REG.SFRSTCR_PIDM = AC.SOVLCUR_PIDM AND AC.SOVLCUR_LMOD_CODE = 'LEARNER' AND AC.SOVLCUR_CACT_CODE = 'ACTIVE' AND AC.SOVLCUR_CURRENT_IND = 'Y'
WHERE REG.SFRSTCR_GRDE_DATE IS NULL --AND COALESCE(REG.SFRSTCR_CAMP_CODE,U.SOVLCUR_CAMP_CODE,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND COALESCE(U.SOVLCUR_CAMP_CODE,CASE WHEN REG.SFRSTCR_CAMP_CODE NOT IN ('VIR','REM') THEN REG.SFRSTCR_CAMP_CODE END,CR.SOVLCUR_CAMP_CODE,AC.SOVLCUR_CAMP_CODE) IS NOT NULL
	AND COALESCE(A.PROGRAM,B.PROGRAM)||'.'||COALESCE(A.TERM_CODE_EFF,B.TERM_CODE_EFF/*,REG.SOVLCUR_TERM_CODE_CTLG*/) IS NOT NULL
;