--PlanEstudio_Curso_yyyymmdd.csv
WITH REQUISITOS AS (
	SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
    	, REPLACE(REPLACE(REPLACE(REPLACE(
    		CASE WHEN SUBSTR(REQUISITOS,1,5) = ' AND ' OR SUBSTR(REQUISITOS,1,4) = ' OR ' THEN TRIM(SUBSTR(REQUISITOS,5)) ELSE REQUISITOS END
    		,'( AND ','(')
    		,'( OR ','(')
    		,' )',')')
    		,'()','') AS REQUISITOS
    FROM (
	    SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
	        , LISTAGG(TRIM(CASE WHEN COALESCE(SCRRTST_TESC_CODE,SCRRTST_TEST_SCORE) IS NOT NULL THEN ''
	        			ELSE COALESCE(CASE SCRRTST_CONNECTOR WHEN 'A' THEN 'AND' WHEN 'O' THEN 'OR' ELSE SCRRTST_CONNECTOR END,'') END
	        		||' '|| COALESCE(SCRRTST_LPAREN,'') --|| COALESCE(SCRRTST_TESC_CODE,'') || COALESCE(SCRRTST_TEST_SCORE,'')
	        		|| COALESCE(SCRRTST_SUBJ_CODE_PREQ,'') || COALESCE(SCRRTST_CRSE_NUMB_PREQ,'') || COALESCE(SCRRTST_RPAREN,'')),' ')
	            WITHIN GROUP (ORDER BY SCRRTST_SEQNO) AS REQUISITOS
	    FROM ODSMGR.LOE_SCRRTST
	    GROUP BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
		)
)
SELECT DISTINCT A.PROGRAM||'.'||A.TERM_CODE_EFF AS "id_plan"
    , B.SUBJ_CODE||B.CRSE_NUMB_LOW AS "id_curso"
	, TO_NUMBER(SUBSTR(A.AREA,LENGTH(A.AREA)-1,2)) AS "numero_nivel"
    , R.REQUISITOS AS "prerrequisitos_curso"
    , NULL AS "correquisitos_curso"
    , 0 AS "indicador_curso_eximible"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.TERM_CODE_EFF = B.TERM_CODE_EFF AND A.AREA = B.AREA_COURSE
		LEFT JOIN ODSMGR.LOE_SMRARUL ON B.TERM_CODE_EFF = SMRARUL_TERM_CODE_EFF AND B.AREA_COURSE = SMRARUL_AREA AND B.AREA_RULE = SMRARUL_KEY_RULE
		LEFT JOIN REQUISITOS R ON B.SUBJ_CODE = R.SCRRTST_SUBJ_CODE AND B.CRSE_NUMB_LOW = R.SCRRTST_CRSE_NUMB
									AND R.SCRRTST_TERM_CODE_EFF = (SELECT MAX(R1.SCRRTST_TERM_CODE_EFF) FROM REQUISITOS R1
																	WHERE R1.SCRRTST_SUBJ_CODE = B.SUBJ_CODE AND R1.SCRRTST_CRSE_NUMB = B.CRSE_NUMB_LOW
																		AND R1.SCRRTST_TERM_CODE_EFF <= B.TERM_CODE_EFF)
WHERE B.SUBJ_CODE||B.CRSE_NUMB_LOW IS NOT NULL AND SMRARUL_KEY_RULE IS NULL
	AND SUBSTR(A.AREA,LENGTH(A.AREA)-1,2) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14')
	AND SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA')
;