--PlanEstudio_BloqueElectivos_yyyymmdd.csv
SELECT DISTINCT A.PROGRAM||'.'||A.TERM_CODE_EFF AS "id_plan_estudio"
    , A.PROGRAM||'.'||A.TERM_CODE_EFF||'.'||C.SMRARUL_KEY_RULE AS "id_bloque"
    , A.PROGRAM||'.'||A.TERM_CODE_EFF||'.'||C.SMRARUL_KEY_RULE AS "codigo_bloque"
    , C.SMBARUL_DESC AS "nombre_bloque"
    , CASE WHEN SUBSTR(A.AREA,LENGTH(A.AREA)-1,2) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14')
            THEN TO_NUMBER(SUBSTR(A.AREA,LENGTH(A.AREA)-1,2))
		ELSE NULL END AS "nivel_inicio_en_plan"
    , CASE WHEN SUBSTR(A.AREA,LENGTH(A.AREA)-1,2) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14')
            THEN TO_NUMBER(SUBSTR(A.AREA,LENGTH(A.AREA)-1,2))
        ELSE NULL END AS "nivel_fin_en_plan"
    , NULL AS "condicion_tomar_bloque"
    , C.CURSOS AS "condicion_aprobacion_cursos_bloque"
    , C.CREDITOS AS "condicion_aprobacion_creditos_bloque"
    , 1 AS "indicador_bloque_obligatorio"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.TERM_CODE_EFF = B.TERM_CODE_EFF AND A.AREA = B.AREA_COURSE
		INNER JOIN (SELECT DISTINCT SMRARUL_TERM_CODE_EFF, SMRARUL_AREA, SMRARUL_KEY_RULE, SMBARUL_DESC, MAX(E.CREDIT_MIN) AS CREDITOS
						, LISTAGG(SMRARUL_SUBJ_CODE||SMRARUL_CRSE_NUMB_LOW,' OR ') WITHIN GROUP(ORDER BY SMRARUL_SUBJ_CODE,SMRARUL_CRSE_NUMB_LOW) AS CURSOS		                        
					FROM ODSMGR.LOE_SMRARUL
							INNER JOIN ODSMGR.LOE_SMBARUL ON SMRARUL_TERM_CODE_EFF = SMBARUL_TERM_CODE_EFF AND SMRARUL_AREA = SMBARUL_AREA AND SMRARUL_KEY_RULE = SMBARUL_KEY_RULE
																--AND SMBARUL_KEY_RULE LIKE '%ELECTIVO%'
							LEFT JOIN ODSMGR.COURSE_CATALOG E ON SMRARUL_TERM_CODE_EFF = E.ACADEMIC_PERIOD AND SMRARUL_SUBJ_CODE = E.SUBJECT AND SMRARUL_CRSE_NUMB_LOW = E.COURSE_NUMBER
					GROUP BY SMRARUL_TERM_CODE_EFF, SMRARUL_AREA, SMRARUL_KEY_RULE, SMBARUL_DESC
						) C ON B.TERM_CODE_EFF = C.SMRARUL_TERM_CODE_EFF AND B.AREA_COURSE = C.SMRARUL_AREA AND B.AREA_RULE = C.SMRARUL_KEY_RULE
WHERE SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA')
;