
BEGIN
ODSMGR.REMOVE_ALL_S3_FILES('COMPOSITE_TABLE');
END;

BEGIN
ODSMGR.REMOVE_ALL_S3_FILES('LOE_TABLE');
END;

BEGIN
ODSMGR.REMOVE_ALL_S3_FILES('BANNER_CUSTOM_LOG');
END;

BEGIN
ODSMGR.REMOVE_ALL_S3_FILES('CHANGE_TABLE');
END;

BEGIN
ODSMGR.REMOVE_ALL_S3_FILES('CHANGE_UPDATE_TABLE');
END;

BEGIN
ODSMGR.COMPOSITE_TABLES_TO_CSV();
END;


--ODSMGR.FILES_GENERATED

SELECT FILE_NAME, CREATED_AT, PROCESS FROM ODSMGR.FILES_GENERATED;

SELECT PROCESS, MIN(CREATED_AT), MAX(CREATED_AT) FROM ODSMGR.FILES_GENERATED
GROUP BY PROCESS;
