USE ROLE ETL_PROD;
USE DATABASE BI_CDW_PROD;
USE SCHEMA UPN_STG_SIS_BNRODS_ODSMGR;

BEGIN;

  TRUNCATE TABLE MAT_INTEREST;

  ALTER TABLE MAT_INTEREST
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MAT_INTEREST
  FROM @UPN_STAGE_SIS_BNRODS/MAT_INTEREST
  PATTERN='.*MAT_INTEREST_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MAT_INTEREST
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MAT_SALUTATION;

  ALTER TABLE MAT_SALUTATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MAT_SALUTATION
  FROM @UPN_STAGE_SIS_BNRODS/MAT_SALUTATION
  PATTERN='.*MAT_SALUTATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MAT_SALUTATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MAT_SPECIAL_ACTIVITY;

  ALTER TABLE MAT_SPECIAL_ACTIVITY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MAT_SPECIAL_ACTIVITY
  FROM @UPN_STAGE_SIS_BNRODS/MAT_SPECIAL_ACTIVITY
  PATTERN='.*MAT_SPECIAL_ACTIVITY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MAT_SPECIAL_ACTIVITY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MDT_REGISTRATION_PLAN;

  ALTER TABLE MDT_REGISTRATION_PLAN
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MDT_REGISTRATION_PLAN
  FROM @UPN_STAGE_SIS_BNRODS/MDT_REGISTRATION_PLAN
  PATTERN='.*MDT_REGISTRATION_PLAN_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MDT_REGISTRATION_PLAN
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGRSDAX;

  ALTER TABLE MGRSDAX
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGRSDAX
  FROM @UPN_STAGE_SIS_BNRODS/MGRSDAX
  PATTERN='.*MGRSDAX_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGRSDAX
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_ALTERNATIVE_ID;

  ALTER TABLE MGT_ALTERNATIVE_ID
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_ALTERNATIVE_ID
  FROM @UPN_STAGE_SIS_BNRODS/MGT_ALTERNATIVE_ID
  PATTERN='.*MGT_ALTERNATIVE_ID_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_ALTERNATIVE_ID
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_CALENDAR_DATE_HIERARCHY;

  ALTER TABLE MGT_CALENDAR_DATE_HIERARCHY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_CALENDAR_DATE_HIERARCHY
  FROM @UPN_STAGE_SIS_BNRODS/MGT_CALENDAR_DATE_HIERARCHY
  PATTERN='.*MGT_CALENDAR_DATE_HIERARCHY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_CALENDAR_DATE_HIERARCHY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_COMMUNICATION;

  ALTER TABLE MGT_COMMUNICATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_COMMUNICATION
  FROM @UPN_STAGE_SIS_BNRODS/MGT_COMMUNICATION
  PATTERN='.*MGT_COMMUNICATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_COMMUNICATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_GEOGRAPHIC_REGION;

  ALTER TABLE MGT_GEOGRAPHIC_REGION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_GEOGRAPHIC_REGION
  FROM @UPN_STAGE_SIS_BNRODS/MGT_GEOGRAPHIC_REGION
  PATTERN='.*MGT_GEOGRAPHIC_REGION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_GEOGRAPHIC_REGION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_INTERNET_ADDRESS;

  ALTER TABLE MGT_INTERNET_ADDRESS
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_INTERNET_ADDRESS
  FROM @UPN_STAGE_SIS_BNRODS/MGT_INTERNET_ADDRESS
  PATTERN='.*MGT_INTERNET_ADDRESS_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_INTERNET_ADDRESS
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_STUDENT_PERIOD_DEFINITION;

  ALTER TABLE MGT_STUDENT_PERIOD_DEFINITION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_STUDENT_PERIOD_DEFINITION
  FROM @UPN_STAGE_SIS_BNRODS/MGT_STUDENT_PERIOD_DEFINITION
  PATTERN='.*MGT_STUDENT_PERIOD_DEFINITION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_STUDENT_PERIOD_DEFINITION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_VALIDATION;

  ALTER TABLE MGT_VALIDATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_VALIDATION
  FROM @UPN_STAGE_SIS_BNRODS/MGT_VALIDATION
  PATTERN='.*MGT_VALIDATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_VALIDATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MGT_YEAR_TYPE_DEFINITION;

  ALTER TABLE MGT_YEAR_TYPE_DEFINITION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MGT_YEAR_TYPE_DEFINITION
  FROM @UPN_STAGE_SIS_BNRODS/MGT_YEAR_TYPE_DEFINITION
  PATTERN='.*MGT_YEAR_TYPE_DEFINITION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MGT_YEAR_TYPE_DEFINITION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MRT_AWARD_BY_PERSON;

  ALTER TABLE MRT_AWARD_BY_PERSON
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MRT_AWARD_BY_PERSON
  FROM @UPN_STAGE_SIS_BNRODS/MRT_AWARD_BY_PERSON
  PATTERN='.*MRT_AWARD_BY_PERSON_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MRT_AWARD_BY_PERSON
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MRT_AWARD_DISBURSEMENT;

  ALTER TABLE MRT_AWARD_DISBURSEMENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MRT_AWARD_DISBURSEMENT
  FROM @UPN_STAGE_SIS_BNRODS/MRT_AWARD_DISBURSEMENT
  PATTERN='.*MRT_AWARD_DISBURSEMENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MRT_AWARD_DISBURSEMENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MRT_FINAID_APPLICANT_STATUS;

  ALTER TABLE MRT_FINAID_APPLICANT_STATUS
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MRT_FINAID_APPLICANT_STATUS
  FROM @UPN_STAGE_SIS_BNRODS/MRT_FINAID_APPLICANT_STATUS
  PATTERN='.*MRT_FINAID_APPLICANT_STATUS_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MRT_FINAID_APPLICANT_STATUS
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MRT_FINAID_FUND;

  ALTER TABLE MRT_FINAID_FUND
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MRT_FINAID_FUND
  FROM @UPN_STAGE_SIS_BNRODS/MRT_FINAID_FUND
  PATTERN='.*MRT_FINAID_FUND_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MRT_FINAID_FUND
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ACADEMIC_OUTCOME;

  ALTER TABLE MST_ACADEMIC_OUTCOME
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ACADEMIC_OUTCOME
  FROM @UPN_STAGE_SIS_BNRODS/MST_ACADEMIC_OUTCOME
  PATTERN='.*MST_ACADEMIC_OUTCOME_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ACADEMIC_OUTCOME
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ACADEMIC_OUTCOME_SLOT;

  ALTER TABLE MST_ACADEMIC_OUTCOME_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ACADEMIC_OUTCOME_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ACADEMIC_OUTCOME_SLOT
  PATTERN='.*MST_ACADEMIC_OUTCOME_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ACADEMIC_OUTCOME_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ACADEMIC_STANDING;

  ALTER TABLE MST_ACADEMIC_STANDING
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ACADEMIC_STANDING
  FROM @UPN_STAGE_SIS_BNRODS/MST_ACADEMIC_STANDING
  PATTERN='.*MST_ACADEMIC_STANDING_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ACADEMIC_STANDING
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADDRESS;

  ALTER TABLE MST_ADDRESS
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADDRESS
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADDRESS
  PATTERN='.*MST_ADDRESS_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADDRESS
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMINISTRATOR;

  ALTER TABLE MST_ADMINISTRATOR
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMINISTRATOR
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMINISTRATOR
  PATTERN='.*MST_ADMINISTRATOR_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMINISTRATOR
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_APPLICATION;

  ALTER TABLE MST_ADMISSIONS_APPLICATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_APPLICATION
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_APPLICATION
  PATTERN='.*MST_ADMISSIONS_APPLICATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_APPLICATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_APPLICAT_TEST;

  ALTER TABLE MST_ADMISSIONS_APPLICAT_TEST
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_APPLICAT_TEST
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_APPLICAT_TEST
  PATTERN='.*MST_ADMISSIONS_APPLICAT_TEST_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_APPLICAT_TEST
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_ATTRIBUTE;

  ALTER TABLE MST_ADMISSIONS_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_ATTRIBUTE
  PATTERN='.*MST_ADMISSIONS_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_COHORT;

  ALTER TABLE MST_ADMISSIONS_COHORT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_COHORT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_COHORT
  PATTERN='.*MST_ADMISSIONS_COHORT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_COHORT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_DECISION;

  ALTER TABLE MST_ADMISSIONS_DECISION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_DECISION
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_DECISION
  PATTERN='.*MST_ADMISSIONS_DECISION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_DECISION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_DECISION_SLOT;

  ALTER TABLE MST_ADMISSIONS_DECISION_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_DECISION_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_DECISION_SLOT
  PATTERN='.*MST_ADMISSIONS_DECISION_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_DECISION_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_RATING;

  ALTER TABLE MST_ADMISSIONS_RATING
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_RATING
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_RATING
  PATTERN='.*MST_ADMISSIONS_RATING_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_RATING
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_REQUIREMENT;

  ALTER TABLE MST_ADMISSIONS_REQUIREMENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_REQUIREMENT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_REQUIREMENT
  PATTERN='.*MST_ADMISSIONS_REQUIREMENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_REQUIREMENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADMISSIONS_SOURCE;

  ALTER TABLE MST_ADMISSIONS_SOURCE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADMISSIONS_SOURCE
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADMISSIONS_SOURCE
  PATTERN='.*MST_ADMISSIONS_SOURCE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADMISSIONS_SOURCE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADVISOR;

  ALTER TABLE MST_ADVISOR
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADVISOR
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADVISOR
  PATTERN='.*MST_ADVISOR_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADVISOR
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ADVISOR_SLOT;

  ALTER TABLE MST_ADVISOR_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ADVISOR_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ADVISOR_SLOT
  PATTERN='.*MST_ADVISOR_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ADVISOR_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_BLOCK_REGISTRATION_COURSE;

  ALTER TABLE MST_BLOCK_REGISTRATION_COURSE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_BLOCK_REGISTRATION_COURSE
  FROM @UPN_STAGE_SIS_BNRODS/MST_BLOCK_REGISTRATION_COURSE
  PATTERN='.*MST_BLOCK_REGISTRATION_COURSE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_BLOCK_REGISTRATION_COURSE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_CONTACT;

  ALTER TABLE MST_CONTACT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_CONTACT
  FROM @UPN_STAGE_SIS_BNRODS/MST_CONTACT
  PATTERN='.*MST_CONTACT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_CONTACT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_CONTACT_SLOT;

  ALTER TABLE MST_CONTACT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_CONTACT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_CONTACT_SLOT
  PATTERN='.*MST_CONTACT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_CONTACT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_ATTRIBUTE;

  ALTER TABLE MST_COURSE_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_ATTRIBUTE
  PATTERN='.*MST_COURSE_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_ATT_SLOT;

  ALTER TABLE MST_COURSE_ATT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_ATT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_ATT_SLOT
  PATTERN='.*MST_COURSE_ATT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_ATT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_CATALOG;

  ALTER TABLE MST_COURSE_CATALOG
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_CATALOG
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_CATALOG
  PATTERN='.*MST_COURSE_CATALOG_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_CATALOG
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_COREQ;

  ALTER TABLE MST_COURSE_COREQ
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_COREQ
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_COREQ
  PATTERN='.*MST_COURSE_COREQ_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_COREQ
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_LEVEL;

  ALTER TABLE MST_COURSE_LEVEL
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_LEVEL
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_LEVEL
  PATTERN='.*MST_COURSE_LEVEL_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_LEVEL
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_LEVEL_SLOT;

  ALTER TABLE MST_COURSE_LEVEL_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_LEVEL_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_LEVEL_SLOT
  PATTERN='.*MST_COURSE_LEVEL_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_LEVEL_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_OFFERING;

  ALTER TABLE MST_COURSE_OFFERING
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_OFFERING
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_OFFERING
  PATTERN='.*MST_COURSE_OFFERING_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_OFFERING
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_OFFERING_FEES;

  ALTER TABLE MST_COURSE_OFFERING_FEES
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_OFFERING_FEES
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_OFFERING_FEES
  PATTERN='.*MST_COURSE_OFFERING_FEES_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_OFFERING_FEES
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_PREREQ;

  ALTER TABLE MST_COURSE_PREREQ
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_PREREQ
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_PREREQ
  PATTERN='.*MST_COURSE_PREREQ_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_PREREQ
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_SCHEDULE;

  ALTER TABLE MST_COURSE_SCHEDULE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_SCHEDULE
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_SCHEDULE
  PATTERN='.*MST_COURSE_SCHEDULE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_SCHEDULE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_SCHEDULE_SLOT;

  ALTER TABLE MST_COURSE_SCHEDULE_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_SCHEDULE_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_SCHEDULE_SLOT
  PATTERN='.*MST_COURSE_SCHEDULE_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_SCHEDULE_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_COURSE_SUPPLEMENTAL;

  ALTER TABLE MST_COURSE_SUPPLEMENTAL
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_COURSE_SUPPLEMENTAL
  FROM @UPN_STAGE_SIS_BNRODS/MST_COURSE_SUPPLEMENTAL
  PATTERN='.*MST_COURSE_SUPPLEMENTAL_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_COURSE_SUPPLEMENTAL
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_CURRICULUM;

  ALTER TABLE MST_CURRICULUM
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_CURRICULUM
  FROM @UPN_STAGE_SIS_BNRODS/MST_CURRICULUM
  PATTERN='.*MST_CURRICULUM_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_CURRICULUM
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_CURRICULUM_FOS;

  ALTER TABLE MST_CURRICULUM_FOS
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_CURRICULUM_FOS
  FROM @UPN_STAGE_SIS_BNRODS/MST_CURRICULUM_FOS
  PATTERN='.*MST_CURRICULUM_FOS_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_CURRICULUM_FOS
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ENROLLMENT;

  ALTER TABLE MST_ENROLLMENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ENROLLMENT
  FROM @UPN_STAGE_SIS_BNRODS/MST_ENROLLMENT
  PATTERN='.*MST_ENROLLMENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ENROLLMENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ENROLLMENT_WITHDRAWAL;

  ALTER TABLE MST_ENROLLMENT_WITHDRAWAL
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ENROLLMENT_WITHDRAWAL
  FROM @UPN_STAGE_SIS_BNRODS/MST_ENROLLMENT_WITHDRAWAL
  PATTERN='.*MST_ENROLLMENT_WITHDRAWAL_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ENROLLMENT_WITHDRAWAL
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY_ATTRIBUTE;

  ALTER TABLE MST_FACULTY_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY_ATTRIBUTE
  PATTERN='.*MST_FACULTY_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY_ATT_SLOT;

  ALTER TABLE MST_FACULTY_ATT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY_ATT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY_ATT_SLOT
  PATTERN='.*MST_FACULTY_ATT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY_ATT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY_CONTRACT;

  ALTER TABLE MST_FACULTY_CONTRACT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY_CONTRACT
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY_CONTRACT
  PATTERN='.*MST_FACULTY_CONTRACT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY_CONTRACT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY;

  ALTER TABLE MST_FACULTY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY
  PATTERN='.*MST_FACULTY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY_DEPT_COLLEGE;

  ALTER TABLE MST_FACULTY_DEPT_COLLEGE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY_DEPT_COLLEGE
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY_DEPT_COLLEGE
  PATTERN='.*MST_FACULTY_DEPT_COLLEGE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY_DEPT_COLLEGE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FACULTY_FEEDBACK_DETAIL;

  ALTER TABLE MST_FACULTY_FEEDBACK_DETAIL
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FACULTY_FEEDBACK_DETAIL
  FROM @UPN_STAGE_SIS_BNRODS/MST_FACULTY_FEEDBACK_DETAIL
  PATTERN='.*MST_FACULTY_FEEDBACK_DETAIL_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FACULTY_FEEDBACK_DETAIL
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_FIELD_OF_STUDY;

  ALTER TABLE MST_FIELD_OF_STUDY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_FIELD_OF_STUDY
  FROM @UPN_STAGE_SIS_BNRODS/MST_FIELD_OF_STUDY
  PATTERN='.*MST_FIELD_OF_STUDY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_FIELD_OF_STUDY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_GENERAL_STUDENT;

  ALTER TABLE MST_GENERAL_STUDENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_GENERAL_STUDENT
  FROM @UPN_STAGE_SIS_BNRODS/MST_GENERAL_STUDENT
  PATTERN='.*MST_GENERAL_STUDENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_GENERAL_STUDENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_GPA;

  ALTER TABLE MST_GPA
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_GPA
  FROM @UPN_STAGE_SIS_BNRODS/MST_GPA
  PATTERN='.*MST_GPA_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_GPA
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_HOLD;

  ALTER TABLE MST_HOLD
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_HOLD
  FROM @UPN_STAGE_SIS_BNRODS/MST_HOLD
  PATTERN='.*MST_HOLD_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_HOLD
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_HOLD_SLOT;

  ALTER TABLE MST_HOLD_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_HOLD_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_HOLD_SLOT
  PATTERN='.*MST_HOLD_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_HOLD_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INSTITUTION_CHARACTERISTIC;

  ALTER TABLE MST_INSTITUTION_CHARACTERISTIC
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INSTITUTION_CHARACTERISTIC
  FROM @UPN_STAGE_SIS_BNRODS/MST_INSTITUTION_CHARACTERISTIC
  PATTERN='.*MST_INSTITUTION_CHARACTERISTIC_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INSTITUTION_CHARACTERISTIC
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INSTITUTION;

  ALTER TABLE MST_INSTITUTION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INSTITUTION
  FROM @UPN_STAGE_SIS_BNRODS/MST_INSTITUTION
  PATTERN='.*MST_INSTITUTION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INSTITUTION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INSTITUTION_DEMOGRAPHIC;

  ALTER TABLE MST_INSTITUTION_DEMOGRAPHIC
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INSTITUTION_DEMOGRAPHIC
  FROM @UPN_STAGE_SIS_BNRODS/MST_INSTITUTION_DEMOGRAPHIC
  PATTERN='.*MST_INSTITUTION_DEMOGRAPHIC_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INSTITUTION_DEMOGRAPHIC
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INSTRUCTIONAL_ASSIGNMENT;

  ALTER TABLE MST_INSTRUCTIONAL_ASSIGNMENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INSTRUCTIONAL_ASSIGNMENT
  FROM @UPN_STAGE_SIS_BNRODS/MST_INSTRUCTIONAL_ASSIGNMENT
  PATTERN='.*MST_INSTRUCTIONAL_ASSIGNMENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INSTRUCTIONAL_ASSIGNMENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INSTRUCT_ASSIGN_SLOT;

  ALTER TABLE MST_INSTRUCT_ASSIGN_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INSTRUCT_ASSIGN_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_INSTRUCT_ASSIGN_SLOT
  PATTERN='.*MST_INSTRUCT_ASSIGN_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INSTRUCT_ASSIGN_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INST_CHARACTERISTIC_SLOT;

  ALTER TABLE MST_INST_CHARACTERISTIC_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INST_CHARACTERISTIC_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_INST_CHARACTERISTIC_SLOT
  PATTERN='.*MST_INST_CHARACTERISTIC_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INST_CHARACTERISTIC_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INTEREST;

  ALTER TABLE MST_INTEREST
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INTEREST
  FROM @UPN_STAGE_SIS_BNRODS/MST_INTEREST
  PATTERN='.*MST_INTEREST_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INTEREST
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_INTEREST_SLOT;

  ALTER TABLE MST_INTEREST_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_INTEREST_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_INTEREST_SLOT
  PATTERN='.*MST_INTEREST_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_INTEREST_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_MEDICAL_INFORMATION;

  ALTER TABLE MST_MEDICAL_INFORMATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_MEDICAL_INFORMATION
  FROM @UPN_STAGE_SIS_BNRODS/MST_MEDICAL_INFORMATION
  PATTERN='.*MST_MEDICAL_INFORMATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_MEDICAL_INFORMATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_MEDICAL_INFORMATION_SLOT;

  ALTER TABLE MST_MEDICAL_INFORMATION_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_MEDICAL_INFORMATION_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_MEDICAL_INFORMATION_SLOT
  PATTERN='.*MST_MEDICAL_INFORMATION_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_MEDICAL_INFORMATION_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_MEETING_TIME;

  ALTER TABLE MST_MEETING_TIME
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_MEETING_TIME
  FROM @UPN_STAGE_SIS_BNRODS/MST_MEETING_TIME
  PATTERN='.*MST_MEETING_TIME_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_MEETING_TIME
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_MEETING_TIME_SLOT;

  ALTER TABLE MST_MEETING_TIME_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_MEETING_TIME_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_MEETING_TIME_SLOT
  PATTERN='.*MST_MEETING_TIME_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_MEETING_TIME_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_NONINSTRUCT_ASSIGN_SLOT;

  ALTER TABLE MST_NONINSTRUCT_ASSIGN_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_NONINSTRUCT_ASSIGN_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_NONINSTRUCT_ASSIGN_SLOT
  PATTERN='.*MST_NONINSTRUCT_ASSIGN_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_NONINSTRUCT_ASSIGN_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_OFFERING_COREQ;

  ALTER TABLE MST_OFFERING_COREQ
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_OFFERING_COREQ
  FROM @UPN_STAGE_SIS_BNRODS/MST_OFFERING_COREQ
  PATTERN='.*MST_OFFERING_COREQ_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_OFFERING_COREQ
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_OFFERING_GRADE_MODE;

  ALTER TABLE MST_OFFERING_GRADE_MODE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_OFFERING_GRADE_MODE
  FROM @UPN_STAGE_SIS_BNRODS/MST_OFFERING_GRADE_MODE
  PATTERN='.*MST_OFFERING_GRADE_MODE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_OFFERING_GRADE_MODE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_OFFERING_PREREQ;

  ALTER TABLE MST_OFFERING_PREREQ
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_OFFERING_PREREQ
  FROM @UPN_STAGE_SIS_BNRODS/MST_OFFERING_PREREQ
  PATTERN='.*MST_OFFERING_PREREQ_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_OFFERING_PREREQ
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_ORGANIZATION_ENTITY;

  ALTER TABLE MST_ORGANIZATION_ENTITY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_ORGANIZATION_ENTITY
  FROM @UPN_STAGE_SIS_BNRODS/MST_ORGANIZATION_ENTITY
  PATTERN='.*MST_ORGANIZATION_ENTITY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_ORGANIZATION_ENTITY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_OUTCOME_HONOR;

  ALTER TABLE MST_OUTCOME_HONOR
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_OUTCOME_HONOR
  FROM @UPN_STAGE_SIS_BNRODS/MST_OUTCOME_HONOR
  PATTERN='.*MST_OUTCOME_HONOR_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_OUTCOME_HONOR
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_PERSON;

  ALTER TABLE MST_PERSON
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_PERSON
  FROM @UPN_STAGE_SIS_BNRODS/MST_PERSON
  PATTERN='.*MST_PERSON_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_PERSON
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_PREVIOUS_DEGREE;

  ALTER TABLE MST_PREVIOUS_DEGREE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_PREVIOUS_DEGREE
  FROM @UPN_STAGE_SIS_BNRODS/MST_PREVIOUS_DEGREE
  PATTERN='.*MST_PREVIOUS_DEGREE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_PREVIOUS_DEGREE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_PREVIOUS_EDUCATION;

  ALTER TABLE MST_PREVIOUS_EDUCATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_PREVIOUS_EDUCATION
  FROM @UPN_STAGE_SIS_BNRODS/MST_PREVIOUS_EDUCATION
  PATTERN='.*MST_PREVIOUS_EDUCATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_PREVIOUS_EDUCATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_PREVIOUS_EDUCATION_SLOT;

  ALTER TABLE MST_PREVIOUS_EDUCATION_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_PREVIOUS_EDUCATION_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_PREVIOUS_EDUCATION_SLOT
  PATTERN='.*MST_PREVIOUS_EDUCATION_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_PREVIOUS_EDUCATION_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_PRE_STUDENT;

  ALTER TABLE MST_PRE_STUDENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_PRE_STUDENT
  FROM @UPN_STAGE_SIS_BNRODS/MST_PRE_STUDENT
  PATTERN='.*MST_PRE_STUDENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_PRE_STUDENT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_RACE;

  ALTER TABLE MST_RACE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_RACE
  FROM @UPN_STAGE_SIS_BNRODS/MST_RACE
  PATTERN='.*MST_RACE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_RACE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_RACE_SLOT;

  ALTER TABLE MST_RACE_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_RACE_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_RACE_SLOT
  PATTERN='.*MST_RACE_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_RACE_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_RECRUITMENT_SOURCE_SLOT;

  ALTER TABLE MST_RECRUITMENT_SOURCE_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_RECRUITMENT_SOURCE_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_RECRUITMENT_SOURCE_SLOT
  PATTERN='.*MST_RECRUITMENT_SOURCE_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_RECRUITMENT_SOURCE_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_REGISTRATION_PLAN;

  ALTER TABLE MST_REGISTRATION_PLAN
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_REGISTRATION_PLAN
  FROM @UPN_STAGE_SIS_BNRODS/MST_REGISTRATION_PLAN
  PATTERN='.*MST_REGISTRATION_PLAN_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_REGISTRATION_PLAN
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_REQUIREMENT_SLOT;

  ALTER TABLE MST_REQUIREMENT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_REQUIREMENT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_REQUIREMENT_SLOT
  PATTERN='.*MST_REQUIREMENT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_REQUIREMENT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_SCHEDULE_ATTRIBUTE;

  ALTER TABLE MST_SCHEDULE_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_SCHEDULE_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_SCHEDULE_ATTRIBUTE
  PATTERN='.*MST_SCHEDULE_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_SCHEDULE_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_SPORT;

  ALTER TABLE MST_SPORT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_SPORT
  FROM @UPN_STAGE_SIS_BNRODS/MST_SPORT
  PATTERN='.*MST_SPORT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_SPORT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_ACTIVITY;

  ALTER TABLE MST_STUDENT_ACTIVITY
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_ACTIVITY
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_ACTIVITY
  PATTERN='.*MST_STUDENT_ACTIVITY_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_ACTIVITY
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_ATTRIBUTE;

  ALTER TABLE MST_STUDENT_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_ATTRIBUTE
  PATTERN='.*MST_STUDENT_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_ATTRIBUTE_SLOT;

  ALTER TABLE MST_STUDENT_ATTRIBUTE_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_ATTRIBUTE_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_ATTRIBUTE_SLOT
  PATTERN='.*MST_STUDENT_ATTRIBUTE_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_ATTRIBUTE_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_CLASSIFICATION;

  ALTER TABLE MST_STUDENT_CLASSIFICATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_CLASSIFICATION
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_CLASSIFICATION
  PATTERN='.*MST_STUDENT_CLASSIFICATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_CLASSIFICATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COHORT;

  ALTER TABLE MST_STUDENT_COHORT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COHORT
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COHORT
  PATTERN='.*MST_STUDENT_COHORT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COHORT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COHORT_SLOT;

  ALTER TABLE MST_STUDENT_COHORT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COHORT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COHORT_SLOT
  PATTERN='.*MST_STUDENT_COHORT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COHORT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COURSE_ATTRIBUTE;

  ALTER TABLE MST_STUDENT_COURSE_ATTRIBUTE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COURSE_ATTRIBUTE
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE_ATTRIBUTE
  PATTERN='.*MST_STUDENT_COURSE_ATTRIBUTE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COURSE_ATTRIBUTE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COURSE_ATT_SLOT;

  ALTER TABLE MST_STUDENT_COURSE_ATT_SLOT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COURSE_ATT_SLOT
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE_ATT_SLOT
  PATTERN='.*MST_STUDENT_COURSE_ATT_SLOT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COURSE_ATT_SLOT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COURSE;

  ALTER TABLE MST_STUDENT_COURSE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COURSE
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE
  PATTERN='.*MST_STUDENT_COURSE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COURSE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COURSE_GRADE_CHG;

  ALTER TABLE MST_STUDENT_COURSE_GRADE_CHG
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COURSE_GRADE_CHG
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE_GRADE_CHG
  PATTERN='.*MST_STUDENT_COURSE_GRADE_CHG_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COURSE_GRADE_CHG
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_COURSE_TEMP;

  ALTER TABLE MST_STUDENT_COURSE_TEMP
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_COURSE_TEMP
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE_TEMP
  PATTERN='.*MST_STUDENT_COURSE_TEMP_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_COURSE_TEMP
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_TRANSFERRED_COURSE;

  ALTER TABLE MST_STUDENT_TRANSFERRED_COURSE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_TRANSFERRED_COURSE
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_TRANSFERRED_COURSE
  PATTERN='.*MST_STUDENT_TRANSFERRED_COURSE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_TRANSFERRED_COURSE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_STUDENT_WORK_EXPERIENCE;

  ALTER TABLE MST_STUDENT_WORK_EXPERIENCE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_STUDENT_WORK_EXPERIENCE
  FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_WORK_EXPERIENCE
  PATTERN='.*MST_STUDENT_WORK_EXPERIENCE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_STUDENT_WORK_EXPERIENCE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_TELEPHONE;

  ALTER TABLE MST_TELEPHONE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_TELEPHONE
  FROM @UPN_STAGE_SIS_BNRODS/MST_TELEPHONE
  PATTERN='.*MST_TELEPHONE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_TELEPHONE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_TEST;

  ALTER TABLE MST_TEST
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_TEST
  FROM @UPN_STAGE_SIS_BNRODS/MST_TEST
  PATTERN='.*MST_TEST_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_TEST
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_TEST_PERCENTILE;

  ALTER TABLE MST_TEST_PERCENTILE
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_TEST_PERCENTILE
  FROM @UPN_STAGE_SIS_BNRODS/MST_TEST_PERCENTILE
  PATTERN='.*MST_TEST_PERCENTILE_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_TEST_PERCENTILE
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MST_VETERAN_CERTIFICATION;

  ALTER TABLE MST_VETERAN_CERTIFICATION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MST_VETERAN_CERTIFICATION
  FROM @UPN_STAGE_SIS_BNRODS/MST_VETERAN_CERTIFICATION
  PATTERN='.*MST_VETERAN_CERTIFICATION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MST_VETERAN_CERTIFICATION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MTT_ACCOUNT;

  ALTER TABLE MTT_ACCOUNT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_ACCOUNT
  FROM @UPN_STAGE_SIS_BNRODS/MTT_ACCOUNT
  PATTERN='.*MTT_ACCOUNT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_ACCOUNT
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MTT_ACCOUNT_DETAIL;

  ALTER TABLE MTT_ACCOUNT_DETAIL
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_ACCOUNT_DETAIL
  FROM @UPN_STAGE_SIS_BNRODS/MTT_ACCOUNT_DETAIL
  PATTERN='.*MTT_ACCOUNT_DETAIL_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_ACCOUNT_DETAIL
  DROP COLUMN ROWNUM;

COMMIT;
/*BEGIN;

  TRUNCATE TABLE MTT_APPLICATION_OF_PAYMENT;

  ALTER TABLE MTT_APPLICATION_OF_PAYMENT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_APPLICATION_OF_PAYMENT
  FROM @UPN_STAGE_SIS_BNRODS/MTT_APPLICATION_OF_PAYMENT
  PATTERN='.*MTT_APPLICATION_OF_PAYMENT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_APPLICATION_OF_PAYMENT
  DROP COLUMN ROWNUM;

COMMIT;*/
BEGIN;

  TRUNCATE TABLE MTT_EXEMPTION;

  ALTER TABLE MTT_EXEMPTION
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_EXEMPTION
  FROM @UPN_STAGE_SIS_BNRODS/MTT_EXEMPTION
  PATTERN='.*MTT_EXEMPTION_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_EXEMPTION
  DROP COLUMN ROWNUM;

COMMIT;
BEGIN;

  TRUNCATE TABLE MTT_LEDGER_ACCOUNTING;

  ALTER TABLE MTT_LEDGER_ACCOUNTING
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_LEDGER_ACCOUNTING
  FROM @UPN_STAGE_SIS_BNRODS/MTT_LEDGER_ACCOUNTING
  PATTERN='.*MTT_LEDGER_ACCOUNTING_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_LEDGER_ACCOUNTING
  DROP COLUMN ROWNUM;

COMMIT;

BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_STUDENT_COURSE_REG_AUDIT;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_STUDENT_COURSE_REG_AUDIT
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.MST_STUDENT_COURSE_REG_AUDIT
FROM @UPN_STAGE_SIS_BNRODS/MST_STUDENT_COURSE_REG_AUDIT_
PATTERN='.*MST_STUDENT_COURSE_REG_AUDIT_[0-9].*[.]csv'
FILE_FORMAT=CSV_UPN_ODS
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_STUDENT_COURSE_REG_AUDIT
DROP COLUMN ROWNUM;
COMMIT;

BEGIN;
TRUNCATE TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_BASE_STUDENT;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_BASE_STUDENT
ADD COLUMN ROWNUM NUMBER;
COPY INTO UPN_STG_SIS_BNRODS_ODSMGR.MST_BASE_STUDENT
FROM @UPN_STAGE_SIS_BNRODS/MST_BASE_STUDENT_
PATTERN='.*MST_BASE_STUDENT_[0-9].*[.]csv'
FILE_FORMAT=CSV_UPN_ODS
ON_ERROR=CONTINUE;
ALTER TABLE UPN_STG_SIS_BNRODS_ODSMGR.MST_BASE_STUDENT
DROP COLUMN ROWNUM;
COMMIT;

BEGIN;

  TRUNCATE TABLE MTT_CONTRACT;

  ALTER TABLE MTT_CONTRACT
  ADD COLUMN ROWNUM NUMBER;

  COPY INTO MTT_CONTRACT
  FROM @UPN_STAGE_SIS_BNRODS/MTT_CONTRACT
  PATTERN='.*MTT_CONTRACT_[0-9].*[.]csv'
  FILE_FORMAT=CSV_UPN_ODS
  ON_ERROR=CONTINUE;

  ALTER TABLE MTT_CONTRACT
  DROP COLUMN ROWNUM;

COMMIT;