--Cursos_
SELECT 'EXTERNAL_COURSE_KEY|COURSE_ID|COURSE_NAME|AVAILABLE_IND|ROW_STATUS|DURATION|START_DATE|END_DATE|TERM_KEY|DATA_SOURCE_KEY|PRIMARY_EXTERNAL_NODE_KEY|EXTERNAL_ASSOCIATION_KEY' FROM DUAL;
	SELECT DISTINCT
		CASE WHEN A.SSBSECT_SCHD_CODE = 'VIR' OR A.SSBSECT_INSM_CODE = 'V'
			THEN A.SSBSECT_SUBJ_CODE ||'.'|| A.SSBSECT_CRSE_NUMB ||'.'|| A.SSBSECT_TERM_CODE ||'.'|| A.SSBSECT_CRN ||'.'|| 'V'
			ELSE A.SSBSECT_SUBJ_CODE ||'.'|| A.SSBSECT_CRSE_NUMB ||'.'|| A.SSBSECT_TERM_CODE ||'.'|| A.SSBSECT_CRN ||'.'|| 'P' END ||'|'||
        CASE WHEN A.SSBSECT_SCHD_CODE = 'VIR' OR A.SSBSECT_INSM_CODE = 'V'
			THEN A.SSBSECT_SUBJ_CODE ||'.'|| A.SSBSECT_CRSE_NUMB ||'.'|| A.SSBSECT_TERM_CODE ||'.'|| A.SSBSECT_CRN ||'.'|| 'V'
			ELSE A.SSBSECT_SUBJ_CODE ||'.'|| A.SSBSECT_CRSE_NUMB ||'.'|| A.SSBSECT_TERM_CODE ||'.'|| A.SSBSECT_CRN ||'.'|| 'P' END ||'|'||
        CASE WHEN A.SSBSECT_SCHD_CODE = 'VIR' OR A.SSBSECT_INSM_CODE = 'V'
            THEN B.SCBCRSE_TITLE ||'(Virtual)'
            ELSE B.SCBCRSE_TITLE ||'(Presencial)' END ||'|'||
        CASE WHEN A.SSBSECT_SSTS_CODE = 'A' THEN 'Y' ELSE 'N' END ||'|'||
        CASE WHEN A.SSBSECT_SSTS_CODE = 'A' THEN 'ENABLED' ELSE 'DISABLED' END ||'|'||
        'R|'||
        TO_CHAR(TO_DATE(D.START_DATE)-14,'YYYYMMDD') ||'|'||
        TO_CHAR(TO_DATE(D.END_DATE)+10,'YYYYMMDD') ||'|'||
        A.SSBSECT_TERM_CODE ||'|'||
        CASE SUBSTR(A.SSBSECT_TERM_CODE,4,1) --'UPN.<Instancia>.Banner.<Nivel>'
            WHEN '3' THEN 'UPN.Cursos.Banner.PDN'
            WHEN '4' THEN 'UPN.Cursos.Banner.UG'
            WHEN '5' THEN 'UPN.Cursos.Banner.WA'
            WHEN '7' THEN 'UPN.Cursos.Banner.Ingles'
            ELSE 'UPN.Cursos.Banner.EPEC' END ||'|'||
        'PEPN01.UPN.' ||
            CASE SUBSTR(A.SSBSECT_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN A.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE A.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE ||'.'|| A.SSBSECT_TERM_CODE ||'|'||
        A.SSBSECT_CRN || '.PEPN01.UPN.' ||
            CASE SUBSTR(A.SSBSECT_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN A.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE A.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE ||'.'|| A.SSBSECT_TERM_CODE
    FROM ODSMGR.LOE_SSBSECT A
    		INNER JOIN ODSMGR.SCBCRSE B ON A.SSBSECT_SUBJ_CODE = B.SCBCRSE_SUBJ_CODE AND A.SSBSECT_CRSE_NUMB = B.SCBCRSE_CRSE_NUMB
            								AND B.SCBCRSE_EFF_TERM = (SELECT MAX(B1.SCBCRSE_EFF_TERM) FROM ODSMGR.SCBCRSE B1
            															WHERE B1.SCBCRSE_SUBJ_CODE = A.SSBSECT_SUBJ_CODE AND B1.SCBCRSE_CRSE_NUMB = A.SSBSECT_CRSE_NUMB
            																AND B1.SCBCRSE_EFF_TERM <= A.SSBSECT_TERM_CODE)
            INNER JOIN ODSMGR.SSRATTR C ON A.SSBSECT_TERM_CODE = C.SSRATTR_TERM_CODE AND A.SSBSECT_CRN = C.SSRATTR_CRN
            INNER JOIN (SELECT DISTINCT SSRMEET_TERM_CODE, SSRMEET_CRN
            				, MIN(SSRMEET_START_DATE) AS START_DATE, MAX(SSRMEET_END_DATE) AS END_DATE
						FROM ODSMGR.SSRMEET GROUP BY SSRMEET_TERM_CODE, SSRMEET_CRN
						) D ON A.SSBSECT_TERM_CODE = D.SSRMEET_TERM_CODE AND A.SSBSECT_CRN = D.SSRMEET_CRN
    WHERE A.SSBSECT_SSTS_CODE = 'A' AND A.SSBSECT_ENRL > 0 --AND A.SSBSECT_MAX_ENRL > 0
        AND A.SSBSECT_SUBJ_CODE NOT IN ('ACAD','REPS','TEST','XPEN','XSER')
        AND CURRENT_DATE BETWEEN TO_DATE(D.START_DATE)-14 AND TO_DATE(D.END_DATE)+10
        AND A.SSBSECT_TERM_CODE IN (SELECT DISTINCT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM
                                    WHERE CURRENT_DATE BETWEEN TO_DATE(START_DATE)-14 AND TO_DATE(END_DATE)+10)
	;
	SPOOL OFF