--Usuarios_Nodos_
SELECT 'EXTERNAL_ASSOCIATION_KEY|EXTERNAL_NODE_KEY|EXTERNAL_USER_KEY|DATA_SOURCE_KEY' FROM DUAL;
    SELECT DISTINCT
        E.SPRIDEN_ID ||'.PEPN01.UPN.'||
            CASE SUBSTR(A.SFRSTCR_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN B.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE B.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE  ||'.'|| A.SFRSTCR_TERM_CODE ||'|'||
        'PEPN01.UPN.' ||
            CASE SUBSTR(A.SFRSTCR_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN B.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE B.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE  ||'.'|| A.SFRSTCR_TERM_CODE ||'|'||
        A.SFRSTCR_PIDM ||'|'||
        CASE SUBSTR(A.SFRSTCR_TERM_CODE,4,1) --'UPN.<Instancia>.Banner.<Nivel>'
            WHEN '3' THEN 'UPN.UsuarioNodo.Banner.PDN'
            WHEN '4' THEN 'UPN.UsuarioNodo.Banner.UG'
            WHEN '5' THEN 'UPN.UsuarioNodo.Banner.WA'
            WHEN '7' THEN 'UPN.UsuarioNodo.Banner.Ingles'
            ELSE 'UPN.UsuarioNodo.Banner.EPEC' END
    FROM ODSMGR.SFRSTCR A
    		INNER JOIN ODSMGR.LOE_SSBSECT B ON A.SFRSTCR_TERM_CODE = B.SSBSECT_TERM_CODE AND A.SFRSTCR_CRN = B.SSBSECT_CRN
    		INNER JOIN ODSMGR.SSRATTR C ON B.SSBSECT_TERM_CODE = C.SSRATTR_TERM_CODE AND B.SSBSECT_CRN = C.SSRATTR_CRN
    		INNER JOIN (SELECT DISTINCT SSRMEET_TERM_CODE, SSRMEET_CRN
							, MIN(SSRMEET_START_DATE) AS START_DATE, MAX(SSRMEET_END_DATE) AS END_DATE
						FROM ODSMGR.SSRMEET GROUP BY SSRMEET_TERM_CODE, SSRMEET_CRN
						) D ON B.SSBSECT_TERM_CODE = D.SSRMEET_TERM_CODE AND B.SSBSECT_CRN = D.SSRMEET_CRN
			INNER JOIN ODSMGR.LOE_SPRIDEN E ON A.SFRSTCR_PIDM = E.SPRIDEN_PIDM AND E.SPRIDEN_CHANGE_IND IS NULL
    WHERE A.SFRSTCR_RSTS_CODE IN ('RW','RE','RA')
        AND B.SSBSECT_SSTS_CODE = 'A' AND B.SSBSECT_ENRL > 0 --AND B.SSBSECT_MAX_ENRL > 0
        AND B.SSBSECT_SUBJ_CODE NOT IN ('ACAD','REPS','TEST','XPEN','XSER')
        AND CURRENT_DATE BETWEEN TO_DATE(D.START_DATE)-14 AND TO_DATE(D.END_DATE)+10
        AND B.SSBSECT_TERM_CODE IN (SELECT DISTINCT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM
                                    WHERE CURRENT_DATE BETWEEN TO_DATE(START_DATE)-14 AND TO_DATE(END_DATE)+10)
    UNION
    SELECT DISTINCT
        E.SPRIDEN_ID ||'.PEPN01.UPN.'||
            CASE SUBSTR(A.SIRASGN_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN B.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE B.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE  ||'.'|| A.SIRASGN_TERM_CODE ||'|'||
        'PEPN01.UPN.' ||
            CASE SUBSTR(A.SIRASGN_TERM_CODE,4,1)
                WHEN '3' THEN 'PN'
                WHEN '4' THEN 'UG'
                WHEN '5' THEN 'WA'
                WHEN '7' THEN 'IN'
                ELSE 'EP' END ||'.'||
            CASE WHEN B.SSBSECT_CAMP_CODE IN ('TML','TSI') THEN 'TRU' ELSE B.SSBSECT_CAMP_CODE END ||'.'||
            C.SSRATTR_ATTR_CODE  ||'.'|| A.SIRASGN_TERM_CODE ||'|'||
        A.SIRASGN_PIDM ||'|'||
        CASE SUBSTR(A.SIRASGN_TERM_CODE,4,1) --'UPN.<Instancia>.Banner.<Nivel>'
            WHEN '3' THEN 'UPN.UsuarioNodo.Banner.PDN'
            WHEN '4' THEN 'UPN.UsuarioNodo.Banner.UG'
            WHEN '5' THEN 'UPN.UsuarioNodo.Banner.WA'
            WHEN '7' THEN 'UPN.UsuarioNodo.Banner.Ingles'
            ELSE 'UPN.UsuarioNodo.Banner.EPEC' END
    FROM ODSMGR.SIRASGN A
    		INNER JOIN ODSMGR.LOE_SSBSECT B ON A.SIRASGN_TERM_CODE = B.SSBSECT_TERM_CODE AND A.SIRASGN_CRN = B.SSBSECT_CRN
    		INNER JOIN ODSMGR.SSRATTR C ON B.SSBSECT_TERM_CODE = C.SSRATTR_TERM_CODE AND B.SSBSECT_CRN = C.SSRATTR_CRN
    		INNER JOIN (SELECT DISTINCT SSRMEET_TERM_CODE, SSRMEET_CRN
							, MIN(SSRMEET_START_DATE) AS START_DATE, MAX(SSRMEET_END_DATE) AS END_DATE
						FROM ODSMGR.SSRMEET GROUP BY SSRMEET_TERM_CODE, SSRMEET_CRN
						) D ON B.SSBSECT_TERM_CODE = D.SSRMEET_TERM_CODE AND B.SSBSECT_CRN = D.SSRMEET_CRN
			INNER JOIN ODSMGR.LOE_SPRIDEN E ON A.SIRASGN_PIDM = E.SPRIDEN_PIDM AND E.SPRIDEN_CHANGE_IND IS NULL
    WHERE B.SSBSECT_SSTS_CODE = 'A' AND B.SSBSECT_ENRL > 0 --AND B.SSBSECT_MAX_ENRL > 0
        AND B.SSBSECT_SUBJ_CODE NOT IN ('ACAD','REPS','TEST','XPEN','XSER')
        AND CURRENT_DATE BETWEEN TO_DATE(D.START_DATE)-14 AND TO_DATE(D.END_DATE)+10
        AND B.SSBSECT_TERM_CODE IN (SELECT DISTINCT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM
                                    WHERE CURRENT_DATE BETWEEN TO_DATE(START_DATE)-14 AND TO_DATE(END_DATE)+10)
	;
	SPOOL OFF