--PlanEstudio_yyyymmdd.csv
SELECT DISTINCT A.PROGRAM||'.'||A.TERM_CODE_EFF AS "id_plan_estudio"
    , NULL AS "codigo_plan_estudio"
    , SMRPRLE_PROGRAM_DESC||'.'||A.TERM_CODE_EFF AS "nombre_plan_estudio"
    , A.PROGRAM AS "id_carrera"
    , SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-1) AS "id_modalidad"
    , CASE SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-1) WHEN 'UG' THEN 'Pregrado Regular' WHEN 'WA' THEN 'Pregrado Adulto Trabajador' END AS "nombre_modalidad"
    , NULL AS "numero_creditos_plan_estudio"
    , CASE WHEN B.TERM_CODE_EFF IS NULL THEN 0 ELSE 1 END AS "indicador_version_actual"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_SMRPRLE ON A.PROGRAM = SMRPRLE_PROGRAM
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY B ON A.PROGRAM = B.PROGRAM AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
														AND B.TERM_CODE_EFF = (SELECT MAX(B1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY B1
																				WHERE B1.PROGRAM = B.PROGRAM)
WHERE SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA')
;