--Demanda_yyyymmdd.csv
SELECT DISTINCT 'UPN' AS "id_institucion"
    , STVCAMP_CODE AS "id_campus"
    , STVTERM_CODE AS "id_periodo_academico"
    , 'JORNADA UNICA' AS "id_jornada"
    , A.PROGRAM AS "id_carrera"
    , NULL AS "nombre_carrera"
    , A.PROGRAM || '.' || A.TERM_CODE_EFF AS "id_plan_estudio"
    , NULL AS "nombre_plan_estudio"
    , CASE WHEN SUBSTR(A.AREA,LENGTH(A.AREA)-1,2) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14')
    	THEN TO_NUMBER(SUBSTR(A.AREA,LENGTH(A.AREA)-1,2)) END AS "numero_nivel"
    , CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE C.SMRARUL_SUBJ_CODE END
        || CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE C.SMRARUL_CRSE_NUMB_LOW END/*
        || A.TERM_CODE_EFF*/ AS "id_curso"
    , COALESCE(D.TITLE_LONG_DESC,D.TITLE_SHORT_DESC) AS "nombre_curso"
    , '' AS "anio_cohorte_estudiantes"
    , '' AS "inscripciones_estimadas"
    , NULL AS "nota_clase"
    , NULL AS "modalidad"
    , NULL AS "sesion"
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.TERM_CODE_EFF = B.TERM_CODE_EFF AND A.AREA = B.AREA_COURSE
		INNER JOIN ODSMGR.STVCAMP ON STVCAMP_CODE <> 'M'
		INNER JOIN ODSMGR.STVTERM
		LEFT JOIN ODSMGR.LOE_SMRARUL C ON B.TERM_CODE_EFF = C.SMRARUL_TERM_CODE_EFF AND B.AREA_COURSE = C.SMRARUL_AREA AND B.AREA_RULE = C.SMRARUL_KEY_RULE
		LEFT JOIN ODSMGR.COURSE_CATALOG D ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE C.SMRARUL_SUBJ_CODE END = D.SUBJECT
											AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE C.SMRARUL_CRSE_NUMB_LOW END = D.COURSE_NUMBER 
WHERE SUBSTR(A.PROGRAM,5,2) = CASE SUBSTR(STVTERM_CODE,4,1) WHEN '4' THEN 'UG' WHEN '5' THEN 'WA' ELSE NULL END	
    --AND A.TERM_CODE_EFF = D.ACADEMIC_PERIOD
    AND D.STATUS = 'A' AND D.ACADEMIC_PERIOD = '999999' AND D.COLLEGE <> 'GR'
    AND STVTERM_CODE IN ('221413')     --INGRESAR_PERIODO_NUEVO
;