
SELECT DISTINCT
    SSBSECT_TERM_CODE ||'.'|| SSBSECT_CRN AS SIS_COURSE_KEY
    , SSBSECT_SUBJ_CODE AS SUBJECT_CODE
    , STVSUBJ_DESC AS SUBJECT
    , SCBCRSE_DEPT_CODE AS DEPARTMENT_CODE
    , STVDEPT_DESC AS DEPARTMENT
    , SCBCRSE_COLL_CODE AS COLLEGE
    , SSBSECT_CRSE_NUMB AS COURSE_NUMBER
    , SSBSECT_CRN AS SECTION
    , 'UPN' AS INSTITUTION
    , SSBSECT_CAMP_CODE AS CAMPUS_CODE
    , STVCAMP_DESC AS CAMPUS
    , SSBSECT_SCHD_CODE AS COURSE_TYPE
    , SSBSECT_TERM_CODE AS TERM_SOURCE_KEY
    , SCRLEVL_LEVL_CODE AS COURSE_LEVEL
    , SSBSECT_SSTS_CODE AS SECTION_STATUS
    , SSBSECT_INSM_CODE AS INSTRUCTION_METHOD
    , SPRIDEN_ID AS SIS_INSTRUCTOR_KEY
    , CASE WHEN SSBSECT_SCHD_CODE = 'VIR' OR SSBSECT_INSM_CODE = 'V'
            THEN SSBSECT_SUBJ_CODE ||'.'|| SSBSECT_CRSE_NUMB ||'.'|| SSBSECT_TERM_CODE ||'.'|| SSBSECT_CRN ||'.'|| 'V'
          ELSE SSBSECT_SUBJ_CODE ||'.'|| SSBSECT_CRSE_NUMB ||'.'|| SSBSECT_TERM_CODE ||'.'|| SSBSECT_CRN ||'.'|| 'P' END AS BATCHUID
FROM SSBSECT, 
     SCBCRSE, 
     SCRLEVL, 
     SIRASGN, 
     SPRIDEN, 
     STVSUBJ, 
     STVDEPT, 
     STVCAMP
WHERE SSBSECT_SUBJ_CODE = SCBCRSE_SUBJ_CODE AND SSBSECT_CRSE_NUMB = SCBCRSE_CRSE_NUMB
    AND SCBCRSE_SUBJ_CODE = SCRLEVL_SUBJ_CODE AND SCBCRSE_CRSE_NUMB = SCRLEVL_CRSE_NUMB AND SCBCRSE_EFF_TERM = SCRLEVL_EFF_TERM
    AND SSBSECT_TERM_CODE = SIRASGN_TERM_CODE(+) AND SSBSECT_CRN = SIRASGN_CRN(+) AND SIRASGN_PRIMARY_IND(+) = 'Y'
    AND SIRASGN_PIDM = SPRIDEN_PIDM(+) AND SPRIDEN_CHANGE_IND(+) IS NULL
    AND SSBSECT_SUBJ_CODE = STVSUBJ_CODE AND SCBCRSE_DEPT_CODE = STVDEPT_CODE AND SSBSECT_CAMP_CODE = STVCAMP_CODE
    AND SSBSECT_TERM_CODE IN (SELECT DISTINCT term_code FROM LOE_SECTION_PART_OF_TERM
                            WHERE start_date <= SYSDATE +7 AND end_date >= SYSDATE -16);
