
Enrollment Status Description
Enrollment Status Code
SIS Term Key
SIS Course Key
SIS Student Key 
Credits Attempted
Credits Earned
Grade Points
Has Course Grade
Is Enrolled
Is Dropped
Is Pass
Is Failed
Academic Level
Institution

SELECT DISTINCT
    f.STVRSTS_DESC AS ENROLLMENT_STATUS_DESCRIPTION
    , a.SFRSTCR_RSTS_CODE AS ENROLLMENT_STATUS_CODE
    , a.SFRSTCR_TERM_CODE AS SIS_TERM_KEY
    , a.SFRSTCR_TERM_CODE ||'.'|| a.SFRSTCR_CRN AS SIS_COURSE_KEY
    , e.SPRIDEN_ID AS SIS_STUDENT_KEY
    , a.SFRSTCR_CREDIT_HR AS CREDITS_ATTEMPTED
    , CASE WHEN a.SFRSTCR_RSTS_CODE IN ('RE','RW','RA') THEN 1 ELSE 0 END AS IS_ENROLLED
    , CASE WHEN a.SFRSTCR_RSTS_CODE NOT IN ('RE','RW','RA') THEN 1 ELSE 0 END AS IS_DROPPED
    , a.SFRSTCR_LEVL_CODE AS ACADEMIC_LEVEL
    , 'UPN' AS INSTITUTION
FROM SFRSTCR a, 
     SHRTCKN b, 
     SHRTCKG c, 
     SHRGRDE d, 
     SPRIDEN e, 
     STVRSTS f
WHERE a.SFRSTCR_TERM_CODE = b.SHRTCKN_TERM_CODE(+) AND a.SFRSTCR_CRN = b.SHRTCKN_CRN(+) AND a.SFRSTCR_PIDM = b.SHRTCKN_PIDM(+)
    AND b.SHRTCKN_PIDM = c.SHRTCKG_PIDM AND b.SHRTCKN_TERM_CODE = c.SHRTCKG_TERM_CODE AND b.SHRTCKN_SEQ_NO = c.SHRTCKG_TCKN_SEQ_NO
    AND a.SFRSTCR_PIDM = e.SPRIDEN_PIDM AND e.SPRIDEN_CHANGE_IND IS NULL
    AND a.SFRSTCR_RSTS_CODE = f.STVRSTS_CODE(+);



SELECT * FROM SFRSTCR
WHERE SFRSTCR_TERM_CODE LIKE '218%'

SELECT * FROM SHRTCKN
WHERE SHRTCKN_TERM_CODE LIKE '218%'

SELECT * FROM SHRTCKG
WHERE SHRTCKG_TERM_CODE LIKE '218%'

SELECT * FROM SHRGRDE
