--SISMatrEstudBanner.sql
SELECT CAST(A.SFRSTCR_TERM_CODE AS VARCHAR(20)) AS "SISPeriodo"
	, CAST(SFRSTCR_CAMP_CODE AS VARCHAR(20)) AS "SISCampusSeccion"
	, CAST(B.SSBSECT_SUBJ_CODE ||'.'|| B.SSBSECT_CRSE_NUMB ||'.'|| A.SFRSTCR_TERM_CODE ||'.'|| A.SFRSTCR_CRN
			||'.'|| CASE WHEN B.SSBSECT_SCHD_CODE = 'VIR' OR B.ssbsect_insm_code = 'V' THEN 'V' ELSE 'P' END AS VARCHAR(50)) AS "SISSeccion"
	, CASE WHEN SUBSTR(E.AREA_COURSE,LENGTH(E.AREA_COURSE)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
			THEN TO_NUMBER(SUBSTR(E.AREA_COURSE,LENGTH(E.AREA_COURSE)-1)) END AS "SISCicloCurso"
	, CAST(C.SPRIDEN_ID AS VARCHAR(20)) AS "SISCodEstudiante"
	, COALESCE(F.COURSE_COUNT,0) +1 AS "SISVezMatCurso"
	, CAST(TO_CHAR(A.SFRSTCR_ADD_DATE,'YYYY-MM-DD HH24:MI:SS') AS VARCHAR(50)) AS "SISFechaMatricula"
	, CAST(G.SOVLCUR_CAMP_CODE AS VARCHAR(20)) AS "SISCampusEstudiante"
	, CAST(G.SOVLCUR_PROGRAM AS VARCHAR(20)) AS "SISCodProgEstudiante"
	, CAST(H.SMRPRLE_PROGRAM_DESC AS VARCHAR(100)) AS "SISProgrEstudiante"
	, CAST(MAX(I.SPRTELE_PHONE_NUMBER) AS VARCHAR(200)) AS "SISMovilEstudiante"
	, CAST(MAX(J.GOREMAL_EMAIL_ADDRESS) AS VARCHAR(200)) AS "SISEmailPersEstudiante"
FROM ODSMGR.SFRSTCR A
		INNER JOIN ODSMGR.LOE_SSBSECT B ON A.SFRSTCR_TERM_CODE = B.SSBSECT_TERM_CODE AND A.SFRSTCR_CRN = B.SSBSECT_CRN
		INNER JOIN ODSMGR.LOE_SPRIDEN C ON A.SFRSTCR_PIDM = C.SPRIDEN_PIDM AND C.SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN ODSMGR.SSRATTR D ON B.SSBSECT_TERM_CODE = D.SSRATTR_TERM_CODE AND B.SSBSECT_CRN = D.SSRATTR_CRN
		LEFT JOIN ODSMGR.LOE_AREA_COURSE E ON B.SSBSECT_SUBJ_CODE = E.SUBJ_CODE AND B.SSBSECT_CRSE_NUMB = E.CRSE_NUMB_LOW AND D.SSRATTR_ATTR_CODE = SUBSTR(E.AREA_COURSE,1,4)
													AND E.TERM_CODE_EFF = (SELECT MAX(E1.TERM_CODE_EFF) FROM ODSMGR.LOE_AREA_COURSE E1
																			WHERE E1.SUBJ_CODE = E.SUBJ_CODE AND E1.CRSE_NUMB_LOW = E.CRSE_NUMB_LOW
																				AND SUBSTR(E1.AREA_COURSE,1,4) = SUBSTR(E.AREA_COURSE,1,4))
		LEFT JOIN ODSMGR.LOE_REPEAT_COURSE_CRN F ON A.SFRSTCR_PIDM = F.SFRSTCR_PIDM AND A.SFRSTCR_TERM_CODE = F.SFRSTCR_TERM_CODE
													AND B.SSBSECT_SUBJ_CODE = F.SSBSECT_SUBJ_CODE AND B.SSBSECT_CRSE_NUMB = F.SSBSECT_CRSE_NUMB
		LEFT JOIN ODSMGR.LOE_SOVLCUR G ON A.SFRSTCR_PIDM = G.SOVLCUR_PIDM AND G.SOVLCUR_LEVL_CODE = 'UG'
													AND G.SOVLCUR_LMOD_CODE = 'LEARNER' AND G.SOVLCUR_CACT_CODE = 'ACTIVE' AND G.SOVLCUR_CURRENT_IND = 'Y'
		LEFT JOIN ODSMGR.SMRPRLE H ON G.SOVLCUR_PROGRAM = H.SMRPRLE_PROGRAM
		LEFT JOIN ODSMGR.SPRTELE I ON A.SFRSTCR_PIDM = I.SPRTELE_PIDM AND I.SPRTELE_TELE_CODE = 'CP'
													AND I.SPRTELE_ACTIVITY_DATE = (SELECT MAX(I1.SPRTELE_ACTIVITY_DATE) FROM ODSMGR.SPRTELE I1
																					WHERE I1.SPRTELE_PIDM = I.SPRTELE_PIDM AND I1.SPRTELE_TELE_CODE = 'CP')
		LEFT JOIN ODSMGR.GOREMAL J ON A.SFRSTCR_PIDM = J.GOREMAL_PIDM AND J.GOREMAL_STATUS_IND = 'A' AND J.GOREMAL_EMAL_CODE = 'PERS'
													AND J.GOREMAL_ACTIVITY_DATE = (SELECT MAX(J1.GOREMAL_ACTIVITY_DATE) FROM ODSMGR.GOREMAL J1
																					WHERE J1.GOREMAL_PIDM = J.GOREMAL_PIDM
																						AND J1.GOREMAL_STATUS_IND = 'A' AND J1.GOREMAL_EMAL_CODE = 'PERS')
WHERE A.SFRSTCR_RSTS_CODE IN ('RW','RE','RA') AND B.SSBSECT_SUBJ_CODE NOT IN ('ACAD','REPS','TEST','XPEN','XSER')
	AND A.SFRSTCR_TERM_CODE IN (SELECT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM
								WHERE CURRENT_DATE BETWEEN TO_DATE(START_DATE) -7 AND TO_DATE(END_DATE) +16
									AND SUBSTR(TERM_CODE,4,1) IN ('3','4','5'))
GROUP BY A.SFRSTCR_TERM_CODE
	, SFRSTCR_CAMP_CODE
	, B.SSBSECT_SUBJ_CODE ||'.'|| B.SSBSECT_CRSE_NUMB ||'.'|| A.SFRSTCR_TERM_CODE ||'.'|| A.SFRSTCR_CRN
			||'.'|| CASE WHEN B.SSBSECT_SCHD_CODE = 'VIR' OR B.ssbsect_insm_code = 'V' THEN 'V' ELSE 'P' END
	, CASE WHEN SUBSTR(E.AREA_COURSE,LENGTH(E.AREA_COURSE)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
			THEN TO_NUMBER(SUBSTR(E.AREA_COURSE,LENGTH(E.AREA_COURSE)-1)) END
	, C.SPRIDEN_ID
	, COALESCE(F.COURSE_COUNT,0) +1
	, TO_CHAR(A.SFRSTCR_ADD_DATE,'YYYY-MM-DD HH24:MI:SS')
	, G.SOVLCUR_CAMP_CODE
	, G.SOVLCUR_PROGRAM
	, H.SMRPRLE_PROGRAM_DESC;
