SELECT DISTINCT
    g.PERSON_UID, g.ID, g.NAME, g.ACADEMIC_STUDY_VALUE, g.ACADEMIC_PERIOD, g.CAMPUS, g.PROGRAM, g.PROGRAM_DESC, g.COMPUTATION_DATE, g.GPA, g.CREDITOS_APROBADOS
    , CASE WHEN g.POSICION >= MIN(CASE WHEN g.GPA = g.GPA_PIVOT THEN g.POSICION ELSE 99 END) OVER(PARTITION BY g.ACADEMIC_PERIOD,g.PROGRAM)
        THEN MIN(CASE WHEN g.GPA = g.GPA_PIVOT THEN g.POSICION ELSE 99 END) OVER(PARTITION BY g.ACADEMIC_PERIOD,g.PROGRAM) ELSE g.POSICION END AS POSICION
    , SUM(CASE WHEN h.DUE_DT < SYSDATE THEN h.BAL_AMT ELSE 0 END) OVER(PARTITION BY h.CUST_ID) AS DEUDA
FROM
    (SELECT DISTINCT
        f.PERSON_UID, f.ID, f.NAME, f.ACADEMIC_STUDY_VALUE, f.ACADEMIC_PERIOD, f.CAMPUS, f.PROGRAM, f.PROGRAM_DESC
        , f.COMPUTATION_DATE, f.GPA, f.CREDITOS_APROBADOS, f.POSICION--, f.CURRICULUM_CHANGE_REASON
        , MAX(CASE WHEN f.POSICION = 5 THEN f.GPA ELSE NULL END) OVER(PARTITION BY f.ACADEMIC_PERIOD,f.PROGRAM) AS GPA_PIVOT
    FROM
        (SELECT DISTINCT
            a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_STUDY_VALUE, a.ACADEMIC_PERIOD, d.CAMPUS, d.PROGRAM, d.PROGRAM_DESC
            , a.COMPUTATION_DATE, ROUND(a.GPA,2) AS GPA, c.CREDITOS_APROBADOS, e.CURRICULUM_CHANGE_REASON
            , COUNT(a.PERSON_UID) 
                OVER(PARTITION BY a.ACADEMIC_PERIOD,d.PROGRAM ORDER BY a.ACADEMIC_PERIOD,d.PROGRAM,ROUND(a.GPA,2)DESC 
                  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS POSICION
        FROM 
            ((GPA_BY_TERM a
                INNER JOIN (SELECT DISTINCT
                                b.SHRTCKG_PIDM, b.SHRTCKG_TERM_CODE
                                , SUM(b.SHRTCKG_CREDIT_HOURS) OVER(PARTITION BY b.SHRTCKG_PIDM,b.SHRTCKG_TERM_CODE) AS CREDITOS_APROBADOS
                            FROM SHRTCKG b
                            WHERE b.SHRTCKG_SEQ_NO = (SELECT MAX(b_max.SHRTCKG_SEQ_NO) FROM SHRTCKG b_max
                                    WHERE b.SHRTCKG_PIDM = b_max.SHRTCKG_PIDM AND b.SHRTCKG_TERM_CODE = b_max.SHRTCKG_TERM_CODE
                                        AND b.SHRTCKG_TCKN_SEQ_NO = b_max.SHRTCKG_TCKN_SEQ_NO)
                                AND b.SHRTCKG_GMOD_CODE = 'S' AND b.SHRTCKG_GRDE_CODE_FINAL IN ('12','13','14','15','16','17','18','19','20')) c ON
                    a.PERSON_UID = c.SHRTCKG_PIDM
                    AND a.ACADEMIC_PERIOD = c.SHRTCKG_TERM_CODE)
                LEFT JOIN ACADEMIC_STUDY d ON
                    a.PERSON_UID = d.PERSON_UID
                    AND a.ACADEMIC_STUDY_VALUE = d.STUDENT_LEVEL
                    AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD)
                LEFT JOIN (SELECT DISTINCT
                                PERSON_UID, ID, NAME, CURRICULUM_PRIORITY, CURRICULUM_CURRENT_IND, CURRICULUM_ACTIVE_IND, SOURCE
                                , STUDENT_LEVEL, CAMPUS, PROGRAM, ACADEMIC_PERIOD, CURRICULUM_CHANGE_REASON
                                , MAX(ACADEMIC_PERIOD) OVER(PARTITION BY PERSON_UID,PROGRAM,SOURCE,CURRICULUM_CHANGE_REASON) AS MAX_PERIODO
                            FROM FIELD_OF_STUDY
                            WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO') e ON
                    a.PERSON_UID = e.PERSON_UID
                    AND a.ACADEMIC_STUDY_VALUE = e.STUDENT_LEVEL
                    AND d.PROGRAM = e.PROGRAM
                    AND e.ACADEMIC_PERIOD = e.MAX_PERIODO
        WHERE a.GPA_TYPE = 'I' AND c.CREDITOS_APROBADOS >= 20 AND a.GPA > 0 AND a.ACADEMIC_STUDY_VALUE = 'UG' AND a.ACADEMIC_PERIOD = '218413'
            AND e.CURRICULUM_CHANGE_REASON IS NULL) f) g
        LEFT JOIN PS_ITEM h ON
            g.ID = h.CUST_ID
            AND h.BUSINESS_UNIT = 'PER03'
WHERE g.GPA >= g.GPA_PIVOT
ORDER BY 5,7,12,3;
