
SELECT DISTINCT
    a.PERSON_UID AS PIDM, b.SPRIDEN_ID AS ID, b.SPRIDEN_LAST_NAME AS APELLIDOS, b.SPRIDEN_FIRST_NAME AS NOMBRES
    , a.CAMP_CODE AS CAMPUS, a.PROGRAM AS COD_PROGRAMA, c.SMRPRLE_PROGRAM_DESC AS PROGRAMA, a.LEVL_CODE AS NIVEL, a.CREDITOS_REQUERIDOS
    , a.CREDITOS_RECONOCIDOS, a.PERIODO_HST, a.CURSO_HST, a.NOTA_HST, a.PERIODO_ACTUAL, a.CURSO_ACTUAL, a.CLASE_ACTUAL
FROM (SELECT DISTINCT
          a.PERSON_UID, a.PROGRAM, a.LEVL_CODE, a.CAMP_CODE, a.REQ_CREDITS_OVERALL AS CREDITOS_REQUERIDOS
          , a.ACT_CREDITS_OVERALL AS CREDITOS_RECONOCIDOS, c.ACADEMIC_PERIOD AS PERIODO_HST, d.SHRTCKN_CRSE_TITLE AS CURSO_HST, c.FINAL_GRADE AS NOTA_HST
          , e.ACADEMIC_PERIOD AS PERIODO_ACTUAL, e.COURSE_TITLE_SHORT AS CURSO_ACTUAL, e.COURSE_REFERENCE_NUMBER AS CLASE_ACTUAL
          , CASE WHEN c.ACADEMIC_PERIOD IS NULL AND e.ACADEMIC_PERIOD IS NULL THEN 'OCULTAR' ELSE NULL END AS OCULTAR
      FROM (SELECT
                PERSON_UID, SEQUENCE_NUMBER, MAX(SEQUENCE_NUMBER) OVER(PARTITION BY PERSON_UID,PROGRAM) AS MAX_SEQ
                , PROGRAM, LEVL_CODE, CAMP_CODE, ACTIVITY_DATE, REQ_CREDITS_OVERALL
                , ACT_CREDITS_OVERALL
            FROM LOE_PROGRAM_OVERALL_RESULTS
            WHERE PROGRAM <> 'PREREQ' AND LEVL_CODE = 'UG') a, 
            FIELD_OF_STUDY b, 
            STUDENT_COURSE_GRADE_CHANGE c, 
            SHRTCKN d, 
            STUDENT_COURSE e
      WHERE a.PERSON_UID = b.PERSON_UID(+) AND a.PROGRAM = b.PROGRAM(+) AND a.LEVL_CODE = b.STUDENT_LEVEL(+)
              AND b.SOURCE(+) = 'OUTCOME' AND b.CURRICULUM_CHANGE_REASON(+) = 'EGRESADO'
          AND a.PERSON_UID = c.PERSON_UID(+) AND c.ACADEMIC_PERIOD(+) IN ('218413','218512','218434','218533')
              AND c.SUBJECT(+) = 'INVE' AND c.COURSE_NUMBER(+) IN ('1503','1503A','1508','1522','1532','1626' --UG
                                                                  ,'1611','1626','1628W','2502','2504') --WA
              AND c.FINAL_GRADE(+) IN ('12','13','14','15','16','17','18','19','20')
          AND a.PERSON_UID = d.SHRTCKN_PIDM(+) AND c.ACADEMIC_PERIOD = d.SHRTCKN_TERM_CODE(+)
              AND c.SUBJECT = d.SHRTCKN_SUBJ_CODE(+) AND c.COURSE_NUMBER = d.SHRTCKN_CRSE_NUMB(+) AND c.COURSE_REFERENCE_NUMBER = d.SHRTCKN_CRN(+)
          AND a.PERSON_UID = e.PERSON_UID(+) AND e.ACADEMIC_PERIOD(+) IN ('219402','219501')
              AND e.SUBJECT(+) = 'INVE' AND e.COURSE_NUMBER(+) IN ('1503','1503A','1508','1522','1532','1626' --UG
                                                                  ,'1611','1626','1628W','2502','2504') --WA
          AND a.SEQUENCE_NUMBER = a.MAX_SEQ AND b.PERSON_UID IS NULL) a,
      SPRIDEN b, 
      SMRPRLE c
WHERE a.PERSON_UID = b.SPRIDEN_PIDM AND b.SPRIDEN_CHANGE_IND IS NULL
    AND a.PROGRAM = c.SMRPRLE_PROGRAM(+)
    AND a.CREDITOS_REQUERIDOS -20 <= a.CREDITOS_RECONOCIDOS AND a.OCULTAR IS NULL
ORDER BY 5,6,1;

