SELECT DISTINCT
    f.PERSON_UID, f.ID, f.NAME, f.ACADEMIC_STUDY_VALUE, f.ACADEMIC_PERIOD, f.CAMPUS, f.PROGRAM, f.PROGRAM_DESC
    , f.COMPUTATION_DATE, ROUND(f.GPA,2) AS GPA, f.CREDITOS_APROBADOS, f.CURRICULUM_CHANGE_REASON
    , SUM(CASE WHEN g.DUE_DT < SYSDATE THEN g.BAL_AMT ELSE 0 END) OVER(PARTITION BY g.CUST_ID) AS DEUDA
FROM
    (SELECT DISTINCT
        a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_STUDY_VALUE, a.ACADEMIC_PERIOD, d.CAMPUS, d.PROGRAM, d.PROGRAM_DESC, a.COMPUTATION_DATE, a.GPA, c.CREDITOS_APROBADOS, e.CURRICULUM_CHANGE_REASON
        , MAX(a.GPA) OVER (PARTITION BY a.ACADEMIC_PERIOD,d.CAMPUS,d.PROGRAM) AS GPA_PROGRAMA
    FROM 
        ((GPA_BY_TERM a
            INNER JOIN (SELECT DISTINCT
                            b.SHRTCKG_PIDM, b.SHRTCKG_TERM_CODE
                            , SUM(b.SHRTCKG_CREDIT_HOURS) OVER(PARTITION BY b.SHRTCKG_PIDM,b.SHRTCKG_TERM_CODE) AS CREDITOS_APROBADOS
                        FROM SHRTCKG b
                        WHERE b.SHRTCKG_SEQ_NO = (SELECT MAX(b_max.SHRTCKG_SEQ_NO) FROM SHRTCKG b_max
                                WHERE b.SHRTCKG_PIDM = b_max.SHRTCKG_PIDM AND b.SHRTCKG_TERM_CODE = b_max.SHRTCKG_TERM_CODE AND b.SHRTCKG_TCKN_SEQ_NO = b_max.SHRTCKG_TCKN_SEQ_NO)
                            AND b.SHRTCKG_GMOD_CODE = 'S' AND b.SHRTCKG_GRDE_CODE_FINAL IN ('12','13','14','15','16','17','18','19','20')) c ON
                a.PERSON_UID = c.SHRTCKG_PIDM
                AND a.ACADEMIC_PERIOD = c.SHRTCKG_TERM_CODE)
            LEFT JOIN ACADEMIC_STUDY d ON
                a.PERSON_UID = d.PERSON_UID
                AND a.ACADEMIC_STUDY_VALUE = d.STUDENT_LEVEL
                AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD)
            LEFT JOIN (SELECT DISTINCT
                            PERSON_UID, ID, NAME, CURRICULUM_PRIORITY, CURRICULUM_CURRENT_IND, CURRICULUM_ACTIVE_IND, SOURCE, STUDENT_LEVEL, CAMPUS, PROGRAM, ACADEMIC_PERIOD, CURRICULUM_CHANGE_REASON
                            , MAX(ACADEMIC_PERIOD) OVER(PARTITION BY PERSON_UID,PROGRAM,SOURCE,CURRICULUM_CHANGE_REASON) AS MAX_PERIODO
                        FROM FIELD_OF_STUDY
                        WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO') e ON
                a.PERSON_UID = e.PERSON_UID
                AND a.ACADEMIC_STUDY_VALUE = e.STUDENT_LEVEL
                AND d.PROGRAM = e.PROGRAM
                AND e.ACADEMIC_PERIOD = e.MAX_PERIODO
    WHERE a.GPA_TYPE = 'I' AND a.ACADEMIC_STUDY_VALUE = 'UG' AND c.CREDITOS_APROBADOS >= 20 AND e.CURRICULUM_CHANGE_REASON IS NULL) f
        LEFT JOIN PS_ITEM g ON
            f.ID = g.CUST_ID
            AND g.BUSINESS_UNIT = 'PER03'
WHERE f.GPA = f.GPA_PROGRAMA AND f.GPA > 0 AND f.ACADEMIC_PERIOD = '217434'
ORDER BY 5,6,7,3;
