SELECT DISTINCT
    g.PERSON_UID, g.ID, g.NAME, g.ACADEMIC_STUDY_VALUE, g.ACADEMIC_PERIOD, g.CAMPUS, g.PROGRAM, g.PROGRAM_DESC
    , g.PERIODO_ADMISION, g.CREDITOS_MALLA, g.COMPUTATION_DATE, g.GPA, g.CREDITOS_APROBADOS
    , MIN(g.POSICION) OVER(PARTITION BY g.ACADEMIC_PERIOD,g.CAMPUS,g.PROGRAM,g.GPA) AS POSICION
    , SUM(CASE WHEN h.DUE_DT < SYSDATE THEN h.BAL_AMT ELSE 0 END) OVER(PARTITION BY h.CUST_ID) AS DEUDA
FROM
    (SELECT DISTINCT
        f.PERSON_UID, f.ID, f.NAME, f.ACADEMIC_STUDY_VALUE, f.ACADEMIC_PERIOD, f.CAMPUS, f.PROGRAM, f.PROGRAM_DESC
        , f.PERIODO_ADMISION, f.CREDITOS_MALLA , f.COMPUTATION_DATE, f.GPA, f.CREDITOS_APROBADOS, f.POSICION--, f.CURRICULUM_CHANGE_REASON
        , MAX(CASE WHEN f.POSICION = 5 THEN f.GPA ELSE 0 END) OVER(PARTITION BY f.ACADEMIC_PERIOD,f.CAMPUS,f.PROGRAM) AS GPA_PIVOT
    FROM
        (SELECT DISTINCT
            a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_STUDY_VALUE, a.ACADEMIC_PERIOD            
            , d.CAMPUS, d.PROGRAM, d.PROGRAM_DESC
            , CASE WHEN d.STUDENT_POPULATION = 'N' AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD_ADMITTED
                  THEN d.ACADEMIC_PERIOD_ADMITTED ELSE NULL END AS PERIODO_ADMISION
            , CASE WHEN d.STUDENT_POPULATION = 'N' AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD_ADMITTED
                  THEN f.REQ_CREDITS_OVERALL ELSE NULL END AS CREDITOS_MALLA
            , a.COMPUTATION_DATE, ROUND(a.GPA,2) AS GPA, c.CREDITOS_APROBADOS, e.CURRICULUM_CHANGE_REASON
            , COUNT(a.PERSON_UID) 
                OVER(PARTITION BY a.ACADEMIC_PERIOD,d.CAMPUS,d.PROGRAM ORDER BY a.ACADEMIC_PERIOD,d.CAMPUS,d.PROGRAM,ROUND(a.GPA,2)DESC 
                  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS POSICION
        FROM 
            ((GPA_BY_TERM a
                INNER JOIN (SELECT DISTINCT
                                b.SHRTCKG_PIDM, b.SHRTCKG_TERM_CODE
                                , SUM(b.SHRTCKG_CREDIT_HOURS) OVER(PARTITION BY b.SHRTCKG_PIDM,b.SHRTCKG_TERM_CODE) AS CREDITOS_APROBADOS
                            FROM SHRTCKG b
                            WHERE b.SHRTCKG_SEQ_NO = (SELECT MAX(b_max.SHRTCKG_SEQ_NO) FROM SHRTCKG b_max
                                    WHERE b.SHRTCKG_PIDM = b_max.SHRTCKG_PIDM AND b.SHRTCKG_TERM_CODE = b_max.SHRTCKG_TERM_CODE
                                        AND b.SHRTCKG_TCKN_SEQ_NO = b_max.SHRTCKG_TCKN_SEQ_NO)
                                AND b.SHRTCKG_GMOD_CODE = 'S' AND b.SHRTCKG_GRDE_CODE_FINAL IN ('12','13','14','15','16','17','18','19','20')) c ON
                    a.PERSON_UID = c.SHRTCKG_PIDM
                    AND a.ACADEMIC_PERIOD = c.SHRTCKG_TERM_CODE)
                LEFT JOIN ACADEMIC_STUDY d ON
                    a.PERSON_UID = d.PERSON_UID
                    AND a.ACADEMIC_STUDY_VALUE = d.STUDENT_LEVEL
                    AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD)
                LEFT JOIN (SELECT DISTINCT
                                PERSON_UID, ID, NAME, CURRICULUM_PRIORITY, CURRICULUM_CURRENT_IND, CURRICULUM_ACTIVE_IND, SOURCE
                                , STUDENT_LEVEL, CAMPUS, PROGRAM, ACADEMIC_PERIOD, CURRICULUM_CHANGE_REASON
                                , MAX(ACADEMIC_PERIOD) OVER(PARTITION BY PERSON_UID,PROGRAM,SOURCE,CURRICULUM_CHANGE_REASON) AS MAX_PERIODO
                            FROM FIELD_OF_STUDY
                            WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO') e ON
                    a.PERSON_UID = e.PERSON_UID
                    AND a.ACADEMIC_STUDY_VALUE = e.STUDENT_LEVEL
                    AND d.PROGRAM = e.PROGRAM
                    AND e.ACADEMIC_PERIOD = e.MAX_PERIODO
                LEFT JOIN (SELECT AREA, TERM_CODE_EFF, ACTIVITY_DATE, REQ_CREDITS_OVERALL
                              , MAX(TERM_CODE_EFF) OVER(PARTITION BY AREA) AS MAX_TERM
                          FROM LOE_GENERAL_AREA_REQ WHERE SUBSTR(AREA,LENGTH(AREA)-1) = '01') f ON
                    d.MAJOR = SUBSTR(f.AREA,1,4)
                    AND f.TERM_CODE_EFF = f.MAX_TERM
        WHERE a.GPA_TYPE = 'I' AND a.GPA > 0 AND e.CURRICULUM_CHANGE_REASON IS NULL
            AND (c.CREDITOS_APROBADOS >= 20
                  OR c.CREDITOS_APROBADOS >= CASE WHEN d.STUDENT_POPULATION = 'N' AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD_ADMITTED
                      THEN f.REQ_CREDITS_OVERALL ELSE 20 END)
            AND a.ACADEMIC_STUDY_VALUE = 'UG' AND a.ACADEMIC_PERIOD = '218413') f) g
        LEFT JOIN PS_ITEM h ON
            g.ID = h.CUST_ID
            AND h.BUSINESS_UNIT = 'PER03'
WHERE g.GPA >= g.GPA_PIVOT
ORDER BY 5,6,7,14,3;
