--AC039
WITH AUDIT_REGISTRO AS (
	SELECT PERSON_UID, ID, NAME, ACADEMIC_PERIOD, MIN(SECTION_ADD_DATE) AS SECTION_ADD_DATE
	FROM ODSMGR.STUDENT_COURSE_REG_AUDIT
	WHERE REGISTRATION_SOURCE = 'BASE'
	GROUP BY PERSON_UID, ID, NAME, ACADEMIC_PERIOD
)
SELECT X.PERSON_UID, X.SPRIDEN_ID, X.NOMBRE_ESTUDIANTE, X.ACADEMIC_PERIOD, X.PROGRAM, X.PROGRAM_DESC, X.CAMPUS_DESC, X.FECHA_1ER_REGISTRO_CURSOS, X.FECHA_ULT_REGISTRO_CURSOS
	, X.TIPO_ESTUDIANTE, X.CREDITOS, X.CURSOS, X.TIPO_ESTUDIANTE_V2
FROM (
	SELECT DISTINCT
	    A.PERSON_UID, F.SPRIDEN_ID, CONCAT(F.SPRIDEN_LAST_NAME,CONCAT(', ',F.SPRIDEN_FIRST_NAME)) AS NOMBRE_ESTUDIANTE, A.ACADEMIC_PERIOD, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC
	    , B0.SECTION_ADD_DATE AS FECHA_1ER_REGISTRO_CURSOS
	    , MAX(B.SECTION_ADD_DATE) OVER(PARTITION BY B.PERSON_UID,B.ACADEMIC_PERIOD) AS FECHA_ULT_REGISTRO_CURSOS
		, CASE A.STUDENT_POPULATION
			WHEN 'N' THEN 
				CASE 
					WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
					WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
					WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
					ELSE 'Nuevo' END
			WHEN 'C' THEN 
				CASE 
					WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
					WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
					WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
					WHEN A.ADMISSIONS_POPULATION <> 'RE' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
					WHEN E.ACTIVITY = 'DTO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Doble Titulacion OUT'
					WHEN E.ACTIVITY = 'ITO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
					ELSE 'Continuo' END
			ELSE A.STUDENT_POPULATION END AS TIPO_ESTUDIANTE
	    , SUM(B.COURSE_CREDITS) OVER(PARTITION BY B.PERSON_UID,B.ACADEMIC_PERIOD) AS CREDITOS
	    , COUNT(B.COURSE_REFERENCE_NUMBER) OVER(PARTITION BY B.PERSON_UID,B.ACADEMIC_PERIOD) AS CURSOS
	    , MAX(CASE WHEN B.SUBJECT = 'XSER' THEN B.SUBJECT END) OVER(PARTITION BY B.PERSON_UID,B.ACADEMIC_PERIOD) AS MATERIA_XSER
	    , CASE WHEN T.SHRTCKN_PIDM IS NULL THEN 'Nuevo' ELSE T.TIPO_ESTUDIANTE END AS TIPO_ESTUDIANTE_V2
	FROM ODSMGR.ACADEMIC_STUDY A
			INNER JOIN ODSMGR.STUDENT_COURSE B ON A.PERSON_UID = B.PERSON_UID AND A.ACADEMIC_PERIOD = B.ACADEMIC_PERIOD AND B.TRANSFER_COURSE_IND = 'N' AND B.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF','RO','IA')
			LEFT JOIN AUDIT_REGISTRO B0 ON A.PERSON_UID = B0.PERSON_UID AND A.ACADEMIC_PERIOD = B0.ACADEMIC_PERIOD
	     	LEFT JOIN ODSMGR.STUDENT_COHORT C ON A.PERSON_UID = C.PERSON_UID AND A.ACADEMIC_PERIOD = C.ACADEMIC_PERIOD AND C.COHORT_ACTIVE_IND = 'Y' AND C.COHORT IN ('NEW_REING','REINGRESO')
	     	LEFT JOIN ODSMGR.STUDENT_ATTRIBUTE D ON A.PERSON_UID = D.PERSON_UID AND A.ACADEMIC_PERIOD = D.ACADEMIC_PERIOD AND D.STUDENT_ATTRIBUTE IN ('TINT')
	     	LEFT JOIN ODSMGR.STUDENT_ACTIVITY E ON A.PERSON_UID = E.PERSON_UID AND A.ACADEMIC_PERIOD = E.ACADEMIC_PERIOD AND E.ACTIVITY = 'ITO'
	     	LEFT JOIN ODSMGR.LOE_SPRIDEN F ON A.PERSON_UID = F.SPRIDEN_PIDM AND F.SPRIDEN_CHANGE_IND IS NULL
	     	LEFT JOIN ODSMGR.LOE_TIPO_ESTUDIANTE T ON A.PERSON_UID = T.SHRTCKN_PIDM AND A.ACADEMIC_PERIOD = T.PERIODO_ACTUAL
	WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND A.STUDENT_LEVEL = 'UG' AND A.ACADEMIC_PERIOD IN ('221413','221513') --AND A.PERSON_UID = 264469
	) X
WHERE X.MATERIA_XSER IS NULL
;