
SELECT DISTINCT
    a.PERSON_UID, f.ID, CONCAT(f.LAST_NAME,CONCAT(', ',f.FIRST_NAME)) AS NOMBRE_ESTUDIANTE
    , a.ACADEMIC_PERIOD, a.PROGRAM, a.PROGRAM_DESC, a.CAMPUS_DESC
    , MIN(b.SECTION_ADD_DATE) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS FECHA_REGISTRO_CURSOS
    , CASE g.SORLCUR_STYP_CODE WHEN 'N' THEN 'NUEVO' ELSE 'CONTINUO' END AS TIPO_ESTUDIANTE
    /*, SUM(b.COURSE_CREDITS) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS CREDITOS
    , COUNT(b.COURSE_REFERENCE_NUMBER) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS CURSOS*/
FROM ACADEMIC_STUDY a, 
     STUDENT_COURSE b,      
     PERSON_DETAIL f, 
     SORLCUR g
WHERE a.PERSON_UID = b.PERSON_UID AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD    
        AND b.TRANSFER_COURSE_IND = 'N' AND b.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF')    
    AND a.PERSON_UID = f.PERSON_UID
    AND a.PERSON_UID = g.SORLCUR_PIDM(+) AND a.ACADEMIC_PERIOD = g.SORLCUR_TERM_CODE(+)
        AND g.SORLCUR_CACT_CODE = 'ACTIVE'
    AND a.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND a.STUDENT_LEVEL = 'CR' AND a.ACADEMIC_PERIOD IN ('219703','219704');
