SELECT DISTINCT
    SHRTCKG_PIDM
    , SHRTCKG_TERM_CODE
    , SHRTCKN_SEQ_NO
    , SHRTCKN_CAMP_CODE
    , SHRTCKN_CRN
    , SHRTCKN_SUBJ_CODE
    , SHRTCKN_CRSE_NUMB
    , SHRTCKN_CRSE_TITLE
    , SHRTCKG_SEQ_NO
    , MAX(SHRTCKG_SEQ_NO) OVER(PARTITION BY SHRTCKG_PIDM ,SHRTCKG_TERM_CODE, SHRTCKG_TCKN_SEQ_NO) AS MAX_SEQ
    , SHRTCKG_GRDE_CODE_FINAL
    , SHRTCKG_CREDIT_HOURS
    , SHRTCKG_GCHG_CODE
    , STVGCHG_DESC
    , SHRTCKG_ACTIVITY_DATE
    , SHRTCKG_FINAL_GRDE_CHG_USER
    , SUBSTR(SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
    , TO_DATE(TO_CHAR(MAX(SHRTCKG_ACTIVITY_DATE) OVER(PARTITION BY SHRTCKG_PIDM ,SHRTCKG_TERM_CODE, SHRTCKG_TCKN_SEQ_NO),'DD/MM/YYYY'),'DD/MM/YYYY') AS MAX_FECHA
FROM 
    SHRTCKG
        LEFT JOIN STVGCHG ON
            SHRTCKG_GCHG_CODE = STVGCHG_CODE
    , SHRTCKN
WHERE SHRTCKG_PIDM = SHRTCKN_PIDM
    AND SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
    AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
    AND (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
            WHERE G1.SHRTCKG_PIDM = SHRTCKN_PIDM
                AND G1.SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
                AND G1.SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO) > 1;
--7188  Filas

WITH CALIFICACIONES_NOTAS AS (
    SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO, SHRTCKN_CAMP_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE
        , SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_SEQ_NO, SHRTCKG_GRDE_CODE_FINAL
    FROM SHRTCKG, SHRTCKN
    WHERE SHRTCKG_PIDM = SHRTCKN_PIDM
        AND SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
        AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
        AND (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                WHERE G1.SHRTCKG_PIDM = SHRTCKN_PIDM
                    AND G1.SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
                    AND G1.SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO) > 1)

SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO, SHRTCKN_CAMP_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB
    , SHRTCKN_CRSE_TITLE, COUNT(SHRTCKG_SEQ_NO) OVER(PARTITION BY SHRTCKN_PIDM ,SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO ORDER BY SHRTCKG_SEQ_NO) AS SEQ
    , SHRTCKG_SEQ_NO, SHRTCKG_GRDE_CODE_FINAL, SHRTCKG_GCHG_CODE, STVGCHG_DESC, SHRTCKG_ACTIVITY_DATE, SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
    , TO_DATE(TO_CHAR(MAX(SHRTCKG_ACTIVITY_DATE) OVER(PARTITION BY SHRTCKN_PIDM ,SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO),'DD/MM/YYYY'),'DD/MM/YYYY') AS MAX_FECHA
FROM (  SELECT A.SHRTCKN_PIDM, A.SHRTCKN_TERM_CODE, A.SHRTCKN_SEQ_NO, A.SHRTCKN_CAMP_CODE, A.SHRTCKN_CRN, A.SHRTCKN_SUBJ_CODE
            , A.SHRTCKN_CRSE_NUMB, A.SHRTCKN_CRSE_TITLE, A.SHRTCKG_SEQ_NO, A.SHRTCKG_GRDE_CODE_FINAL, C.SHRTCKG_GCHG_CODE
            , STVGCHG_DESC, C.SHRTCKG_ACTIVITY_DATE, C.SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(C.SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
        FROM CALIFICACIONES_NOTAS A, CALIFICACIONES_NOTAS B, SHRTCKG C, STVGCHG
        WHERE A.SHRTCKN_PIDM = B.SHRTCKN_PIDM
                AND A.SHRTCKN_TERM_CODE = B.SHRTCKN_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = B.SHRTCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO +1 = B.SHRTCKG_SEQ_NO
                AND A.SHRTCKG_GRDE_CODE_FINAL <> B.SHRTCKG_GRDE_CODE_FINAL
                AND A.SHRTCKN_PIDM = C.SHRTCKG_PIDM
                AND A.SHRTCKN_TERM_CODE = C.SHRTCKG_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = C.SHRTCKG_TCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO = C.SHRTCKG_SEQ_NO
                AND C.SHRTCKG_GCHG_CODE = STVGCHG_CODE(+)
        UNION
        SELECT A.SHRTCKN_PIDM, A.SHRTCKN_TERM_CODE, A.SHRTCKN_SEQ_NO, A.SHRTCKN_CAMP_CODE, A.SHRTCKN_CRN, A.SHRTCKN_SUBJ_CODE
            , A.SHRTCKN_CRSE_NUMB, A.SHRTCKN_CRSE_TITLE, B.SHRTCKG_SEQ_NO, B.SHRTCKG_GRDE_CODE_FINAL, C.SHRTCKG_GCHG_CODE
            , STVGCHG_DESC, C.SHRTCKG_ACTIVITY_DATE, C.SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(C.SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
        FROM CALIFICACIONES_NOTAS A, CALIFICACIONES_NOTAS B, SHRTCKG C, STVGCHG
        WHERE A.SHRTCKN_PIDM = B.SHRTCKN_PIDM
                AND A.SHRTCKN_TERM_CODE = B.SHRTCKN_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = B.SHRTCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO +1 = B.SHRTCKG_SEQ_NO
                AND A.SHRTCKG_GRDE_CODE_FINAL <> B.SHRTCKG_GRDE_CODE_FINAL
                AND B.SHRTCKN_PIDM = C.SHRTCKG_PIDM
                AND B.SHRTCKN_TERM_CODE = C.SHRTCKG_TERM_CODE
                AND B.SHRTCKN_SEQ_NO = C.SHRTCKG_TCKN_SEQ_NO
                AND B.SHRTCKG_SEQ_NO = C.SHRTCKG_SEQ_NO
                AND C.SHRTCKG_GCHG_CODE = STVGCHG_CODE(+));

WITH CALIFICACIONES_CREDITOS AS (
    SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO, SHRTCKN_CAMP_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE
        , SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_SEQ_NO, SHRTCKG_CREDIT_HOURS
    FROM SHRTCKG, SHRTCKN
    WHERE SHRTCKG_PIDM = SHRTCKN_PIDM
        AND SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
        AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
        AND (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                WHERE G1.SHRTCKG_PIDM = SHRTCKN_PIDM
                    AND G1.SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
                    AND G1.SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO) > 1)

SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO, SHRTCKN_CAMP_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB
    , SHRTCKN_CRSE_TITLE, COUNT(SHRTCKG_SEQ_NO) OVER(PARTITION BY SHRTCKN_PIDM ,SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO ORDER BY SHRTCKG_SEQ_NO) AS SEQ
    , SHRTCKG_SEQ_NO, SHRTCKG_CREDIT_HOURS, SHRTCKG_GCHG_CODE, STVGCHG_DESC, SHRTCKG_ACTIVITY_DATE, SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
    , TO_DATE(TO_CHAR(MAX(SHRTCKG_ACTIVITY_DATE) OVER(PARTITION BY SHRTCKN_PIDM ,SHRTCKN_TERM_CODE, SHRTCKN_SEQ_NO),'DD/MM/YYYY'),'DD/MM/YYYY') AS MAX_FECHA
FROM (  SELECT A.SHRTCKN_PIDM, A.SHRTCKN_TERM_CODE, A.SHRTCKN_SEQ_NO, A.SHRTCKN_CAMP_CODE, A.SHRTCKN_CRN, A.SHRTCKN_SUBJ_CODE
            , A.SHRTCKN_CRSE_NUMB, A.SHRTCKN_CRSE_TITLE, A.SHRTCKG_SEQ_NO, A.SHRTCKG_CREDIT_HOURS, C.SHRTCKG_GCHG_CODE
            , STVGCHG_DESC, C.SHRTCKG_ACTIVITY_DATE, C.SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(C.SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
        FROM CALIFICACIONES_CREDITOS A, CALIFICACIONES_CREDITOS B, SHRTCKG C, STVGCHG
        WHERE A.SHRTCKN_PIDM = B.SHRTCKN_PIDM
                AND A.SHRTCKN_TERM_CODE = B.SHRTCKN_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = B.SHRTCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO +1 = B.SHRTCKG_SEQ_NO
                AND A.SHRTCKG_CREDIT_HOURS <> B.SHRTCKG_CREDIT_HOURS
                AND A.SHRTCKN_PIDM = C.SHRTCKG_PIDM
                AND A.SHRTCKN_TERM_CODE = C.SHRTCKG_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = C.SHRTCKG_TCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO = C.SHRTCKG_SEQ_NO
                AND C.SHRTCKG_GCHG_CODE = STVGCHG_CODE(+)
        UNION
        SELECT A.SHRTCKN_PIDM, A.SHRTCKN_TERM_CODE, A.SHRTCKN_SEQ_NO, A.SHRTCKN_CAMP_CODE, A.SHRTCKN_CRN, A.SHRTCKN_SUBJ_CODE
            , A.SHRTCKN_CRSE_NUMB, A.SHRTCKN_CRSE_TITLE, B.SHRTCKG_SEQ_NO, B.SHRTCKG_CREDIT_HOURS, C.SHRTCKG_GCHG_CODE
            , STVGCHG_DESC, C.SHRTCKG_ACTIVITY_DATE, C.SHRTCKG_FINAL_GRDE_CHG_USER, SUBSTR(C.SHRTCKG_FINAL_GRDE_CHG_USER,2) ULTIPRO
        FROM CALIFICACIONES_CREDITOS A, CALIFICACIONES_CREDITOS B, SHRTCKG C, STVGCHG
        WHERE A.SHRTCKN_PIDM = B.SHRTCKN_PIDM
                AND A.SHRTCKN_TERM_CODE = B.SHRTCKN_TERM_CODE
                AND A.SHRTCKN_SEQ_NO = B.SHRTCKN_SEQ_NO
                AND A.SHRTCKG_SEQ_NO +1 = B.SHRTCKG_SEQ_NO
                AND A.SHRTCKG_CREDIT_HOURS <> B.SHRTCKG_CREDIT_HOURS
                AND B.SHRTCKN_PIDM = C.SHRTCKG_PIDM
                AND B.SHRTCKN_TERM_CODE = C.SHRTCKG_TERM_CODE
                AND B.SHRTCKN_SEQ_NO = C.SHRTCKG_TCKN_SEQ_NO
                AND B.SHRTCKG_SEQ_NO = C.SHRTCKG_SEQ_NO
                AND C.SHRTCKG_GCHG_CODE = STVGCHG_CODE(+));
