SELECT DISTINCT
    a.CAMPUS AS COD_CAMPUS
    , a.CAMPUS_DESC AS CAMPUS
    , a.PROGRAM AS COD_PROGRAMA
    , a.PROGRAM_DESC AS PROGRAMA
    , a.STUDENT_LEVEL_DESC AS NIVEL
    , a.ACADEMIC_PERIOD_ADMITTED AS PERIODO_ADMISION
    , a.ACADEMIC_PERIOD AS PERIODO_EVALUAR
    , b.ACADEMIC_PERIOD AS ULTIMO_PERIODO
    , d.HOLD AS COD_RETENCION
    , d.HOLD_DESC AS RETENCION
    , a.PERSON_UID AS PIDM
    , e.SPRIDEN_ID AS ID_ESTUDIANTE
    , SUBSTR(e.SPRIDEN_LAST_NAME,1,INSTR(e.SPRIDEN_LAST_NAME,'/')-1) AS AP_PATERNO
    , SUBSTR(e.SPRIDEN_LAST_NAME,INSTR(e.SPRIDEN_LAST_NAME,'/')+1) AS AP_MATERNO
    , e.SPRIDEN_FIRST_NAME AS NOMBRES
    , f.SORLCUR_RATE_CODE AS TARIFA
    , k.DEUDA AS DEUDA
    , l.STATE_PROVINCE_DESC AS DEPARTAMENTO
    , l.COUNTY_DESC AS PROVINCIA
    , SUBSTR(l.CITY,INSTR(l.CITY,'/',1,2)+1) AS DISTRITO
    , l.STREET_LINE2 AS URBANIZACION
    , l.STREET_LINE1 AS DIRECCION
    , MAX(CASE WHEN m.PHONE_TYPE = 'BI' THEN m.PHONE_NUMBER_COMBINED ELSE NULL END) 
        OVER(PARTITION BY m.ENTITY_UID) AS TELEFONO_ESTUDIANTE
    , MAX(CASE WHEN m.PHONE_TYPE = 'BI' THEN m.PHONE_NUMBER_COMBINED ELSE NULL END) 
        OVER(PARTITION BY m.ENTITY_UID) AS CELULAR_ESTUDIANTE
    , MAX(CASE WHEN m.PHONE_TYPE = 'DA' THEN m.PHONE_NUMBER_COMBINED ELSE NULL END) 
        OVER(PARTITION BY m.ENTITY_UID) AS TELEFONO_APODERADO
    , MAX(CASE WHEN m.PHONE_TYPE = 'CA' THEN m.PHONE_NUMBER_COMBINED ELSE NULL END) 
        OVER(PARTITION BY m.ENTITY_UID) AS CELULAR_APODERADO
    , MAX(CASE WHEN n.EMAIL_TYPE = 'UNIV' THEN n.EMAIL_ADDRESS ELSE NULL END) 
        OVER(PARTITION BY n.PERSON_UID) AS EMAIL_ESTUDIANTE
    , MAX(CASE WHEN n.EMAIL_TYPE = 'PERS' THEN n.EMAIL_ADDRESS ELSE NULL END) 
        OVER(PARTITION BY n.PERSON_UID) AS EMAIL_PERSONAL
    , m.COHORT
    , m.COHORT_DESC
FROM 
    (((((((((ACADEMIC_STUDY a
        INNER JOIN STUDENT_COURSE_GRADE_CHANGE b ON
            a.PERSON_UID = b.PERSON_UID 
            AND a.ACADEMIC_PERIOD > b.ACADEMIC_PERIOD
            AND b.ACADEMIC_PERIOD = (SELECT MAX(ACADEMIC_PERIOD) FROM STUDENT_COURSE_GRADE_CHANGE b_max WHERE
                b.PERSON_UID = b_max.PERSON_UID))
        INNER JOIN LOE_PROGRAM_OVERALL_RESULTS c ON
            a.PERSON_UID = c.PERSON_UID
            AND a.PROGRAM = c.PROGRAM)
        LEFT JOIN HOLD d ON
            a.PERSON_UID = d.PERSON_UID
            AND d.HOLD in ('DI','DC','DM','AR')
            AND d.ACTIVE_HOLD_IND = 'Y')
        LEFT JOIN LOE_SPRIDEN e ON
            a.PERSON_UID = e.SPRIDEN_PIDM
            AND e.SPRIDEN_CHANGE_IND IS NULL)
        LEFT JOIN SORLCUR f ON
            a.PERSON_UID = f.SORLCUR_PIDM
            AND a.PROGRAM = f.SORLCUR_PROGRAM
            AND a.CAMPUS = f.SORLCUR_CAMP_CODE
            AND a.STUDENT_LEVEL = f.SORLCUR_LEVL_CODE
            AND f.SORLCUR_LMOD_CODE = 'LEARNER'
            AND f.SORLCUR_CACT_CODE = 'ACTIVE'
            AND f.SORLCUR_TERM_CODE_END IS NULL)
        LEFT JOIN (SELECT DISTINCT 
                      g.BUSINESS_UNIT
                      , g.BILL_TO_CUST_ID
                      , SUM(CASE
                          WHEN (CASE 
                                  WHEN h.DUE_DT IS NULL 
                                      THEN (CASE WHEN (g.PYMNT_TERMS_CD = 00000) THEN g.DUE_DT ELSE j.DUE_DT END) 
                                  ELSE  h.DUE_DT END < SYSDATE)
                              THEN h.BAL_AMT
                          ELSE 0 END) OVER(PARTITION BY g.BILL_TO_CUST_ID) AS DEUDA
                  FROM 
                      (PS_BI_HDR g 
                          LEFT OUTER JOIN  PS_ITEM h ON  
                              g.BUSINESS_UNIT = h.BUSINESS_UNIT 
                              AND g.INVOICE = h.INVOICE 
                              AND g.BILL_TO_CUST_ID = h.CUST_ID) 
                          , PS_PAY_TRMS_NET i
                          , PS_PAY_TRMS_TIME j 
                  WHERE (i.PYMNT_TERMS_CD = g.PYMNT_TERMS_CD 
                       AND i.EFFDT = (SELECT MAX(i_max.EFFDT) FROM PS_PAY_TRMS_NET i_max 
                          WHERE i.SETID = i_max.SETID 
                            AND i.PYMNT_TERMS_CD = i_max.PYMNT_TERMS_CD 
                            AND i_max.EFFDT <= SYSDATE) 
                       AND i.SETID = j.SETID 
                       AND j.PAY_TRMS_TIME_ID = i.PAY_TRMS_TIME_ID 
                       AND g.BUSINESS_UNIT = 'PER03' 
                       AND h.ITEM_STATUS = 'O')) k ON
            e.SPRIDEN_ID = k.BILL_TO_CUST_ID)
        LEFT JOIN ADDRESS l ON
            a.PERSON_UID = l.ENTITY_UID
            AND l.ADDRESS_TYPE = 'BI'
            AND l.ADDRESS_STATUS_IND IS NULL
            AND l.ADDRESS_END_DATE IS NULL)
        LEFT JOIN TELEPHONE m ON
            a.PERSON_UID = m.ENTITY_UID
            AND m.PHONE_TYPE IN ('BI','DA','CA')
            AND m.PHONE_SEQ_NUMBER = (SELECT MAX(m_max.PHONE_SEQ_NUMBER) FROM TELEPHONE m_max 
                                    WHERE m.ENTITY_UID = m_max.ENTITY_UID
                                        AND m.PHONE_TYPE = m_max.PHONE_TYPE
                                        AND m_max.PHONE_STATUS_IND IS NULL
                                        AND m_max.PHONE_NUMBER_COMBINED <> 'NONEPROVIDED'))
        LEFT JOIN LOE_EMAIL n ON
            a.PERSON_UID = n.PERSON_UID
            AND n.EMAIL_TYPE IN ('PERS','UNIV'))
        LEFT JOIN STUDENT_COHORT m ON
            a.PERSON_UID = m.PERSON_UID 
            AND a.ACADEMIC_PERIOD = m.ACADEMIC_PERIOD
WHERE 
    a.STUDENT_LEVEL = 'UG' 
    AND a.ENROLLMENT_STATUS NOT IN ('EL','RO','RF','IA','IS','SE')
    AND c.ACT_CREDITS_OVERALL < 200
    AND a.ACADEMIC_PERIOD = '218413' -- PERIODO EVALUAR    
    AND b.ACADEMIC_PERIOD IN ('217434','201710','201620','201610','201520','201510','201420','201410','201320','201310','201220','201210') -- ULTIMO PERIODO MATRICULADO
    --AND a.ACADEMIC_PERIOD = '218512' -- PERIODO EVALUAR    
    --AND b.ACADEMIC_PERIOD IN ('217534','201740','201730','201650','201640','201630','201550','201540','201530','201450','201440','201430','201350','201340','201330','201330','201250','201240','201230') -- ULTIMO PERIODO MATRICULADO
    --AND a.CAMPUS in ('CAJ') -- CAMPUS
    --AND m.COHORT = '216520WA'
ORDER BY 1, 3, 12;