--Avance_Curricular_
WITH REQUISITOS AS (
	SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
        , LISTAGG(TRIM(COALESCE(SCRRTST_CONNECTOR,'') ||' '|| COALESCE(SCRRTST_LPAREN,'') || COALESCE(SCRRTST_TESC_CODE,'') || COALESCE(SCRRTST_TEST_SCORE,'')
        		|| COALESCE(SCRRTST_SUBJ_CODE_PREQ,'') || COALESCE(SCRRTST_CRSE_NUMB_PREQ,'') || COALESCE(SCRRTST_RPAREN,'')),' ') 
            WITHIN GROUP (ORDER BY SCRRTST_SEQNO) AS REQUISITOS
    FROM LOE_SCRRTST
    GROUP BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
	)
, EQUIVALENCIAS AS (
	SELECT EFF_TERM, SUBJECT, COURSE_NUMBER
        , LISTAGG(SUBJECT_CODE_EQUIV || COURSE_NUMBER_EQUIV,', ') WITHIN GROUP (ORDER BY SURROGATE_ID) AS EQUIVALENCIAS
    FROM LOE_EQUIV_COURSE_REPEATING
    GROUP BY EFF_TERM, SUBJECT, COURSE_NUMBER
	)
, PLAN_ESTUDIOS AS (
	SELECT A.PROGRAM, A.TERM_CODE_EFF, A.AREA, B.AREA_RULE
		, ROW_NUMBER() OVER(PARTITION BY A.PROGRAM, A.TERM_CODE_EFF ORDER BY A.AREA, B.SEQNO, SMRARUL_SEQNO) AS SEQ
	    , CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
	    	|| CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END AS COD_CURSO
	    , COALESCE(D.TITLE_LONG_DESC, D.TITLE_SHORT_DESC) AS CURSO, COALESCE(D.CREDIT_MIN,0) AS CREDITOS
	    , E.REQUISITOS, F.EQUIVALENCIAS
	FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
			INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.AREA = B.AREA_COURSE AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
			LEFT JOIN ODSMGR.LOE_SMRARUL ON B.AREA_COURSE = SMRARUL_AREA AND B.TERM_CODE_EFF = SMRARUL_TERM_CODE_EFF AND B.AREA_RULE = SMRARUL_KEY_RULE
			LEFT JOIN ODSMGR.COURSE_CATALOG D ON B.TERM_CODE_EFF = D.ACADEMIC_PERIOD AND CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = D.SUBJECT
												AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = D.COURSE_NUMBER
			LEFT JOIN REQUISITOS E ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = E.SCRRTST_SUBJ_CODE
										AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = E.SCRRTST_CRSE_NUMB
										AND E.SCRRTST_TERM_CODE_EFF = (SELECT MAX(E1.SCRRTST_TERM_CODE_EFF) FROM REQUISITOS E1
																		WHERE E1.SCRRTST_SUBJ_CODE = CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
																			AND E1.SCRRTST_CRSE_NUMB = CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END
																			AND E1.SCRRTST_TERM_CODE_EFF <= B.TERM_CODE_EFF)
			LEFT JOIN EQUIVALENCIAS F ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = F.SUBJECT
										AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = F.COURSE_NUMBER
										AND F.EFF_TERM = (SELECT MAX(F1.EFF_TERM) FROM EQUIVALENCIAS F1
																		WHERE F1.SUBJECT = CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
																			AND F1.COURSE_NUMBER = CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END
																			AND F1.EFF_TERM <= B.TERM_CODE_EFF)
	WHERE SUBSTR(A.AREA,LENGTH(A.AREA)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
	)
, CUMPLIDOS AS (
	SELECT A.PERSON_UID, A.SEQUENCE_NUMBER, A.PROGRAM, A.TERM_CODE_EFF, A.REQ_CREDITS_OVERALL, A.REQ_COURSES_OVERALL, A.ACT_CREDITS_OVERALL, A.ACT_COURSES_OVERALL
		, SMBAOGN_AREA, SMBAOGN_MET_IND, B.KEY_RULE, B.SUBJECT || B.COURSE_NUMBER AS COD_CURSO, B.COURSE_REFERENCE_NUMBER, B.TITLE, B.GRDE_CODE, B.ACADEMIC_PERIOD
		, B.COURSE_SOURCE, SMRSSUB_SUBJ_CODE_REQ || SMRSSUB_CRSE_NUMB_REQ AS CURSO_SUSTITUIDO
	FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A
			INNER JOIN ODSMGR.SMBAOGN ON A.PERSON_UID = SMBAOGN_PIDM AND A.SEQUENCE_NUMBER = SMBAOGN_REQUEST_NO AND A.PROGRAM = SMBAOGN_PROGRAM AND A.TERM_CODE_EFF = SMBAOGN_TERM_CODE_EFF
			INNER JOIN ODSMGR.LOE_COURSE_ATTRIBUTE_PROGRAM B ON SMBAOGN_PIDM = B.PERSON_UID AND SMBAOGN_REQUEST_NO = B.REQUEST_NO AND SMBAOGN_TERM_CODE_EFF = B.TERM_CODE_EFF AND SMBAOGN_AREA = B.AREA AND SMBAOGN_PROGRAM = B.PROGRAM
			INNER JOIN ODSMGR.LOE_SOVLCUR ON A.PERSON_UID = SOVLCUR_PIDM AND A.PROGRAM = SOVLCUR_PROGRAM AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LEVL_CODE = 'UG'
			LEFT JOIN ODSMGR.SMRSSUB ON B.PERSON_UID = SMRSSUB_PIDM AND B.TERM_CODE_EFF = SMRSSUB_TERM_CODE_EFF AND B.SUBJECT = SMRSSUB_SUBJ_CODE_SUB AND B.COURSE_NUMBER = SMRSSUB_CRSE_NUMB_SUB
	WHERE SUBSTR(SMBAOGN_AREA,LENGTH(SMBAOGN_AREA)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
		AND A.SEQUENCE_NUMBER = (SELECT MAX(A1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A1
									WHERE A1.PERSON_UID = A.PERSON_UID AND A1.PROGRAM = A.PROGRAM)
	)
, MATRICULADOS AS (
	SELECT SFRSTCR_PIDM, SOVLCUR_PROGRAM, C.TERM_CODE_EFF, SSBSECT_SUBJ_CODE || SSBSECT_CRSE_NUMB AS COD_CURSO, SFRSTCR_CRN
		, COALESCE(D.TITLE_LONG_DESC, D.TITLE_SHORT_DESC) AS CURSO, SFRSTCR_RSTS_CODE, SSBSECT_TERM_CODE
	FROM ODSMGR.SFRSTCR
			INNER JOIN ODSMGR.LOE_SSBSECT ON SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
			INNER JOIN ODSMGR.LOE_SOVLCUR ON SFRSTCR_PIDM = SOVLCUR_PIDM AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LEVL_CODE = 'UG'
			INNER JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C ON SOVLCUR_PIDM = C.PERSON_UID AND SOVLCUR_PROGRAM = C.PROGRAM
															AND C.SEQUENCE_NUMBER = (SELECT MAX(C1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C1
																					WHERE C1.PERSON_UID = C.PERSON_UID AND C1.PROGRAM = C.PROGRAM)
			LEFT JOIN ODSMGR.COURSE_CATALOG D ON SSBSECT_TERM_CODE = D.ACADEMIC_PERIOD AND SSBSECT_SUBJ_CODE = D.SUBJECT AND SSBSECT_CRSE_NUMB = D.COURSE_NUMBER
	WHERE SFRSTCR_TERM_CODE IN (SELECT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM WHERE CURRENT_DATE BETWEEN START_DATE AND END_DATE AND SUBSTR(TERM_CODE,4,1) IN ('4','5'))
		AND SFRSTCR_RSTS_CODE IN ('RW','RE','RA','WC','RF','RO','IA')
	)
, PROYECCIONES AS (
	SELECT SFRREGP_PIDM, SFRREGP_PROGRAM, A.TERM_CODE_EFF, SFRREGP_AREA, SFRREGP_SUBJ_CODE || SFRREGP_CRSE_NUMB_LOW AS COD_CURSO
		, COALESCE(B.TITLE_LONG_DESC, B.TITLE_SHORT_DESC) AS CURSO, SFRREGP_TERM_CODE
	FROM ODSMGR.SFRREGP
			INNER JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A ON SFRREGP_PIDM = A.PERSON_UID AND SFRREGP_PROGRAM = A.PROGRAM
															AND A.SEQUENCE_NUMBER = (SELECT MAX(A1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A1
																					WHERE A1.PERSON_UID = A.PERSON_UID AND A1.PROGRAM = A.PROGRAM)
			LEFT JOIN ODSMGR.COURSE_CATALOG B ON SFRREGP_TERM_CODE = B.ACADEMIC_PERIOD AND SFRREGP_SUBJ_CODE = B.SUBJECT AND SFRREGP_CRSE_NUMB_LOW = B.COURSE_NUMBER
	WHERE SFRREGP_TERM_CODE IN (SELECT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM WHERE CURRENT_DATE < END_DATE AND SUBSTR(TERM_CODE,4,1) IN ('4','5'))
	)
SELECT A.PROGRAM, A.TERM_CODE_EFF, B.SEQUENCE_NUMBER, B.ACTIVITY_DATE, A.AREA, A.AREA_RULE, A.SEQ, A.COD_CURSO, A.CURSO, A.CREDITOS, A.REQUISITOS, A.EQUIVALENCIAS
	, SPRIDEN_ID, SPRIDEN_LAST_NAME ||', '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE
	, MAX(C.SMBAOGN_MET_IND) OVER(PARTITION BY A.PROGRAM, A.TERM_CODE_EFF, A.AREA) AS SMBAOGN_MET_IND
	, COALESCE(C.COD_CURSO, D.COD_CURSO, E.COD_CURSO) AS COD_CURSO, COALESCE(C.TITLE, D.CURSO, E.CURSO) AS TITLE, C.GRDE_CODE
	, COALESCE(C.ACADEMIC_PERIOD, D.SSBSECT_TERM_CODE, E.SFRREGP_TERM_CODE) AS ACADEMIC_PERIOD
	, CASE WHEN C.PERSON_UID IS NOT NULL THEN 1 ELSE 0 END AS CUMPLIDO
	, CASE WHEN D.SFRSTCR_PIDM IS NOT NULL THEN 1 ELSE 0 END AS MATRICULADO
	, CASE WHEN E.SFRREGP_PIDM IS NOT NULL THEN 1 ELSE 0 END AS HABILITADO
	, CASE WHEN C.PERSON_UID IS NULL AND D.SFRSTCR_PIDM IS NULL AND E.SFRREGP_PIDM IS NULL THEN 1 ELSE 0 END AS PENDIENTE
	, CASE
		WHEN C.COURSE_SOURCE = 'T' OR SUBSTR(C.GRDE_CODE,1,1) = 'C' THEN 'Convalidado'
		WHEN A.COD_CURSO <> C.COD_CURSO AND A.EQUIVALENCIAS LIKE '%'||C.COD_CURSO||'%' THEN 'Equivalente'
		WHEN A.COD_CURSO = C.CURSO_SUSTITUIDO THEN 'Sustituto'
		WHEN D.SFRSTCR_RSTS_CODE IN ('WC','RF') THEN 'Retirado'
		WHEN D.SFRSTCR_RSTS_CODE IN ('RO','IA') THEN 'Inhabilitado'
		WHEN D.SFRSTCR_RSTS_CODE IN ('RW','RE','RA') THEN 'En curso'
		ELSE NULL END AS COMENTARIO
FROM PLAN_ESTUDIOS A
		INNER JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS B ON A.PROGRAM = B.PROGRAM AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
															AND B.SEQUENCE_NUMBER = (SELECT MAX(B1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS B1
																					WHERE B1.PERSON_UID = B.PERSON_UID AND B1.PROGRAM = B.PROGRAM)
		INNER JOIN ODSMGR.LOE_SOVLCUR ON B.PERSON_UID = SOVLCUR_PIDM AND B.PROGRAM = SOVLCUR_PROGRAM AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LEVL_CODE = 'UG'
		INNER JOIN ODSMGR.LOE_SPRIDEN ON B.PERSON_UID = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN CUMPLIDOS C ON B.PERSON_UID = C.PERSON_UID AND B.PROGRAM = C.PROGRAM AND B.TERM_CODE_EFF = C.TERM_CODE_EFF AND A.AREA = C.SMBAOGN_AREA
								AND (A.COD_CURSO = C.COD_CURSO OR A.EQUIVALENCIAS LIKE '%'||C.COD_CURSO||'%' OR A.AREA_RULE = C.KEY_RULE OR A.COD_CURSO = C.CURSO_SUSTITUIDO)
		LEFT JOIN MATRICULADOS D ON B.PERSON_UID = D.SFRSTCR_PIDM AND B.PROGRAM = D.SOVLCUR_PROGRAM AND B.TERM_CODE_EFF = D.TERM_CODE_EFF AND A.COD_CURSO = D.COD_CURSO
		LEFT JOIN PROYECCIONES E ON B.PERSON_UID = E.SFRREGP_PIDM AND B.PROGRAM = E.SFRREGP_PROGRAM AND B.TERM_CODE_EFF = E.TERM_CODE_EFF
									AND ((A.AREA = E.SFRREGP_AREA AND A.COD_CURSO = E.COD_CURSO) OR A.COD_CURSO = E.COD_CURSO)
WHERE B.PROGRAM = 'SIC-UG' AND B.TERM_CODE_EFF = '201605' AND B.PERSON_UID = 103063
ORDER BY A.PROGRAM, A.TERM_CODE_EFF, A.SEQ
;



