--BbUsuarios
/*EXTERNAL_PERSON_KEY|USER_ID|FIRSTNAME|LASTNAME|EMAIL|ROW_STATUS|AVAILABLE_IND|DATA_SOURCE_KEY
1020|N00001020|CLAUDIO ALBERTO|ROJAS FLORES|N00001020@upn.pe|ENABLED|Y|Banner
1027|N00001027|LUPE YOVANI|GALLARDO PASTOR|N00001027@upn.pe|ENABLED|Y|Banner*/
SELECT DISTINCT
    f.SPRIDEN_PIDM AS EXTERNAL_PERSON_KEY
    , f.SPRIDEN_ID AS USER_ID
    , f.SPRIDEN_FIRST_NAME AS FIRSTNAME
    , REPLACE(f.SPRIDEN_LAST_NAME,'/',' ') AS LASTNAME
    , CONCAT(f.SPRIDEN_ID,'@upn.edu.pe') AS EMAIL
    , c.ROW_STATUS AS ROW_STATUS
    , CASE WHEN c.ROW_STATUS = 'ENABLED' THEN 'Y' ELSE 'N' END AS AVAILABLE_IND
    , 'Banner' AS DATA_SOURCE_KEY
FROM
    (SELECT DISTINCT a.PERSON_UID, a.ACADEMIC_PERIOD, a.COURSE_REFERENCE_NUMBER, CASE WHEN b.ENROLLMENT_STATUS = 'EL' THEN 'ENABLED' ELSE 'DISABLED' END AS ROW_STATUS
    FROM STUDENT_COURSE a INNER JOIN ACADEMIC_STUDY b ON
            a.PERSON_UID = b.PERSON_UID AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD AND b.STUDENT_LEVEL = 'UG'
    UNION
    SELECT DISTINCT PERSON_UID, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 'ENABLED' AS ROW_STATUS FROM INSTRUCTIONAL_ASSIGNMENT) c
        INNER JOIN (SELECT DISTINCT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, MIN(START_DATE) AS MIN_START_DATE, MAX(END_DATE) +7 AS MAX_END_DATE
                FROM MEETING_TIME GROUP BY ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER) d ON
            c.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD
            AND c.COURSE_REFERENCE_NUMBER = d.COURSE_REFERENCE_NUMBER
        INNER JOIN SCHEDULE_OFFERING e ON
            c.ACADEMIC_PERIOD = e.ACADEMIC_PERIOD
            AND c.COURSE_REFERENCE_NUMBER = e.COURSE_REFERENCE_NUMBER
        INNER JOIN SPRIDEN f ON
            c.PERSON_UID = f.SPRIDEN_PIDM
WHERE f.SPRIDEN_CHANGE_IND IS NULL AND SUBSTR(f.SPRIDEN_ID,1,1) = 'N' AND e.INSTRUCTION_METHOD = 'V' AND c.ACADEMIC_PERIOD IN ('218320') 
--AND d.MIN_START_DATE = '02/07/2018' --AND d.MAX_END_DATE <= '05/08/2018' --GRUPO 1
--AND d.MIN_START_DATE = '09/07/2018' --AND d.MAX_END_DATE <= '12/08/2018' --GRUPO 2
AND d.MIN_START_DATE = '16/07/2018' --AND d.MAX_END_DATE <= '19/08/2018' --GRUPO 3
;

--BbPeriodos
/*EXTERNAL_TERM_KEY|NAME|DURATION|START_DATE|END_DATE|DATA_SOURCE_KEY
218413|2018-1 Marzo-Julio UG|R|20180326|20180720|Banner
218512|2018-1 Marzo-Julio WA|R|20180324|20180720|Banner*/
SELECT DISTINCT
    a.TERM_CODE AS EXTERNAL_TERM_KEY
    , b.STVTERM_DESC AS NAME
    , 'R' AS DURATION
    , TO_CHAR(a.START_DATE,'YYYYMMDD') AS START_DATE
    , TO_CHAR(a.END_DATE,'YYYYMMDD') AS END_DATE
    , 'Banner' AS DATA_SOURCE_KEY
FROM LOE_SECTION_PART_OF_TERM a 
    INNER JOIN STVTERM b ON
        a.TERM_CODE = b.STVTERM_CODE
WHERE a.TERM_CODE IN ('218320');

--BbMatricula
/*EXTERNAL_COURSE_KEY|EXTERNAL_PERSON_KEY|ROLE|DATA_SOURCE_KEY
CIAP.1303.218512.2674|11444|PV|Banner
CIAP.1303.218512.2674|15136|S|Banner*/
SELECT DISTINCT
    e.SUBJECT||'.'||e.COURSE_NUMBER||'.'||e.ACADEMIC_PERIOD||'.'||e.COURSE_REFERENCE_NUMBER AS EXTERNAL_COURSE_KEY
    , c.PERSON_UID AS EXTERNAL_PERSON_KEY
    , c.ROLE AS ROLE
    , 'Banner' AS DATA_SOURCE_KEY
FROM
    (SELECT DISTINCT a.PERSON_UID, a.ACADEMIC_PERIOD, a.COURSE_REFERENCE_NUMBER, 'S' AS ROLE FROM STUDENT_COURSE a INNER JOIN ACADEMIC_STUDY b ON
        a.PERSON_UID = b.PERSON_UID AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD AND b.STUDENT_LEVEL = 'UG' AND b.ENROLLMENT_STATUS = 'EL'
    UNION
    SELECT DISTINCT PERSON_UID, ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, 'PV' AS ROLE FROM INSTRUCTIONAL_ASSIGNMENT) c
        INNER JOIN (SELECT DISTINCT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, MIN(START_DATE) AS MIN_START_DATE, MAX(END_DATE) +7 AS MAX_END_DATE
                FROM MEETING_TIME GROUP BY ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER) d ON
            c.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD
            AND c.COURSE_REFERENCE_NUMBER = d.COURSE_REFERENCE_NUMBER
        INNER JOIN SCHEDULE_OFFERING e ON
            c.ACADEMIC_PERIOD = e.ACADEMIC_PERIOD
            AND c.COURSE_REFERENCE_NUMBER = e.COURSE_REFERENCE_NUMBER
WHERE e.INSTRUCTION_METHOD = 'V' AND c.ACADEMIC_PERIOD IN ('218320') 
--AND d.MIN_START_DATE = '02/07/2018' --AND d.MAX_END_DATE <= '05/08/2018' --GRUPO 1
--AND d.MIN_START_DATE = '09/07/2018' --AND d.MAX_END_DATE <= '12/08/2018' --GRUPO 2
AND d.MIN_START_DATE = '16/07/2018' --AND d.MAX_END_DATE <= '19/08/2018' --GRUPO 3
;

--BbCursos
/*EXTERNAL_COURSE_KEY|COURSE_ID|COURSE_NAME|AVAILABLE_IND|ROW_STATUS|DURATION|START_DATE|END_DATE|TERM_KEY|DATA_SOURCE_KEY|PRIMARY_EXTERNAL_NODE_KEY|EXTERNAL_ASSOCIATION_KEY|TEMPLATE_COURSE_KEY
STAT.1203A.218413.11148|STAT.1203A.218413.11148|PROBABILIDAD Y ESTADÍSTICA|Y|ENABLED|R|20180326|20180720|218413|Banner|TSI.DCIE|DCIE.11148|MASTER.2018.II.UG.STAT.2301
INVE.1101.218413.11456|INVE.1101.218413.11456|METODOLOGÍA UNIVERSITARIA|Y|ENABLED|R|20180326|20180720|218413|Banner|LN0.DHUM|DHUM.11456|MASTER.2018.II.UG.INVE.1101*/
SELECT DISTINCT
    a.SUBJECT||'.'||a.COURSE_NUMBER||'.'||a.ACADEMIC_PERIOD||'.'||a.COURSE_REFERENCE_NUMBER AS EXTERNAL_COURSE_KEY
    , a.SUBJECT||'.'||a.COURSE_NUMBER||'.'||a.ACADEMIC_PERIOD||'.'||a.COURSE_REFERENCE_NUMBER AS COURSE_ID
    , c.TITLE_LONG_DESC AS COURSE_NAME
    , CASE WHEN a.STATUS = 'A' THEN 'Y' ELSE 'N' END AS AVAILABLE_IND
    , CASE WHEN a.STATUS = 'A' THEN 'ENABLED' ELSE 'DISABLED' END AS ROW_STATUS
    , 'R' AS DURATION
    , TO_CHAR(b.MIN_START_DATE,'YYYYMMDD') AS START_DATE
    , TO_CHAR(b.MAX_END_DATE,'YYYYMMDD') AS END_DATE
    , a.ACADEMIC_PERIOD AS TERM_KEY
    , 'Banner' AS DATA_SOURCE_KEY
    , a.CAMPUS||'.'||a.DEPARTMENT AS PRIMARY_EXTERNAL_NODE_KEY
    , a.DEPARTMENT||'.'||a.COURSE_REFERENCE_NUMBER AS EXTERNAL_ASSOCIATION_KEY
    --, 'MASTER.2018.II.UG.LENG.2001' --GRUPO 1
    --, 'MASTER.2018.II.UG.LENG.2001' --GRUPO 2
    --, 'MASTER.2018.II.UG.LENG.2001' --GRUPO 3
    , NULL AS TEMPLATE_COURSE_KEY
FROM
    (SCHEDULE_OFFERING a
        INNER JOIN (SELECT DISTINCT ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER, MIN(START_DATE) AS MIN_START_DATE, MAX(END_DATE) +7 AS MAX_END_DATE
                FROM MEETING_TIME GROUP BY ACADEMIC_PERIOD, COURSE_REFERENCE_NUMBER) b ON
            a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD
            AND a.COURSE_REFERENCE_NUMBER = b.COURSE_REFERENCE_NUMBER)
        LEFT JOIN COURSE_CATALOG c ON
            a.ACADEMIC_PERIOD = c.ACADEMIC_PERIOD
            AND a.SUBJECT = c.SUBJECT
            AND a.COURSE_NUMBER = c.COURSE_NUMBER
WHERE a.INSTRUCTION_METHOD = 'V' AND a.ACADEMIC_PERIOD IN ('218320') 
--AND b.MIN_START_DATE = '02/07/2018' --AND b.MAX_END_DATE <= '05/08/2018' --GRUPO 1
--AND b.MIN_START_DATE = '09/07/2018' --AND b.MAX_END_DATE <= '12/08/2018' --GRUPO 2
AND b.MIN_START_DATE = '16/07/2018' --AND b.MAX_END_DATE <= '19/08/2018' --GRUPO 3
;
