SELECT DISTINCT 
    SPRIDEN_ID, A.SOVLCUR_PIDM, A.SOVLCUR_STYP_CODE, A.SOVLCUR_PROGRAM AS PROGRAMA_ACTUAL, A.SOVLCUR_CAMP_CODE AS CAMPUS_ACTUAL--, SUBSTR(A.SOVLCUR_PROGRAM,5,2) AS MODALIDAD_ACTUAL 
    , B.SOVLCUR_PROGRAM AS PROGRAMA_ANTERIOR, B.SOVLCUR_CAMP_CODE AS CAMPUS_ANTERIOR--, SUBSTR(B.SOVLCUR_PROGRAM,5,2) AS MODALIDAD_ANTERIOR
    , A.SOVLCUR_USER_ID, A.SOVLCUR_ACTIVITY_DATE
FROM LOE_SOVLCUR A, LOE_SOVLCUR B, SPRIDEN
WHERE A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_LEVL_CODE IN ('UG','CR') 
    AND A.SOVLCUR_CURRENT_IND = 'Y' AND SUBSTR(A.SOVLCUR_PROGRAM,1,4) <> 'ING-' 
    AND A.SOVLCUR_PIDM = B.SOVLCUR_PIDM 
    AND A.SOVLCUR_TERM_CODE >= B.SOVLCUR_TERM_CODE 
    AND A.SOVLCUR_TERM_CODE = B.SOVLCUR_TERM_CODE_END
    AND A.SOVLCUR_LEVL_CODE = B.SOVLCUR_LEVL_CODE
    AND (A.SOVLCUR_PROGRAM <> B.SOVLCUR_PROGRAM --OR (SUBSTR(A.SOVLCUR_PROGRAM,5,2) <> SUBSTR(B.SOVLCUR_PROGRAM,5,2) 
        OR A.SOVLCUR_CAMP_CODE <> B.SOVLCUR_CAMP_CODE) 
    AND B.SOVLCUR_LMOD_CODE = 'LEARNER' AND B.SOVLCUR_CACT_CODE = 'ACTIVE' --AND B.SOVLCUR_LEVL_CODE = 'UG' 
    AND B.SOVLCUR_PROGRAM NOT LIKE '%PDN%' AND SUBSTR(B.SOVLCUR_PROGRAM,1,4) <> 'ING-' 
    AND A.SOVLCUR_PIDM = SPRIDEN_PIDM 
    AND SPRIDEN_CHANGE_IND IS NULL 
    AND A.SOVLCUR_TERM_CODE = '219435' --AND SPRIDEN_ID = 'N00030614'
ORDER BY 1;