/*1) DATA PARA ALUMNOS CONTINUADORES INGLÉS, de los periodos 220714 y 220715 los siguientes campos:
ID, NOMBRES, APELLIDOS, SEDE, CARRERA, CICLO, AÑO DE INGRESO, UG Ó WA, CELULAR, TELÉFONO FIJO, CORREO PERSONAL, CORREO UPN, ÚLTIMO NIVEL DE INGLÉS CURSADO
, NOTA ÚLTIMO NIVEL DE INGLÉS CURSADO, RINDIÓ EXAMEN DE UBICACIÓN?, UBIGEO, y FECHA EN LA QUE LLEVÓ EL ÚLTIMO NIVEL DE INGLÉS CURSADO EN UPN.*/

SELECT A.SOVLCUR_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, A.SOVLCUR_CAMP_CODE, A.SOVLCUR_PROGRAM, B.SMRPRLE_PROGRAM_DESC, C.SOVLCUR_PROGRAM, D.SMRPRLE_PROGRAM_DESC
	, C.SOVLCUR_TERM_CODE_ADMIT, SUBSTR(C.SOVLCUR_PROGRAM,5,2) AS NIVEL, MAX(E.PHONE_NUMBER) AS CELULAR, MAX(F.PHONE_NUMBER) AS TELEFONO, MAX(G.EMAIL_ADDRESS) AS CORREO_PERSONAL
	, SPRIDEN_ID ||'@upn.pe' AS CORREO_UPN, A.SHRTCKN_SUBJ_CODE || A.SHRTCKN_CRSE_NUMB ||' - '|| A.SHRTCKN_CRSE_TITLE AS ULTIMO_INGLES
	, SHRTCKG_GRDE_CODE_FINAL AS ULTIMO_INGLES_NOTA, MAX(H.TEST_DATE) AS EXAMEN_UBICACION, I.CITY AS UBIGEO, A.SHRTCKN_TERM_CODE AS ULTIMO_INGLES_PERIODO
FROM ( SELECT DISTINCT SOVLCUR_PIDM, SOVLCUR_CAMP_CODE, SOVLCUR_PROGRAM, SHRTCKN_TERM_CODE, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
		FROM ODSMGR.LOE_SOVLCUR, ODSMGR.SHRTCKN H, ODSMGR.SHRTCKG C
		WHERE SOVLCUR_PIDM = SHRTCKN_PIDM AND SHRTCKN_SUBJ_CODE = 'IDIO'
			AND H.SHRTCKN_TERM_CODE = (SELECT MAX(H1.SHRTCKN_TERM_CODE) FROM ODSMGR.SHRTCKN H1
										WHERE H1.SHRTCKN_PIDM = H.SHRTCKN_PIDM AND H1.SHRTCKN_SUBJ_CODE = 'IDIO')
			AND SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
			AND C.SHRTCKG_SEQ_NO = (SELECT MAX(C1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG C1
									WHERE C1.SHRTCKG_PIDM = C.SHRTCKG_PIDM AND C1.SHRTCKG_TERM_CODE = C.SHRTCKG_TERM_CODE
										AND C1.SHRTCKG_TCKN_SEQ_NO = C.SHRTCKG_TCKN_SEQ_NO)
			AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y'
			AND SOVLCUR_LEVL_CODE = 'CR' AND SUBSTR(SOVLCUR_PROGRAM,1,4) = 'ING-' ) A
		, ODSMGR.LOE_SPRIDEN, ODSMGR.SMRPRLE B, ODSMGR.LOE_SOVLCUR C, ODSMGR.SMRPRLE D, ODSMGR.TELEPHONE E, ODSMGR.TELEPHONE F
		,(SELECT PERSON_UID, EMAIL_ADDRESS
          FROM (SELECT PERSON_UID, EMAIL_ADDRESS, ACTIVITY_DATE, MAX(ACTIVITY_DATE) OVER(PARTITION BY PERSON_UID) AS MAX_DATE
          		FROM ODSMGR.LOE_EMAIL
                WHERE STATUS_IND = 'A' AND EMAIL_TYPE = 'PERS')
          WHERE ACTIVITY_DATE = MAX_DATE) G
		, ODSMGR.TEST H, ODSMGR.ADDRESS I
WHERE A.SOVLCUR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
	AND A.SOVLCUR_PROGRAM = B.SMRPRLE_PROGRAM(+)
	AND A.SOVLCUR_PIDM = C.SOVLCUR_PIDM(+)
	AND C.SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND C.SOVLCUR_CACT_CODE(+) = 'ACTIVE'
	AND C.SOVLCUR_CURRENT_IND(+) = 'Y' AND C.SOVLCUR_LEVL_CODE(+) = 'UG'
	AND C.SOVLCUR_PROGRAM = D.SMRPRLE_PROGRAM(+)
	AND A.SOVLCUR_PIDM = E.ENTITY_UID(+) AND E.PHONE_TYPE(+) = 'CP'
	AND A.SOVLCUR_PIDM = F.ENTITY_UID(+) AND F.PHONE_TYPE(+) = 'BI'
	AND A.SOVLCUR_PIDM = G.PERSON_UID(+)
	AND A.SOVLCUR_PIDM = H.PERSON_UID(+) AND H.TEST(+) = 'EXUB'
	AND A.SOVLCUR_PIDM = I.ENTITY_UID(+) AND I.ADDRESS_TYPE(+) = 'BI'
	AND I.ADDRESS_END_DATE(+) IS NULL AND I.ADDRESS_STATUS_IND(+) IS NULL
GROUP BY A.SOVLCUR_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, A.SOVLCUR_CAMP_CODE, A.SOVLCUR_PROGRAM, B.SMRPRLE_PROGRAM_DESC, C.SOVLCUR_PROGRAM
	, D.SMRPRLE_PROGRAM_DESC, C.SOVLCUR_TERM_CODE_ADMIT, SUBSTR(C.SOVLCUR_PROGRAM,5,2), SPRIDEN_ID ||'@upn.pe', A.SHRTCKN_SUBJ_CODE || A.SHRTCKN_CRSE_NUMB ||' - '|| A.SHRTCKN_CRSE_TITLE
	, SHRTCKG_GRDE_CODE_FINAL, I.CITY, A.SHRTCKN_TERM_CODE;


/*2) DATA PARA ALUNNOS QUE NUNCA HAN LLEVADO INGLÉS, de los periodos 220413 y 220513, los siguientes campos:
ID,	NOMBRES, APELLIDOS, SEDE, CARRERA, CICLO, AÑO DE INGRESO, UG Ó WA, CELULAR, TELÉFONO FIJO, CORREO PERSONAL, CORREO UPN, RINDIÓ EXAMEN DE UBICACIÓN?, NOTA EXAMEN DE UBICACIÓN, y UBIGEO.*/

SELECT SOVLCUR_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, SOVLCUR_CAMP_CODE, SOVLCUR_PROGRAM, SMRPRLE_PROGRAM_DESC, SOVLCUR_TERM_CODE_ADMIT
	, SUBSTR(SOVLCUR_PROGRAM,5,2) AS NIVEL, MAX(E.PHONE_NUMBER) AS CELULAR, MAX(F.PHONE_NUMBER) AS TELEFONO, MAX(G.EMAIL_ADDRESS) AS CORREO_PERSONAL
	, SPRIDEN_ID ||'@upn.pe' AS CORREO_UPN, H.TEST_DATE AS EXAMEN_UBICACION, H.TEST_SCORE AS EXAMEN_UBICACION_NOTA, I.CITY AS UBIGEO
FROM ODSMGR.LOE_SOVLCUR
		LEFT JOIN ODSMGR.SHRTCKN ON SOVLCUR_PIDM = SHRTCKN_PIDM AND SHRTCKN_SUBJ_CODE = 'IDIO'
		LEFT JOIN ODSMGR.LOE_SPRIDEN ON SOVLCUR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN ODSMGR.SMRPRLE ON SOVLCUR_PROGRAM = SMRPRLE_PROGRAM
		LEFT JOIN ODSMGR.TELEPHONE E ON SOVLCUR_PIDM = E.ENTITY_UID AND E.PHONE_TYPE = 'CP'
		LEFT JOIN ODSMGR.TELEPHONE F ON SOVLCUR_PIDM = F.ENTITY_UID AND F.PHONE_TYPE = 'BI'
		LEFT JOIN (SELECT PERSON_UID, EMAIL_ADDRESS
			          FROM (SELECT PERSON_UID, EMAIL_ADDRESS, ACTIVITY_DATE, MAX(ACTIVITY_DATE) OVER(PARTITION BY PERSON_UID) AS MAX_DATE
			          		FROM ODSMGR.LOE_EMAIL
			                WHERE STATUS_IND = 'A' AND EMAIL_TYPE = 'PERS')
			          WHERE ACTIVITY_DATE = MAX_DATE) G ON SOVLCUR_PIDM = G.PERSON_UID
		LEFT JOIN ODSMGR.TEST H ON SOVLCUR_PIDM = H.PERSON_UID AND H.TEST = 'EXUB'
									AND H.TEST_DATE = (SELECT MAX(H1.TEST_DATE) FROM ODSMGR.TEST H1
														WHERE H1.PERSON_UID = H.PERSON_UID AND H1.TEST = 'EXUB')
		LEFT JOIN ODSMGR.ADDRESS I ON SOVLCUR_PIDM = I.ENTITY_UID AND I.ADDRESS_TYPE = 'BI' AND I.ADDRESS_END_DATE IS NULL AND I.ADDRESS_STATUS_IND IS NULL
WHERE SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y'
	AND SOVLCUR_LEVL_CODE = 'UG' AND SHRTCKN_PIDM IS NULL
GROUP BY SOVLCUR_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, SOVLCUR_CAMP_CODE, SOVLCUR_PROGRAM, SMRPRLE_PROGRAM_DESC, SOVLCUR_TERM_CODE_ADMIT
	, SUBSTR(SOVLCUR_PROGRAM,5,2), SPRIDEN_ID ||'@upn.pe', H.TEST_DATE, H.TEST_SCORE, I.CITY;
