SELECT DISTINCT
    a.DEPOSIT_BU, a.ACCOUNTING_DT, b.REF_VALUE, c.ACCOUNT_UID, c.ID, c.NAME, c.TRANSACTION_NUMBER, d.SVRSVPR_SRVC_CODE, e.SVVSRVC_DESC, c.AMOUNT
FROM PS_PAYMENT a, PS_PAYMENT_ID_ITEM b, RECEIVABLE_ACCOUNT_DETAIL c, LOE_SVRSVPR d, LOE_SVVSRVC e
WHERE a.DEPOSIT_BU = b.DEPOSIT_BU
    AND a.PAYMENT_SEQ_NUM = b.PAYMENT_SEQ_NUM
    AND a.DEPOSIT_ID = b.DEPOSIT_ID
    AND b.REF_VALUE = c.CREDIT_CARD_NUMBER
    AND c.ACADEMIC_PERIOD = '000000'
    AND c.ACCOUNT_UID = d.SVRSVPR_PIDM
    AND c.TRANSACTION_NUMBER = d.SVRSVPR_ACCD_TRAN_NUMBER
    AND d.SVRSVPR_SRVC_CODE = e.SVVSRVC_CODE
    AND d.SVRSVPR_SRVC_CODE IN ('UG.007','WA.005','CAR3','CAR4' --CAJ
        ,'UG.066','WA.059','CAR7','CAR8' --LC0
        ,'UG.219','WA.197' --LE0
        ,'UG.168','WA.151','CAR5','CAR6' --LN0
        ,'UG.117','WA.105' --LN1
        ,'UG.270','WA.243','CAR1','CAR2' --TML
        ,'UG.321','WA.289') --TSI
    AND a.ACCOUNTING_DT >= '01/01/2018' AND a.ACCOUNTING_DT <= '30/10/2018'
ORDER BY 4,7,2;