
SELECT DISTINCT A.BUSINESS_UNIT, A.PO_REF
    , MAX(C.PRODUCT) OVER(PARTITION BY C.INVOICE) AS PRODUCT
    , MAX(C.OPERATING_UNIT) OVER(PARTITION BY C.INVOICE) AS OPERATING_UNIT
    , A.BILL_TO_CUST_ID, REPLACE(CONCAT(CONCAT(E.NAME2,' '),E.NAME1),'/',' ') AS NOMBRE_COMPLETO, E.SUBCUST_QUAL1
	, E.CORPORATE_CUST_ID, REPLACE(CONCAT(CONCAT(F.NAME2,' '),F.NAME1),'/',' ') AS NOMBRE_COMPLETO_CORPORATE    
    , A.BILL_TYPE_ID, A.BILL_STATUS, I.INSTALL_NBR, A.INVOICE, G.INVOICE2, D.DESCR, A.INVOICE_DT
    , CASE WHEN L.DUE_DT IS NULL 
        THEN (CASE WHEN A.PYMNT_TERMS_CD IN ('000','0000','00000') 
            THEN A.DUE_DT 
            ELSE K.DUE_DT END) 
        ELSE L.DUE_DT END AS FECHA_VENCIMIENTO
	, H.VAT_RGSTRN_ID, A.TOT_VAT, A.INVOICE_AMT_PRETAX, A.INVOICE_AMOUNT, B.SALDO_CALCULADO
	, M.ENTRY_TYPE, M.ENTRY_REASON, CASE WHEN N.ITEM IS NOT NULL THEN 'Y' ELSE 'N' END AS COBRANZA_DUDOSA
FROM ODSMGR.PS_BI_HDR A
	, ( SELECT BUSINESS_UNIT, ITEM, SUM(ENTRY_AMT) AS SALDO_CALCULADO FROM ODSMGR.PS_ITEM_ACTIVITY
		WHERE BUSINESS_UNIT = 'PER03' AND ACCOUNTING_DT BETWEEN :PERIODO_INICIO AND :PERIODO_FIN
		GROUP BY BUSINESS_UNIT, ITEM) B
	, ODSMGR.PS_BI_LINE_DST C, ODSMGR.PS_BI_LINE D, ODSMGR.PS_CUSTOMER E, ODSMGR.PS_CUSTOMER F, ODSMGR.PS_LI_GBL_BI_INV G, ODSMGR.PS_CUST_VAT_REG H, ODSMGR.PS_BI_INSTALL_SCHE I
	, ODSMGR.PS_PAY_TRMS_NET J, ODSMGR.PS_PAY_TRMS_TIME K, ODSMGR.PS_ITEM L, ODSMGR.PS_ITEM_ACTIVITY M, ODSMGR.PS_LI_PER_BDBTCALC N
WHERE A.INVOICE = B.ITEM
	AND A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.INVOICE = C.INVOICE
	AND A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.INVOICE = D.INVOICE
    AND D.LINE_SEQ_NUM = (SELECT MIN(D1.LINE_SEQ_NUM) FROM PS_BI_LINE D1
                            WHERE D.BUSINESS_UNIT = D1.BUSINESS_UNIT AND D.INVOICE = D1.INVOICE
                            GROUP BY D1.INVOICE)
    AND A.BILL_TO_CUST_ID = E.CUST_ID(+)
    AND E.CORPORATE_CUST_ID = F.CUST_ID(+)
    AND A.BUSINESS_UNIT = G.BUSINESS_UNIT(+) AND A.INVOICE = G.INVOICE(+)
    AND A.BILL_TO_CUST_ID = H.CUST_ID(+)
    AND A.INVOICE = I.GENERATED_INVOICE(+)
    AND A.BUSINESS_UNIT = J.SETID(+) AND A.PYMNT_TERMS_CD = J.PYMNT_TERMS_CD(+) AND J.EFFDT(+) <= CURRENT_DATE
    AND J.SETID = K.SETID(+) AND J.PAY_TRMS_TIME_ID = K.PAY_TRMS_TIME_ID(+)
    AND A.BUSINESS_UNIT = L.BUSINESS_UNIT(+) AND A.INVOICE = L.ITEM(+)
    AND B.BUSINESS_UNIT = M.BUSINESS_UNIT(+) AND B.ITEM = M.ITEM(+)
    AND M.ITEM_SEQ_NUM = (SELECT MAX(M1.ITEM_SEQ_NUM) FROM PS_ITEM_ACTIVITY M1
								WHERE M.BUSINESS_UNIT = M1.BUSINESS_UNIT AND M.ITEM = M1.ITEM
									AND M1.ACCOUNTING_DT BETWEEN :PERIODO_INICIO AND :PERIODO_FIN
								GROUP BY M1.ITEM)
    AND A.BUSINESS_UNIT = N.BUSINESS_UNIT(+) AND A.INVOICE = N.ITEM(+)
	AND A.BUSINESS_UNIT = 'PER03' AND A.BILL_TYPE_ID IN ('B1','F1','C1','C2','D1','D2') AND A.BILL_STATUS = 'INV'
	AND A.INVOICE_DT BETWEEN :PERIODO_INICIO AND :PERIODO_FIN
	AND B.SALDO_CALCULADO <> 0
;


WITH PS_ITEM_ACTIVITY_RUN AS (
	SELECT A.BUSINESS_UNIT, A.PO_REF, A.BILL_TO_CUST_ID, REPLACE(CONCAT(CONCAT(E.NAME2,' '),E.NAME1),'/',' ') AS NOMBRE_COMPLETO
    	, E.CORPORATE_CUST_ID, REPLACE(CONCAT(CONCAT(E0.NAME2,' '),E0.NAME1),'/',' ') AS NOMBRE_COMPLETO_CORPORATE, A.BILL_TYPE_ID
    	, A.BILL_STATUS, COALESCE(S.INSTALL_NBR,S0.INSTALL_NBR) AS INSTALL_NBR, A.INVOICE, A.INVOICE_DT
		, CASE WHEN I.DUE_DT IS NULL THEN (CASE WHEN A.PYMNT_TERMS_CD IN ('000','0000','00000') THEN A.DUE_DT ELSE T.DUE_DT END) ELSE I.DUE_DT END AS FECHA_VENCIMIENTO
		, A.TOT_VAT, A.INVOICE_AMT_PRETAX, A.INVOICE_AMOUNT, D.OPERATING_UNIT, D.CAMPUS, D.PRODUCT, D.NIVEL, B.ACCOUNTING_DT, I.BAL_CURRENCY
		, SUM(C.ENTRY_AMT) AS SALDO_CALCULADO
		, SUM(CASE WHEN C.USER_AMT3 IS NULL THEN 0.00 ELSE C.USER_AMT3 END) AS MORA
		, SUM(CASE WHEN C.USER_AMT4 IS NULL THEN 0.00 ELSE C.USER_AMT4 END) AS GASTO_ADM
		, MAX(CASE WHEN C.CUST_ID = '9999999999' THEN '9999999999' END) AS CUST_ID
		, MAX(CASE WHEN CONCAT(C.ENTRY_TYPE,C.ENTRY_REASON) = 'WOCASTI' THEN 'WOCASTI' END) AS WO_CASTI
	FROM ODSMGR.PS_BI_HDR A
			INNER JOIN (SELECT DISTINCT BUSINESS_UNIT, ITEM, ACCOUNTING_DT, ENTRY_CURRENCY
						FROM ODSMGR.PS_ITEM_ACTIVITY
						WHERE BUSINESS_UNIT = 'PER03'
							) B ON A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.ITEM
			INNER JOIN ODSMGR.PS_ITEM_ACTIVITY C ON B.BUSINESS_UNIT = C.BUSINESS_UNIT AND B.ITEM = C.ITEM AND B.ACCOUNTING_DT >= C.ACCOUNTING_DT
			INNER JOIN ODSMGR.PS_ITEM I ON B.BUSINESS_UNIT = I.BUSINESS_UNIT AND B.ITEM = I.ITEM
			INNER JOIN ODSMGR.PS_PAY_TRMS_NET N ON A.BUSINESS_UNIT = N.SETID AND A.PYMNT_TERMS_CD = N.PYMNT_TERMS_CD
													AND N.EFFDT = (SELECT MAX(N_ED.EFFDT) FROM ODSMGR.PS_PAY_TRMS_NET N_ED
															        WHERE N.SETID = N_ED.SETID AND N.PYMNT_TERMS_CD = N_ED.PYMNT_TERMS_CD AND N_ED.EFFDT <= CURRENT_DATE)
			INNER JOIN ODSMGR.PS_PAY_TRMS_TIME T ON N.SETID = T.SETID AND N.PAY_TRMS_TIME_ID = T.PAY_TRMS_TIME_ID
			LEFT JOIN ( SELECT BUSINESS_UNIT, INVOICE, LINE_SEQ_NUM, LINE_DST_SEQ_NUM, OPERATING_UNIT, CAMPUS, PRODUCT, NIVEL
							, MAX(LINE_SEQ_NUM) OVER(PARTITION BY INVOICE) AS MAX_LINE_SEQ_NUM
						FROM (
							SELECT BUSINESS_UNIT, INVOICE, LINE_SEQ_NUM, LINE_DST_SEQ_NUM, OPERATING_UNIT, C.VALUE2 AS CAMPUS, PRODUCT, L.VALUE2 AS NIVEL
								, MAX(LINE_DST_SEQ_NUM) OVER(PARTITION BY INVOICE) AS MAX_LINE_DST_SEQ_NUM
							FROM ODSMGR.PS_BI_LINE_DST
									INNER JOIN ODSMGR.LOE_BASE_TABLE_EQUIV C ON OPERATING_UNIT = C.VALUE1 AND C.ESTADO = 'Y' AND C.TABLE_PARENT_ID = 1
									INNER JOIN ODSMGR.LOE_BASE_TABLE_EQUIV L ON PRODUCT = L.VALUE1 AND L.ESTADO = 'Y' AND L.TABLE_PARENT_ID = 9
								)
						WHERE LINE_DST_SEQ_NUM = MAX_LINE_DST_SEQ_NUM
							) D ON A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.INVOICE = D.INVOICE AND D.LINE_SEQ_NUM = D.MAX_LINE_SEQ_NUM
			LEFT JOIN ODSMGR.PS_CUSTOMER E ON A.BILL_TO_CUST_ID = E.CUST_ID			
			LEFT JOIN ODSMGR.PS_CUSTOMER E0 ON E.CORPORATE_CUST_ID = E0.CUST_ID
			LEFT JOIN ODSMGR.PS_BI_INSTALL_SCHE S ON A.INVOICE = S.GENERATED_INVOICE
			LEFT JOIN ODSMGR.PS_BI_LINE_NOTE O ON A.INVOICE = O.INVOICE AND O.TEXT254 LIKE '%ORIGINAL_INVOICE:%'
												    	AND O.LINE_SEQ_NUM = (SELECT MIN(O1.LINE_SEQ_NUM) FROM ODSMGR.PS_BI_LINE_NOTE O1
																			WHERE O1.BUSINESS_UNIT = O.BUSINESS_UNIT AND O1.INVOICE = O.INVOICE AND O1.TEXT254 LIKE '%ORIGINAL_INVOICE:%')
			LEFT JOIN ODSMGR.PS_BI_LINE_NOTE O0 ON A.INVOICE = O0.INVOICE AND O0.NOTE_TYPE = 'INVOICE'
													AND O0.LINE_SEQ_NUM = (SELECT MIN(O2.LINE_SEQ_NUM) FROM ODSMGR.PS_BI_LINE_NOTE O2
																			WHERE O2.BUSINESS_UNIT = O0.BUSINESS_UNIT AND O2.INVOICE = O0.INVOICE AND O2.NOTE_TYPE = 'INVOICE')
			LEFT JOIN ODSMGR.PS_BI_INSTALL_SCHE S0 ON COALESCE(SUBSTR(O.TEXT254,LENGTH(O.TEXT254)-9),O0.TEXT254) = S0.GENERATED_INVOICE
	GROUP BY A.BUSINESS_UNIT, A.PO_REF, A.BILL_TO_CUST_ID, REPLACE(CONCAT(CONCAT(E.NAME2,' '),E.NAME1),'/',' ')
    	, E.CORPORATE_CUST_ID, REPLACE(CONCAT(CONCAT(E0.NAME2,' '),E0.NAME1),'/',' '), A.BILL_TYPE_ID, A.BILL_STATUS, COALESCE(S.INSTALL_NBR,S0.INSTALL_NBR), A.INVOICE, A.INVOICE_DT
		, CASE WHEN I.DUE_DT IS NULL THEN (CASE WHEN A.PYMNT_TERMS_CD IN ('000','0000','00000') THEN A.DUE_DT ELSE T.DUE_DT END) ELSE I.DUE_DT END
		, A.TOT_VAT, A.INVOICE_AMT_PRETAX, A.INVOICE_AMOUNT, D.OPERATING_UNIT, D.CAMPUS, D.PRODUCT, D.NIVEL, B.ACCOUNTING_DT, I.BAL_CURRENCY
)
SELECT Y.*
FROM (
	SELECT X.BUSINESS_UNIT, X.PO_REF, X.BILL_TO_CUST_ID, X.NOMBRE_COMPLETO, X.CORPORATE_CUST_ID, X.NOMBRE_COMPLETO_CORPORATE, X.BILL_TYPE_ID, X.BILL_STATUS, X.INSTALL_NBR
		, X.INVOICE, X.INVOICE_DT, X.FECHA_VENCIMIENTO, X.TOT_VAT, X.INVOICE_AMT_PRETAX, X.INVOICE_AMOUNT, X.OPERATING_UNIT, X.CAMPUS, X.PRODUCT, X.NIVEL, X.ACCOUNTING_DT, X.BAL_CURRENCY
		, MAX(X.ACCOUNTING_DT) OVER(PARTITION BY X.INVOICE) AS MAX_ACCOUNTING_DT, X.SALDO_CALCULADO, X.MORA, X.GASTO_ADM, X.CUST_ID, X.WO_CASTI
	FROM PS_ITEM_ACTIVITY_RUN X
	WHERE X.ACCOUNTING_DT BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
	) Y
WHERE (ROUND(Y.SALDO_CALCULADO,3) <> 0 OR Y.WO_CASTI = 'WOCASTI') AND Y.ACCOUNTING_DT = Y.MAX_ACCOUNTING_DT
ORDER BY Y.INVOICE
;












