
SELECT I.OPERATING_UNIT, N.VALUE2 AS CAMPUS, I.PRODUCT, O.VALUE2 AS NIVEL, D.PO_REF, CASE WHEN SUBSTR(E.DRAWER_ID,1,1) = 'C' OR E.PAYMENT_METHOD_CDR = 'CSH' THEN 'CAJA' ELSE 'BANCO' END AS ORIGEN
	, D.BILL_TO_CUST_ID, REPLACE(CONCAT(CONCAT(J.NAME2,' '),J.NAME1),'/',' ') AS NOMBRE_COMPLETO, D.BILL_TYPE_ID, D.INVOICE, K.INVOICE2
	, NVL(E.PAYMENT_METHOD_CDR,G.PAYMENT_METHOD) AS FORMA_PAGO
	, NVL(CASE E.PAYMENT_METHOD_CDR
			WHEN 'CSH' THEN 'Efectivo'
			WHEN 'CC' THEN 'Tarjeta de Crédito'
			WHEN 'CV' THEN 'Boleta de Depósito'
			WHEN 'DC' THEN 'Tarjeta de Débito'
			WHEN 'PC' THEN 'Procurenment Card'
			WHEN 'EFT' THEN 'Asbanc'
			ELSE E.PAYMENT_METHOD_CDR END
		, CASE G.PAYMENT_METHOD
			WHEN 'CSH' THEN 'Efectivo'
			WHEN 'EFT' THEN 'Asbanc'
			ELSE G.PAYMENT_METHOD END) AS FORMA_PAGO_DESC
	, CASE WHEN F.CR_CARD_TYPE = ' ' OR F.CR_CARD_TYPE IS NULL THEN NULL ELSE F.CR_CARD_TYPE END AS TIPO_TARJETA
	, CASE
		WHEN F.CR_CARD_TYPE = '01' THEN 'Visa'
		WHEN F.CR_CARD_TYPE = '02' THEN 'MasterCard'
		WHEN F.CR_CARD_TYPE = '03' THEN 'Diners Club'
		WHEN F.CR_CARD_TYPE = '04' THEN 'Amex'
		WHEN NVL(E.PAYMENT_METHOD_CDR,G.PAYMENT_METHOD) = 'EFT' THEN 'Banco'
		WHEN NVL(E.PAYMENT_METHOD_CDR,G.PAYMENT_METHOD) = 'CSH' THEN 'Caja'
		WHEN NVL(E.PAYMENT_METHOD_CDR,G.PAYMENT_METHOD) = 'CV' THEN 'Depósito'
		WHEN F.CR_CARD_TYPE = ' ' THEN NULL
		ELSE F.CR_CARD_TYPE END AS TIPO_TARJETA_DESC
	, C.DEPOSIT_ID, C.PAYMENT_ID, E.DRAWER_ID, NVL(E.CREATEDTTM,C.ACCOUNTING_DT) AS FECHA_COBRANZA, C.ACCOUNTING_DT, C.POST_DT, D.INVOICE_DT
	, CASE WHEN A.DUE_DT IS NULL 
        THEN ( CASE WHEN D.PYMNT_TERMS_CD IN ('000','0000','00000') 
            THEN D.DUE_DT 
            ELSE M.DUE_DT END ) 
        ELSE A.DUE_DT END AS FECHA_VENCIMIENTO
	, D.INVOICE_AMOUNT, B.MONETARY_AMOUNT, G.PAYMENT_AMT
	, CASE WHEN B.MONETARY_AMOUNT = D.INVOICE_AMOUNT THEN 'TOTAL' ELSE 'PARCIAL' END AS PAGO
	, CASE WHEN G.PAYMENT_STATUS = 'C' AND G.WO_ADJ_USED_SW = 'Y' THEN 'Y' ELSE 'N' END AS ANULADO
	, CASE WHEN G.UNPOST_REASON = 'ERROR' THEN 'Y' ELSE 'N' END AS DESCONTABILIZADO
	, H.RECON_ID, G.BNK_ID_NBR, G.BANK_ACCOUNT_NUM, B.ACCOUNT, B.JOURNAL_ID, B.JOURNAL_DATE
	, CASE WHEN B.JOURNAL_ID = ' ' OR B.JOURNAL_ID IS NULL THEN 'Y' ELSE 'N' END AS MIGRADO
	--SUM(B.MONETARY_AMOUNT) AS MONTO_PAGO

FROM ODSMGR.PS_ITEM A

		INNER JOIN ODSMGR.PS_ITEM_DST B ON A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.ITEM = B.ITEM AND A.ITEM_LINE = B.ITEM_LINE AND B.LEDGER = 'ACTUALS'
											AND B.ACCOUNT NOT IN ('1140000','4000000')
											AND B.JOURNAL_DATE BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
											
		INNER JOIN ODSMGR.PS_ITEM_ACTIVITY C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.ITEM = C.ITEM AND A.ITEM_LINE = C.ITEM_LINE AND B.ITEM_SEQ_NUM = C.ITEM_SEQ_NUM AND C.ENTRY_TYPE = 'PY'											
											AND C.ACCOUNTING_DT BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
											
		INNER JOIN ODSMGR.PS_BI_HDR D ON A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.ITEM = D.INVOICE
		
		LEFT JOIN ODSMGR.PS_LI_PER_ARPMT_VW E ON C.BUSINESS_UNIT = E.DEPOSIT_BU AND C.DEPOSIT_ID = E.DEPOSIT_ID AND C.PAYMENT_ID = E.PAYMENT_ID AND C.PAYMENT_SEQ_NUM = E.PAYMENT_SEQ_NUM AND C.ITEM = E.INVOICE
		
		LEFT JOIN ODSMGR.PS_LI_GBL_ARPY_DTL F ON E.DEPOSIT_BU = F.DEPOSIT_BU AND E.PYMNT_REF_ID = F.PYMNT_REF_ID
		
		LEFT JOIN ODSMGR.PS_PAYMENT G ON C.BUSINESS_UNIT = G.DEPOSIT_BU AND C.PAYMENT_ID = G.PAYMENT_ID AND C.PAYMENT_SEQ_NUM = G.PAYMENT_SEQ_NUM AND C.DEPOSIT_ID = G.DEPOSIT_ID
		
		LEFT JOIN ODSMGR.PS_CDR_RECEIPT H ON E.DEPOSIT_BU = H.DEPOSIT_BU AND E.RECEIPT_NBR = H.RECEIPT_NBR
		
		LEFT JOIN ODSMGR.PS_BI_LINE_DST I ON D.BUSINESS_UNIT = I.BUSINESS_UNIT AND D.INVOICE = I.INVOICE
												AND I.LINE_SEQ_NUM = (SELECT MAX(I1.LINE_SEQ_NUM) FROM ODSMGR.PS_BI_LINE_DST I1 WHERE I1.BUSINESS_UNIT = I.BUSINESS_UNIT AND I1.INVOICE = I.INVOICE)
		
		LEFT JOIN ODSMGR.PS_CUSTOMER J ON D.BILL_TO_CUST_ID = J.CUST_ID
												
		LEFT JOIN ODSMGR.PS_LI_GBL_BI_INV K ON D.BUSINESS_UNIT = K.BUSINESS_UNIT AND D.INVOICE = K.INVOICE
		
		LEFT JOIN ODSMGR.PS_PAY_TRMS_NET L ON D.BUSINESS_UNIT = L.SETID AND D.PYMNT_TERMS_CD = L.PYMNT_TERMS_CD AND L.EFFDT <= CURRENT_DATE
			
		LEFT JOIN ODSMGR.PS_PAY_TRMS_TIME M ON L.SETID = M.SETID AND L.PAY_TRMS_TIME_ID = M.PAY_TRMS_TIME_ID
		
		LEFT JOIN ODSMGR.LOE_BASE_TABLE_EQUIV N ON I.OPERATING_UNIT = N.VALUE1 AND N.TABLE_PARENT_ID = 1
		
		LEFT JOIN ODSMGR.LOE_BASE_TABLE_EQUIV O ON I.PRODUCT = O.VALUE1 AND O.TABLE_PARENT_ID = 9
		
WHERE A.BUSINESS_UNIT = 'PER03' AND (A.CUST_ID <> '9999999999' OR A.CUST_ID IS NULL)

