--Convalidaciones_ICACIT
--ID	ESTUDIANTE	CARRERA	COD CARRERA	PERIODO DE CONV	COD CURSO CONV	CURSO CONV	CRED CURSO CONV	TIPO DE CURSO	INSTITUCION ORIGEN	TIPO DE INSTITUCION ORIGEN
SELECT DISTINCT
	A.SHRTRIT_PIDM AS PIDM, SPRIDEN_ID AS ID, SPRIDEN_LAST_NAME ||', '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE, SMRPRLE_PROGRAM_DESC AS CARRERA, SOVLCUR_PROGRAM AS COD_CARRERA
	, A.SHRTRAM_TERM_CODE_ENTERED AS PERIODO_CONV, A.SHRTRCE_SUBJ_CODE || A.SHRTRCE_CRSE_NUMB AS COD_CURSO, A.SHRTRCE_CRSE_TITLE AS CURSO_CONV, A.SHRTRCE_CREDIT_HOURS AS CRED_CURSO_CONV
	, COALESCE(MAX(CASE COALESCE(B.SSBSECT_INSM_CODE,B0.SSBSECT_INSM_CODE) WHEN 'P' THEN 'Presencial' WHEN 'S' THEN 'Semipresencial' WHEN 'V' THEN 'Virtual' END)
		OVER(PARTITION BY A.SHRTRAM_TERM_CODE_ENTERED, A.SHRTRCE_SUBJ_CODE, A.SHRTRCE_CRSE_NUMB),'Presencial') AS TIPO_CURSO
	, STVSBGI_DESC AS INSTITUCION_ORIGEN, CASE STVSBGI_TYPE_IND WHEN 'C' THEN 'UNIVERSIDAD' WHEN 'H' THEN 'INSTITUTO' ELSE STVSBGI_TYPE_IND END AS TIPO_INSTITUCION_ORIGEN
FROM 
    (SELECT DISTINCT
        SHRTRIT_PIDM, SHRTRIT_SEQ_NO, SHRTRIT_SBGI_CODE, SHRTRIT_OFFICIAL_TRANS_IND
        , SHRTRAM_SEQ_NO, SHRTRAM_LEVL_CODE, SHRTRAM_TERM_CODE_ENTERED, SHRTRAM_ACCEPTANCE_DATE
        , SHRTRCE_SEQ_NO, SHRTRCE_SUBJ_CODE, SHRTRCE_CRSE_NUMB, SHRTRCE_CRSE_TITLE, SHRTRCE_CREDIT_HOURS, SHRTRCE_GRDE_CODE, SHRTRCE_ACTIVITY_DATE
    FROM ODSMGR.SHRTRIT, ODSMGR.SHRTRAM, ODSMGR.SHRTRCE
    WHERE SHRTRIT_PIDM = SHRTRAM_PIDM AND SHRTRIT_SEQ_NO = SHRTRAM_TRIT_SEQ_NO
        AND SHRTRIT_PIDM = SHRTRCE_PIDM AND SHRTRIT_SEQ_NO = SHRTRCE_TRIT_SEQ_NO AND SHRTRAM_SEQ_NO = SHRTRCE_TRAM_SEQ_NO
        AND TO_CHAR(SHRTRCE_ACTIVITY_DATE,'YYYY') = '2019'
	) A
		LEFT JOIN ODSMGR.LOE_SSBSECT B ON A.SHRTRCE_SUBJ_CODE = B.SSBSECT_SUBJ_CODE AND A.SHRTRCE_CRSE_NUMB = B.SSBSECT_CRSE_NUMB
											AND B.SSBSECT_TERM_CODE = (SELECT MAX(B1.SSBSECT_TERM_CODE) FROM ODSMGR.LOE_SSBSECT B1
																		WHERE B1.SSBSECT_SUBJ_CODE = A.SHRTRCE_SUBJ_CODE AND B1.SSBSECT_CRSE_NUMB = A.SHRTRCE_CRSE_NUMB
																			AND B1.SSBSECT_TERM_CODE <= A.SHRTRAM_TERM_CODE_ENTERED)
		LEFT JOIN ODSMGR.LOE_SSBSECT B0 ON A.SHRTRCE_SUBJ_CODE = B0.SSBSECT_SUBJ_CODE AND A.SHRTRCE_CRSE_NUMB = B0.SSBSECT_CRSE_NUMB
											AND B0.SSBSECT_TERM_CODE = (SELECT MIN(B2.SSBSECT_TERM_CODE) FROM ODSMGR.LOE_SSBSECT B2
																		WHERE B2.SSBSECT_SUBJ_CODE = A.SHRTRCE_SUBJ_CODE AND B2.SSBSECT_CRSE_NUMB = A.SHRTRCE_CRSE_NUMB
																			AND B2.SSBSECT_TERM_CODE > A.SHRTRAM_TERM_CODE_ENTERED)
	    LEFT JOIN ODSMGR.LOE_SPRIDEN ON A.SHRTRIT_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
	    LEFT JOIN ODSMGR.STVSBGI ON A.SHRTRIT_SBGI_CODE = STVSBGI_CODE
	    LEFT JOIN ODSMGR.LOE_SOVLCUR ON A.SHRTRIT_PIDM = SOVLCUR_PIDM AND A.SHRTRAM_LEVL_CODE = SOVLCUR_LEVL_CODE AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LMOD_CODE = 'LEARNER'
	    LEFT JOIN ODSMGR.SMRPRLE ON SOVLCUR_PROGRAM = SMRPRLE_PROGRAM
WHERE SOVLCUR_PROGRAM IN ('CIV-UG','CIV-WA') AND SOVLCUR_CAMP_CODE = 'TSI'
ORDER BY A.SHRTRIT_PIDM, A.SHRTRAM_TERM_CODE_ENTERED
;
