SELECT DISTINCT
    a.SHRTRIT_PIDM AS PIDM, SPRIDEN_ID AS ID, SPRIDEN_LAST_NAME AS APELLIDOS, SPRIDEN_FIRST_NAME AS NOMBRES
    , a.SHRTRIT_SBGI_CODE AS COD_INSTITUCION, c.STVSBGI_DESC AS INSTITUCION
    , CASE c.STVSBGI_TYPE_IND 
          WHEN 'C' THEN 'UNIVERSIDAD' 
          WHEN 'H' THEN 'INSTITUTO' 
      ELSE c.STVSBGI_TYPE_IND END AS TIPO_INSTITUCION
    , a.SHRTRIT_OFFICIAL_TRANS_IND AS OFICIAL, a.SHRTRAM_LEVL_CODE AS NIVEL, a.SHRTRAM_TERM_CODE_ENTERED AS PERIODO_CONV
    , a.SHRTRCR_SEQ_NO AS SEQ_TRANSF, a.SHRTRCR_TCRSE_TITLE AS CURSO_TRANSF, a.SHRTRCR_TRANS_GRADE AS CURSO_NOTA_TRANSF
    , a.SHRTRCE_SEQ_NO AS SEQ_EQUIV, a.SHRTRCE_CRSE_TITLE AS CURSO_EQUIV, a.SHRTRCE_CREDIT_HOURS AS CURSO_CRED_EQUIV, a.SHRTRCE_ACTIVITY_DATE AS FECHA
    , d.SOVLCUR_CAMP_CODE AS COD_CAMPUS_CURR, e.STVCAMP_DESC AS CAMPUS_CURR, d.SOVLCUR_PROGRAM AS PROGRAMA_CURR
    , CASE WHEN SUBSTR(d.SOVLCUR_PROGRAM,5,2) IN ('UG','WA') THEN SUBSTR(d.SOVLCUR_PROGRAM,5,2) ELSE NULL END AS TIPO_PROGRAMA_CURR
FROM 
    ((((SELECT 
        SHRTRIT_PIDM, SHRTRIT_SEQ_NO, SHRTRIT_SBGI_CODE, SHRTRIT_OFFICIAL_TRANS_IND
        , SHRTRAM_SEQ_NO, SHRTRAM_LEVL_CODE, SHRTRAM_TERM_CODE_ENTERED, SHRTRAM_ACCEPTANCE_DATE
        , SHRTRCR_SEQ_NO, SHRTRCR_TRANS_COURSE_NAME, SHRTRCR_TRANS_COURSE_NUMBERS, SHRTRCR_TRANS_CREDIT_HOURS, SHRTRCR_TRANS_GRADE, SHRTRCR_ACTIVITY_DATE, SHRTRCR_TCRSE_TITLE
        , SHRTRCE_SEQ_NO, SHRTRCE_SUBJ_CODE, SHRTRCE_CRSE_NUMB, SHRTRCE_CRSE_TITLE, SHRTRCE_CREDIT_HOURS, SHRTRCE_GRDE_CODE, SHRTRCE_ACTIVITY_DATE
    FROM SHRTRIT, SHRTRAM, SHRTRCR, SHRTRCE
    WHERE SHRTRIT_PIDM = SHRTRAM_PIDM AND SHRTRIT_SEQ_NO = SHRTRAM_TRIT_SEQ_NO 
        AND SHRTRIT_PIDM = SHRTRCR_PIDM AND SHRTRIT_SEQ_NO = SHRTRCR_TRIT_SEQ_NO AND SHRTRAM_SEQ_NO = SHRTRCR_TRAM_SEQ_NO
        AND SHRTRIT_PIDM = SHRTRCE_PIDM AND SHRTRIT_SEQ_NO = SHRTRCE_TRIT_SEQ_NO AND SHRTRAM_SEQ_NO = SHRTRCE_TRAM_SEQ_NO AND SHRTRCR_SEQ_NO = SHRTRCE_TRCR_SEQ_NO
        AND TO_CHAR(SHRTRCE_ACTIVITY_DATE,'YYYY') = '2018') a
        LEFT JOIN SPRIDEN b ON
            a.SHRTRIT_PIDM = b.SPRIDEN_PIDM
            AND b.SPRIDEN_CHANGE_IND IS NULL)
        LEFT JOIN STVSBGI c ON
            a.SHRTRIT_SBGI_CODE = c.STVSBGI_CODE)
        LEFT JOIN LOE_SOVLCUR d ON
            a.SHRTRIT_PIDM = d.SOVLCUR_PIDM
            AND a.SHRTRAM_LEVL_CODE = d.SOVLCUR_LEVL_CODE
            AND d.SOVLCUR_CACT_CODE = 'ACTIVE'
            AND d.SOVLCUR_CURRENT_IND = 'Y'
            AND d.SOVLCUR_LMOD_CODE = 'LEARNER')
        LEFT JOIN STVCAMP e ON
            d.SOVLCUR_CAMP_CODE = e.STVCAMP_CODE
--WHERE a.SHRTRIT_PIDM = 32531
ORDER BY a.SHRTRIT_PIDM, a.SHRTRAM_TERM_CODE_ENTERED, a.SHRTRCR_SEQ_NO, a.SHRTRCE_SEQ_NO;

