
SELECT SHRTRCE_PIDM, SPRIDEN_ID, CONCAT(CONCAT(SPRIDEN_LAST_NAME,', '),SPRIDEN_FIRST_NAME) AS ESTUDIANTE, SHRTRCE_LEVL_CODE
    , SHRTRCE_TERM_CODE_EFF, COUNT(SHRTRCE_CREDIT_HOURS) AS CURSOS, SUM(SHRTRCE_CREDIT_HOURS) AS CREDITOS
    , SHRTRAM_USER_ID, MAX(SHRTRCE_ACTIVITY_DATE) AS FECHA, a.SOVLCUR_CAMP_CODE, a.SOVLCUR_PROGRAM, a.SOVLCUR_ADMT_CODE
    , MIN(b.SOVLCUR_TERM_CODE_ADMIT) AS PERIODO_ADMISION
FROM SHRTRCE, SHRTRAM, SPRIDEN, LOE_SOVLCUR a, LOE_SOVLCUR b
WHERE SHRTRCE_PIDM = SHRTRAM_PIDM AND SHRTRCE_TRIT_SEQ_NO = SHRTRAM_TRIT_SEQ_NO AND SHRTRCE_TRAM_SEQ_NO = SHRTRAM_SEQ_NO
    AND SHRTRCE_TERM_CODE_EFF = SHRTRAM_TERM_CODE_ENTERED AND SHRTRCE_LEVL_CODE = SHRTRAM_LEVL_CODE AND SHRTRCE_LEVL_CODE = 'UG'
    AND (TO_CHAR(SHRTRCE_ACTIVITY_DATE,'YYYY') = '2019' OR TO_CHAR(SHRTRAM_ACCEPTANCE_DATE,'YYYY') = '2019')
    AND SHRTRCE_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SHRTRCE_PIDM = a.SOVLCUR_PIDM(+) AND SHRTRCE_LEVL_CODE = a.SOVLCUR_LEVL_CODE(+)
    AND a.SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND a.SOVLCUR_CACT_CODE(+) = 'ACTIVE' AND a.SOVLCUR_CURRENT_IND(+) = 'Y'
    AND SHRTRCE_PIDM = b.SOVLCUR_PIDM(+) AND SHRTRCE_LEVL_CODE = b.SOVLCUR_LEVL_CODE(+)
    AND b.SOVLCUR_TERM_CODE_ADMIT(+) <> '000000' AND b.SOVLCUR_TERM_CODE_ADMIT(+) IS NOT NULL
GROUP BY SHRTRCE_PIDM, SPRIDEN_ID, CONCAT(CONCAT(SPRIDEN_LAST_NAME,', '),SPRIDEN_FIRST_NAME), SHRTRCE_LEVL_CODE
    , SHRTRCE_TERM_CODE_EFF, SHRTRAM_USER_ID, a.SOVLCUR_CAMP_CODE, a.SOVLCUR_PROGRAM, a.SOVLCUR_ADMT_CODE;
