--Convalidaciones_Detalle_
SELECT DISTINCT
    a.SHRTRIT_PIDM AS PIDM, b.SPRIDEN_ID AS ID, b.SPRIDEN_LAST_NAME ||', '|| b.SPRIDEN_FIRST_NAME AS ESTUDIANTE, d.SOVLCUR_LEVL_CODE AS NIVEL
    , d.SOVLCUR_TERM_CODE_ADMIT AS PERIODO_ADMISION, F.SMRPRLE_PROGRAM_DESC AS CARRERA, d.SOVLCUR_PROGRAM AS COD_CARRERA, G.STVADMT_DESC AS TIPO_INGRESO
    , CASE 
		WHEN d.SOVLCUR_ADMT_CODE <> 'RE' AND I.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
		WHEN J.ACTIVITY = 'DTO' AND I.STUDENT_ATTRIBUTE = 'TINT' THEN 'Doble Titulacion OUT'
		WHEN J.ACTIVITY = 'ITO' AND I.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
		WHEN d.SOVLCUR_LEVL_CODE = 'UG' AND H.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
		WHEN d.SOVLCUR_LEVL_CODE = 'UG' AND H.COHORT = 'REINGRESO' THEN 'Reingreso'
		WHEN d.SOVLCUR_ADMT_CODE = 'II' THEN 'Intercambio IN'
		WHEN d.SOVLCUR_STYP_CODE = 'N' THEN 'Nuevo'
		WHEN d.SOVLCUR_STYP_CODE = 'C' OR d.SOVLCUR_STYP_CODE IS NULL THEN 'Continuo'
		ELSE d.SOVLCUR_STYP_CODE END AS TIPO_ESTUDIANTE
    , a.SHRTRAM_TERM_CODE_ENTERED AS PERIODO_CONV, a.SHRTRIT_SBGI_CODE AS COD_INSTITUCION, c.STVSBGI_DESC AS INSTITUCION
    , CASE c.STVSBGI_TYPE_IND WHEN 'C' THEN 'UNIVERSIDAD' WHEN 'H' THEN 'INSTITUTO' ELSE c.STVSBGI_TYPE_IND END AS TIPO_INSTITUCION
    --, a.SHRTRIT_OFFICIAL_TRANS_IND AS OFICIAL, a.SHRTRAM_LEVL_CODE AS NIVEL, a.SHRTRCR_SEQ_NO AS SEQ_TRANSF
    , a.SHRTRCR_TCRSE_TITLE AS CURSO_PROCEDENCIA, a.SHRTRCR_TRANS_CREDIT_HOURS AS CR_CURSO_PROCEDENCIA, a.SHRTRCR_TRANS_GRADE AS NOTA_CURSO_PROCEDENCIA --, a.SHRTRCE_SEQ_NO AS SEQ_EQUIV
    , a.SHRTRCE_CRSE_TITLE AS CURSO_CONV, a.SHRTRCE_SUBJ_CODE || a.SHRTRCE_CRSE_NUMB AS COD_CURSO_CONV, a.SHRTRCE_CREDIT_HOURS AS CR_CURSO_CONV, a.SHRTRCE_ACTIVITY_DATE AS FECHA_REGISTRO
    /*, d.SOVLCUR_CAMP_CODE AS COD_CAMPUS_CURR, e.STVCAMP_DESC AS CAMPUS_CURR, d.SOVLCUR_PROGRAM AS PROGRAMA_CURR
    , CASE WHEN SUBSTR(d.SOVLCUR_PROGRAM,5,2) IN ('UG','WA') THEN SUBSTR(d.SOVLCUR_PROGRAM,5,2) ELSE NULL END AS TIPO_PROGRAMA_CURR*/
FROM 
    (SELECT 
        SHRTRIT_PIDM, SHRTRIT_SEQ_NO, SHRTRIT_SBGI_CODE, SHRTRIT_OFFICIAL_TRANS_IND
        , SHRTRAM_SEQ_NO, SHRTRAM_LEVL_CODE, SHRTRAM_TERM_CODE_ENTERED, SHRTRAM_ACCEPTANCE_DATE
        , SHRTRCR_SEQ_NO, SHRTRCR_TRANS_COURSE_NAME, SHRTRCR_TRANS_COURSE_NUMBERS, SHRTRCR_TRANS_CREDIT_HOURS, SHRTRCR_TRANS_GRADE, SHRTRCR_ACTIVITY_DATE, SHRTRCR_TCRSE_TITLE
        , SHRTRCE_SEQ_NO, SHRTRCE_SUBJ_CODE, SHRTRCE_CRSE_NUMB, SHRTRCE_CRSE_TITLE, SHRTRCE_CREDIT_HOURS, SHRTRCE_GRDE_CODE, SHRTRCE_ACTIVITY_DATE
    FROM SHRTRIT, SHRTRAM, SHRTRCR, SHRTRCE
    WHERE SHRTRIT_PIDM = SHRTRAM_PIDM AND SHRTRIT_SEQ_NO = SHRTRAM_TRIT_SEQ_NO 
        AND SHRTRIT_PIDM = SHRTRCR_PIDM AND SHRTRIT_SEQ_NO = SHRTRCR_TRIT_SEQ_NO AND SHRTRAM_SEQ_NO = SHRTRCR_TRAM_SEQ_NO
        AND SHRTRIT_PIDM = SHRTRCE_PIDM AND SHRTRIT_SEQ_NO = SHRTRCE_TRIT_SEQ_NO AND SHRTRAM_SEQ_NO = SHRTRCE_TRAM_SEQ_NO AND SHRTRCR_SEQ_NO = SHRTRCE_TRCR_SEQ_NO
        AND TO_CHAR(SHRTRCE_ACTIVITY_DATE,'YYYYMM') > '201908'
	) a
	    LEFT JOIN SPRIDEN b ON a.SHRTRIT_PIDM = b.SPRIDEN_PIDM AND b.SPRIDEN_CHANGE_IND IS NULL
	    LEFT JOIN STVSBGI c ON a.SHRTRIT_SBGI_CODE = c.STVSBGI_CODE
	    LEFT JOIN LOE_SOVLCUR d ON a.SHRTRIT_PIDM = d.SOVLCUR_PIDM AND a.SHRTRAM_LEVL_CODE = d.SOVLCUR_LEVL_CODE AND d.SOVLCUR_CACT_CODE = 'ACTIVE' AND d.SOVLCUR_CURRENT_IND = 'Y' AND d.SOVLCUR_LMOD_CODE = 'LEARNER'	    
	    --LEFT JOIN ODSMGR.STVCAMP e ON d.SOVLCUR_CAMP_CODE = e.STVCAMP_CODE
	    LEFT JOIN SMRPRLE F ON d.SOVLCUR_PROGRAM = F.SMRPRLE_PROGRAM
	    LEFT JOIN STVADMT G ON d.SOVLCUR_ADMT_CODE = G.STVADMT_CODE
	    LEFT JOIN STUDENT_COHORT H ON d.SOVLCUR_PIDM = H.PERSON_UID AND H.COHORT_ACTIVE_IND = 'Y' AND H.COHORT IN ('NEW_REING','REINGRESO') AND H.ACADEMIC_PERIOD IN ('220435','220534')
	    LEFT JOIN STUDENT_ATTRIBUTE I ON d.SOVLCUR_PIDM = I.PERSON_UID AND I.STUDENT_ATTRIBUTE IN ('TINT') AND I.ACADEMIC_PERIOD IN ('220435','220534')
	    LEFT JOIN STUDENT_ACTIVITY J ON d.SOVLCUR_PIDM = J.PERSON_UID AND J.ACTIVITY = 'ITO' AND J.ACADEMIC_PERIOD IN ('220435','220534')
--WHERE a.SHRTRIT_PIDM = 32531
ORDER BY a.SHRTRIT_PIDM, a.SHRTRAM_TERM_CODE_ENTERED, a.SHRTRCE_SUBJ_CODE || a.SHRTRCE_CRSE_NUMB
;