--DA002_
SELECT SSBSECT_TERM_CODE AS PERIODO, SSBSECT_CAMP_CODE AS CAMPUS, SSRATTR_ATTR_CODE AS COD_PROG, STVATTR_DESC AS PROGRAMA, SSBSECT_SUBJ_CODE || SSBSECT_CRSE_NUMB AS COD_CURSO
    , SCBCRSE_TITLE AS NOMBRE_CURSO, CICLO, SSBSECT_CRN AS NRC, STVSSTS_DESC AS ESTATUS, SSRXLST_XLST_GROUP AS LST_CRZ, SSBSECT_SCHD_CODE AS TIP_HOR, SSBSECT_INSM_CODE AS MET_EDU
    , SSBSECT_MAX_ENRL AS MAXIMO, SSBSECT_ENRL AS REAL, SSBSECT_SEATS_AVAIL AS RESTANTE, SCBCRSE_BILL_HR_LOW AS HRS_CREDITO, SPRIDEN_ID AS ID_DOCENTE, DOCENTE_NAME AS DOCENTE
    , SIRASGN_PRIMARY_IND AS ID_PRINC, STVWKLD_DESC AS TIPO_JORNADA, STVFCST_DESC AS ESTADO_DOCENTE, SSRMEET_START_DATE AS FECHA_INICIO, SSRMEET_END_DATE AS FECHA_FIN
    , SSRMEET_MON_DAY AS LUNES, SSRMEET_TUE_DAY AS MARTES, SSRMEET_WED_DAY AS MIERCOLES, SSRMEET_THU_DAY AS JUEVES, SSRMEET_FRI_DAY AS VIERNES, SSRMEET_SAT_DAY AS SABADO, SSRMEET_SUN_DAY AS DOMINGO
    , CASE WHEN SSRMEET_BEGIN_TIME IS NOT NULL THEN SSRMEET_BEGIN_TIME ||' - '|| SSRMEET_END_TIME END AS HORA
    , SSRMEET_BLDG_CODE AS EDIFICIO, SSRMEET_ROOM_CODE AS AULA, SSRRPRG_PROGRAM_IND AS INCLUIR_EXCLUIR_PROG, SSRRPRG_PROGRAM AS COD_PROGRAMAS_COMPARTIDOS, SMRPRLE_PROGRAM_DESC AS PROGRAMAS_COMPARTIDOS
    , SSRRCMP_CAMP_IND AS INCLUIR_EXCLUIR_CAMP, SSRRCMP_CAMP_CODE AS CAMPUS_COMPARTIDOS, SSBSECT_PREREQ_CHK_METHOD_CDE AS TIPO_PRERREQUISITO, REQUISITOS, BLOQUES_HORARIOS
FROM (SELECT DISTINCT
          SSBSECT_TERM_CODE, SSBSECT_CRN, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB, SSBSECT_SSTS_CODE, STVSSTS_DESC, SSBSECT_SCHD_CODE
          , SSBSECT_CAMP_CODE, SCBCRSE_TITLE, SCBCRSE_BILL_HR_LOW, SSBSECT_MAX_ENRL, SSBSECT_ENRL, SSBSECT_SEATS_AVAIL, SSBSECT_INSM_CODE
          , SSBSECT_PREREQ_CHK_METHOD_CDE, SSRXLST_XLST_GROUP, SSRMEET_BEGIN_TIME, SSRMEET_END_TIME, SSRMEET_BLDG_CODE, SSRMEET_ROOM_CODE
          , SSRMEET_START_DATE, SSRMEET_END_DATE, SSRMEET_CATAGORY, SIRASGN_PIDM, SPRIDEN_ID, TRIM(SPRIDEN_LAST_NAME||' '||SPRIDEN_FIRST_NAME) AS DOCENTE_NAME
          , SIRASGN_PRIMARY_IND, SIBINST_TERM_CODE_EFF, SIBINST_FCST_CODE, STVFCST_DESC, SIBINST_WKLD_CODE, STVWKLD_DESC
          , SSRMEET_SUN_DAY, SSRMEET_MON_DAY, SSRMEET_TUE_DAY, SSRMEET_WED_DAY, SSRMEET_THU_DAY, SSRMEET_FRI_DAY, SSRMEET_SAT_DAY
          , SSRMEET_HRS_WEEK, SSRATTR_ATTR_CODE, STVATTR_DESC, SSRRPRG_PROGRAM_IND, SSRRPRG_PROGRAM, SMRPRLE_PROGRAM_DESC, SSRRCMP_CAMP_IND, SSRRCMP_CAMP_CODE
          , TRIM(REQUISITOS) AS REQUISITOS, TRIM(BLOQUES_HORARIOS) AS BLOQUES_HORARIOS, CICLO
      FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSBSECT 
			LEFT JOIN (SELECT
							SCBCRSE_SUBJ_CODE, SCBCRSE_CRSE_NUMB, SCBCRSE_EFF_TERM, SCBCRSE_CSTA_CODE, SCBCRSE_TITLE, SCBCRSE_BILL_HR_LOW
							, MAX(SCBCRSE_EFF_TERM) OVER(PARTITION BY SCBCRSE_SUBJ_CODE, SCBCRSE_CRSE_NUMB) AS SCBCRSE_MAX_TERM
						FROM UPN_RPT_DM_PROD.ODSMGR.SCBCRSE
                      ) TEMP_SCBCRSE ON SSBSECT_SUBJ_CODE = SCBCRSE_SUBJ_CODE 
                                    AND SSBSECT_CRSE_NUMB = SCBCRSE_CRSE_NUMB
                                    AND SCBCRSE_EFF_TERM = SCBCRSE_MAX_TERM
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.SSRXLST ON SSBSECT_TERM_CODE = SSRXLST_TERM_CODE AND SSBSECT_CRN = SSRXLST_CRN
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.STVSSTS ON SSBSECT_SSTS_CODE = STVSSTS_CODE
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.SSRMEET ON SSBSECT_TERM_CODE = SSRMEET_TERM_CODE AND SSBSECT_CRN = SSRMEET_CRN
			LEFT JOIN (SELECT SIRASGN_TERM_CODE, SIRASGN_CRN, SIRASGN_PIDM, SIRASGN_CATEGORY, SIRASGN_PRIMARY_IND
							, SIBINST_TERM_CODE_EFF, SIBINST_FCST_CODE, SIBINST_WKLD_CODE
							, MAX(SIBINST_TERM_CODE_EFF) OVER(PARTITION BY SIRASGN_PIDM, SIRASGN_TERM_CODE) AS MAX_PERIOD_DOCENTE
						FROM UPN_RPT_DM_PROD.ODSMGR.SIRASGN
								LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.LOE_SIBINST ON SIRASGN_PIDM = SIBINST_PIDM AND SIRASGN_TERM_CODE >= SIBINST_TERM_CODE_EFF
																			AND (SUBSTR(SIRASGN_TERM_CODE,4,1) = SUBSTR(SIBINST_TERM_CODE_EFF,4,1) OR SUBSTR(SIBINST_TERM_CODE_EFF,4,1) NOT IN ('3','4','5'))
					) SIRASGN ON SSRMEET_TERM_CODE = SIRASGN_TERM_CODE AND SSRMEET_CRN = SIRASGN_CRN 
							AND SSRMEET_CATAGORY = SIRASGN_CATEGORY AND SIBINST_TERM_CODE_EFF = MAX_PERIOD_DOCENTE
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.LOE_SPRIDEN ON SIRASGN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.STVFCST ON SIBINST_FCST_CODE = STVFCST_CODE
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.STVWKLD ON SIBINST_WKLD_CODE = STVWKLD_CODE
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.SSRATTR ON SSBSECT_TERM_CODE = SSRATTR_TERM_CODE AND SSBSECT_CRN = SSRATTR_CRN
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.STVATTR ON SSRATTR_ATTR_CODE = STVATTR_CODE
			LEFT JOIN (SELECT SSRRPRG_TERM_CODE AS SSRRPRG_TERM_CODE_1, SSRRPRG_CRN AS SSRRPRG_CRN_1, SSRRPRG_PROGRAM_IND
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRRPRG WHERE SSRRPRG_REC_TYPE = 1
					  ) LOE_SSRRPRG ON SSBSECT_TERM_CODE = SSRRPRG_TERM_CODE_1 AND SSBSECT_CRN = SSRRPRG_CRN_1
			LEFT JOIN (SELECT SSRRPRG_TERM_CODE AS SSRRPRG_TERM_CODE_2, SSRRPRG_CRN AS SSRRPRG_CRN_2, SSRRPRG_PROGRAM
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRRPRG WHERE SSRRPRG_REC_TYPE = 2
					  ) LOE_SSRRPRG_1 ON SSBSECT_TERM_CODE = SSRRPRG_TERM_CODE_2 AND SSBSECT_CRN = SSRRPRG_CRN_2
			LEFT JOIN UPN_RPT_DM_PROD.ODSMGR.LOE_SMRPRLE ON SSRRPRG_PROGRAM = SMRPRLE_PROGRAM
			LEFT JOIN (SELECT SSRRCMP_TERM_CODE AS SSRRCMP_TERM_CODE_1, SSRRCMP_CRN AS SSRRCMP_CRN_1, SSRRCMP_CAMP_IND
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRRCMP WHERE SSRRCMP_REC_TYPE = 1
					  ) LOE_SSRRCMP_2 ON SSBSECT_TERM_CODE = SSRRCMP_TERM_CODE_1 AND SSBSECT_CRN = SSRRCMP_CRN_1
			LEFT JOIN (SELECT SSRRCMP_TERM_CODE AS SSRRCMP_TERM_CODE_2, SSRRCMP_CRN AS SSRRCMP_CRN_2, SSRRCMP_CAMP_CODE
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRRCMP WHERE SSRRCMP_REC_TYPE = 2
					  ) LOE_SSRRCMP_3 ON SSBSECT_TERM_CODE = SSRRCMP_TERM_CODE_2 AND SSBSECT_CRN = SSRRCMP_CRN_2
			LEFT JOIN (SELECT DISTINCT SSRRTST_TERM_CODE, SSRRTST_CRN
							, LISTAGG(' ' || TRIM(SSRRTST_CONNECTOR || ' ' || SSRRTST_LPAREN 
									  || SSRRTST_TESC_CODE || SSRRTST_TEST_SCORE 
									  || SSRRTST_SUBJ_CODE_PREQ || SSRRTST_CRSE_NUMB_PREQ 
									  || SSRRTST_RPAREN)) WITHIN GROUP (ORDER BY SSRRTST_SEQNO) AS REQUISITOS
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRRTST GROUP BY SSRRTST_TERM_CODE, SSRRTST_CRN
					  ) LOE_SSRRTST ON SSBSECT_TERM_CODE = SSRRTST_TERM_CODE AND SSBSECT_CRN = SSRRTST_CRN
		LEFT JOIN (SELECT DISTINCT SSRBLCK_TERM_CODE, SSRBLCK_CRN
							, LISTAGG(' ' || SSRBLCK_BLCK_CODE) WITHIN GROUP (ORDER BY SSRBLCK_BLCK_CODE) AS BLOQUES_HORARIOS
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_SSRBLCK GROUP BY SSRBLCK_TERM_CODE, SSRBLCK_CRN
					  ) LOE_SSRBLCK ON SSBSECT_TERM_CODE = SSRBLCK_TERM_CODE AND SSBSECT_CRN = SSRBLCK_CRN
		LEFT JOIN (SELECT DISTINCT SUBJ_CODE, CRSE_NUMB_LOW, SUBSTR(AREA_COURSE,1,4) AS MAJOR, TERM_CODE_EFF
							, MAX(TERM_CODE_EFF) OVER(PARTITION BY SUBJ_CODE,CRSE_NUMB_LOW,SUBSTR(AREA_COURSE,1,4)) AS MAX_TERM
							, CASE WHEN SUBSTR(AREA_COURSE,LENGTH(AREA_COURSE)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
								THEN TO_NUMBER(SUBSTR(AREA_COURSE,LENGTH(AREA_COURSE)-1)) END AS CICLO
						FROM UPN_RPT_DM_PROD.ODSMGR.LOE_AREA_COURSE
					  ) LOE_AREA_COURSE ON SSBSECT_SUBJ_CODE = SUBJ_CODE AND SSBSECT_CRSE_NUMB = CRSE_NUMB_LOW
                                        AND SSRATTR_ATTR_CODE = MAJOR AND TERM_CODE_EFF = MAX_TERM
	WHERE SSBSECT_TERM_CODE IN ('221502') --INGRESAR PERIODO
	ORDER BY SSBSECT_TERM_CODE, SSBSECT_CRN, SSRRPRG_PROGRAM
	)
;