
SELECT 
    PROGRAM, TERM_CODE_EFF, AREA, COD_CURSO, CURSO, CR, HT, HL, HP, REQUISITOS, EQUIVALENCIAS
FROM (SELECT 
          a.PROGRAM, a.TERM_CODE_EFF, a.AREA, a.AREA_PRIORITY, a.SEQNO, a.AREA_RULE, a.SMRARUL_SEQNO, a.SUBJECT, a.CRSE_NUMB
          , a.SUBJECT || a.CRSE_NUMB AS COD_CURSO, CASE WHEN a.CURSO IS NULL THEN '  *  ' || COALESCE(b.TITLE_LONG_DESC,b.TITLE_SHORT_DESC) ELSE a.CURSO END AS CURSO
          , CASE WHEN a.CURSO IS NULL THEN NVL(b.CREDIT_MIN,0) END AS CR, CASE WHEN a.CURSO IS NULL THEN NVL(b.LECTURE_MIN,0) END AS HT
          , CASE WHEN a.CURSO IS NULL THEN NVL(b.LAB_MIN,0) END AS HL, CASE WHEN a.CURSO IS NULL THEN NVL(b.OTHER_MIN,0) END AS HP
          , c.SCRRTST_TERM_CODE_EFF, MAX(c.SCRRTST_TERM_CODE_EFF) OVER(PARTITION BY a.SUBJECT,a.CRSE_NUMB,a.TERM_CODE_EFF) AS MAX_TERM_REQ, c.REQUISITOS
          , d.EFF_TERM, MAX(d.EFF_TERM) OVER(PARTITION BY a.SUBJECT,a.CRSE_NUMB,a.TERM_CODE_EFF) AS MAX_TERM_EQUIV, d.EQUIVALENCIAS
      FROM (SELECT DISTINCT
                a.PROGRAM, a.TERM_CODE_EFF, a.AREA, a.AREA_PRIORITY, b.SEQNO, b.AREA_RULE, c.SMRARUL_SEQNO
                , CASE WHEN b.AREA_RULE IS NULL THEN b.SUBJ_CODE ELSE c.SMRARUL_SUBJ_CODE END AS SUBJECT
                , CASE WHEN b.AREA_RULE IS NULL THEN b.CRSE_NUMB_LOW ELSE c.SMRARUL_CRSE_NUMB_LOW END AS CRSE_NUMB
                , NULL AS CURSO
            FROM LOE_PROGRAM_AREA_PRIORITY a, LOE_AREA_COURSE b, LOE_SMRARUL c
            WHERE a.TERM_CODE_EFF = b.TERM_CODE_EFF AND a.AREA = b.AREA_COURSE
                AND a.TERM_CODE_EFF = c.SMRARUL_TERM_CODE_EFF(+) AND a.AREA = c.SMRARUL_AREA(+) AND b.AREA_RULE = c.SMRARUL_KEY_RULE(+)
            UNION
            SELECT DISTINCT
                a.PROGRAM, a.TERM_CODE_EFF, a.AREA, a.AREA_PRIORITY, b.SEQNO, b.AREA_RULE, -1, NULL, NULL, c.SMBARUL_DESC
            FROM LOE_PROGRAM_AREA_PRIORITY a, LOE_AREA_COURSE b, LOE_SMBARUL c
            WHERE a.TERM_CODE_EFF = b.TERM_CODE_EFF AND a.AREA = b.AREA_COURSE
                AND a.TERM_CODE_EFF = c.SMBARUL_TERM_CODE_EFF AND a.AREA = c.SMBARUL_AREA AND b.AREA_RULE = c.SMBARUL_KEY_RULE) a, 
            COURSE_CATALOG b, 
           (SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
                , LISTAGG(TRIM(SCRRTST_CONNECTOR ||' '|| SCRRTST_LPAREN || SCRRTST_TESC_CODE || SCRRTST_TEST_SCORE || SCRRTST_SUBJ_CODE_PREQ || SCRRTST_CRSE_NUMB_PREQ || SCRRTST_RPAREN),' ') 
                    WITHIN GROUP (ORDER BY SCRRTST_SEQNO) AS REQUISITOS
            FROM LOE_SCRRTST
            GROUP BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB) c, 
           (SELECT EFF_TERM, SUBJECT, COURSE_NUMBER
                , LISTAGG(SUBJECT_CODE_EQUIV || COURSE_NUMBER_EQUIV,', ') WITHIN GROUP (ORDER BY SURROGATE_ID) AS EQUIVALENCIAS
            FROM LOE_EQUIV_COURSE_REPEATING
            GROUP BY EFF_TERM, SUBJECT, COURSE_NUMBER) d
      WHERE a.TERM_CODE_EFF = b.ACADEMIC_PERIOD(+) AND a.SUBJECT = b.SUBJECT(+) AND a.CRSE_NUMB = b.COURSE_NUMBER(+)
          AND a.TERM_CODE_EFF >= c.SCRRTST_TERM_CODE_EFF(+) AND a.SUBJECT = c.SCRRTST_SUBJ_CODE(+) AND a.CRSE_NUMB = c.SCRRTST_CRSE_NUMB(+)
          AND a.TERM_CODE_EFF >= d.EFF_TERM(+) AND a.SUBJECT = d.SUBJECT(+) AND a.CRSE_NUMB = d.COURSE_NUMBER(+))
WHERE (SCRRTST_TERM_CODE_EFF = MAX_TERM_REQ OR SCRRTST_TERM_CODE_EFF IS NULL) AND (EFF_TERM = MAX_TERM_EQUIV OR EFF_TERM IS NULL)
    AND TERM_CODE_EFF = '000000' AND PROGRAM = 'ABF-UG'
ORDER BY TERM_CODE_EFF, PROGRAM, AREA, SEQNO, SMRARUL_SEQNO;

SELECT * FROM COURSE_CATALOG
