--DA028_
WITH SVQ_SSRMEET_TIMECONFLICT AS (
	--BANINST1.SVQ_SSRMEET_TIMECONFLICT
	SELECT A.SSRMEET_SURROGATE_ID,
		A.SSRMEET_VERSION,
		A.SSRMEET_CRN,
		A.SSRMEET_TERM_CODE,
		B.SSRMEET_CRN AS SSRMEET_CRN_CONFLICT
		, A1.SSRBLCK_BLCK_CODE --EDIT
	FROM ODSMGR.SSRMEET A, ODSMGR.SSRMEET B
		, ODSMGR.LOE_SSRBLCK A1, ODSMGR.LOE_SSRBLCK B1 --EDIT
	WHERE A.SSRMEET_TERM_CODE = B.SSRMEET_TERM_CODE AND A.SSRMEET_CRN <> B.SSRMEET_CRN
		AND ( (TO_DATE(A.SSRMEET_START_DATE) BETWEEN TO_DATE(B.SSRMEET_START_DATE) AND TO_DATE(B.SSRMEET_END_DATE))
			OR (TO_DATE(A.SSRMEET_END_DATE) BETWEEN TO_DATE(B.SSRMEET_START_DATE) AND TO_DATE(B.Ssrmeet_End_Date))
			OR (TO_DATE(B.SSRMEET_START_DATE) BETWEEN TO_DATE(A.SSRMEET_START_DATE) AND TO_DATE(A.SSRMEET_END_DATE))
			OR (TO_DATE(B.SSRMEET_END_DATE) BETWEEN TO_DATE(A.SSRMEET_START_DATE) AND TO_DATE(A.SSRMEET_END_DATE)) )
		AND ( DECODE(A.SSRMEET_MON_DAY, 'M', 'Y', 'X') = DECODE(B.SSRMEET_MON_DAY, 'M', 'Y', 'N')
			OR DECODE(A.SSRMEET_TUE_DAY, 'T', 'Y', 'X') = DECODE(B.SSRMEET_TUE_DAY, 'T', 'Y', 'N')
			OR DECODE(A.SSRMEET_WED_DAY, 'W', 'Y', 'X') = DECODE(B.SSRMEET_WED_DAY, 'W', 'Y', 'N')
			OR DECODE(A.SSRMEET_THU_DAY, 'R', 'Y', 'X') = DECODE(B.SSRMEET_THU_DAY, 'R', 'Y', 'N')
			OR DECODE(A.SSRMEET_FRI_DAY, 'F', 'Y', 'X') = DECODE(B.SSRMEET_FRI_DAY, 'F', 'Y', 'N')
			OR DECODE(A.SSRMEET_SAT_DAY, 'S', 'Y', 'X') = DECODE(B.SSRMEET_SAT_DAY, 'S', 'Y', 'N')
			OR DECODE(A.SSRMEET_SUN_DAY, 'U', 'Y', 'X') = DECODE(B.SSRMEET_SUN_DAY, 'U', 'Y', 'N') )
		AND ( (NVL(A.SSRMEET_BEGIN_TIME, To_Char(0)) BETWEEN NVL(B.SSRMEET_BEGIN_TIME, TO_CHAR(0)) AND NVL(B.SSRMEET_END_TIME, TO_CHAR(0)))
			OR (NVL(A.SSRMEET_END_TIME, TO_CHAR(0)) BETWEEN NVL(B.SSRMEET_BEGIN_TIME, TO_CHAR(0)) AND NVL(B.SSRMEET_END_TIME, TO_CHAR(0)))
			OR (NVL(B.SSRMEET_BEGIN_TIME, TO_CHAR(0)) BETWEEN NVL(A.SSRMEET_BEGIN_TIME, TO_CHAR(0)) AND NVL(A.SSRMEET_END_TIME, TO_CHAR(0)))
			OR (NVL(B.SSRMEET_END_TIME, TO_CHAR(0)) BETWEEN NVL(A.SSRMEET_BEGIN_TIME, TO_CHAR(0)) AND NVL(A.SSRMEET_END_TIME, TO_CHAR(0))) )
		--EDIT
		AND A.SSRMEET_TERM_CODE = A1.SSRBLCK_TERM_CODE AND A.SSRMEET_CRN = A1.SSRBLCK_CRN
		AND B.SSRMEET_TERM_CODE = B1.SSRBLCK_TERM_CODE AND B.SSRMEET_CRN = B1.SSRBLCK_CRN
		AND A1.SSRBLCK_BLCK_CODE = B1.SSRBLCK_BLCK_CODE
)
SELECT DISTINCT SSRBLCK_TERM_CODE AS PERIODO, SFRBRDH_CAMP_CODE AS CAMPUS, SFRBRDH_PROGRAM AS PROGRAMA, B.SSRBLCK_BLCK_CODE AS BLOQUE, SSBSECT_SCHD_CODE AS TIP_HOR
	, CASE 
		WHEN SUBSTR(SSRBLCK_TERM_CODE,4,1) IN ('3','4') THEN (
			CASE 
				WHEN SSRMEET_BEGIN_TIME BETWEEN '0730' AND '1400' THEN 'MAÑANA'
				WHEN SSRMEET_BEGIN_TIME BETWEEN '1430' AND '1740' THEN 'TARDE'
				WHEN SSRMEET_BEGIN_TIME BETWEEN '1750' AND '1920' THEN 'TARDE/NOCHE'
				WHEN SSRMEET_BEGIN_TIME BETWEEN '1930' AND '2240' THEN 'NOCHE'
				END)
		WHEN SUBSTR(SSRBLCK_TERM_CODE,4,1) = '5' THEN (
			CASE 
				WHEN DIA IN ('M','W','F') THEN 'D1' --LXV
				WHEN DIA IN ('T','R') OR (DIA = 'S' AND SSRMEET_BEGIN_TIME >= '1930') THEN 'D2' --MJS
				WHEN (DIA = 'S' AND SSRMEET_BEGIN_TIME BETWEEN '1430' AND '1745') OR DIA = 'U' THEN 'D3' --SD
				END)
		END AS TURNO_FRECUENCIA
	, SSBSECT_SSTS_CODE AS STATUS_NRC, SFRBRDH_ATTS_CODE AS ATRIBUTO, SFRBRDH_CHRT_CODE AS COHORTE, SFBBLCD_CAPACITY AS AFORO_BLOQUE
	, COUNT(DISTINCT CASE WHEN SGBSTDN_BLCK_CODE IS NOT NULL THEN SFRSTCR_PIDM END) OVER(PARTITION BY SSRBLCK_TERM_CODE,B.SSRBLCK_BLCK_CODE) AS PRE_INSCRITOS
	, SSRBLCK_CRN AS NRC, SSBSECT_SUBJ_CODE || SSBSECT_CRSE_NUMB AS COD_CURSO, SCBCRSE_TITLE AS CURSO, SSBSECT_ENRL AS REAL, SSBSECT_MAX_ENRL AS MAXIMO, SSBSECT_SEATS_AVAIL AS RESTANTES
	, SSRRPRG_PROGRAM AS CONFLICTO_PROGRAMA, SSRRCMP_CAMP_CODE AS CONFLICTO_CAMPUS, SSRMEET_CRN_CONFLICT AS NRC_CONFLICTO
FROM ODSMGR.LOE_SSRBLCK B
		INNER JOIN ODSMGR.SFBBLCD ON SSRBLCK_TERM_CODE = SFBBLCD_TERM_CODE AND B.SSRBLCK_BLCK_CODE = SFBBLCD_BLCK_CODE
		INNER JOIN ODSMGR.LOE_SSBSECT ON SSRBLCK_TERM_CODE = SSBSECT_TERM_CODE AND SSRBLCK_CRN = SSBSECT_CRN
		INNER JOIN ODSMGR.SFRBRDH ON SSRBLCK_TERM_CODE = SFRBRDH_TERM_CODE
		INNER JOIN ODSMGR.SFRBRDB ON B.SSRBLCK_BLCK_CODE = SFRBRDB_BLCK_CODE AND SFRBRDH_SEQ_NUM = SFRBRDB_BRDH_SEQ_NUM
		LEFT JOIN ODSMGR.SCBCRSE C ON SSBSECT_SUBJ_CODE = SCBCRSE_SUBJ_CODE AND SSBSECT_CRSE_NUMB = SCBCRSE_CRSE_NUMB
								AND SCBCRSE_EFF_TERM = (SELECT MAX(C1.SCBCRSE_EFF_TERM) FROM ODSMGR.SCBCRSE C1
														WHERE C1.SCBCRSE_SUBJ_CODE = C.SCBCRSE_SUBJ_CODE AND C1.SCBCRSE_CRSE_NUMB = C.SCBCRSE_CRSE_NUMB)
		LEFT JOIN ODSMGR.SFRSTCR ON SSRBLCK_TERM_CODE = SFRSTCR_TERM_CODE AND SSRBLCK_CRN = SFRSTCR_CRN AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA','WC','RF','RO','IA')
		LEFT JOIN ODSMGR.LOE_SGBSTDN G ON B.SSRBLCK_BLCK_CODE = SGBSTDN_BLCK_CODE AND SFRSTCR_PIDM = SGBSTDN_PIDM
								AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(G1.SGBSTDN_TERM_CODE_EFF) FROM ODSMGR.LOE_SGBSTDN G1
																WHERE G1.SGBSTDN_BLCK_CODE = B.SSRBLCK_BLCK_CODE AND G1.SGBSTDN_PIDM = SFRSTCR_PIDM
																	AND G1.SGBSTDN_TERM_CODE_EFF <= SSRBLCK_TERM_CODE)
		LEFT JOIN ( SELECT H.SSRMEET_TERM_CODE, H.SSRMEET_CRN, MIN(H.SSRMEET_BEGIN_TIME) AS SSRMEET_BEGIN_TIME
						, COALESCE(H.SSRMEET_MON_DAY,H.SSRMEET_TUE_DAY,H.SSRMEET_WED_DAY,H.SSRMEET_THU_DAY,H.SSRMEET_FRI_DAY,H.SSRMEET_SAT_DAY,H.SSRMEET_SUN_DAY) AS DIA
					FROM ODSMGR.SSRMEET H
							INNER JOIN (SELECT SSRMEET_TERM_CODE, SSRMEET_CRN
											, MAX(SSRMEET_MON_DAY) AS SSRMEET_MON_DAY
											, MAX(SSRMEET_TUE_DAY) AS SSRMEET_TUE_DAY
											, MAX(SSRMEET_WED_DAY) AS SSRMEET_WED_DAY
											, MAX(SSRMEET_THU_DAY) AS SSRMEET_THU_DAY
											, MAX(SSRMEET_FRI_DAY) AS SSRMEET_FRI_DAY
											, MAX(SSRMEET_SAT_DAY) AS SSRMEET_SAT_DAY
											, MAX(SSRMEET_SUN_DAY) AS SSRMEET_SUN_DAY
										FROM ODSMGR.SSRMEET
										WHERE COALESCE(SSRMEET_MON_DAY,SSRMEET_TUE_DAY,SSRMEET_WED_DAY,SSRMEET_THU_DAY,SSRMEET_FRI_DAY,SSRMEET_SAT_DAY,SSRMEET_SUN_DAY) IS NOT NULL
										GROUP BY SSRMEET_TERM_CODE, SSRMEET_CRN
										) D ON H.SSRMEET_TERM_CODE = D.SSRMEET_TERM_CODE AND H.SSRMEET_CRN = D.SSRMEET_CRN
												AND COALESCE(H.SSRMEET_MON_DAY,H.SSRMEET_TUE_DAY,H.SSRMEET_WED_DAY,H.SSRMEET_THU_DAY,H.SSRMEET_FRI_DAY,H.SSRMEET_SAT_DAY,H.SSRMEET_SUN_DAY)
													= COALESCE(D.SSRMEET_MON_DAY,D.SSRMEET_TUE_DAY,D.SSRMEET_WED_DAY,D.SSRMEET_THU_DAY,D.SSRMEET_FRI_DAY,D.SSRMEET_SAT_DAY,D.SSRMEET_SUN_DAY)
					GROUP BY H.SSRMEET_TERM_CODE, H.SSRMEET_CRN, COALESCE(H.SSRMEET_MON_DAY,H.SSRMEET_TUE_DAY,H.SSRMEET_WED_DAY,H.SSRMEET_THU_DAY,H.SSRMEET_FRI_DAY,H.SSRMEET_SAT_DAY,H.SSRMEET_SUN_DAY)
					) ON SSRBLCK_TERM_CODE = SSRMEET_TERM_CODE AND SSRBLCK_CRN = SSRMEET_CRN
		LEFT JOIN ( SELECT SSRRPRG_TERM_CODE AS SSRRPRG_TERM_CODE_1, SSRRPRG_CRN AS SSRRPRG_CRN_1, SSRRPRG_PROGRAM_IND
					FROM ODSMGR.LOE_SSRRPRG WHERE SSRRPRG_REC_TYPE = 1
					) SSRRPRG_1 ON SSRBLCK_TERM_CODE = SSRRPRG_TERM_CODE_1 AND SSRBLCK_CRN = SSRRPRG_CRN_1
		LEFT JOIN ( SELECT DISTINCT SSRRPRG_TERM_CODE AS SSRRPRG_TERM_CODE_2, SSRBLCK_BLCK_CODE AS SSRBLCK_BLCK_CODE_P, SSRRPRG_CRN AS SSRRPRG_CRN_2, SSRRPRG_PROGRAM
					FROM ODSMGR.LOE_SSRBLCK
							INNER JOIN ODSMGR.SFRBRDH ON SSRBLCK_TERM_CODE = SFRBRDH_TERM_CODE
							INNER JOIN ODSMGR.SFRBRDB ON SSRBLCK_BLCK_CODE = SFRBRDB_BLCK_CODE AND SFRBRDH_SEQ_NUM = SFRBRDB_BRDH_SEQ_NUM
							INNER JOIN ODSMGR.LOE_SSRRPRG ON SSRBLCK_TERM_CODE = SSRRPRG_TERM_CODE AND SSRBLCK_CRN = SSRRPRG_CRN
					WHERE SSRRPRG_REC_TYPE = 2 AND SFRBRDH_PROGRAM = SSRRPRG_PROGRAM
					) SSRRPRG_2 ON SSRBLCK_TERM_CODE = SSRRPRG_TERM_CODE_2 AND SSRBLCK_CRN = SSRRPRG_CRN_2 AND B.SSRBLCK_BLCK_CODE = SSRBLCK_BLCK_CODE_P
									AND ((SSRRPRG_PROGRAM_IND = 'I' AND SFRBRDH_PROGRAM <> SSRRPRG_PROGRAM)
										OR (SSRRPRG_PROGRAM_IND = 'E' AND SFRBRDH_PROGRAM = SSRRPRG_PROGRAM))
		LEFT JOIN ( SELECT SSRRCMP_TERM_CODE AS SSRRCMP_TERM_CODE_1, SSRRCMP_CRN AS SSRRCMP_CRN_1, SSRRCMP_CAMP_IND
					FROM ODSMGR.LOE_SSRRCMP WHERE SSRRCMP_REC_TYPE = 1
					) SSRRCMP_1 ON SSRBLCK_TERM_CODE = SSRRCMP_TERM_CODE_1 AND SSRBLCK_CRN = SSRRCMP_CRN_1
		LEFT JOIN ( SELECT DISTINCT SSRRCMP_TERM_CODE AS SSRRCMP_TERM_CODE_2, SSRBLCK_BLCK_CODE AS SSRBLCK_BLCK_CODE_C, SSRRCMP_CRN AS SSRRCMP_CRN_2, SSRRCMP_CAMP_CODE
					FROM ODSMGR.LOE_SSRBLCK
							INNER JOIN ODSMGR.SFRBRDH ON SSRBLCK_TERM_CODE = SFRBRDH_TERM_CODE
							INNER JOIN ODSMGR.SFRBRDB ON SSRBLCK_BLCK_CODE = SFRBRDB_BLCK_CODE AND SFRBRDH_SEQ_NUM = SFRBRDB_BRDH_SEQ_NUM
							INNER JOIN ODSMGR.LOE_SSRRCMP ON SSRBLCK_TERM_CODE = SSRRCMP_TERM_CODE AND SSRBLCK_CRN = SSRRCMP_CRN
					WHERE SSRRCMP_REC_TYPE = 2 AND SFRBRDH_CAMP_CODE = SSRRCMP_CAMP_CODE
					) SSRRCMP_2 ON SSRBLCK_TERM_CODE = SSRRCMP_TERM_CODE_2 AND SSRBLCK_CRN = SSRRCMP_CRN_2 AND B.SSRBLCK_BLCK_CODE = SSRBLCK_BLCK_CODE_C
									AND ((SSRRCMP_CAMP_IND = 'I' AND SFRBRDH_CAMP_CODE <> SSRRCMP_CAMP_CODE)
										OR (SSRRCMP_CAMP_IND = 'E' AND SFRBRDH_CAMP_CODE = SSRRCMP_CAMP_CODE))
		LEFT JOIN SVQ_SSRMEET_TIMECONFLICT CNFL ON SSRBLCK_TERM_CODE = CNFL.SSRMEET_TERM_CODE AND SSRBLCK_CRN = CNFL.SSRMEET_CRN AND B.SSRBLCK_BLCK_CODE = CNFL.SSRBLCK_BLCK_CODE
WHERE SSRBLCK_TERM_CODE IN ('221434','221534')
ORDER BY SSRBLCK_TERM_CODE, B.SSRBLCK_BLCK_CODE
;
