--Datos_Personales_
SELECT B.NRO_TICKET,
	SPRIDEN_ID AS CODIGO, REPLACE(SPRIDEN_LAST_NAME,'/',' ') ||', '|| SPRIDEN_FIRST_NAME AS APELLIDOS_NOMBRES_ESTUDIANTE
	, ALTERNATIVE_ID AS DNI, TRUNC(MONTHS_BETWEEN(CURRENT_DATE,SPBPERS_BIRTH_DATE)/12,0) AS EDAD, SPBPERS_BIRTH_DATE AS FECHA_NACIMIENTO
	, NULL AS DNI_APODERADO, REPLACE(P.PARENT_LAST_NAME,'/',' ') ||', '|| P.PARENT_FIRST_NAME AS APELLIDOS_NOMBRES_APODERADO
FROM ODSMGR.LOE_SPRIDEN
		INNER JOIN UPN_RPT_DM_DEV.ODSMGR.SELECCION_CUSTOM B ON SPRIDEN_ID = TRIM(B.KEY1) AND B.NRO_TICKET = 'RITM0112745'
		LEFT JOIN ODSMGR.ALTERNATIVE_ID I ON SPRIDEN_PIDM = I.ENTITY_UID AND I.ATERNATIVE_ID_TYPE = 'DNI'
											AND I.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(I1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ODSMGR.ALTERNATIVE_ID I1
																				WHERE I1.ENTITY_UID = SPRIDEN_PIDM AND I1.ATERNATIVE_ID_TYPE = 'DNI')
		LEFT JOIN ODSMGR.SPBPERS ON SPRIDEN_PIDM = SPBPERS_PIDM
		LEFT JOIN ODSMGR.LOE_PARENT_INFORMATION P ON SPRIDEN_PIDM = P.PERSON_UID AND P.RELATIONSHIP_CODE = 'Q'
													AND P.ACTIVITY_DATE = (SELECT MAX(P1.ACTIVITY_DATE) FROM ODSMGR.LOE_PARENT_INFORMATION P1
																				WHERE P1.PERSON_UID = SPRIDEN_PIDM AND P1.RELATIONSHIP_CODE = 'Q')
WHERE SPRIDEN_CHANGE_IND IS NULL
;
