--Deuda_Activa_Castigada_
SELECT DISTINCT A.BUSINESS_UNIT, C.CUST_ID AS ID, D.PO_REF AS PERIODO_ACADEMICO, A.ITEM, D.BILL_STATUS AS ESTADO_BI, D.INVOICE_DT AS FECHA_EMISION
	, CASE WHEN C.DUE_DT IS NULL THEN (CASE WHEN D.PYMNT_TERMS_CD IN ('000','0000','00000') THEN D.DUE_DT ELSE T.DUE_DT END) ELSE C.DUE_DT END AS FECHA_VENCIMIENTO
	, B.ITEM_STATUS AS ESTADO_AR, D.INVOICE_AMOUNT AS MONTO_DOCUMENTO, B.BAL_AMT AS SALDO
	, CASE WHEN E.USER_AMT3 IS NULL THEN 0.00 ELSE E.USER_AMT3 END AS MORA
	, CASE WHEN E.USER_AMT4 IS NULL THEN 0.00 ELSE E.USER_AMT4 END AS GASTO_ADM
	, B.BAL_AMT + CASE WHEN E.USER_AMT3 IS NULL THEN 0.00 ELSE E.USER_AMT3 END + CASE WHEN E.USER_AMT4 IS NULL THEN 0.00 ELSE E.USER_AMT4 END AS MONTO_DEUDA
	, CASE WHEN D.INVOICE_AMOUNT > B.BAL_AMT AND SALDO <> 0 THEN 'PARCIAL' END AS TIPO_DEUDA	
	, CASE 
		WHEN F.ACCOUNT = '6551000' THEN 'CASTIGADA SPRING'
		WHEN A.CUST_ID = '9999999999' OR CONCAT(A.ENTRY_TYPE,A.ENTRY_REASON) = 'WOCASTI' THEN 'CASTIGADA PEOPLESOFT'
		ELSE 'ACTIVA' END AS DEUDA
FROM ODSMGR.PS_ITEM_ACTIVITY A
		INNER JOIN ODSMGR.PS_ITEM B ON A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.ITEM = B.ITEM AND A.CUST_ID = B.CUST_ID --AND B.ITEM_STATUS = 'O'
		INNER JOIN ODSMGR.PS_BI_HDR D ON B.BUSINESS_UNIT = D.BUSINESS_UNIT AND B.ITEM = D.INVOICE
		INNER JOIN ODSMGR.PS_PAY_TRMS_NET N ON D.BUSINESS_UNIT = N.SETID AND D.PYMNT_TERMS_CD = N.PYMNT_TERMS_CD
													AND N.EFFDT = (SELECT MAX(N_ED.EFFDT) FROM ODSMGR.PS_PAY_TRMS_NET N_ED
															        WHERE N.SETID = N_ED.SETID AND N.PYMNT_TERMS_CD = N_ED.PYMNT_TERMS_CD AND N_ED.EFFDT <= CURRENT_DATE)
		INNER JOIN ODSMGR.PS_PAY_TRMS_TIME T ON N.SETID = T.SETID AND N.PAY_TRMS_TIME_ID = T.PAY_TRMS_TIME_ID
		LEFT JOIN ODSMGR.PS_ITEM C ON B.BUSINESS_UNIT = C.BUSINESS_UNIT AND B.ITEM = C.ITEM AND (C.CUST_ID <> '9999999999' OR C.CUST_ID IS NULL)
		LEFT JOIN ODSMGR.PS_ITEM_ACTIVITY E ON B.BUSINESS_UNIT = E.BUSINESS_UNIT AND B.ITEM = E.ITEM AND B.CUST_ID = E.CUST_ID
												AND B.ITEM_LINE = E.ITEM_LINE AND B.ITEM_SEQ_NUM = E.ITEM_SEQ_NUM
		LEFT JOIN ODSMGR.PS_BI_LINE_DST F ON B.BUSINESS_UNIT = F.BUSINESS_UNIT AND B.ITEM = F.INVOICE AND F.ACCOUNT = '6551000'
WHERE A.BUSINESS_UNIT = 'PER03' AND (B.ITEM_STATUS = 'O' OR F.ACCOUNT = '6551000')
	--AND C.CUST_ID = 'N00056090'
--ORDER BY D.INVOICE_DT DESC
;
