SELECT DISTINCT
    a.PERSON_UID,
    b.SPRIDEN_ID AS CODBANNER, 
    b.SPRIDEN_FIRST_NAME AS NOMBRES, 
    b.SPRIDEN_LAST_NAME AS APELLIDOS, 
    c.SIBINST_WKLD_CODE AS WORKLOAD
FROM 
    (INSTRUCTIONAL_ASSIGNMENT a
        LEFT JOIN LOE_SPRIDEN b ON
            a.PERSON_UID = b.SPRIDEN_PIDM 
            AND b.SPRIDEN_CHANGE_IND IS NULL)
        LEFT JOIN SIBINST c ON
            a.PERSON_UID = c.SIBINST_PIDM
            AND c.SIBINST_FCST_CODE = 'AC'
            AND c.SIBINST_TERM_CODE_EFF = (SELECT MAX(c_max.SIBINST_TERM_CODE_EFF) FROM SIBINST c_max 
                WHERE c.SIBINST_PIDM = c_max.SIBINST_PIDM AND c_max.SIBINST_FCST_CODE = 'AC')
ORDER BY a.PERSON_UID;