SELECT DISTINCT 
    b.SPRIDEN_ID
    --, a.TBRACCD_PIDM
    , a.TBRACCD_TRAN_NUMBER
    , a.TBRACCD_SURROGATE_ID
FROM ODSMGR.LOE_TBRACCD a
    INNER JOIN ODSMGR.LOE_SPRIDEN b ON
        a.TBRACCD_PIDM = b.SPRIDEN_PIDM
        AND b.SPRIDEN_CHANGE_IND IS NULL
WHERE b.SPRIDEN_ID = 'N000183573' --ID
AND a.TBRACCD_TRAN_NUMBER IN (24,25,26,27); --NRO TRANSACCION