SELECT DISTINCT
	a.PERSON_UID, SPRIDEN_ID, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME, a.PROGRAM, a.CAMP_CODE
	, ROUND(a.ACT_CREDITS_OVERALL /20,0) +1 AS CICLO, b.EMAIL_ADDRESS, c.PHONE_NUMBER_COMBINED
FROM (	SELECT PERSON_UID, SEQUENCE_NUMBER, MAX(SEQUENCE_NUMBER) OVER(PARTITION BY PERSON_UID,PROGRAM) AS MAX_SEQ
            , PROGRAM, LEVL_CODE, CAMP_CODE, ACTIVITY_DATE, REQ_CREDITS_OVERALL
            , ACT_CREDITS_OVERALL
        FROM LOE_PROGRAM_OVERALL_RESULTS
        WHERE PROGRAM <> 'PREREQ' AND LEVL_CODE = 'UG') a, LOE_SOVLCUR, SPRIDEN, LOE_EMAIL b, TELEPHONE c
WHERE a.PERSON_UID = SOVLCUR_PIDM
	AND a.LEVL_CODE = SOVLCUR_LEVL_CODE
	AND a.SEQUENCE_NUMBER = a.MAX_SEQ
	AND a.PERSON_UID = SPRIDEN_PIDM
	AND SPRIDEN_CHANGE_IND IS NULL
	AND a.ACT_CREDITS_OVERALL > 0
	AND SOVLCUR_LMOD_CODE = 'LEARNER'
	AND SOVLCUR_CACT_CODE = 'ACTIVE'
	AND SOVLCUR_CURRENT_IND = 'Y'
	AND a.PERSON_UID = b.PERSON_UID(+)
	AND b.EMAIL_TYPE(+) = 'PERS' AND b.STATUS_IND(+) = 'A'
	AND a.PERSON_UID = c.ENTITY_UID(+)
	AND c.PHONE_TYPE(+) = 'CP'
	AND a.PERSON_UID NOT IN (SELECT DISTINCT SHRTGPA_PIDM
								FROM LOE_SHRTGPA
								WHERE SHRTGPA_LEVL_CODE = 'CR')
    AND a.PERSON_UID NOT IN (SELECT DISTINCT SFRSTCR_PIDM
                                FROM SFRSTCR
                                WHERE SFRSTCR_LEVL_CODE = 'CR'
                                    AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA','RO'))
    AND a.PERSON_UID NOT IN (SELECT DISTINCT PERSON_UID
    							FROM FIELD_OF_STUDY
								WHERE STUDENT_LEVEL = 'UG' AND SOURCE = 'OUTCOME'
                                    AND CURRICULUM_CHANGE_REASON = 'EGRESADO');
                                