SELECT DISTINCT
	a.PERSON_UID, SPRIDEN_ID, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME, a.PROGRAM, a.CAMP_CODE
	, ROUND(a.ACT_CREDITS_OVERALL /20,0) +1 AS CICLO, b.EMAIL_ADDRESS AS EMAIL_PERSONAL, SPRIDEN_ID||'@upn.pe' AS EMAIL_UPN
    , c.PHONE_NUMBER_COMBINED AS CELULAR, e.PHONE_NUMBER_COMBINED AS TELEFONO, d.SHRTCKN_CRSE_TITLE
FROM (	SELECT PERSON_UID, SEQUENCE_NUMBER, MAX(SEQUENCE_NUMBER) OVER(PARTITION BY PERSON_UID,PROGRAM) AS MAX_SEQ
            , PROGRAM, LEVL_CODE, CAMP_CODE, ACTIVITY_DATE, REQ_CREDITS_OVERALL
            , ACT_CREDITS_OVERALL
        FROM LOE_PROGRAM_OVERALL_RESULTS
        WHERE PROGRAM <> 'PREREQ' AND LEVL_CODE = 'UG') a, 
    (	SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE
            , SHRTCKN_SURROGATE_ID, MAX(SHRTCKN_SURROGATE_ID) OVER(PARTITION BY SHRTCKN_PIDM) AS MAX_SURROGATE_ID
        FROM SHRTCKN
        WHERE SHRTCKN_SUBJ_CODE = 'IDIO' AND SHRTCKN_CRSE_TITLE LIKE '%INGL%' AND SHRTCKN_TERM_CODE >= '201600') d, 
        LOE_SOVLCUR, SPRIDEN, LOE_EMAIL b, TELEPHONE c, TELEPHONE e
WHERE a.PERSON_UID = SOVLCUR_PIDM
	AND a.LEVL_CODE = SOVLCUR_LEVL_CODE
	AND a.SEQUENCE_NUMBER = a.MAX_SEQ
	AND a.PERSON_UID = SPRIDEN_PIDM
	AND SPRIDEN_CHANGE_IND IS NULL
    AND a.PERSON_UID = d.SHRTCKN_PIDM
    AND d.SHRTCKN_SURROGATE_ID = d.MAX_SURROGATE_ID
	AND a.ACT_CREDITS_OVERALL > 0
	AND SOVLCUR_LMOD_CODE = 'LEARNER'
	AND SOVLCUR_CACT_CODE = 'ACTIVE'
	AND SOVLCUR_CURRENT_IND = 'Y'
	AND a.PERSON_UID = b.PERSON_UID(+)
	AND b.EMAIL_TYPE(+) = 'PERS' AND b.STATUS_IND(+) = 'A'
	AND a.PERSON_UID = c.ENTITY_UID(+)
	AND c.PHONE_TYPE(+) = 'CP'
    AND a.PERSON_UID = e.ENTITY_UID(+)
	AND e.PHONE_TYPE(+) = 'TP'
	AND a.PERSON_UID IN (SELECT DISTINCT SHRTGPA_PIDM
								FROM LOE_SHRTGPA
								WHERE SHRTGPA_LEVL_CODE = 'CR')
    /*AND a.PERSON_UID NOT IN (SELECT DISTINCT SFRSTCR_PIDM
                                FROM SFRSTCR
                                WHERE SFRSTCR_LEVL_CODE = 'CR'
                                    AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA','RO'))*/
    AND a.PERSON_UID NOT IN (SELECT DISTINCT PERSON_UID
    							FROM FIELD_OF_STUDY
								WHERE STUDENT_LEVEL = 'UG' AND SOURCE = 'OUTCOME'
                                    AND CURRICULUM_CHANGE_REASON = 'BACHILLER')
ORDER BY a.PERSON_UID;