SELECT DISTINCT T.PERSON_UID, T.ID, T.NAME, SOVLCUR_CAMP_CODE, STVCAMP_DESC, SOVLCUR_PROGRAM, SMRPRLE_PROGRAM_DESC
    , SUBSTR(SOVLCUR_PROGRAM,LENGTH(SOVLCUR_PROGRAM)-1) AS NIVEL, NVL(ROUND(ACT_CREDITS_OVERALL /20,0),0) AS CICLO
    , T.TEST, T.TEST_DESC, T.TEST_SCORE, T.TEST_DATE
    , MAX(SPRTELE_PHONE_NUMBER) OVER(PARTITION BY SPRTELE_PIDM) AS CELULAR, GOREMAL_EMAIL_ADDRESS
FROM TEST T, LOE_SOVLCUR, LOE_PROGRAM_OVERALL_RESULTS C, STVCAMP, SMRPRLE, SPRTELE, 
    ( SELECT GOREMAL_PIDM, GOREMAL_EMAIL_ADDRESS
      FROM (SELECT GOREMAL_PIDM, GOREMAL_EMAIL_ADDRESS, GOREMAL_ACTIVITY_DATE
                , MAX(GOREMAL_ACTIVITY_DATE) OVER(PARTITION BY GOREMAL_PIDM) AS MAX_DATE
            FROM GOREMAL WHERE GOREMAL_STATUS_IND = 'A' AND GOREMAL_EMAL_CODE = 'PERS')
      WHERE GOREMAL_ACTIVITY_DATE = MAX_DATE )
WHERE T.PERSON_UID = SOVLCUR_PIDM(+)
    AND SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND SOVLCUR_CACT_CODE(+) = 'ACTIVE'
    AND SOVLCUR_LEVL_CODE(+) = 'UG' AND SOVLCUR_TERM_CODE_END(+) IS NULL
    AND SOVLCUR_PIDM = C.PERSON_UID(+) AND SOVLCUR_PROGRAM = C.PROGRAM(+)
    AND C.LEVL_CODE(+) = 'UG'
    AND (C.SEQUENCE_NUMBER = (SELECT MAX(C1.SEQUENCE_NUMBER) FROM LOE_PROGRAM_OVERALL_RESULTS C1
                            WHERE C1.PERSON_UID = C.PERSON_UID AND C1.PROGRAM = C.PROGRAM
                                AND C1.LEVL_CODE = 'UG') OR C.SEQUENCE_NUMBER IS NULL)
    AND SOVLCUR_CAMP_CODE = STVCAMP_CODE(+)
    AND SOVLCUR_PROGRAM = SMRPRLE_PROGRAM(+)
    AND T.PERSON_UID = SPRTELE_PIDM(+) AND SPRTELE_TELE_CODE(+) = 'CP'
    AND T.PERSON_UID = GOREMAL_PIDM(+)
    AND T.TEST_DATE BETWEEN TO_DATE('01/03/2020','DD/MM/YYYY') AND CURRENT_DATE;
    