
SELECT DISTINCT
    a.*, CASE WHEN c.EXEMPTION_CODE IS NULL THEN 'T1/TA' ELSE 'TA' END AS CARGO
    , b.ACADEMIC_PERIOD, b.CAMPUS, b.PROGRAM, b.PROGRAM_DESC, b.TIPO_ESTUDIANTE, b.TBBESTU_EXEMPTION_CODE
FROM (SELECT DISTINCT
          a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_PERIOD, a.CAMPUS, a.PROGRAM, a.PROGRAM_DESC
          , CASE b.SORLCUR_STYP_CODE WHEN 'N' THEN 'NUEVO' ELSE 'CONTINUO' END AS TIPO_ESTUDIANTE
          , c.TBBESTU_EXEMPTION_CODE
      FROM ADMISSIONS_APPLICATION a, SORLCUR b, TBBESTU c, LOE_EXEMPTION_DETAIL_LEVEL d
      WHERE a.PERSON_UID = b.SORLCUR_PIDM AND a.ACADEMIC_PERIOD = b.SORLCUR_TERM_CODE
          AND b.SORLCUR_CACT_CODE = 'ACTIVE' AND b.SORLCUR_STYP_CODE = 'N'
          AND a.PERSON_UID = c.TBBESTU_PIDM AND a.ACADEMIC_PERIOD = c.TBBESTU_TERM_CODE AND TBBESTU_DEL_IND IS NULL
          AND a.ACADEMIC_PERIOD = d.EXEMPTION_TERM AND c.TBBESTU_EXEMPTION_CODE = d.EXEMPTION_CODE AND SUBSTR(d.REGISTRATION_DETAIL_CODE,1,2) IN ('T1','TA')
          AND a.STUDENT_LEVEL = 'UG' AND a.ACADEMIC_PERIOD = '218413') a, 
     (SELECT DISTINCT
          a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_PERIOD, a.CAMPUS, a.PROGRAM, a.PROGRAM_DESC
          , CASE b.SORLCUR_STYP_CODE WHEN 'N' THEN 'NUEVO' ELSE 'CONTINUO' END AS TIPO_ESTUDIANTE
          , c.TBBESTU_EXEMPTION_CODE
      FROM ACADEMIC_STUDY a, SORLCUR b, TBBESTU c, LOE_EXEMPTION_DETAIL_LEVEL d
      WHERE a.PERSON_UID = b.SORLCUR_PIDM(+) AND a.ACADEMIC_PERIOD = b.SORLCUR_TERM_CODE(+)
          AND b.SORLCUR_CACT_CODE(+) = 'ACTIVE' AND (b.SORLCUR_STYP_CODE(+) <> 'N' OR b.SORLCUR_STYP_CODE(+) IS NULL)
          AND a.PERSON_UID = c.TBBESTU_PIDM AND a.ACADEMIC_PERIOD = c.TBBESTU_TERM_CODE AND TBBESTU_DEL_IND IS NULL
          AND a.ACADEMIC_PERIOD = d.EXEMPTION_TERM AND c.TBBESTU_EXEMPTION_CODE = d.EXEMPTION_CODE AND SUBSTR(d.REGISTRATION_DETAIL_CODE,1,2) IN ('T1','TA')
          AND a.STUDENT_LEVEL = 'UG' AND a.ACADEMIC_PERIOD = '218434') b, 
     (SELECT DISTINCT EXEMPTION_CODE FROM LOE_EXEMPTION_DETAIL_LEVEL
      WHERE SUBSTR(REGISTRATION_DETAIL_CODE,1,2) IN ('T1','TA') AND EXEMPTION_TERM = '218413'
      MINUS
      SELECT DISTINCT EXEMPTION_CODE FROM LOE_EXEMPTION_DETAIL_LEVEL
      WHERE SUBSTR(REGISTRATION_DETAIL_CODE,1,2) = 'T1' AND EXEMPTION_TERM = '218413') c
WHERE a.PERSON_UID = b.PERSON_UID AND a.TBBESTU_EXEMPTION_CODE = c.EXEMPTION_CODE(+) AND a.TBBESTU_EXEMPTION_CODE <> b.TBBESTU_EXEMPTION_CODE;

