create or replace FUNCTION F_CRSE_EQIV_AP (P_PIDM NUMBER,P_TERM VARCHAR2, P_SUBJ VARCHAR2,P_CRSE VARCHAR2)
RETURN VARCHAR2 AS 
V_RET VARCHAR2(1):='N';
CURSOR cursoeqiv IS
SELECT SCREQIV_SUBJ_CODE_EQIV,SCREQIV_CRSE_NUMB_EQIV
FROM SCREQIV
WHERE SCREQIV_SUBJ_CODE = P_SUBJ
AND SCREQIV_CRSE_NUMB = P_CRSE
AND P_TERM BETWEEN SCREQIV_START_TERM AND SCREQIV_END_TERM
UNION 
SELECT DISTINCT SHRTCKN_SUBJ_CODE , SHRTCKN_CRSE_NUMB
FROM SHRTCKN
WHERE SHRTCKN_PIDM = P_PIDM
AND SHRTCKN_SUBJ_CODE = P_SUBJ
AND SHRTCKN_CRSE_NUMB = P_CRSE
;
BEGIN
V_RET:='N';
for cursoeqiv_rec in cursoeqiv
loop
    BEGIN
    SELECT DISTINCT 'Y'
    INTO V_RET
    FROM 
    SHRTCKN N1,SHRTCKG G1, SHRGRDE H
    WHERE  G1.shrtckg_pidm = N1.shrtckn_pidm
    AND N1.shrtckn_term_code = G1.shrtckg_term_code
     and N1.shrtckn_seq_no = G1.shrtckg_tckn_seq_no
    AND G1.shrtckg_grde_code_final  = SHRGRDE_CODE
    AND  (
    (N1.SHRTCKN_SUBJ_CODE = cursoeqiv_rec.SCREQIV_SUBJ_CODE_EQIV
   AND  N1.SHRTCKN_CRSE_NUMB = cursoeqiv_rec.SCREQIV_CRSE_NUMB_EQIV)
   OR 
     (N1.SHRTCKN_SUBJ_CODE = P_SUBJ
   AND  N1.SHRTCKN_CRSE_NUMB = P_CRSE)
   )
AND SHRGRDE_PASSED_IND = 'Y'
AND SHRTCKN_PIDM = P_PIDM;
IF V_RET = 'Y' THEN RETURN(V_RET);
END IF;
EXCEPTION
WHEN NO_DATA_FOUND  THEN  V_RET:='N';
  WHEN OTHERS  THEN  V_RET:='X';
END;
END LOOP;
RETURN(V_RET);
END;

