SELECT HD.SHRTCKN_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME AS NOMBRE_ESTUDIANTE, HD.SHRTCKN_TERM_CODE
    , HD.SHRTCKN_SUBJ_CODE || HD.SHRTCKN_CRSE_NUMB AS COD_CURSO, HD.SHRTCKN_CRSE_TITLE, HD.SHRTCKG_GRDE_CODE_FINAL
FROM ((--HISTORIA_DESAPROBO
      SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
      FROM SHRTCKN, SHRTCKG G
      WHERE SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE
          AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
          AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                                  WHERE G.SHRTCKG_PIDM        = G1.SHRTCKG_PIDM
                                      AND G.SHRTCKG_TERM_CODE   = G1.SHRTCKG_TERM_CODE
                                      AND G.SHRTCKG_TCKN_SEQ_NO = G1.SHRTCKG_TCKN_SEQ_NO)
          AND SHRTCKG_GRDE_CODE_FINAL NOT IN (SELECT SHRGRDE_CODE FROM SHRGRDE WHERE SHRGRDE_PASSED_IND = 'Y')
          AND SHRTCKG_GRDE_CODE_FINAL NOT LIKE 'R%'
          --AND SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB IN ('1502','1510')
          AND ((SHRTCKN_SUBJ_CODE = 'TPRO' AND SHRTCKN_CRSE_NUMB = '1510') OR (SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB = '1504'))) HD 
        LEFT JOIN (--HISTORIA_APROBO
                  SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
                  FROM SHRTCKN, SHRTCKG G
                  WHERE SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE
                      AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
                      AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                                              WHERE G.SHRTCKG_PIDM        = G1.SHRTCKG_PIDM
                                                  AND G.SHRTCKG_TERM_CODE   = G1.SHRTCKG_TERM_CODE
                                                  AND G.SHRTCKG_TCKN_SEQ_NO = G1.SHRTCKG_TCKN_SEQ_NO)
                      AND SHRTCKG_GRDE_CODE_FINAL IN (SELECT SHRGRDE_CODE FROM SHRGRDE WHERE SHRGRDE_PASSED_IND = 'Y')
                      --AND SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB IN ('1502','1510')
                      AND ((SHRTCKN_SUBJ_CODE = 'TPRO' AND SHRTCKN_CRSE_NUMB = '1510') OR (SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB = '1504'))) HA ON 
                HD.SHRTCKN_PIDM = HA.SHRTCKN_PIDM AND HD.SHRTCKN_SUBJ_CODE = HA.SHRTCKN_SUBJ_CODE AND HD.SHRTCKN_CRSE_NUMB = HA.SHRTCKN_CRSE_NUMB)
    , LOE_SPRIDEN
WHERE HD.SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND HA.SHRTCKN_PIDM IS NULL
ORDER BY SHRTCKN_PIDM, SHRTCKN_TERM_CODE;

-----------------------------------------
SELECT SHRTCKN_PIDM, SPRIDEN_ID, NOMBRE_ESTUDIANTE, SHRTCKN_TERM_CODE, COD_CURSO, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
FROM (
SELECT HD.SHRTCKN_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME AS NOMBRE_ESTUDIANTE, HD.SHRTCKN_TERM_CODE
    , HD.SHRTCKN_SUBJ_CODE || HD.SHRTCKN_CRSE_NUMB AS COD_CURSO, HD.SHRTCKN_CRSE_TITLE, HD.SHRTCKG_GRDE_CODE_FINAL
    , MAX(CASE WHEN HD.SHRTCKN_SUBJ_CODE = 'TPRO' AND HD.SHRTCKN_CRSE_NUMB = '1510' THEN 'TPRO1510' ELSE NULL END) OVER(PARTITION BY HD.SHRTCKN_PIDM) AS CURSO1
    , MAX(CASE WHEN HD.SHRTCKN_SUBJ_CODE = 'INVE' AND HD.SHRTCKN_CRSE_NUMB = '1504' THEN 'INVE1504' ELSE NULL END) OVER(PARTITION BY HD.SHRTCKN_PIDM) AS CURSO2
FROM ((--HISTORIA_DESAPROBO
      SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
      FROM SHRTCKN, SHRTCKG G
      WHERE SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE
          AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
          AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                                  WHERE G.SHRTCKG_PIDM        = G1.SHRTCKG_PIDM
                                      AND G.SHRTCKG_TERM_CODE   = G1.SHRTCKG_TERM_CODE
                                      AND G.SHRTCKG_TCKN_SEQ_NO = G1.SHRTCKG_TCKN_SEQ_NO)
          AND SHRTCKG_GRDE_CODE_FINAL NOT IN (SELECT SHRGRDE_CODE FROM SHRGRDE WHERE SHRGRDE_PASSED_IND = 'Y')
          AND SHRTCKG_GRDE_CODE_FINAL NOT LIKE 'R%'
          --AND SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB IN ('1502','1510')
          AND ((SHRTCKN_SUBJ_CODE = 'TPRO' AND SHRTCKN_CRSE_NUMB = '1510') OR (SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB = '1504'))) HD 
        LEFT JOIN (--HISTORIA_APROBO
                  SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKN_CRSE_TITLE, SHRTCKG_GRDE_CODE_FINAL
                  FROM SHRTCKN, SHRTCKG G
                  WHERE SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE
                      AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
                      AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                                              WHERE G.SHRTCKG_PIDM        = G1.SHRTCKG_PIDM
                                                  AND G.SHRTCKG_TERM_CODE   = G1.SHRTCKG_TERM_CODE
                                                  AND G.SHRTCKG_TCKN_SEQ_NO = G1.SHRTCKG_TCKN_SEQ_NO)
                      AND SHRTCKG_GRDE_CODE_FINAL IN (SELECT SHRGRDE_CODE FROM SHRGRDE WHERE SHRGRDE_PASSED_IND = 'Y')
                      --AND SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB IN ('1502','1510')
                      AND ((SHRTCKN_SUBJ_CODE = 'TPRO' AND SHRTCKN_CRSE_NUMB = '1510') OR (SHRTCKN_SUBJ_CODE = 'INVE' AND SHRTCKN_CRSE_NUMB = '1504'))) HA ON 
                HD.SHRTCKN_PIDM = HA.SHRTCKN_PIDM AND HD.SHRTCKN_SUBJ_CODE = HA.SHRTCKN_SUBJ_CODE AND HD.SHRTCKN_CRSE_NUMB = HA.SHRTCKN_CRSE_NUMB)
    , LOE_SPRIDEN
WHERE HD.SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL AND HA.SHRTCKN_PIDM IS NULL)
WHERE CURSO1 IS NOT NULL AND CURSO2 IS NOT NULL
ORDER BY SHRTCKN_PIDM, SHRTCKN_TERM_CODE;
