--Historia_Notas_
SELECT SPRIDEN_ID, SPRIDEN_LAST_NAME ||', '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE, C.*
FROM ( SELECT A.SHRTCKN_PIDM, A.SHRTCKN_TERM_CODE, A.SHRTCKN_SEQ_NO, A.SHRTCKN_CRN, A.SHRTCKN_SUBJ_CODE, A.SHRTCKN_CRSE_NUMB
			, A.SHRTCKN_CRSE_TITLE, B.SHRTCKG_CREDIT_HOURS, B.SHRTCKG_GRDE_CODE_FINAL, 'Historia' AS SOURCE
		FROM ODSMGR.SHRTCKN A
				INNER JOIN ODSMGR.SHRTCKG B ON A.SHRTCKN_PIDM = B.SHRTCKG_PIDM AND A.SHRTCKN_TERM_CODE = B.SHRTCKG_TERM_CODE AND A.SHRTCKN_SEQ_NO = B.SHRTCKG_TCKN_SEQ_NO
												AND B.SHRTCKG_SEQ_NO = (SELECT MAX(b_max.SHRTCKG_SEQ_NO) FROM SHRTCKG b_max
																		WHERE A.SHRTCKN_PIDM = b_max.SHRTCKG_PIDM AND A.SHRTCKN_TERM_CODE = b_max.SHRTCKG_TERM_CODE
																			AND A.SHRTCKN_SEQ_NO = b_max.SHRTCKG_TCKN_SEQ_NO)
		UNION
		SELECT SHRTRCE_PIDM, SHRTRCE_TERM_CODE_EFF, SHRTRCE_SEQ_NO, NULL, SHRTRCE_SUBJ_CODE, SHRTRCE_CRSE_NUMB
			, SHRTRCE_CRSE_TITLE, SHRTRCE_CREDIT_HOURS, SHRTRCE_GRDE_CODE, 'Convalidado'
		FROM ODSMGR.SHRTRCE
		) C
        INNER JOIN ODSMGR.LOE_SPRIDEN ON C.SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
WHERE SPRIDEN_ID = 'N00158480'
ORDER BY SHRTCKN_TERM_CODE DESC, SOURCE, SHRTCKN_SEQ_NO, SHRTCKN_CRN
;

SELECT * FROM ODSMGR.LOE_SPRIDEN
WHERE SPRIDEN_LAST_NAME LIKE 'VELASQUEZ/SANDO%'