select 
a.PERSON_UID, a.ID, a.NAME, a.ACADEMIC_PERIOD, b.PROGRAM, b.PROGRAM_DESC, a.SUBJECT, a.COURSE_NUMBER
, a.COURSE_REFERENCE_NUMBER, a.TRANSFER_COURSE_IND, a.REGISTRATION_STATUS, a.REGISTRATION_STATUS_DATE
, a.COURSE_TITLE_SHORT, a.CAMPUS, a.CAMPUS_DESC
from STUDENT_COURSE a
    left join ACADEMIC_STUDY b on
        a.PERSON_UID = b.PERSON_UID
        and b.ACADEMIC_PERIOD in ( '218413', '218512')
        and b.STUDENT_LEVEL = 'UG'
where a.ACADEMIC_PERIOD in ( '218714', '218715');