--Inicio_Clases_WA_
SELECT C.ID, C.NAME AS ESTUDIANTE, C.PROGRAM_DESC AS CARRERA, C.CAMPUS_DESC AS SEDE, E.ALTERNATIVE_ID AS DNI, ROUND(D.ACT_CREDITS_OVERALL/20,0) AS CICLO
    , SUM(C.COURSE_CREDITS) AS CREDITOS_MATRICULADOS, C.FECHA_INICIO_CLASES
FROM ( SELECT DISTINCT A.PERSON_UID, A.ID, A.NAME, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC, B.COURSE_REFERENCE_NUMBER, B.COURSE_CREDITS
			, MIN(SSRMEET_START_DATE) OVER(PARTITION BY A.ID) AS FECHA_INICIO_CLASES
		FROM ODSMGR.ACADEMIC_STUDY A
				INNER JOIN ODSMGR.STUDENT_COURSE B ON A.PERSON_UID = B.PERSON_UID AND A.ACADEMIC_PERIOD = B.ACADEMIC_PERIOD
														AND B.TRANSFER_COURSE_IND = 'N' AND B.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF','RO','IA')
				LEFT JOIN ODSMGR.SSRMEET ON B.ACADEMIC_PERIOD = SSRMEET_TERM_CODE AND B.COURSE_REFERENCE_NUMBER = SSRMEET_CRN AND SSRMEET_START_DATE IS NOT NULL
		WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND A.STUDENT_LEVEL = 'UG' AND A.ACADEMIC_PERIOD = '221513'
		) C
			LEFT JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS D ON C.PERSON_UID = D.PERSON_UID AND C.PROGRAM = D.PROGRAM
																AND D.SEQUENCE_NUMBER = (SELECT MAX(D1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS D1
																						WHERE D1.PERSON_UID = D.PERSON_UID AND D1.PROGRAM = D.PROGRAM)
			LEFT JOIN ODSMGR.ALTERNATIVE_ID E ON C.PERSON_UID = E.ENTITY_UID AND E.ATERNATIVE_ID_TYPE = 'DNI'
													AND E.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(E1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ODSMGR.ALTERNATIVE_ID E1
																							WHERE E1.ENTITY_UID = E.ENTITY_UID AND E1.ATERNATIVE_ID_TYPE = 'DNI')
GROUP BY C.ID, C.NAME, C.PROGRAM_DESC, C.CAMPUS_DESC, E.ALTERNATIVE_ID, ROUND(D.ACT_CREDITS_OVERALL/20,0), C.FECHA_INICIO_CLASES
;