
SELECT DISTINCT a.SFRSTCR_TERM_CODE, a.SFRSTCR_PIDM, SPRIDEN_ID, a.SFRSTCR_CRN, b.SSBSECT_SUBJ_CODE, b.SSBSECT_CRSE_NUMB, a.SFRSTCR_RSTS_CODE, a.SFRSTCR_RSTS_DATE
	, a.SFRSTCR_ADD_DATE, a.SFRSTCR_LEVL_CODE, a.SFRSTCR_CAMP_CODE, c.REQUISITOS, d.SFRSTCR_CRN, d.SSBSECT_SUBJ_CODE, d.SSBSECT_CRSE_NUMB
FROM SFRSTCR a, SSBSECT b, SPRIDEN, 
    (SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
        , LISTAGG(TRIM(SCRRTST_CONNECTOR ||' '|| SCRRTST_LPAREN || SCRRTST_TESC_CODE || SCRRTST_TEST_SCORE || SCRRTST_SUBJ_CODE_PREQ || SCRRTST_CRSE_NUMB_PREQ || SCRRTST_RPAREN),' ') 
            WITHIN GROUP (ORDER BY SCRRTST_SEQNO) OVER(PARTITION BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB) AS REQUISITOS
       	, MAX(SCRRTST_TERM_CODE_EFF) OVER(PARTITION BY SCRRTST_SUBJ_CODE,SCRRTST_CRSE_NUMB) AS MAX_TERM
    FROM LOE_SCRRTST WHERE SCRRTST_TERM_CODE_EFF <= '219534') c, 
    (SELECT DISTINCT SFRSTCR_TERM_CODE, SFRSTCR_PIDM, SFRSTCR_CRN, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB
	FROM SFRSTCR, SSBSECT
	WHERE SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
	    AND SFRSTCR_TERM_CODE IN ('219435','219534') AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA')) d
WHERE a.SFRSTCR_TERM_CODE = b.SSBSECT_TERM_CODE AND a.SFRSTCR_CRN = b.SSBSECT_CRN
    AND b.SSBSECT_TERM_CODE >= c.SCRRTST_TERM_CODE_EFF(+) AND b.SSBSECT_SUBJ_CODE = c.SCRRTST_SUBJ_CODE(+) AND b.SSBSECT_CRSE_NUMB = c.SCRRTST_CRSE_NUMB(+)
    AND (SCRRTST_TERM_CODE_EFF = MAX_TERM OR SCRRTST_TERM_CODE_EFF IS NULL)
    AND a.SFRSTCR_TERM_CODE = d.SFRSTCR_TERM_CODE(+) AND a.SFRSTCR_PIDM = d.SFRSTCR_PIDM(+) AND c.REQUISITOS LIKE '%'||d.SSBSECT_SUBJ_CODE||d.SSBSECT_CRSE_NUMB||'%'
    AND a.SFRSTCR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND a.SFRSTCR_TERM_CODE IN ('219435','219534') AND a.SFRSTCR_RSTS_CODE IN ('RE','RW','RA')
ORDER BY a.SFRSTCR_TERM_CODE, a.SFRSTCR_PIDM, a.SFRSTCR_CRN;
