
SELECT DISTINCT
    SHRTCKN_TERM_CODE, SHRTCKN_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME, SPRIDEN_LAST_NAME, STVCAMP_DESC
    --, PROGRAM AS COD_CARRERA, PROGRAM_DESC AS CARRERA, SUBSTR(PROGRAM,5,2) AS PROGRAMA
    --, ACADEMIC_PERIOD_ADMITTED, ACADEMIC_PERIOD_ADMITTED_DESC
    , SHRTCKN_SUBJ_CODE || SHRTCKN_CRSE_NUMB AS COD_CURSO, SHRTCKN_CRSE_TITLE
    , CASE WHEN SSBSECT_SCHD_CODE = 'VIR' OR SSBSECT_INSM_CODE = 'V'
      THEN SHRTCKN_SUBJ_CODE ||'.'|| SHRTCKN_CRSE_NUMB ||'.'|| SHRTCKN_TERM_CODE ||'.'|| SHRTCKN_CRN ||'.'|| 'V'
    ELSE SHRTCKN_SUBJ_CODE ||'.'|| SHRTCKN_CRSE_NUMB ||'.'|| SHRTCKN_TERM_CODE ||'.'|| SHRTCKN_CRN ||'.'|| 'P' END AS SECCION
    , MAX(SUBSTR(AREA_COURSE,7,2)) OVER(PARTITION BY SHRTCKN_SUBJ_CODE,SHRTCKN_CRSE_NUMB) AS CICLO
FROM SHRTCKN, 
     SSBSECT, 
     SPRIDEN, 
     --ACADEMIC_STUDY, 
     LOE_AREA_COURSE, 
     STVCAMP
WHERE SHRTCKN_TERM_CODE = SSBSECT_TERM_CODE AND SHRTCKN_CRN = SSBSECT_CRN
    AND SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    --AND SHRTCKN_TERM_CODE = ACADEMIC_PERIOD(+) AND SHRTCKN_PIDM = PERSON_UID(+) AND STUDENT_LEVEL(+) = 'UG'
    AND SHRTCKN_SUBJ_CODE = SUBJ_CODE(+) AND SHRTCKN_CRSE_NUMB = CRSE_NUMB_LOW(+)
        AND SUBSTR(AREA_COURSE(+),7,2) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12')
    AND SHRTCKN_CAMP_CODE = STVCAMP_CODE(+)
    AND SHRTCKN_TERM_CODE IN ('218434','218533');
