--LOE_REPEAT_COURSE_LCUR_
--USE ROLE ADMIN_PROD;

USE DATABASE UPN_RPT_DM_PROD;
USE SCHEMA ODSMGR;

--CREATE OR REPLACE VIEW LOE_REPEAT_COURSE_LCUR AS
WITH SOATERM AS (
	SELECT STVTERM_CODE, SUBSTR(STVTERM_DESC,1,6) AS PERIODO_LBL, STVTERM_DESC, COALESCE(START_DATE,STVTERM_START_DATE) AS FECHA_INICIO, COALESCE(END_DATE,STVTERM_END_DATE) AS FECHA_FIN
		, TO_CHAR(COALESCE(START_DATE,STVTERM_START_DATE),'YYYYMMDD') AS FECHA_INICIO_NRO, TO_CHAR(COALESCE(END_DATE,STVTERM_END_DATE),'YYYYMMDD') AS FECHA_FIN_NRO
	FROM ODSMGR.LOE_STVTERM LEFT JOIN ODSMGR.LOE_SECTION_PART_OF_TERM ON STVTERM_CODE = TERM_CODE
	)
, AVANCE_CURRICULAR AS (
	SELECT DISTINCT PERSON_UID, PROGRAM, TERM_CODE_EFF, ACADEMIC_PERIOD, FECHA_INICIO_NRO, SUBJECT, COURSE_NUMBER
		, COALESCE(MAX(ORIGEN1) OVER(PARTITION BY PERSON_UID, PROGRAM, TERM_CODE_EFF, ACADEMIC_PERIOD, SUBJECT, COURSE_NUMBER)
			, MAX(ORIGEN2) OVER(PARTITION BY PERSON_UID, PROGRAM, TERM_CODE_EFF, ACADEMIC_PERIOD, SUBJECT, COURSE_NUMBER)) AS ORIGEN
		, MIN(FECHA_INICIO_NRO) OVER(PARTITION BY PERSON_UID, PROGRAM, TERM_CODE_EFF) AS MIN_PERIODO
	FROM (	--CUMPLIDOS
		SELECT A.PERSON_UID, A.PROGRAM, A.TERM_CODE_EFF, B.ACADEMIC_PERIOD, FECHA_INICIO_NRO, B.SUBJECT, B.COURSE_NUMBER, 'CAPP' AS ORIGEN1, NULL AS ORIGEN2
		FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A
				INNER JOIN ODSMGR.SMBAOGN ON A.PERSON_UID = SMBAOGN_PIDM AND A.SEQUENCE_NUMBER = SMBAOGN_REQUEST_NO AND A.PROGRAM = SMBAOGN_PROGRAM AND A.TERM_CODE_EFF = SMBAOGN_TERM_CODE_EFF
				INNER JOIN ODSMGR.LOE_COURSE_ATTRIBUTE_PROGRAM B ON SMBAOGN_PIDM = B.PERSON_UID AND SMBAOGN_REQUEST_NO = B.REQUEST_NO AND SMBAOGN_TERM_CODE_EFF = B.TERM_CODE_EFF AND SMBAOGN_AREA = B.AREA AND SMBAOGN_PROGRAM = B.PROGRAM
				INNER JOIN ODSMGR.LOE_SOVLCUR ON A.PERSON_UID = SOVLCUR_PIDM AND A.PROGRAM = SOVLCUR_PROGRAM AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LEVL_CODE = 'UG'
				INNER JOIN SOATERM ON B.ACADEMIC_PERIOD = STVTERM_CODE
		WHERE SUBSTR(SMBAOGN_AREA,LENGTH(SMBAOGN_AREA)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12')
			AND A.SEQUENCE_NUMBER = (SELECT MAX(A1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS A1
										WHERE A1.PERSON_UID = A.PERSON_UID AND A1.PROGRAM = A.PROGRAM)
		UNION --MATRICULADOS
		SELECT DISTINCT SFRSTCR_PIDM, SOVLCUR_PROGRAM, COALESCE(C.TERM_CODE_EFF, D.TERM_CODE_EFF), SFRSTCR_TERM_CODE, B.FECHA_INICIO_NRO, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB, NULL, 'INSCRIPCION'
		FROM ODSMGR.SFRSTCR A
				INNER JOIN ODSMGR.LOE_SSBSECT ON SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
				INNER JOIN ODSMGR.LOE_SOVLCUR ON SFRSTCR_PIDM = SOVLCUR_PIDM AND SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE' AND SOVLCUR_CURRENT_IND = 'Y' AND SOVLCUR_LEVL_CODE = 'UG'
				INNER JOIN SOATERM B ON SFRSTCR_TERM_CODE = B.STVTERM_CODE
				LEFT JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C ON SOVLCUR_PIDM = C.PERSON_UID AND SOVLCUR_PROGRAM = C.PROGRAM
																AND C.SEQUENCE_NUMBER = (SELECT MAX(C1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C1
																						WHERE C1.PERSON_UID = C.PERSON_UID AND C1.PROGRAM = C.PROGRAM)
				LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY D ON SOVLCUR_PROGRAM = D.PROGRAM
																AND D.TERM_CODE_EFF = (SELECT MAX(D1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY D1
																						WHERE D1.PROGRAM = SOVLCUR_PROGRAM AND D1.TERM_CODE_EFF <= SOVLCUR_TERM_CODE_CTLG)
		WHERE SFRSTCR_RSTS_CODE NOT IN ('DD','DW') AND SSBSECT_SUBJ_CODE NOT IN ('TUTO','REPS','XSER','ACAD','TEST','XPEN') AND (SSBSECT_SUBJ_CODE <> 'IDIO' OR SFRSTCR_LEVL_CODE <> 'CR')
			AND B.FECHA_INICIO = (SELECT MAX(B1.START_DATE) FROM ODSMGR.SFRSTCR A1 INNER JOIN ODSMGR.LOE_SECTION_PART_OF_TERM B1 ON A1.SFRSTCR_TERM_CODE = B1.TERM_CODE WHERE A1.SFRSTCR_PIDM = A.SFRSTCR_PIDM)
			--AND SFRSTCR_TERM_CODE IN (SELECT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM WHERE CURRENT_DATE BETWEEN START_DATE AND END_DATE AND SUBSTR(TERM_CODE,4,1) IN ('4','5'))
		UNION --PROYECCIONES
		SELECT SFRREGP_PIDM, SFRREGP_PROGRAM, C.TERM_CODE_EFF, SFRREGP_TERM_CODE, B.FECHA_INICIO_NRO, SFRREGP_SUBJ_CODE, SFRREGP_CRSE_NUMB_LOW, NULL, NULL
		FROM ODSMGR.SFRREGP A
				INNER JOIN SOATERM B ON SFRREGP_TERM_CODE = B.STVTERM_CODE
				INNER JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C ON SFRREGP_PIDM = C.PERSON_UID AND SFRREGP_PROGRAM = C.PROGRAM
																AND C.SEQUENCE_NUMBER = (SELECT MAX(C1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS C1
																						WHERE C1.PERSON_UID = C.PERSON_UID AND C1.PROGRAM = C.PROGRAM)
		WHERE B.FECHA_INICIO = (SELECT MAX(B1.START_DATE) FROM ODSMGR.SFRREGP A1 INNER JOIN ODSMGR.LOE_SECTION_PART_OF_TERM B1 ON A1.SFRREGP_TERM_CODE = B1.TERM_CODE WHERE A1.SFRREGP_PIDM = A.SFRREGP_PIDM)
			--SFRREGP_TERM_CODE IN (SELECT TERM_CODE FROM ODSMGR.LOE_SECTION_PART_OF_TERM WHERE CURRENT_DATE < END_DATE AND SUBSTR(TERM_CODE,4,1) IN ('4','5'))
		)
	)
SELECT AV.PERSON_UID, AV.PROGRAM, AV.TERM_CODE_EFF, AV.ACADEMIC_PERIOD, AV.SUBJECT, AV.COURSE_NUMBER, COALESCE(AV.ORIGEN,'PROYECCION') AS ORIGEN, COUNT(DISTINCT HST.SHRTCKN_TERM_CODE) AS COURSE_COUNT
FROM AVANCE_CURRICULAR AV
	INNER JOIN (SELECT SHRTCKN_PIDM, SHRTCKN_TERM_CODE, FECHA_INICIO_NRO, SHRTCKN_SEQ_NO, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, SHRTCKG_SEQ_NO, SHRTCKG_GRDE_CODE_FINAL, SCREQIV_SUBJ_CODE, SCREQIV_CRSE_NUMB
				FROM ODSMGR.SHRTCKN
					INNER JOIN ODSMGR.SHRTCKG G ON SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
													AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM ODSMGR.SHRTCKG G1
																			WHERE G.SHRTCKG_PIDM = G1.SHRTCKG_PIDM AND G.SHRTCKG_TERM_CODE = G1.SHRTCKG_TERM_CODE AND G.SHRTCKG_TCKN_SEQ_NO = G1.SHRTCKG_TCKN_SEQ_NO)
													AND SHRTCKG_GRDE_CODE_FINAL NOT IN (SELECT SHRGRDE_CODE FROM ODSMGR.SHRGRDE WHERE SHRGRDE_PASSED_IND = 'Y' AND SHRGRDE_LEVL_CODE = 'UG') AND SHRTCKG_GRDE_CODE_FINAL NOT LIKE 'R%'
					INNER JOIN SOATERM ON SHRTCKN_TERM_CODE = STVTERM_CODE
					LEFT JOIN ODSMGR.SCREQIV ON SHRTCKN_SUBJ_CODE = SCREQIV_SUBJ_CODE_EQIV AND SHRTCKN_CRSE_NUMB = SCREQIV_CRSE_NUMB_EQIV AND SHRTCKN_TERM_CODE BETWEEN SCREQIV_START_TERM AND SCREQIV_END_TERM
					) HST ON AV.PERSON_UID = HST.SHRTCKN_PIDM AND AV.FECHA_INICIO_NRO > HST.FECHA_INICIO_NRO
							AND ( (AV.SUBJECT = HST.SHRTCKN_SUBJ_CODE AND AV.COURSE_NUMBER = HST.SHRTCKN_CRSE_NUMB) OR (AV.SUBJECT = HST.SCREQIV_SUBJ_CODE AND AV.COURSE_NUMBER = HST.SCREQIV_CRSE_NUMB) )
	LEFT JOIN ( SELECT PERSON_UID, PROGRAM, MAX(FECHA_INICIO_NRO) AS FECHA_INICIO_NRO
				FROM ODSMGR.FIELD_OF_STUDY
					INNER JOIN SOATERM ON ACADEMIC_PERIOD = STVTERM_CODE
				WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO' AND STUDENT_LEVEL = 'UG'
				GROUP BY PERSON_UID, PROGRAM
					) EGR ON AV.PERSON_UID = EGR.PERSON_UID AND AV.PROGRAM <> EGR.PROGRAM AND AV.MIN_PERIODO > EGR.FECHA_INICIO_NRO
WHERE HST.FECHA_INICIO_NRO > COALESCE(EGR.FECHA_INICIO_NRO,'00000000')
GROUP BY AV.PERSON_UID, AV.PROGRAM, AV.TERM_CODE_EFF, AV.ACADEMIC_PERIOD, AV.SUBJECT, AV.COURSE_NUMBER, COALESCE(AV.ORIGEN,'PROYECCION')
--ORDER BY AV.PERSON_UID, AV.PROGRAM, AV.TERM_CODE_EFF, AV.ACADEMIC_PERIOD, AV.SUBJECT, AV.COURSE_NUMBER
;
