--LOE_AREA_CERTIFICADA_
SELECT SMBAOGN_PIDM AS PERSON_UID, SPRIDEN_ID AS ID, SMBAOGN_REQUEST_NO AS REQUEST_NO, SMBAOGN_PROGRAM AS PROGRAM, SMRPRLE_PROGRAM_DESC AS PROGRAM_DESC
	, SMBAOGN_TERM_CODE_EFF AS TERM_CODE_EFF, SMBAOGN_ACTIVITY_DATE AS ACTIVITY_DATE, SMBAOGN_AREA AS AREA
	, MIN(A.ACADEMIC_PERIOD) AS MIN_TERM_CODE, MAX(A.ACADEMIC_PERIOD) AS MAX_TERM_CODE, SMRDORQ_SUBSET AS SUBCONJUNTO
	, COALESCE( 
		TRIM(MAX(CASE WHEN M.SMRACMT_PRNT_CODE = 'LNAME1' THEN TRIM(SUBSTR(M.SMRACMT_TEXT,5)) ELSE NULL END) ||' '||
			COALESCE(MAX(CASE WHEN M.SMRACMT_PRNT_CODE = 'LNAME2' THEN TRIM(SUBSTR(M.SMRACMT_TEXT,5)) ELSE NULL END),' '))
		, TRIM(MAX(CASE WHEN C.SMRACMT_PRNT_CODE = 'LNAME1' THEN TRIM(C.SMRACMT_TEXT) ELSE NULL END) ||' '||
			COALESCE(MAX(CASE WHEN C.SMRACMT_PRNT_CODE = 'LNAME2' THEN TRIM(C.SMRACMT_TEXT) ELSE NULL END),' ')) ) AS LNAME
FROM ODSMGR.SMBAOGN
		INNER JOIN ODSMGR.LOE_COURSE_ATTRIBUTE_PROGRAM A ON SMBAOGN_PIDM = A.PERSON_UID AND SMBAOGN_REQUEST_NO = A.REQUEST_NO AND SMBAOGN_AREA = A.AREA
		INNER JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS P ON SMBAOGN_PIDM = P.PERSON_UID AND SMBAOGN_REQUEST_NO = P.SEQUENCE_NUMBER
								AND P.SEQUENCE_NUMBER = (SELECT MAX(P1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS P1
															WHERE P1.PERSON_UID = P.PERSON_UID AND P1.PROGRAM = P.PROGRAM)
		INNER JOIN ODSMGR.LOE_SPRIDEN ON SMBAOGN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN ODSMGR.SMRDORQ ON SMBAOGN_PIDM = SMRDORQ_PIDM AND SMBAOGN_REQUEST_NO = SMRDORQ_REQUEST_NO AND SMBAOGN_AREA = SMRDORQ_AREA AND SMRDORQ_MET_IND = 'Y'
		LEFT JOIN ODSMGR.LOE_SMRACMT M ON SMRDORQ_AREA = M.SMRACMT_AREA AND SMRDORQ_TERM_CODE_EFF = M.SMRACMT_TERM_CODE_EFF AND TO_CHAR(SMRDORQ_SUBSET) = SUBSTR(M.SMRACMT_TEXT,1,3)
								AND SUBSTR(M.SMRACMT_TEXT,4,1) = '-' AND M.SMRACMT_PRNT_CODE IN ('LNAME1','LNAME2')
		LEFT JOIN ODSMGR.LOE_SMRACMT C ON SMBAOGN_AREA = C.SMRACMT_AREA AND SMBAOGN_TERM_CODE_EFF = C.SMRACMT_TERM_CODE_EFF AND C.SMRACMT_PRNT_CODE IN ('LNAME1','LNAME2')
		LEFT JOIN ODSMGR.SMRPRLE ON SMBAOGN_PROGRAM = SMRPRLE_PROGRAM
WHERE SMBAOGN_MET_IND = 'Y' AND (SMBAOGN_AREA LIKE '%-CERT' OR SMBAOGN_AREA LIKE '%-CON')
GROUP BY SMBAOGN_PIDM, SPRIDEN_ID, SMBAOGN_REQUEST_NO, SMBAOGN_PROGRAM, SMRPRLE_PROGRAM_DESC, SMBAOGN_TERM_CODE_EFF, SMBAOGN_ACTIVITY_DATE, SMBAOGN_AREA, SMRDORQ_SUBSET
ORDER BY SMBAOGN_PIDM
;