SELECT DISTINCT
    c.SHRTCKG_PIDM
    , e.SPRIDEN_ID
    , e.SPRIDEN_LAST_NAME
    , e.SPRIDEN_FIRST_NAME
    , c.SHRTCKG_TERM_CODE
    , d.CAMPUS
    , d.CAMPUS_DESC
    , c.SHRTCKN_CRN
    , c.SHRTCKN_SUBJ_CODE
    , c.SHRTCKN_CRSE_NUMB
    , c.SHRTCKG_SEQ_NO
    , c.SHRTCKG_GRDE_CODE_FINAL
    , c.SHRTCKG_GMOD_CODE
    , c.SHRTCKG_CREDIT_HOURS
    , c.SHRTCKG_GCHG_CODE
    , c.SHRTCKG_FINAL_GRDE_CHG_DATE
    , c.SHRTCKG_FINAL_GRDE_CHG_USER
    , f.SPRIDEN_LAST_NAME
    , f.SPRIDEN_FIRST_NAME
FROM
    (((SELECT DISTINCT
        a.SHRTCKG_PIDM
        , a.SHRTCKG_TERM_CODE
        , b.SHRTCKN_CRN
        , b.SHRTCKN_SUBJ_CODE
        , b.SHRTCKN_CRSE_NUMB
        , a.SHRTCKG_SEQ_NO
        , MAX(a.SHRTCKG_SEQ_NO) OVER(PARTITION BY a.SHRTCKG_PIDM ,a.SHRTCKG_TERM_CODE, a.SHRTCKG_TCKN_SEQ_NO) AS MAX_SEQ
        , a.SHRTCKG_GRDE_CODE_FINAL
        , a.SHRTCKG_GMOD_CODE
        , a.SHRTCKG_CREDIT_HOURS
        , a.SHRTCKG_GCHG_CODE
        , a.SHRTCKG_FINAL_GRDE_CHG_DATE
        , a.SHRTCKG_FINAL_GRDE_CHG_USER
        , MAX(CASE WHEN SHRTCKG_FINAL_GRDE_CHG_USER NOT IN ('SATURN','CONVERT1')
                  THEN 'FUNCIONAL'
              ELSE NULL END) OVER(PARTITION BY a.SHRTCKG_PIDM ,a.SHRTCKG_TERM_CODE, a.SHRTCKG_TCKN_SEQ_NO) AS INTERVENCION
    FROM
        SHRTCKG a
            INNER JOIN SHRTCKN b ON
                a.SHRTCKG_PIDM = b.SHRTCKN_PIDM
                AND a.SHRTCKG_TERM_CODE = b.SHRTCKN_TERM_CODE
                AND a.SHRTCKG_TCKN_SEQ_NO = b.SHRTCKN_SEQ_NO) c
        LEFT JOIN ACADEMIC_STUDY d ON
            c.SHRTCKG_PIDM = d.PERSON_UID
            AND c.SHRTCKG_TERM_CODE = d.ACADEMIC_PERIOD
            AND d.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') )
        LEFT JOIN SPRIDEN e ON
            c.SHRTCKG_PIDM = e.SPRIDEN_PIDM
            AND e.SPRIDEN_CHANGE_IND IS NULL )
        LEFT JOIN SPRIDEN f ON
            SUBSTR(c.SHRTCKG_FINAL_GRDE_CHG_USER,2,9) = f.SPRIDEN_ID
            AND f.SPRIDEN_CHANGE_IND IS NULL
WHERE c.MAX_SEQ > 1/* AND c.INTERVENCION = 'FUNCIONAL' AND c.SHRTCKG_TERM_CODE IN ('218714','218715')*/ AND d.CAMPUS = 'CAJ'
ORDER BY c.SHRTCKG_PIDM, c.SHRTCKG_TERM_CODE, c.SHRTCKN_SUBJ_CODE, c.SHRTCKN_CRSE_NUMB, c.SHRTCKG_SEQ_NO;
