--Malla_Curricular_
/*
WITH REQUISITOS AS (
	SELECT SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
        , LISTAGG(TRIM(COALESCE(SCRRTST_CONNECTOR,'') ||' '|| COALESCE(SCRRTST_LPAREN,'') || COALESCE(SCRRTST_TESC_CODE,'') || COALESCE(SCRRTST_TEST_SCORE,'')
        		|| COALESCE(SCRRTST_SUBJ_CODE_PREQ,'') || COALESCE(SCRRTST_CRSE_NUMB_PREQ,'') || COALESCE(SCRRTST_RPAREN,'')),' ')
            WITHIN GROUP (ORDER BY SCRRTST_SEQNO) AS REQUISITOS
    FROM ODSMGR.LOE_SCRRTST
    GROUP BY SCRRTST_TERM_CODE_EFF, SCRRTST_SUBJ_CODE, SCRRTST_CRSE_NUMB
	)
, EQUIVALENCIAS AS (
	SELECT EFF_TERM, SUBJECT, COURSE_NUMBER
        , LISTAGG(SUBJECT_CODE_EQUIV || COURSE_NUMBER_EQUIV,', ') WITHIN GROUP (ORDER BY SURROGATE_ID) AS EQUIVALENCIAS
    FROM ODSMGR.LOE_EQUIV_COURSE_REPEATING
    GROUP BY EFF_TERM, SUBJECT, COURSE_NUMBER
	)
*/
SELECT DISTINCT A.PROGRAM, A.TERM_CODE_EFF/*, A.AREA, B.AREA_RULE, SMBARUL_DESC, B.SEQNO, SMRARUL_SEQNO
	, ROW_NUMBER() OVER(PARTITION BY A.PROGRAM, A.TERM_CODE_EFF ORDER BY A.AREA, B.SEQNO, SMRARUL_SEQNO) AS SEQ*/
	, SUBSTR(A.AREA,LENGTH(A.AREA)-1) AS CICLO
    , CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END || CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END AS COD_CURSO
    , COALESCE(D.TITLE_LONG_DESC, D.TITLE_SHORT_DESC) AS CURSO, COALESCE(D.CREDIT_MIN,0) AS CREDITOS--, E.REQUISITOS, F.EQUIVALENCIAS
    , CASE WHEN V.TERM_CODE_EFF IS NULL THEN 0 ELSE 1 END AS VIGENTE
FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY A
		INNER JOIN ODSMGR.LOE_AREA_COURSE B ON A.AREA = B.AREA_COURSE AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
		LEFT JOIN ODSMGR.LOE_SMRARUL ON B.AREA_COURSE = SMRARUL_AREA AND B.TERM_CODE_EFF = SMRARUL_TERM_CODE_EFF AND B.AREA_RULE = SMRARUL_KEY_RULE
		LEFT JOIN ODSMGR.LOE_SMBARUL ON B.AREA_COURSE = SMBARUL_AREA AND B.TERM_CODE_EFF = SMBARUL_TERM_CODE_EFF AND B.AREA_RULE = SMBARUL_KEY_RULE
		LEFT JOIN ODSMGR.COURSE_CATALOG D ON B.TERM_CODE_EFF = D.ACADEMIC_PERIOD AND CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = D.SUBJECT
															AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = D.COURSE_NUMBER
		/*
		LEFT JOIN REQUISITOS E ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = E.SCRRTST_SUBJ_CODE
									AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = E.SCRRTST_CRSE_NUMB
									AND E.SCRRTST_TERM_CODE_EFF = (SELECT MAX(E1.SCRRTST_TERM_CODE_EFF) FROM REQUISITOS E1
																	WHERE E1.SCRRTST_SUBJ_CODE = CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
																		AND E1.SCRRTST_CRSE_NUMB = CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END
																		AND E1.SCRRTST_TERM_CODE_EFF <= B.TERM_CODE_EFF)
		LEFT JOIN EQUIVALENCIAS F ON CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END = F.SUBJECT
									AND CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END = F.COURSE_NUMBER
									AND F.EFF_TERM = (SELECT MAX(F1.EFF_TERM) FROM EQUIVALENCIAS F1
														WHERE F1.SUBJECT = CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END
															AND F1.COURSE_NUMBER = CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END
															AND F1.EFF_TERM <= B.TERM_CODE_EFF)
		*/
		LEFT JOIN ODSMGR.LOE_PROGRAM_AREA_PRIORITY V ON A.PROGRAM = V.PROGRAM AND A.TERM_CODE_EFF = V.TERM_CODE_EFF
														AND V.TERM_CODE_EFF = (SELECT MAX(V1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY V1
																				WHERE V1.PROGRAM = V.PROGRAM)
WHERE SUBSTR(A.AREA,LENGTH(A.AREA)-1) IN ('01','02','03','04','05','06','07','08','09','10','11','12') AND SUBSTR(A.PROGRAM,LENGTH(A.PROGRAM)-2) IN ('-UG','-WA')
    AND CASE WHEN B.AREA_RULE IS NULL THEN B.SUBJ_CODE ELSE SMRARUL_SUBJ_CODE END || CASE WHEN B.AREA_RULE IS NULL THEN B.CRSE_NUMB_LOW ELSE SMRARUL_CRSE_NUMB_LOW END IS NOT NULL
;