--Matriculas_xReclutar
SELECT X.SFRSTCR_PIDM, CAST(X.SPRIDEN_ID AS VARCHAR(20)) AS ID, CAST(X.ESTUDIANTE AS VARCHAR(50)) AS ESTUDIANTE, CAST(X.SFRSTCR_TERM_CODE AS VARCHAR(20)) AS PERIODO
	, CAST(X.RETIRO AS VARCHAR(10)) AS RETIRO, CAST(X.SOVLCUR_CAMP_CODE AS VARCHAR(10)) AS CAMPUS, X.FECHA_PAGO_FM, X.FECHA_PAGO_T1, ROUND(X.DEUDA,2) AS DEUDA, X.CUOTAS
	, CAST(CASE
		WHEN X.RETIRO IS NOT NULL THEN 'RETIRADO'
		WHEN X.DEUDA > 0 THEN 'CON DEUDA'
		WHEN X.FECHA_PAGO_FM IS NOT NULL OR FECHA_PAGO_T1 IS NOT NULL THEN 'CON PAGO_MATR'
		WHEN X.DEUDA IS NULL THEN 'SIN DEUDA'
		ELSE NULL END AS VARCHAR(20)) AS ESTADO_INICIAL
	, X.FECHA_REGISTRO_CURSO
FROM (
	SELECT A.SFRSTCR_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE, A.SFRSTCR_TERM_CODE
		, CASE WHEN SFBETRM_ESTS_CODE IN ('RF','RO') THEN SFBETRM_ESTS_CODE END AS RETIRO, E.SOVLCUR_CAMP_CODE
		, MAX(CASE 
			WHEN P.CARGO = 'MATRICULA' AND P.INVOICE_AMOUNT = 0 THEN FECHA_EMISION
			WHEN P.CARGO = 'MATRICULA' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
			WHEN P.CARGO = 'MATRICULA' THEN P.FECHA_PAGO
			END) AS FECHA_PAGO_FM
		, MAX(CASE 
			WHEN P.CARGO = 'CUOTA INICIAL' AND P.INVOICE_AMOUNT = 0 THEN P.FECHA_EMISION
			WHEN P.CARGO = 'CUOTA INICIAL' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
			WHEN P.CARGO = 'CUOTA INICIAL' THEN P.FECHA_PAGO
			END) AS FECHA_PAGO_T1
		, F.DEUDA, F.CUOTAS
		, MIN(B.SFRSTCR_ADD_DATE) AS FECHA_REGISTRO_CURSO
	FROM ODSMGR.SFRSTCR A
			INNER JOIN ODSMGR.LOE_SPRIDEN ON A.SFRSTCR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
			LEFT JOIN ODSMGR.SFRSTCR B ON A.SFRSTCR_PIDM = B.SFRSTCR_PIDM AND B.SFRSTCR_TERM_CODE IN ('220435','220534') AND B.SFRSTCR_RSTS_CODE IN ('RE','RW','RA','WC','RF')
			LEFT JOIN ODSMGR.HOLD C ON A.SFRSTCR_PIDM = C.PERSON_UID AND HOLD = 'BA' AND ACTIVE_HOLD_IND = 'Y'
			LEFT JOIN ( SELECT DISTINCT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON FROM ODSMGR.FIELD_OF_STUDY
						WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO' AND STUDENT_LEVEL = 'UG' AND ACADEMIC_PERIOD IN ('220413','220513')
						) D ON A.SFRSTCR_PIDM = D.PERSON_UID
			LEFT JOIN ODSMGR.SFBETRM ON A.SFRSTCR_PIDM = SFBETRM_PIDM AND A.SFRSTCR_TERM_CODE = SFBETRM_TERM_CODE
			LEFT JOIN ODSMGR.LOE_SOVLCUR E ON A.SFRSTCR_PIDM = E.SOVLCUR_PIDM
												AND E.SOVLCUR_SEQNO = (SELECT MAX(E1.SOVLCUR_SEQNO) FROM ODSMGR.LOE_SOVLCUR E1
																		WHERE E1.SOVLCUR_PIDM = A.SFRSTCR_PIDM AND A.SFRSTCR_TERM_CODE BETWEEN SOVLCUR_TERM_CODE AND COALESCE(SOVLCUR_TERM_CODE_END,'999996')
																			AND E1.SOVLCUR_LMOD_CODE = 'LEARNER' AND E1.SOVLCUR_CACT_CODE = 'ACTIVE' AND E1.SOVLCUR_LEVL_CODE = 'UG')
			LEFT JOIN ODSMGR.PS_MATRICULA_CUOTAINICIAL P ON A.SFRSTCR_PIDM = P.PIDM AND P.PERIODO IN ('220435','220534') AND P.CARGO IN ('MATRICULA','CUOTA INICIAL')
			LEFT JOIN ( SELECT A.CUST_ID, SUM(A.BAL_AMT) AS DEUDA, COUNT(DISTINCT B.INSTALL_NBR) AS CUOTAS
						FROM ODSMGR.PS_ITEM A LEFT JOIN ODSMGR.PS_BI_INSTALL_SCHE B ON A.ITEM = B.GENERATED_INVOICE
						WHERE A.CUST_ID <> '9999999999' AND A.ITEM_STATUS = 'O' AND A.DUE_DT < CURRENT_DATE
						GROUP BY A.CUST_ID
						) F ON SPRIDEN_ID = F.CUST_ID AND F.DEUDA > 0
	WHERE A.SFRSTCR_TERM_CODE IN ('220413','220513') AND A.SFRSTCR_RSTS_CODE IN ('RE','RW','RA','WC','RF')
		/*AND B.SFRSTCR_PIDM IS NULL */AND C.PERSON_UID IS NULL AND D.PERSON_UID IS NULL
	GROUP BY A.SFRSTCR_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME, A.SFRSTCR_TERM_CODE
		, CASE WHEN SFBETRM_ESTS_CODE IN ('RF','RO') THEN SFBETRM_ESTS_CODE END, E.SOVLCUR_CAMP_CODE, F.DEUDA, F.CUOTAS
	) X
;
