
SELECT DISTINCT
    a.PERSON_UID, e.ID, CONCAT(e.LAST_NAME,CONCAT(', ',e.FIRST_NAME)) AS NOMBRE_ESTUDIANTE
    , CASE WHEN SUBSTR(a.PROGRAM,5,2) IN ('UG','WA') THEN SUBSTR(a.PROGRAM,5,2) ELSE NULL END AS NIVEL
    , a.ACADEMIC_PERIOD, a.PROGRAM, a.PROGRAM_DESC, a.CAMPUS_DESC, d.ACT_CREDITS_OVERALL
    , MAX(CASE WHEN f.PHONE_TYPE = 'TP' THEN f.PHONE_NUMBER_COMBINED ELSE NULL END) OVER(PARTITION BY f.ENTITY_UID) AS TELEFONO
    , MAX(CASE WHEN f.PHONE_TYPE = 'CP' THEN f.PHONE_NUMBER_COMBINED ELSE NULL END) OVER(PARTITION BY f.ENTITY_UID) AS CELULAR
    , MAX(g.EMAIL_ADDRESS) OVER(PARTITION BY g.PERSON_UID) AS CORREO
    , CASE WHEN h.PERSON_UID IS NOT NULL THEN 'Y' ELSE NULL END AS CURRICULA_INGLES
FROM ACADEMIC_STUDY a, 
     STUDENT_COURSE b, 
     SHRTGPA c, 
     (SELECT DISTINCT
          PERSON_UID, SEQUENCE_NUMBER, PROGRAM, TERM_CODE_CATLG, LEVL_CODE, CAMP_CODE, ACT_CREDITS_OVERALL
          , MAX(SEQUENCE_NUMBER) OVER(PARTITION BY PERSON_UID,PROGRAM) AS MAX_SEQ
      FROM LOE_PROGRAM_OVERALL_RESULTS
      WHERE PROGRAM <> 'PREREQ') d, 
     PERSON_DETAIL e, 
     TELEPHONE f, 
     LOE_EMAIL g, 
     FIELD_OF_STUDY h
WHERE a.PERSON_UID = b.PERSON_UID AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD
        AND b.TRANSFER_COURSE_IND = 'N' AND b.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF')
    AND a.PERSON_UID = c.SHRTGPA_PIDM(+) AND c.SHRTGPA_LEVL_CODE(+) = 'CR' AND c.SHRTGPA_LEVL_CODE IS NULL
    AND a.PERSON_UID = d.PERSON_UID(+) AND a.PROGRAM = d.PROGRAM(+)
        AND d.SEQUENCE_NUMBER(+) = d.MAX_SEQ(+)    
    AND a.PERSON_UID = e.PERSON_UID
    AND a.PERSON_UID = f.ENTITY_UID(+) AND f.PHONE_TYPE(+) IN ('TP','CP')
    AND a.PERSON_UID = g.PERSON_UID(+) AND g.STATUS_IND(+) = 'A' AND g.EMAIL_TYPE(+) = 'PERS'
    AND a.PERSON_UID = h.PERSON_UID(+) AND h.SOURCE(+) = 'LEARNER' AND h.STUDENT_LEVEL(+) = 'CR'
    AND a.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND a.STUDENT_LEVEL = 'UG' AND a.ACADEMIC_PERIOD IN ('218434','218533');
