SELECT DISTINCT
	PS.*, BN.PROGRAM, BN.PROGRAM_DESC, BN.CAMPUS_DESC, BN.FECHA_REGISTRO_CURSOS
	, BN.TIPO_ESTUDIANTE, BN.CREDITOS, BN.CURSOS, BN.CUOTA_INICIAL, BN.ARANCEL
FROM ( SELECT DISTINCT SPRIDEN_PIDM, C.BILL_TO_CUST_ID, CONCAT(CONCAT(SPRIDEN_LAST_NAME,', '),SPRIDEN_FIRST_NAME) AS NOMBRE_ESTUDIANTE
			, CASE WHEN D.ITEM_STATUS = 'C' THEN NVL(E.CREATEDTTM,D.LAST_ACTIVITY_DT) ELSE E.CREATEDTTM END AS FECHA_PAGO
			, CASE WHEN D.ITEM_STATUS = 'C' THEN D.LAST_ACTIVITY_DT END AS FECHA_CONTABLE, C.PO_REF
		FROM (SELECT DISTINCT A.BUSINESS_UNIT, A.INVOICE, A.BILL_TO_CUST_ID, A.BILL_STATUS, A.BILL_TYPE_ID, A.NAME1
				  , A.INVOICE_AMOUNT, A.INVOICE_DT, A.PO_REF, A.ADD_DTTM
		    	  , MAX(A.ADD_DTTM) OVER(PARTITION BY A.BILL_TO_CUST_ID, A.PO_REF) AS MAX_ADD_DTTM
				  FROM PS_BI_HDR A, PS_BI_LINE B
			  WHERE A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.INVOICE
		    	  AND (UPPER(B.DESCR) LIKE '%CUOTA%INI%' OR UPPER(B.DESCR) LIKE '%CUOTA 0%' 
		        	  OR UPPER(B.DESCR) LIKE '%CUOTA 1%') AND UPPER(B.DESCR) NOT LIKE '%ARANCEL%'
		    	  AND A.BUSINESS_UNIT = 'PER03' AND A.BILL_STATUS = 'INV'
		    	  AND A.BILL_TYPE_ID IN ('B1','F1') AND A.PO_REF IN ('220402','220502')) C --INGRESAR PERIODO
			, PS_ITEM D, PS_LI_GBL_ARPY_REF E, SPRIDEN
		WHERE C.BUSINESS_UNIT = D.BUSINESS_UNIT AND C.INVOICE = D.ITEM
		    AND C.BUSINESS_UNIT = E.DEPOSIT_BU(+) AND C.INVOICE = E.INVOICE(+)
		    AND (E.CREATEDTTM = (SELECT MAX(E1.CREATEDTTM) FROM PS_LI_GBL_ARPY_REF E1
				    				WHERE E1.DEPOSIT_BU = E.DEPOSIT_BU
				    					AND E1.INVOICE = E.INVOICE) OR E.CREATEDTTM IS NULL)
			AND C.ADD_DTTM = C.MAX_ADD_DTTM
			AND C.BILL_TO_CUST_ID = SPRIDEN_ID AND SPRIDEN_CHANGE_IND IS NULL ) PS
	, ( SELECT DISTINCT a.*
		    , SUM(CASE WHEN SUBSTR(b.DETAIL_CODE,1,2) = 'T1'
		        OR SUBSTR(b.CROSSREF_DETAIL_CODE,1,2) = 'T1' THEN b.BALANCE ELSE 0 END)
		          OVER(PARTITION BY b.ACCOUNT_UID,b.ACADEMIC_PERIOD) AS CUOTA_INICIAL
		    , SUM(CASE WHEN SUBSTR(b.DETAIL_CODE,1,2) = 'TA'
		        OR SUBSTR(b.CROSSREF_DETAIL_CODE,1,2) = 'TA' THEN b.BALANCE ELSE 0 END)
		          OVER(PARTITION BY b.ACCOUNT_UID,b.ACADEMIC_PERIOD) AS ARANCEL
		FROM (SELECT DISTINCT a.PERSON_UID, a.ACADEMIC_PERIOD, a.PROGRAM, a.PROGRAM_DESC, a.CAMPUS_DESC
		          , MIN(b.SECTION_ADD_DATE) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS FECHA_REGISTRO_CURSOS
		          , CASE a.STUDENT_POPULATION
		                WHEN 'N'
		                    THEN CASE WHEN a.ADMISSIONS_POPULATION = 'II' THEN 'INTERCAMBIO IN'
		                            ELSE 'NUEVO' END
		                WHEN 'C'
		                    THEN CASE WHEN a.STUDENT_LEVEL = 'UG' AND c.COHORT = 'NEW_REING' THEN 'NUEVO REINGRESO'
		                            WHEN a.STUDENT_LEVEL = 'UG' AND c.COHORT = 'REINGRESO' THEN 'REINGRESO'
		                            WHEN a.ADMISSIONS_POPULATION = 'II' THEN 'INTERCAMBIO IN'
		                            WHEN a.ADMISSIONS_POPULATION <> 'RE' AND d.STUDENT_ATTRIBUTE = 'TINT' THEN 'INTERCAMBIO OUT'
		                            WHEN e.ACTIVITY = 'ITO' THEN 'INTERCAMBIO OUT'
		                            ELSE 'CONTINUO' END
		                ELSE a.STUDENT_POPULATION END AS TIPO_ESTUDIANTE
		          , SUM(b.COURSE_CREDITS) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS CREDITOS
		          , COUNT(b.COURSE_REFERENCE_NUMBER) OVER(PARTITION BY b.PERSON_UID,b.ACADEMIC_PERIOD) AS CURSOS
		      FROM ACADEMIC_STUDY a, 
		           STUDENT_COURSE b, 
		           STUDENT_COHORT c, 
		           STUDENT_ATTRIBUTE d, 
		           STUDENT_ACTIVITY e
		      WHERE a.PERSON_UID = b.PERSON_UID(+) AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD(+)
		              AND b.TRANSFER_COURSE_IND(+) = 'N' AND b.REGISTRATION_STATUS(+) IN ('RE','RW','RA','WC','RF')
		          AND a.PERSON_UID = c.PERSON_UID(+) AND a.ACADEMIC_PERIOD = c.ACADEMIC_PERIOD(+)
		              AND c.COHORT_ACTIVE_IND(+) = 'Y' AND c.COHORT(+) IN ('NEW_REING','REINGRESO')
		          AND a.PERSON_UID = d.PERSON_UID(+) AND a.ACADEMIC_PERIOD = d.ACADEMIC_PERIOD(+)
		              AND d.STUDENT_ATTRIBUTE(+) IN ('TINT','ADOS','DDOS','DLEN','DMAT')
		          AND a.PERSON_UID = e.PERSON_UID(+) AND a.ACADEMIC_PERIOD = e.ACADEMIC_PERIOD(+)
		              AND e.ACTIVITY(+) = 'ITO'
		          AND a.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND a.STUDENT_LEVEL = 'UG' AND a.ACADEMIC_PERIOD IN ('220402','220502')) a, --INGRESAR PERIODO
		     RECEIVABLE_ACCOUNT_DETAIL b
		WHERE a.PERSON_UID = b.ACCOUNT_UID(+) AND a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD(+)) BN
WHERE PS.SPRIDEN_PIDM = BN.PERSON_UID AND PS.PO_REF = BN.ACADEMIC_PERIOD;