--Matriculas_BECO_CRCO_
--CAMPUS 	DNI	APELLIDOS Y NOMBRES	MODALIDAD DE BECA	CARRERA	CONVOCATORIA	CICLO ACADEMICO	 	MATRÍCULA POR 1RA VEZ	MATRÍCULA POR 2DA VEZ	MATRÍCULA POR 3RA VEZ	TOTAL DE CURSOS MATRICULADOS	TOTAL DE CREDITOS MATRICULADOS	CONDICIÓN
--MATRICULA_CONTRATO, CUOTA_INICIAL_CONTRATO, ARANCEL_CONTRADO
SELECT F.PERSON_UID, F.ID, F.NAME, I.ALTERNATIVE_ID AS DNI, F.ACADEMIC_PERIOD, F.PROGRAM, F.PROGRAM_DESC, F.CAMPUS_DESC, F.STUDENT_ATTRIBUTE, H.BECAS, H.DESCUENTOS, F.CURSOS_1, F.CREDITOS_1, F.CURSOS_2, F.CREDITOS_2
	, F.CURSOS_3, F.CREDITOS_3, F.CURSOS_1 +F.CURSOS_2 +F.CURSOS_3 AS TOTAL_CURSOS, F.CREDITOS_1 +F.CREDITOS_2 +F.CREDITOS_3 AS TOTAL_CREDITOS
	, SUM(CASE WHEN SOURCE IN ('R','T') AND SUBSTR(DETAIL_CODE,1,2) IN ('T2','T3') THEN BALANCE ELSE 0 END) AS PENALIDAD
	, SUM(CASE WHEN SOURCE IN ('R','E') AND (SUBSTR(DETAIL_CODE,1,2) = 'FM' OR SUBSTR(CROSSREF_DETAIL_CODE,1,2) = 'FM') THEN BALANCE ELSE 0 END) AS MATRICULA_ESTUDIANTE
	, SUM(CASE WHEN SOURCE = 'C' AND SUBSTR(CROSSREF_DETAIL_CODE,1,2) = 'FM' THEN AMOUNT ELSE 0 END) AS MATRICULA_CONTRATO
	, SUM(CASE WHEN SOURCE IN ('R','E') AND (SUBSTR(DETAIL_CODE,1,2) IN ('T1','X1','Y1','Z1') OR SUBSTR(CROSSREF_DETAIL_CODE,1,2) IN ('T1','X1','Y1','Z1')) THEN BALANCE ELSE 0 END) AS CUOTA_INICIAL_ESTUDIANTE
	, SUM(CASE WHEN SOURCE = 'C' AND SUBSTR(CROSSREF_DETAIL_CODE,1,2) IN ('T1','X1','Y1','Z1') THEN AMOUNT ELSE 0 END) AS CUOTA_INICIAL_CONTRATO
	, SUM(CASE WHEN SOURCE IN ('R','E') AND (SUBSTR(DETAIL_CODE,1,2) IN ('TA','XA','YA','ZA') OR SUBSTR(CROSSREF_DETAIL_CODE,1,2) IN ('TA','XA','YA','ZA')) THEN BALANCE ELSE 0 END) AS ARANCEL_ESTUDIANTE
	, SUM(CASE WHEN SOURCE = 'C' AND SUBSTR(CROSSREF_DETAIL_CODE,1,2) IN ('TA','XA','YA','ZA') THEN AMOUNT ELSE 0 END) AS ARANCEL_CONTRATO
FROM ( SELECT A.PERSON_UID, A.ID, A.NAME, A.ACADEMIC_PERIOD, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC, B.STUDENT_ATTRIBUTE--, COALESCE(E.COURSE_COUNT,0)+1 AS VEZ
			, COUNT(CASE WHEN E.COURSE_COUNT IS NULL THEN C.SFRSTCR_CRN ELSE NULL END) AS CURSOS_1, SUM(CASE WHEN E.COURSE_COUNT IS NULL THEN C.SFRSTCR_CREDIT_HR ELSE 0 END) AS CREDITOS_1
			, COUNT(CASE WHEN E.COURSE_COUNT = 1 THEN C.SFRSTCR_CRN ELSE NULL END) AS CURSOS_2, SUM(CASE WHEN E.COURSE_COUNT = 1 THEN C.SFRSTCR_CREDIT_HR ELSE 0 END) AS CREDITOS_2
			, COUNT(CASE WHEN E.COURSE_COUNT = 2 THEN C.SFRSTCR_CRN ELSE NULL END) AS CURSOS_3, SUM(CASE WHEN E.COURSE_COUNT = 2 THEN C.SFRSTCR_CREDIT_HR ELSE 0 END) AS CREDITOS_3
		FROM ODSMGR.ACADEMIC_STUDY A
				INNER JOIN ODSMGR.STUDENT_ATTRIBUTE B ON A.PERSON_UID = B.PERSON_UID AND A.ACADEMIC_PERIOD = B.ACADEMIC_PERIOD AND B.STUDENT_ATTRIBUTE IN ('BECO','CRCO')
				INNER JOIN ODSMGR.SFRSTCR C ON B.PERSON_UID = C.SFRSTCR_PIDM AND B.ACADEMIC_PERIOD = C.SFRSTCR_TERM_CODE AND C.SFRSTCR_RSTS_CODE IN ('RE','RW','RA','WC','RF','RO','IA')
				INNER JOIN ODSMGR.LOE_SSBSECT D ON C.SFRSTCR_TERM_CODE = D.SSBSECT_TERM_CODE AND C.SFRSTCR_CRN = D.SSBSECT_CRN
				LEFT JOIN ODSMGR.LOE_REPEAT_COURSE_CRN E ON C.SFRSTCR_PIDM = E.SFRSTCR_PIDM AND C.SFRSTCR_TERM_CODE = E.SFRSTCR_TERM_CODE AND D.SSBSECT_SUBJ_CODE = E.SSBSECT_SUBJ_CODE AND D.SSBSECT_CRSE_NUMB = E.SSBSECT_CRSE_NUMB		
		WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND A.STUDENT_LEVEL = 'UG' AND A.ACADEMIC_PERIOD IN ('220435','220534') --AND A.PERSON_UID IN (21803,44488,190807)
		GROUP BY A.PERSON_UID, A.ID, A.NAME, A.ACADEMIC_PERIOD, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC, B.STUDENT_ATTRIBUTE--, COALESCE(E.COURSE_COUNT,0)+1
		ORDER BY A.PERSON_UID, A.ACADEMIC_PERIOD
		) F
			LEFT JOIN ODSMGR.RECEIVABLE_ACCOUNT_DETAIL G ON F.PERSON_UID = G.ACCOUNT_UID AND F.ACADEMIC_PERIOD = G.ACADEMIC_PERIOD
			LEFT JOIN ( SELECT TBBESTU_PIDM, TBBESTU_TERM_CODE
							, LISTAGG(CASE WHEN SUBSTR(TBBESTU_EXEMPTION_CODE,5,1) = '1' THEN TBBEXPT_DESC END,', ') WITHIN GROUP (ORDER BY TBBEXPT_DESC) AS BECAS
							, LISTAGG(CASE WHEN SUBSTR(TBBESTU_EXEMPTION_CODE,5,1) IN ('2','3') THEN TBBEXPT_DESC END,', ') WITHIN GROUP (ORDER BY TBBEXPT_DESC) AS DESCUENTOS
						FROM ODSMGR.LOE_EXEMPTION_STU_AUTHOR, ODSMGR.LOE_TBBEXPT
						WHERE TBBESTU_EXEMPTION_CODE = TBBEXPT_EXEMPTION_CODE AND TBBESTU_TERM_CODE = TBBEXPT_TERM_CODE
							AND TBBESTU_DEL_IND IS NULL
						GROUP BY TBBESTU_PIDM, TBBESTU_TERM_CODE
						) H ON F.PERSON_UID = H.TBBESTU_PIDM AND F.ACADEMIC_PERIOD = H.TBBESTU_TERM_CODE
			LEFT JOIN ODSMGR.ALTERNATIVE_ID I ON F.PERSON_UID = I.ENTITY_UID AND I.ATERNATIVE_ID_TYPE = 'DNI'
												AND I.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(I1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ODSMGR.ALTERNATIVE_ID I1
																						WHERE I1.ENTITY_UID = I.ENTITY_UID AND I1.ATERNATIVE_ID_TYPE = 'DNI')
GROUP BY F.PERSON_UID, F.ID, F.NAME, I.ALTERNATIVE_ID, F.ACADEMIC_PERIOD, F.PROGRAM, F.PROGRAM_DESC, F.CAMPUS_DESC, F.STUDENT_ATTRIBUTE, H.BECAS, H.DESCUENTOS, F.CURSOS_1, F.CREDITOS_1, F.CURSOS_2, F.CREDITOS_2
	, F.CURSOS_3, F.CREDITOS_3, F.CURSOS_1 +F.CURSOS_2 +F.CURSOS_3, F.CREDITOS_1 +F.CREDITOS_2 +F.CREDITOS_3
;
