--Matriculas_PreMatricula
SELECT X.*
FROM (
SELECT DISTINCT
    A.PERSON_UID, F.SPRIDEN_ID, CONCAT(F.SPRIDEN_LAST_NAME,CONCAT(', ',F.SPRIDEN_FIRST_NAME)) AS NOMBRE_ESTUDIANTE, A.ACADEMIC_PERIOD, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC
    , CASE WHEN SFRSTCR_CRN IS NOT NULL THEN 'Y' ELSE 'N' END AS REGISTRO_CURSOS
	, CASE A.STUDENT_POPULATION
		WHEN 'N' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				ELSE 'Nuevo' END
		WHEN 'C' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				WHEN A.ADMISSIONS_POPULATION <> 'RE' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				WHEN E.ACTIVITY = 'DTO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Doble Titulacion OUT'
				WHEN E.ACTIVITY = 'ITO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				ELSE 'Continuo' END
		ELSE A.STUDENT_POPULATION END AS TIPO_ESTUDIANTE
	, MAX(CASE 
		WHEN P.CARGO = 'MATRICULA' AND P.INVOICE_AMOUNT = 0 THEN FECHA_EMISION
		WHEN P.CARGO = 'MATRICULA' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
		WHEN P.CARGO = 'MATRICULA' THEN P.FECHA_PAGO
		END) AS FECHA_PAGO_FM
	, MAX(CASE 
		WHEN P.CARGO = 'CUOTA INICIAL' AND P.INVOICE_AMOUNT = 0 THEN P.FECHA_EMISION
		WHEN P.CARGO = 'CUOTA INICIAL' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
		WHEN P.CARGO = 'CUOTA INICIAL' THEN P.FECHA_PAGO
		END) AS FECHA_PAGO_T1
FROM ODSMGR.ACADEMIC_STUDY A
		INNER JOIN ODSMGR.PS_MATRICULA_CUOTAINICIAL P ON A.PERSON_UID = P.PIDM AND A.ACADEMIC_PERIOD = P.PERIODO AND P.CARGO IN ('MATRICULA','CUOTA INICIAL')
		LEFT JOIN ODSMGR.SFRSTCR ON A.PERSON_UID = SFRSTCR_PIDM AND A.ACADEMIC_PERIOD = SFRSTCR_TERM_CODE AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA','WC','RF','RO')
     	LEFT JOIN ODSMGR.STUDENT_COHORT C ON A.PERSON_UID = C.PERSON_UID AND A.ACADEMIC_PERIOD = C.ACADEMIC_PERIOD AND C.COHORT_ACTIVE_IND = 'Y' AND C.COHORT IN ('NEW_REING','REINGRESO')
     	LEFT JOIN ODSMGR.STUDENT_ATTRIBUTE D ON A.PERSON_UID = D.PERSON_UID AND A.ACADEMIC_PERIOD = D.ACADEMIC_PERIOD AND D.STUDENT_ATTRIBUTE IN ('TINT')
     	LEFT JOIN ODSMGR.STUDENT_ACTIVITY E ON A.PERSON_UID = E.PERSON_UID AND A.ACADEMIC_PERIOD = E.ACADEMIC_PERIOD AND E.ACTIVITY = 'ITO'
     	LEFT JOIN ODSMGR.LOE_SPRIDEN F ON A.PERSON_UID = F.SPRIDEN_PIDM AND F.SPRIDEN_CHANGE_IND IS NULL
WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE') AND A.STUDENT_LEVEL = 'UG' AND A.ACADEMIC_PERIOD IN ('220435','220534')
	--AND A.STUDENT_POPULATION = 'N' AND A.ACADEMIC_PERIOD = A.ACADEMIC_PERIOD_ADMITTED AND C.COHORT IS NULL
GROUP BY A.PERSON_UID, F.SPRIDEN_ID, CONCAT(F.SPRIDEN_LAST_NAME,CONCAT(', ',F.SPRIDEN_FIRST_NAME)), A.ACADEMIC_PERIOD, A.PROGRAM, A.PROGRAM_DESC, A.CAMPUS_DESC
	, CASE WHEN SFRSTCR_CRN IS NOT NULL THEN 'Y' ELSE 'N' END
	, CASE A.STUDENT_POPULATION
		WHEN 'N' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				ELSE 'Nuevo' END
		WHEN 'C' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				WHEN A.ADMISSIONS_POPULATION <> 'RE' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				WHEN E.ACTIVITY = 'DTO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Doble Titulacion OUT'
				WHEN E.ACTIVITY = 'ITO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				ELSE 'Continuo' END
		ELSE A.STUDENT_POPULATION END
) X
WHERE X.FECHA_PAGO_FM IS NOT NULL AND X.FECHA_PAGO_T1 IS NULL
;
