--Matriculas_Registros_Eliminados
SELECT SFBETRM_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME AS NOMBRE, SFBETRM_TERM_CODE, SFBETRM_ESTS_CODE, SFBETRM_ESTS_DATE
	, MIN(D.REGISTRATION_STATUS_DATE) AS REGISTRATION_STATUS_DATE
	, MAX(D.REGISTRATION_USER_ID) AS REGISTRATION_USER_ID
	, MAX(CASE 
		WHEN P.CARGO = 'MATRICULA' AND P.INVOICE_AMOUNT = 0 THEN FECHA_EMISION
		WHEN P.CARGO = 'MATRICULA' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
		WHEN P.CARGO = 'MATRICULA' THEN P.FECHA_PAGO
		END) AS FECHA_PAGO_FM
	, MAX(CASE 
		WHEN P.CARGO = 'CUOTA INICIAL' AND P.INVOICE_AMOUNT = 0 THEN P.FECHA_EMISION
		WHEN P.CARGO = 'CUOTA INICIAL' AND P.ESTADO_AR = 'O' AND P.INVOICE_AMOUNT <> P.SALDO THEN COALESCE(P.FECHA_PAGO,P.FECHA_CONTABLE)
		WHEN P.CARGO = 'CUOTA INICIAL' THEN P.FECHA_PAGO
		END) AS FECHA_PAGO_T1
FROM ODSMGR.SFBETRM
		INNER JOIN ODSMGR.LOE_SPRIDEN ON SFBETRM_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
		INNER JOIN ODSMGR.PS_MATRICULA_CUOTAINICIAL P ON SFBETRM_PIDM = P.PIDM AND SFBETRM_TERM_CODE = P.PERIODO AND P.CARGO IN ('MATRICULA','CUOTA INICIAL')
		INNER JOIN ODSMGR.STUDENT_COURSE_REG_AUDIT D ON SFBETRM_PIDM = D.PERSON_UID AND SFBETRM_TERM_CODE = D.ACADEMIC_PERIOD AND D.REGISTRATION_SOURCE = 'BASE' AND D.REGISTRATION_STATUS IN ('DW','DD')
		LEFT JOIN ODSMGR.SFRSTCR R ON SFBETRM_PIDM = R.SFRSTCR_PIDM AND SFBETRM_TERM_CODE = R.SFRSTCR_TERM_CODE AND R.SFRSTCR_RSTS_CODE NOT IN ('DW','DD')		
WHERE SFBETRM_TERM_CODE IN ('220435','220534') AND SFBETRM_ESTS_CODE = 'EL'
	AND R.SFRSTCR_PIDM IS NULL
GROUP BY SFBETRM_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||' '|| SPRIDEN_FIRST_NAME, SFBETRM_TERM_CODE, SFBETRM_ESTS_CODE, SFBETRM_ESTS_DATE
;