SELECT DISTINCT 
    A.BUSINESS_UNIT AS UN, 
    D.PAYMENT_ID AS ID_PAGO, 
    J.PYMNT_REF_ID AS ID_PAGO_CAJA, 
    --N.BANK_CD, 
    TO_CHAR(D.ACCOUNTING_DT,'YYYY-MM-DD') AS FECHA_PAGO, 
    A.BILL_TO_CUST_ID AS CLIENTE, 
    CONCAT(CONCAT( I.NAME1,' '), I.NAME2) AS APELLIDOS_NOMBRES, 
    A.PO_REF AS PERIODO, 
    A.INVOICE AS TRANSACCION, 
    C.INSTALL_NBR AS NRO_CUOTA, 
    E.INVOICE2 AS GOB_ID, 
    A.INVOICE_AMOUNT AS TOTAL, 
    F.BAL_AMT AS SALDO, 
    F.BAL_CURRENCY AS MON_SALDO, 
    A.BILLING_FREQUENCY AS FRECUENCIA, 
    A.BILL_STATUS AS ESTADO_BI, 
    F.ITEM_STATUS AS ESTADO_AR, 
    TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD') AS FECHA_EMISION, 
    CASE 
        WHEN  TO_CHAR(F.DUE_DT,'YYYY-MM-DD') IS NULL 
            THEN (CASE WHEN ( A.PYMNT_TERMS_CD = 00000) THEN  TO_CHAR(A.DUE_DT,'YYYY-MM-DD')  ELSE  TO_CHAR(H.DUE_DT,'YYYY-MM-DD')  END) 
        ELSE  TO_CHAR(F.DUE_DT,'YYYY-MM-DD') END AS FECHA_VENCIMIENTO, 
    A.LAST_MAINT_OPRID AS ID_ULT_USR, 
    A.CREATEOPRID AS USUARIO, 
    A.BILL_TYPE_ID AS TIPO_FAC, 
    D.DEPOSIT_ID AS ID_DEP, 
    D.PAYMENT_SEQ_NUM AS SEC, 
    K.RECEIPT_NBR AS NRO_RECEP, 
    D.PAYMENT_METHOD AS MET_PAGO, 
    K.DRAWER_ID AS ID_CAJA_EFVO, 
    M.RECON_ID AS ID_CONCIL, 
    M.ORIG_OPRID AS CAJERO, 
    L.ENTRY_TYPE AS TP_ENTRADA, 
    CASE 
        WHEN  L.ENTRY_TYPE = 'IN' 
            THEN (CASE WHEN ( F.DEDUCTION_STATUS = 'CAST') THEN 'CASTI' ELSE  L.ENTRY_REASON END ) 
        ELSE  L.ENTRY_REASON END AS MOTIVO
FROM 
    (((((((((PS_BI_HDR A 
        LEFT OUTER JOIN  PS_PAYMENT_ID_ITEM B ON  
            A.BUSINESS_UNIT = B.BUSINESS_UNIT
            AND B.REF_VALUE = A.INVOICE ) 
        LEFT OUTER JOIN  PS_PAYMENT D ON  
            B.DEPOSIT_BU = D.DEPOSIT_BU 
            AND B.DEPOSIT_ID = D.DEPOSIT_ID 
            AND B.PAYMENT_SEQ_NUM = D.PAYMENT_SEQ_NUM ) 
        LEFT OUTER JOIN  PS_BI_INSTALL_SCHE C ON  
            A.BUSINESS_UNIT = C.BUSINESS_UNIT 
            AND A.INVOICE = C.GENERATED_INVOICE ) 
        LEFT OUTER JOIN  PS_LI_GBL_BI_INV E ON  
            A.BUSINESS_UNIT = E.BUSINESS_UNIT 
            AND A.INVOICE = E.INVOICE ) 
        LEFT OUTER JOIN  PS_ITEM F ON  
            A.BUSINESS_UNIT = F.BUSINESS_UNIT 
            AND A.INVOICE = F.INVOICE 
            AND A.BILL_TO_CUST_ID = F.CUST_ID ) 
        LEFT OUTER JOIN  PS_ITEM_ACTIVITY L ON  
            F.BUSINESS_UNIT = L.BUSINESS_UNIT 
            AND F.CUST_ID = L.CUST_ID 
            AND F.ITEM = L.ITEM 
            AND F.ITEM_LINE = L.ITEM_LINE 
            AND L.ITEM_SEQ_NUM = F.ITEM_SEQ_NUM ) 
        LEFT OUTER JOIN  PS_LI_GBL_ARPY_REF J ON  
            A.INVOICE = J.INVOICE ) 
        LEFT OUTER JOIN  PS_LI_GBL_ARPY_TBL K ON  
            J.DEPOSIT_BU = K.DEPOSIT_BU 
            AND J.PYMNT_REF_ID = K.PYMNT_REF_ID ) 
        LEFT OUTER JOIN  PS_CDR_RECEIPT M ON  
            K.DEPOSIT_BU = M.DEPOSIT_BU 
            AND M.RECEIPT_NBR = K.RECEIPT_NBR )
        , PS_PAY_TRMS_NET G
        , PS_PAY_TRMS_TIME H
        , PS_CUSTOMER I 
WHERE ( G.PYMNT_TERMS_CD = A.PYMNT_TERMS_CD 
     AND G.EFFDT = 
        (SELECT MAX(G_ED.EFFDT) FROM PS_PAY_TRMS_NET G_ED 
        WHERE G.SETID = G_ED.SETID 
          AND G.PYMNT_TERMS_CD = G_ED.PYMNT_TERMS_CD 
          AND G_ED.EFFDT <= SYSDATE) 
     AND G.SETID = H.SETID 
     AND H.PAY_TRMS_TIME_ID = G.PAY_TRMS_TIME_ID 
     AND I.CUST_ID = A.BILL_TO_CUST_ID 
     AND I.SETID = 'PER03' 
     AND I.CUST_ID IN ('N00159625') 
     --AND A.BILL_STATUS = '' 
     --AND F.ITEM_STATUS = '' 
     --AND A.PO_REF = '218413' 
     --AND C.INSTALL_NBR = '' 
     --AND A.BILL_TYPE_ID = '' 
     --AND A.BILLING_FREQUENCY = '' 
     --AND A.INVOICE = '0000520410'
     ) 
ORDER BY 6, 19, 10;