--PER_BI_REV_REC_REC_FINAL_V3G  (nueva versión con el acumulado)
SELECT SUBSTR( A.JOURNAL_ID,1,3), A.INVOICE, I.CREATEOPRID, I.BILL_STATUS, S.ITEM_STATUS, M.INVOICE2, TO_CHAR(I.DT_INVOICED,'YYYY-MM-DD'), CASE WHEN ( I.PYMNT_TERMS_CD = 00000) THEN  TO_CHAR(I.DUE_DT,'YYYY-MM-DD')  ELSE  TO_CHAR(V.DUE_DT,'YYYY-MM-DD')  END, C.DESCR, I.BILL_TO_CUST_ID, Q.INSTALL_PLAN_ID, P.INSTALL_NBR, C.PO_REF, A.ACCOUNT, A.ALTACCT, A.ACCT_ENTRY_TYPE, E.DESCR, A.JOURNAL_ID, TO_CHAR(A.ACCOUNTING_DT,'YYYY-MM-DD'), A.ACCOUNTING_PERIOD, A.FISCAL_YEAR, S.BAL_CURRENCY, A.MONETARY_AMOUNT, TO_CHAR(C.CHARGE_FROM_DT,'YYYY-MM-DD'), TO_CHAR(C.CHARGE_TO_DT,'YYYY-MM-DD'), A.OPERATING_UNIT, A.DEPTID, A.CHARTFIELD2, A.PRODUCT, C.REV_RECOG_BASIS, CASE WHEN   G.JRNL_HDR_STATUS =  'P'  THEN 'Contabilizado'  ELSE 'No Contabilizado' END, A.LINE_SEQ_NUM, A.APPL_JRNL_ID, C.NET_EXTENDED_AMT--, TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'), TO_CHAR(CURRENT_DATE,'YYYY-MM-DD') 
  FROM PS_BI_ACCT_ENTRY A, PS_BI_LINE C, PS_GL_ACCOUNT_TBL E, PS_JRNL_HEADER G, (((((PS_BI_HDR I INNER JOIN PS_SP_BU_BI_CLSVW I1 ON (I.BUSINESS_UNIT = I1.BUSINESS_UNIT AND  I1.OPRCLASS = 'LI_PPL_PER03_PER' )) LEFT OUTER JOIN  PS_LI_GBL_BI_INV M ON  I.BUSINESS_UNIT = M.BUSINESS_UNIT AND I.INVOICE = M.INVOICE ) LEFT OUTER JOIN  PS_BI_INSTALL_SCHE P ON  I.BUSINESS_UNIT = P.BUSINESS_UNIT AND I.INVOICE = P.GENERATED_INVOICE ) LEFT OUTER JOIN  PS_BI_INSTALL_TRMS Q ON  P.BUSINESS_UNIT = Q.BUSINESS_UNIT AND P.INVOICE = Q.INVOICE ) LEFT OUTER JOIN  PS_ITEM S ON  I.BUSINESS_UNIT = S.BUSINESS_UNIT AND I.INVOICE = S.INVOICE ), PS_PAY_TRMS_NET U, PS_PAY_TRMS_TIME V 
  WHERE ( ( A.BUSINESS_UNIT = C.BUSINESS_UNIT 
     AND A.INVOICE = C.INVOICE 
     AND A.LINE_SEQ_NUM = C.LINE_SEQ_NUM 
     AND E.ACCOUNT = A.ACCOUNT 
     AND E.EFFDT = 
        (SELECT MAX(E_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL E_ED 
        WHERE E.SETID = E_ED.SETID 
          AND E.ACCOUNT = E_ED.ACCOUNT 
          AND E_ED.EFFDT <= CURRENT_DATE) 
     AND A.BUSINESS_UNIT = G.BUSINESS_UNIT 
     AND G.JOURNAL_ID = A.JOURNAL_ID 
     AND G.JOURNAL_DATE = A.JOURNAL_DATE 
     AND A.BUSINESS_UNIT = I.BUSINESS_UNIT 
     AND A.INVOICE = I.INVOICE 
     AND U.PYMNT_TERMS_CD = I.PYMNT_TERMS_CD 
     AND U.EFFDT = 
        (SELECT MAX(U_ED.EFFDT) FROM PS_PAY_TRMS_NET U_ED 
        WHERE U.SETID = U_ED.SETID 
          AND U.PYMNT_TERMS_CD = U_ED.PYMNT_TERMS_CD 
          AND U_ED.EFFDT <= CURRENT_DATE) 
     AND U.SETID = V.SETID 
     AND V.PAY_TRMS_TIME_ID = U.PAY_TRMS_TIME_ID 
     AND A.ACCOUNTING_PERIOD <= :2 
     AND A.FISCAL_YEAR = :1 
     AND A.ACCOUNT >= :3 
     AND A.ACCOUNT <= :4 
     AND A.BUSINESS_UNIT = 'PER03' )) 
UNION 
SELECT SUBSTR( B.JOURNAL_ID,1,3), B.INVOICE, J.CREATEOPRID, J.BILL_STATUS, T.ITEM_STATUS, N.INVOICE2, TO_CHAR(J.DT_INVOICED,'YYYY-MM-DD'), CASE WHEN ( J.PYMNT_TERMS_CD = 00000) THEN  TO_CHAR(J.DUE_DT,'YYYY-MM-DD')  ELSE  TO_CHAR(X.DUE_DT,'YYYY-MM-DD')  END, D.DESCR, J.BILL_TO_CUST_ID, R.INSTALL_PLAN_ID, O.INSTALL_NBR, D.PO_REF, B.ACCOUNT, B.ALTACCT, B.ACCT_ENTRY_TYPE, F.DESCR, B.JOURNAL_ID, TO_CHAR(B.ACCOUNTING_DT,'YYYY-MM-DD'), B.ACCOUNTING_PERIOD, B.FISCAL_YEAR, T.BAL_CURRENCY, B.MONETARY_AMOUNT, TO_CHAR(D.CHARGE_FROM_DT,'YYYY-MM-DD'), TO_CHAR(D.CHARGE_TO_DT,'YYYY-MM-DD'), B.OPERATING_UNIT, B.DEPTID, B.CHARTFIELD2, B.PRODUCT, D.REV_RECOG_BASIS, CASE WHEN   H.JRNL_HDR_STATUS =  'P'  THEN 'Contabilizado'  ELSE 'No Contabilizado' END, B.LINE_SEQ_NUM, B.APPL_JRNL_ID, D.NET_EXTENDED_AMT 
  FROM PS_LI_PER_ACTENTRY B, PS_BI_LINE D, PS_GL_ACCOUNT_TBL F, PS_JRNL_HEADER H, (((((PS_BI_HDR J INNER JOIN PS_SP_BU_BI_CLSVW J1 ON (J.BUSINESS_UNIT = J1.BUSINESS_UNIT AND  J1.OPRCLASS = 'LI_PPL_PER03_PER' )) LEFT OUTER JOIN  PS_LI_GBL_BI_INV N ON  J.BUSINESS_UNIT = N.BUSINESS_UNIT AND J.INVOICE = N.INVOICE ) LEFT OUTER JOIN  PS_BI_INSTALL_SCHE O ON  J.BUSINESS_UNIT = O.BUSINESS_UNIT AND J.INVOICE = O.GENERATED_INVOICE ) LEFT OUTER JOIN  PS_BI_INSTALL_TRMS R ON  O.BUSINESS_UNIT = R.BUSINESS_UNIT AND O.INVOICE = R.INVOICE ) LEFT OUTER JOIN  PS_ITEM T ON  J.BUSINESS_UNIT = T.BUSINESS_UNIT AND J.INVOICE = T.INVOICE ), PS_PAY_TRMS_NET W, PS_PAY_TRMS_TIME X 
  WHERE ( ( B.BUSINESS_UNIT = D.BUSINESS_UNIT 
     AND B.INVOICE = D.INVOICE 
     AND B.LINE_SEQ_NUM = D.LINE_SEQ_NUM 
     AND F.ACCOUNT = B.ACCOUNT 
     AND F.EFFDT = 
        (SELECT MAX(F_ED.EFFDT) FROM PS_GL_ACCOUNT_TBL F_ED 
        WHERE F.SETID = F_ED.SETID 
          AND F.ACCOUNT = F_ED.ACCOUNT 
          AND F_ED.EFFDT <= CURRENT_DATE) 
     AND B.BUSINESS_UNIT = H.BUSINESS_UNIT 
     AND H.JOURNAL_ID = B.JOURNAL_ID 
     AND H.JOURNAL_DATE = B.JOURNAL_DATE 
     AND B.BUSINESS_UNIT = J.BUSINESS_UNIT 
     AND B.INVOICE = J.INVOICE 
     AND W.PYMNT_TERMS_CD = J.PYMNT_TERMS_CD 
     AND W.EFFDT = 
        (SELECT MAX(W_ED.EFFDT) FROM PS_PAY_TRMS_NET W_ED 
        WHERE W.SETID = W_ED.SETID 
          AND W.PYMNT_TERMS_CD = W_ED.PYMNT_TERMS_CD 
          AND W_ED.EFFDT <= CURRENT_DATE) 
     AND W.SETID = X.SETID 
     AND X.PAY_TRMS_TIME_ID = W.PAY_TRMS_TIME_ID 
     AND B.ACCOUNTING_PERIOD <= :2 
     AND B.FISCAL_YEAR <= :1 
     AND B.ACCOUNT <= :4 
     AND B.ACCOUNT >= :3 
     AND B.BUSINESS_UNIT = 'PER03' ))
