--PER_AR_DEBIT_CREDIT_MEMO_ - Notas_Credito_Debito
SELECT DISTINCT A.BILL_TO_CUST_ID, CONCAT(CONCAT((REPLACE( H.NAME1,'/',' ')),' '), H.NAME2), A.INVOICE, C.INVOICE2, CASE WHEN  G.INVOICE_LINE = '1' THEN  A.INVOICE_AMOUNT ELSE 0 END
    , G.NET_EXTENDED_AMT, G.LINE_SEQ_NUM, A.ENTRY_TYPE, A.ENTRY_REASON, L.TEXT254, CASE WHEN SUBSTR(L.TEXT254,1,17) = 'ORIGINAL_INVOICE:' THEN SUBSTR(L.TEXT254,19,12) ELSE ' ' END, M.INVOICE2
    , CASE WHEN G.INVOICE_LINE = '1' THEN J.INVOICE_AMOUNT ELSE 0 END, G.PO_REF, A.BILL_TYPE_ID, A.BILL_STATUS, A.BILLING_FREQUENCY, B.ITEM_STATUS, TO_CHAR(A.INVOICE_DT,'YYYY-MM-DD')
    , CASE WHEN ( A.PYMNT_TERMS_CD = 00000) THEN TO_CHAR(B.DUE_DT,'YYYY-MM-DD') ELSE TO_CHAR(D.DUE_DT,'YYYY-MM-DD') END, TO_CHAR(A.FROM_DT,'YYYY-MM-DD'), TO_CHAR(A.TO_DT,'YYYY-MM-DD')
    , G.DESCR, I.OPERATING_UNIT, A.CREATEOPRID, TO_CHAR(CAST((A.LAST_UPDATE_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF'), A.LAST_MAINT_OPRID/*, F.OPRDEFNDESC*/, K.ENTRY_TYPE, K.ENTRY_REASON
    --, TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'), TO_CHAR(CURRENT_DATE,'YYYY-MM-DD'), TO_CHAR(CURRENT_DATE,'YYYY-MM-DD')
FROM ((((ODSMGR.PS_BI_HDR A
            INNER JOIN ODSMGR.PS_SP_BU_BI_CLSVW A1 ON (A.BUSINESS_UNIT = A1.BUSINESS_UNIT AND  A1.OPRCLASS = 'LI_PPL_PER03_PER' ))
            LEFT OUTER JOIN ODSMGR.PS_ITEM B ON A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.INVOICE )
            LEFT OUTER JOIN ODSMGR.PS_ITEM_ACTIVITY K ON B.BUSINESS_UNIT = K.BUSINESS_UNIT AND B.CUST_ID = K.CUST_ID AND B.ITEM = K.ITEM AND B.ITEM_LINE = K.ITEM_LINE AND K.ITEM_SEQ_NUM = B.ITEM_SEQ_NUM )
            LEFT OUTER JOIN ODSMGR.PS_LI_GBL_BI_INV C ON A.BUSINESS_UNIT = C.BUSINESS_UNIT AND A.INVOICE = C.INVOICE AND C.INVOICE2 <> ' ' )
        , ODSMGR.PS_PAY_TRMS_NET E, ODSMGR.PS_PAY_TRMS_TIME D--, ODSMGR.PSOPRDEFN F
        , ((ODSMGR.PS_BI_LINE G
            LEFT OUTER JOIN ODSMGR.PS_BI_LINE_NOTE L ON G.BUSINESS_UNIT = L.BUSINESS_UNIT AND G.INVOICE = L.INVOICE AND G.LINE_SEQ_NUM = L.LINE_SEQ_NUM )
            LEFT OUTER JOIN ODSMGR.PS_LI_GBL_BI_INV M ON CASE WHEN SUBSTR(L.TEXT254,1,17) = 'ORIGINAL_INVOICE:' THEN SUBSTR(L.TEXT254,19,12) ELSE ' ' END = M.INVOICE )
		, ODSMGR.PS_CUSTOMER H, ODSMGR.PS_BI_LINE_DST I, ODSMGR.PS_BI_HDR J, ODSMGR.PS_SP_BU_BI_CLSVW J1
WHERE ( J.BUSINESS_UNIT = J1.BUSINESS_UNIT
    AND J1.OPRCLASS = 'LI_PPL_PER03_PER'
    AND ( A.BUSINESS_UNIT = 'PER03'
     AND E.PYMNT_TERMS_CD = A.PYMNT_TERMS_CD
     AND E.EFFDT =
        (SELECT MAX(E_ED.EFFDT) FROM ODSMGR.PS_PAY_TRMS_NET E_ED
        WHERE E.SETID = E_ED.SETID
          AND E.PYMNT_TERMS_CD = E_ED.PYMNT_TERMS_CD
          AND E_ED.EFFDT <= CURRENT_DATE)
     AND E.SETID = D.SETID
     AND D.PAY_TRMS_TIME_ID = E.PAY_TRMS_TIME_ID
     --AND F.OPRID = A.LAST_MAINT_OPRID
     AND A.BUSINESS_UNIT = G.BUSINESS_UNIT
     AND A.INVOICE = G.INVOICE
     AND H.CUST_ID = A.BILL_TO_CUST_ID
     AND G.BUSINESS_UNIT = I.BUSINESS_UNIT
     AND G.INVOICE = I.INVOICE
     AND G.LINE_SEQ_NUM = I.LINE_SEQ_NUM
     AND (( L.NOTES_SEQ_NUM IS NULL OR L.NOTES_SEQ_NUM <> 2) OR ( SUBSTR(L.TEXT254,1,9) <> 'EXEMPTION' OR L.TEXT254 IS NULL))
     AND A.BILL_TYPE_ID IN ('C1','C2','D1','D2')
     /*AND A.BUSINESS_UNIT = :1
     AND A.BILL_TO_CUST_ID = :2*/
     AND G.PO_REF IN ('220435','220534')
     /*AND A.BILL_TYPE_ID = :4
     AND A.BILL_STATUS = :5
     AND B.ITEM_STATUS = :6
     AND A.BILLING_FREQUENCY = :7
     AND A.ENTRY_TYPE = :8
     AND A.ENTRY_REASON = :9*/
     AND SUBSTR(L.TEXT254,19,12) = J.INVOICE
     /*AND K.ENTRY_TYPE = :10
     AND K.ENTRY_REASON = :11
     AND I.OPERATING_UNIT = :12*/ ))
ORDER BY 19, 4
;