--CURRICULAS CON PRIORIDADES INCORRECTAS

--QUERY CURRICULAS UG TERMINADAS POR PRIORIDAD IGUAL
SELECT 
    P.SPRIDEN_ID AS ID_ESTUDIANTE, P.SPRIDEN_LAST_NAME AS APELLIDOS, P.SPRIDEN_FIRST_NAME AS NOMBRES, S.SOVLCUR_PRIORITY_NO AS PRIORIDAD_CURRICULA
    , S.SOVLCUR_CACT_CODE AS ACTIVIDAD_CURRICULA, S.SOVLCUR_ACTIVITY_DATE AS FECHA_ACTIVIDAD, S.SOVLCUR_LEVL_CODE AS NIVEL
    , S.SOVLCUR_TERM_CODE_END AS PERIODO_FIN_CURRICULA, S.SOVLCUR_TERM_CODE_MATRIC AS PERIODO_MATRICULA, S.SOVLCUR_TERM_CODE_ADMIT AS PERIODO_ADMISION
    , S.SOVLCUR_ADMT_CODE AS TIPO_ADMISION, S.SOVLCUR_CAMP_CODE AS CAMPUS, S.SOVLCUR_PROGRAM AS PROGRAMA, S.SOVLCUR_CURRENT_IND AS CURRICULA_ACTUAL
FROM LOE_SOVLCUR S, SPRIDEN P
WHERE S.SOVLCUR_PIDM = P.SPRIDEN_PIDM AND P.SPRIDEN_CHANGE_IND IS NULL
    AND S.SOVLCUR_LMOD_CODE = 'LEARNER'
    AND S.SOVLCUR_CACT_CODE = 'ACTIVE'
    AND S.SOVLCUR_CURRENT_IND <> 'Y'
    AND S.SOVLCUR_LEVL_CODE = 'UG'
    --AND SOVLCUR_PIDM = 9732
    AND S.SOVLCUR_TERM_CODE < ( SELECT MAX(SOVLCUR_TERM_CODE)
                                FROM LOE_SOVLCUR S2
                                WHERE S2.SOVLCUR_PIDM = S.SOVLCUR_PIDM
                                    AND S2.SOVLCUR_LMOD_CODE = S.SOVLCUR_LMOD_CODE
                                    AND S2.SOVLCUR_CACT_CODE = S.SOVLCUR_CACT_CODE
                                    AND S2.SOVLCUR_CURRENT_IND = 'Y'
                                    AND S2.SOVLCUR_LEVL_CODE <> S.SOVLCUR_LEVL_CODE
                                    AND S2.SOVLCUR_PRIORITY_NO = S.SOVLCUR_PRIORITY_NO );
?

--QUERY POSTGRADO PRIORIDAD DIFERENTE A 10
SELECT 
    P.SPRIDEN_ID AS ID_ESTUDIANTE, P.SPRIDEN_LAST_NAME AS APELLIDOS, P.SPRIDEN_FIRST_NAME AS NOMBRES, S.SOVLCUR_PRIORITY_NO AS PRIORIDAD_CURRICULA
    , S.SOVLCUR_CACT_CODE AS ACTIVIDAD_CURRICULA, S.SOVLCUR_ACTIVITY_DATE AS FECHA_ACTIVIDAD, S.SOVLCUR_LEVL_CODE AS NIVEL
    , S.SOVLCUR_TERM_CODE_END AS PERIODO_FIN_CURRICULA, S.SOVLCUR_TERM_CODE_MATRIC AS PERIODO_MATRICULA, S.SOVLCUR_TERM_CODE_ADMIT AS PERIODO_ADMISION
    , S.SOVLCUR_ADMT_CODE AS TIPO_ADMISION, S.SOVLCUR_CAMP_CODE AS CAMPUS, S.SOVLCUR_PROGRAM AS PROGRAMA, S.SOVLCUR_CURRENT_IND AS CURRICULA_ACTUAL
FROM LOE_SOVLCUR S, SPRIDEN P
WHERE S.SOVLCUR_PIDM = P.SPRIDEN_PIDM AND P.SPRIDEN_CHANGE_IND IS NULL
    AND S.SOVLCUR_LMOD_CODE = 'LEARNER'
    AND S.SOVLCUR_CACT_CODE = 'ACTIVE'
    AND S.SOVLCUR_CURRENT_IND = 'Y'
    AND S.SOVLCUR_LEVL_CODE IN ('EC','MA','DO')
    AND S.SOVLCUR_TERM_CODE = ( SELECT MAX(SOVLCUR_TERM_CODE)
                                FROM LOE_SOVLCUR S2
                                WHERE S2.SOVLCUR_PIDM = S.SOVLCUR_PIDM
                                    AND S2.SOVLCUR_LMOD_CODE = S.SOVLCUR_LMOD_CODE
                                    AND S2.SOVLCUR_CACT_CODE = S.SOVLCUR_CACT_CODE
                                    AND S2.SOVLCUR_CURRENT_IND = S.SOVLCUR_CURRENT_IND
                                    AND S2.SOVLCUR_LEVL_CODE = S.SOVLCUR_LEVL_CODE )
    --AND SUBSTR(S.SOVLCUR_TERM_CODE,1,4) NOT IN ('2199','2198','2188')
    AND S.SOVLCUR_PRIORITY_NO <> 10;
?

--ESTUDIANTES CON PRIORIDAD 1 EN INGLES CON “EL” EN UG
SELECT 
    P.SPRIDEN_ID AS ID_ESTUDIANTE, P.SPRIDEN_LAST_NAME AS APELLIDOS, P.SPRIDEN_FIRST_NAME AS NOMBRES, S.SOVLCUR_PRIORITY_NO AS PRIORIDAD_CURRICULA
    , S.SOVLCUR_CACT_CODE AS ACTIVIDAD_CURRICULA, S.SOVLCUR_ACTIVITY_DATE AS FECHA_ACTIVIDAD, S.SOVLCUR_LEVL_CODE AS NIVEL
    , S.SOVLCUR_TERM_CODE_END AS PERIODO_FIN_CURRICULA, S.SOVLCUR_TERM_CODE_MATRIC AS PERIODO_MATRICULA, S.SOVLCUR_TERM_CODE_ADMIT AS PERIODO_ADMISION
    , S.SOVLCUR_ADMT_CODE AS TIPO_ADMISION, S.SOVLCUR_CAMP_CODE AS CAMPUS, S.SOVLCUR_PROGRAM AS PROGRAMA, S.SOVLCUR_CURRENT_IND AS CURRICULA_ACTUAL
FROM LOE_SOVLCUR S, SFBETRM F, SPRIDEN P
WHERE S.SOVLCUR_PIDM = P.SPRIDEN_PIDM AND P.SPRIDEN_CHANGE_IND IS NULL
    AND F.SFBETRM_PIDM = S.SOVLCUR_PIDM
    AND S.SOVLCUR_LMOD_CODE = 'LEARNER'
    AND S.SOVLCUR_CACT_CODE = 'ACTIVE'
    AND S.SOVLCUR_CURRENT_IND = 'Y'
    AND S.SOVLCUR_TERM_CODE = ( SELECT MAX(SOVLCUR_TERM_CODE)
                                FROM LOE_SOVLCUR S2
                                WHERE S2.SOVLCUR_PIDM = S.SOVLCUR_PIDM
                                    AND S2.SOVLCUR_LMOD_CODE = S.SOVLCUR_LMOD_CODE
                                    AND S2.SOVLCUR_CACT_CODE = S.SOVLCUR_CACT_CODE
                                    AND S2.SOVLCUR_CURRENT_IND = S.SOVLCUR_CURRENT_IND
                                    AND S2.SOVLCUR_LEVL_CODE = S.SOVLCUR_LEVL_CODE )
    --AND S.SOVLCUR_TERM_CODE IN ('219714','219715')
    AND S.SOVLCUR_PRIORITY_NO = 1
    AND SUBSTR(S.SOVLCUR_PROGRAM,1,3) = 'ING'
    AND F.SFBETRM_TERM_CODE IN ('219413','219513','219414','219514')
    AND F.SFBETRM_ESTS_CODE = 'EL';

--QUERY INGLES PRIORIDAD DIFERENTE A 5
SELECT 
    P.SPRIDEN_ID AS ID_ESTUDIANTE, P.SPRIDEN_LAST_NAME AS APELLIDOS, P.SPRIDEN_FIRST_NAME AS NOMBRES, S.SOVLCUR_PRIORITY_NO AS PRIORIDAD_CURRICULA
    , S.SOVLCUR_CACT_CODE AS ACTIVIDAD_CURRICULA, S.SOVLCUR_ACTIVITY_DATE AS FECHA_ACTIVIDAD, S.SOVLCUR_LEVL_CODE AS NIVEL
    , S.SOVLCUR_TERM_CODE_END AS PERIODO_FIN_CURRICULA, S.SOVLCUR_TERM_CODE_MATRIC AS PERIODO_MATRICULA, S.SOVLCUR_TERM_CODE_ADMIT AS PERIODO_ADMISION
    , S.SOVLCUR_ADMT_CODE AS TIPO_ADMISION, S.SOVLCUR_CAMP_CODE AS CAMPUS, S.SOVLCUR_PROGRAM AS PROGRAMA, S.SOVLCUR_CURRENT_IND AS CURRICULA_ACTUAL
FROM LOE_SOVLCUR S, SPRIDEN P
WHERE S.SOVLCUR_PIDM = P.SPRIDEN_PIDM AND P.SPRIDEN_CHANGE_IND IS NULL
    AND S.SOVLCUR_LMOD_CODE = 'LEARNER'
    AND S.SOVLCUR_CACT_CODE = 'ACTIVE'
    AND S.SOVLCUR_CURRENT_IND = 'Y'
    AND S.SOVLCUR_LEVL_CODE = 'CR'
    AND SUBSTR(S.SOVLCUR_PROGRAM,1,3) = 'ING'
    AND S.SOVLCUR_TERM_CODE = ( SELECT MAX(SOVLCUR_TERM_CODE)
                                FROM LOE_SOVLCUR S2
                                WHERE S2.SOVLCUR_PIDM = S.SOVLCUR_PIDM
                                    AND S2.SOVLCUR_LMOD_CODE = S.SOVLCUR_LMOD_CODE
                                    AND S2.SOVLCUR_CACT_CODE = S.SOVLCUR_CACT_CODE
                                    AND S2.SOVLCUR_CURRENT_IND = S.SOVLCUR_CURRENT_IND
                                    AND S2.SOVLCUR_LEVL_CODE = S.SOVLCUR_LEVL_CODE )
    --AND SUBSTR(S.SOVLCUR_TERM_CODE,1,4) NOT IN ('2199','2198','2188')
    AND S.SOVLCUR_PRIORITY_NO <> 5;
