
WITH CICLO_MALLA AS
    (SELECT DISTINCT A.TERM_CODE_EFF, A.PROGRAM, NVL(B.SUBJ_CODE,C.SMRARUL_SUBJ_CODE) AS SUBJ_CODE
        , NVL(B.CRSE_NUMB_LOW,C.SMRARUL_CRSE_NUMB_LOW) AS CRSE_NUMB_LOW--, B.AREA_RULE
        , MAX(CASE WHEN SUBSTR(A.AREA,LENGTH(A.AREA)-1) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')
            THEN SUBSTR(A.AREA,LENGTH(A.AREA)-1) ELSE NULL END) AS CICLO_CURSO
    FROM LOE_PROGRAM_AREA_PRIORITY A, LOE_AREA_COURSE B, LOE_SMRARUL C
    WHERE A.AREA = B.AREA_COURSE AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
        AND B.AREA_RULE = C.SMRARUL_KEY_RULE(+) AND B.AREA_COURSE = C.SMRARUL_AREA(+) AND B.TERM_CODE_EFF = C.SMRARUL_TERM_CODE_EFF(+)
    GROUP BY A.PROGRAM, A.TERM_CODE_EFF, NVL(B.SUBJ_CODE,C.SMRARUL_SUBJ_CODE), NVL(B.CRSE_NUMB_LOW,C.SMRARUL_CRSE_NUMB_LOW))
    
    , CICLO_RECONOCIDO AS
    (SELECT DISTINCT SMRDOUS_PIDM, SMRDOUS_SUBJ_CODE, SMRDOUS_CRSE_NUMB
		, MAX(CASE WHEN SUBSTR(SMRDOUS_AREA,LENGTH(SMRDOUS_AREA)-1) IN ('00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15')
	            THEN SUBSTR(SMRDOUS_AREA,LENGTH(SMRDOUS_AREA)-1) ELSE NULL END) AS CICLO_CURSO	
	FROM SMRDOUS R GROUP BY SMRDOUS_PIDM, SMRDOUS_SUBJ_CODE, SMRDOUS_CRSE_NUMB)

SELECT SHRTCKN_PIDM, SPRIDEN_ID, GORADID_ADDITIONAL_ID AS DNI, SPRIDEN_FIRST_NAME AS NOMBRES, SUBSTR(SPRIDEN_LAST_NAME,1,INSTR(SPRIDEN_LAST_NAME,'/',1,1)-1) AS APELLIDO_PATERNO
    , SUBSTR(SPRIDEN_LAST_NAME,INSTR(SPRIDEN_LAST_NAME,'/',1,1)+1) AS APELLIDO_MATERNO, SOVLCUR_PROGRAM AS CARRERA, SOVLCUR_TERM_CODE_CTLG AS PERIODO_CATALOGO
    , SHRTCKN_TERM_CODE AS SEMESTRE_ACADÉMICO, SHRTCKL_LEVL_CODE, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB, NVL(SHRTCKN_LONG_COURSE_TITLE,SHRTCKN_CRSE_TITLE) AS NOMBRE_CURSO
    , NVL(C.CICLO_CURSO,R.CICLO_CURSO) AS CICLO_CURSO, SHRTCKG_CREDIT_HOURS AS CREDITOS_CURSO, SHRTCKG_GRDE_CODE_FINAL AS NOTA_CURSO
FROM SHRTCKN, SHRTCKL, SHRTCKG G, SPRIDEN, GORADID, LOE_SOVLCUR U, CICLO_MALLA C, CICLO_RECONOCIDO R
WHERE SHRTCKN_PIDM = SHRTCKL_PIDM AND SHRTCKN_TERM_CODE = SHRTCKL_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKL_TCKN_SEQ_NO AND SHRTCKL_LEVL_CODE IN ('UG','CR')
    AND SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
    AND SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SHRTCKN_PIDM = GORADID_PIDM(+) AND GORADID_ADID_CODE(+) = 'DNI'
    AND SHRTCKN_PIDM = SOVLCUR_PIDM(+) /*AND SHRTCKN_TERM_CODE >= SOVLCUR_TERM_CODE(+)
        AND (SHRTCKN_TERM_CODE < SOVLCUR_TERM_CODE_END OR SOVLCUR_TERM_CODE_END IS NULL)
        AND SHRTCKN_TERM_CODE < NVL(SOVLCUR_TERM_CODE_END(+),'999996')
        AND SOVLCUR_TERM_CODE_END(+) IS NULL
        AND SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND SOVLCUR_CACT_CODE(+) = 'ACTIVE' AND SOVLCUR_LEVL_CODE(+) = 'UG'*/
        AND (U.SOVLCUR_SEQNO = (SELECT MAX(U1.SOVLCUR_SEQNO) FROM LOE_SOVLCUR U1
                                WHERE U1.SOVLCUR_LMOD_CODE = 'LEARNER' AND U1.SOVLCUR_CACT_CODE = 'ACTIVE'
                                    AND U1.SOVLCUR_LEVL_CODE = 'UG' AND U1.SOVLCUR_PIDM = U.SOVLCUR_PIDM) OR U.SOVLCUR_SEQNO IS NULL)
    AND SHRTCKN_SUBJ_CODE = C.SUBJ_CODE(+) AND SHRTCKN_CRSE_NUMB = C.CRSE_NUMB_LOW(+) AND SOVLCUR_PROGRAM = C.PROGRAM(+)
        AND (C.TERM_CODE_EFF = (SELECT MAX(C1.TERM_CODE_EFF) FROM CICLO_MALLA C1
                                WHERE C1.SUBJ_CODE = SHRTCKN_SUBJ_CODE AND C1.CRSE_NUMB_LOW = SHRTCKN_CRSE_NUMB
                                    AND C1.PROGRAM = SOVLCUR_PROGRAM AND C1.TERM_CODE_EFF <= SOVLCUR_TERM_CODE_CTLG) OR C.TERM_CODE_EFF IS NULL)
    AND SHRTCKN_PIDM = R.SMRDOUS_PIDM(+) AND SHRTCKN_SUBJ_CODE = R.SMRDOUS_SUBJ_CODE(+) AND SHRTCKN_CRSE_NUMB = R.SMRDOUS_CRSE_NUMB(+)
    AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                            WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
                                AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
    /*AND SHRTCKG_GRDE_CODE_FINAL IN (SELECT SHRGRDE_CODE FROM SHRGRDE
                                    WHERE SHRGRDE_PASSED_IND = 'Y' AND SHRGRDE_LEVL_CODE = 'UG')*/
    AND SHRTCKN_PIDM IN (SELECT DISTINCT SOVLCUR_PIDM FROM LOE_SOVLCUR
                            WHERE SOVLCUR_ADMT_CODE = 'BK' AND SOVLCUR_CACT_CODE = 'ACTIVE'
                            UNION
                            SELECT DISTINCT SPRIDEN_PIDM FROM SPRIDEN
                            WHERE SPRIDEN_ID IN (
                            'N00031815'
                            ,'N00063134'
                            ,'N00082139'
                            ,'N00034973'
                            ,'N00024122'
                            ,'N00121759'
                            ,'N00043861'
                            ,'N00013887'
                            ,'N00028530'
                            ,'N00035053'
                            ,'N00031728'
                            ,'N00022212'
                            ,'N00148352'
                            ,'N00029745'
                            ,'N00017292'
                            ,'N00027159')
                            MINUS
                            SELECT DISTINCT SPRIDEN_PIDM FROM SPRIDEN
                            WHERE SPRIDEN_ID IN (
                            'N00056981'
                            ,'N00176629'
                            ,'N00095489'
                            ,'N00070143'
                            ,'N00050061'
                            ,'N00173492'));

--577  Filas
SELECT DISTINCT SGRSATT_PIDM, SPRIDEN_ID FROM SGRSATT, SPRIDEN
WHERE SGRSATT_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SGRSATT_ATTS_CODE = 'BK18';
--527  Filas
SELECT DISTINCT SOVLCUR_PIDM, SPRIDEN_ID FROM LOE_SOVLCUR, SPRIDEN
WHERE SOVLCUR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SOVLCUR_RATE_CODE = 'TB18' AND SOVLCUR_CACT_CODE = 'ACTIVE';

--680  Filas
SELECT DISTINCT SOVLCUR_PIDM, SPRIDEN_ID FROM LOE_SOVLCUR, SPRIDEN
WHERE SOVLCUR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SOVLCUR_ADMT_CODE = 'BK' AND SOVLCUR_CACT_CODE = 'ACTIVE';

--690  Filas
SELECT DISTINCT SOVLCUR_PIDM FROM LOE_SOVLCUR
WHERE SOVLCUR_ADMT_CODE = 'BK' AND SOVLCUR_CACT_CODE = 'ACTIVE'
UNION
SELECT DISTINCT SPRIDEN_PIDM FROM SPRIDEN
WHERE SPRIDEN_ID IN (
'N00031815'
,'N00063134'
,'N00082139'
,'N00034973'
,'N00024122'
,'N00121759'
,'N00043861'
,'N00013887'
,'N00028530'
,'N00035053'
,'N00031728'
,'N00022212'
,'N00148352'
,'N00029745'
,'N00017292'
,'N00027159')
MINUS
SELECT DISTINCT SPRIDEN_PIDM FROM SPRIDEN
WHERE SPRIDEN_ID IN (
'N00056981'
,'N00176629'
,'N00095489'
,'N00070143'
,'N00050061'
,'N00173492');
