
WITH CICLO AS
    (SELECT DISTINCT A.PROGRAM, MAX(A.AREA_PRIORITY) AS CICLO_CURSO, A.TERM_CODE_EFF, NVL(B.SUBJ_CODE,C.SMRARUL_SUBJ_CODE) AS SUBJ_CODE
        , NVL(B.CRSE_NUMB_LOW,C.SMRARUL_CRSE_NUMB_LOW) AS CRSE_NUMB_LOW--, B.AREA_RULE
    FROM LOE_PROGRAM_AREA_PRIORITY A, LOE_AREA_COURSE B, LOE_SMRARUL C
    WHERE A.AREA = B.AREA_COURSE AND A.TERM_CODE_EFF = B.TERM_CODE_EFF
        AND B.AREA_RULE = C.SMRARUL_KEY_RULE(+) AND B.AREA_COURSE = C.SMRARUL_AREA(+) AND B.TERM_CODE_EFF = C.SMRARUL_TERM_CODE_EFF(+)
    GROUP BY A.PROGRAM, A.TERM_CODE_EFF, NVL(B.SUBJ_CODE,C.SMRARUL_SUBJ_CODE), NVL(B.CRSE_NUMB_LOW,C.SMRARUL_CRSE_NUMB_LOW))

SELECT SHRTCKN_PIDM, SPRIDEN_ID, GORADID_ADDITIONAL_ID AS DNI, SPRIDEN_FIRST_NAME AS NOMBRES, SUBSTR(SPRIDEN_LAST_NAME,1,INSTR(SPRIDEN_LAST_NAME,'/',1,1)-1) AS APELLIDO_PATERNO
    , SUBSTR(SPRIDEN_LAST_NAME,INSTR(SPRIDEN_LAST_NAME,'/',1,1)+1) AS APELLIDO_MATERNO, SOVLCUR_PROGRAM AS CARRERA, SHRTCKN_TERM_CODE AS SEMESTRE_ACADÉMICO, SHRTCKN_CRN, SHRTCKN_SUBJ_CODE, SHRTCKN_CRSE_NUMB
    , NVL(SHRTCKN_LONG_COURSE_TITLE,SHRTCKN_CRSE_TITLE) AS NOMBRE_CURSO, C.CICLO_CURSO, SHRTCKG_CREDIT_HOURS AS CREDITOS_CURSO, SHRTCKG_GRDE_CODE_FINAL AS NOTA_CURSO
FROM SHRTCKN, SHRTCKG G, SPRIDEN, GORADID, LOE_SOVLCUR, CICLO C
WHERE SHRTCKN_PIDM = SHRTCKG_PIDM AND SHRTCKN_TERM_CODE = SHRTCKG_TERM_CODE AND SHRTCKN_SEQ_NO = SHRTCKG_TCKN_SEQ_NO
    AND SHRTCKN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
    AND SHRTCKN_PIDM = GORADID_PIDM(+) AND GORADID_ADID_CODE(+) = 'DNI'
    AND SHRTCKN_PIDM = SOVLCUR_PIDM(+) AND SHRTCKN_TERM_CODE >= SOVLCUR_TERM_CODE(+)
        AND (SHRTCKN_TERM_CODE < SOVLCUR_TERM_CODE_END OR SOVLCUR_TERM_CODE_END IS NULL)
        AND SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND SOVLCUR_CACT_CODE(+) = 'ACTIVE' AND SOVLCUR_LEVL_CODE(+) = 'UG'
    AND SHRTCKN_SUBJ_CODE = C.SUBJ_CODE(+) AND SHRTCKN_CRSE_NUMB = C.CRSE_NUMB_LOW(+) AND SOVLCUR_PROGRAM = C.PROGRAM(+)
        AND (C.TERM_CODE_EFF = (SELECT MAX(C1.TERM_CODE_EFF) FROM CICLO C1
                                WHERE C1.SUBJ_CODE = SHRTCKN_SUBJ_CODE AND C1.CRSE_NUMB_LOW = SHRTCKN_CRSE_NUMB
                                    AND C1.PROGRAM = SOVLCUR_PROGRAM AND C1.TERM_CODE_EFF <= SOVLCUR_TERM_CODE_CTLG) OR C.TERM_CODE_EFF IS NULL)
    AND G.SHRTCKG_SEQ_NO = (SELECT MAX(G1.SHRTCKG_SEQ_NO) FROM SHRTCKG G1
                            WHERE G1.SHRTCKG_PIDM = G.SHRTCKG_PIDM AND G1.SHRTCKG_TERM_CODE = G.SHRTCKG_TERM_CODE
                                AND G1.SHRTCKG_TCKN_SEQ_NO = G.SHRTCKG_TCKN_SEQ_NO)
    /*AND SHRTCKG_GRDE_CODE_FINAL IN (SELECT SHRGRDE_CODE FROM SHRGRDE
                                    WHERE SHRGRDE_PASSED_IND = 'Y' AND SHRGRDE_LEVL_CODE = 'UG')*/
    AND SHRTCKN_PIDM IN (SELECT DISTINCT SGRSATT_PIDM FROM SGRSATT
                            WHERE SGRSATT_ATTS_CODE = 'BK18');

SELECT * FROM GORADID
WHERE GORADID_ADID_CODE = 'DNI'

SELECT * FROM LOE_SOVLCUR   --SOVLCUR_TERM_CODE_CTLG
WHERE SHRTCKG_TERM_CODE = '219413'

SELECT DISTINCT SGRSATT_PIDM FROM SGRSATT
WHERE SGRSATT_ATTS_CODE = 'BK18';

SELECT SOVLCUR_PIDM FROM LOE_SOVLCUR
WHERE SOVLCUR_RATE_CODE = 'TB18' AND SOVLCUR_CACT_CODE = 'ACTIVE';

