SELECT DISTINCT SFRREGP_PIDM, S.SPRIDEN_ID AS ID_ESTUDIANTE, S.SPRIDEN_LAST_NAME, S.SPRIDEN_FIRST_NAME
    , SOVLCUR_CAMP_CODE AS CAMPUS_ESTUDIANTE, SFRREGP_TERM_CODE, SFRREGP_MAINT_IND, SFRREGP_ACTIVITY_DATE
    , SFRREGP_PROGRAM, SMRPRLE_PROGRAM_DESC, SFRREGP_AREA, SFRREGP_SUBJ_CODE, SFRREGP_CRSE_NUMB_LOW
    , SCBCRSE_TITLE, SFRREGP_CRN_SCHEDULE, SFRREGP_LEVL_CODE, SFRREGP_CAMP_CODE AS CAMPUS_CURSO
    , SFRREGP_USER_ID, U.SPRIDEN_LAST_NAME, U.SPRIDEN_FIRST_NAME
FROM SFRREGP, LOE_SPRIDEN S, SMRPRLE, SCBCRSE C, LOE_SPRIDEN U, LOE_SOVLCUR
WHERE SFRREGP_PIDM = S.SPRIDEN_PIDM AND S.SPRIDEN_CHANGE_IND IS NULL
    AND SFRREGP_PROGRAM = SMRPRLE_PROGRAM(+)
    AND SFRREGP_SUBJ_CODE = SCBCRSE_SUBJ_CODE(+) AND SFRREGP_CRSE_NUMB_LOW = SCBCRSE_CRSE_NUMB(+)
    AND SCBCRSE_CSTA_CODE(+) = 'A'
    AND (C.SCBCRSE_EFF_TERM = (SELECT MAX(C1.SCBCRSE_EFF_TERM) FROM SCBCRSE C1
                                WHERE C1.SCBCRSE_SUBJ_CODE = SFRREGP_SUBJ_CODE
                                    AND C1.SCBCRSE_CRSE_NUMB = SFRREGP_CRSE_NUMB_LOW
                                    AND C1.SCBCRSE_EFF_TERM <= SFRREGP_TERM_CODE
                                    AND C1.SCBCRSE_CSTA_CODE = 'A') OR C.SCBCRSE_EFF_TERM IS NULL)
    AND SUBSTR(SFRREGP_USER_ID,2) = U.SPRIDEN_ID(+) AND U.SPRIDEN_CHANGE_IND IS NULL
    AND SFRREGP_PIDM = SOVLCUR_PIDM(+)
    AND SOVLCUR_LMOD_CODE(+) = 'LEARNER' AND SOVLCUR_CACT_CODE(+) = 'ACTIVE'
    AND SOVLCUR_LEVL_CODE(+) = 'UG' AND SOVLCUR_TERM_CODE_END(+) IS NULL
    AND SFRREGP_MAINT_IND = 'U' AND SFRREGP_TERM_CODE IN ('220435','220534')
ORDER BY SFRREGP_PIDM;
