--FACT_ANULACION_
SELECT DISTINCT F.BUSINESS_UNIT, F.ITEM, F.ITEM_LINE, F.ITEM_SEQ_NUM, F.ENTRY_TYPE, F.ENTRY_REASON, F.ENTRY_AMT, F.ACCOUNTING_DT
	, F.PERIODO_CONTABLE, G.JOURNAL_ID AS JOURNAL_ID_AR, G.JOURNAL_DATE AS JOURNAL_DATE_AR
FROM ( SELECT BUSINESS_UNIT, ITEM, ITEM_LINE, ITEM_SEQ_NUM, ENTRY_TYPE, ENTRY_REASON, ENTRY_AMT, ACCOUNTING_DT, TO_CHAR(ACCOUNTING_DT,'YYYYMM') AS PERIODO_CONTABLE
            , MAX(CASE WHEN ENTRY_TYPE IN ('WO','WOC') AND ENTRY_REASON = 'A-DIR' THEN 'WO_WOC_A-DIR' END) OVER(PARTITION BY ITEM, TO_CHAR(ACCOUNTING_DT,'YYYYMM')) AS WO_WOC_A_DIR
        FROM ODSMGR.PS_ITEM_ACTIVITY
        WHERE BUSINESS_UNIT = 'PER03' AND ENTRY_TYPE NOT IN ('PY','MT') AND ACCOUNTING_DT BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
        ) F
			LEFT JOIN ODSMGR.PS_ITEM_DST G ON F.BUSINESS_UNIT = G.BUSINESS_UNIT AND F.ITEM = G.ITEM AND F.ITEM_LINE = G.ITEM_LINE AND F.ITEM_SEQ_NUM = G.ITEM_SEQ_NUM
												AND F.PERIODO_CONTABLE = TO_CHAR(G.JOURNAL_DATE,'YYYYMM') AND G.LEDGER = 'ACTUALS'
												--AND G.JOURNAL_DATE BETWEEN TO_DATE(:FECHA_INICIO,'YYYY-MM-DD') AND TO_DATE(:FECHA_FIN,'YYYY-MM-DD')
WHERE F.WO_WOC_A_DIR = 'WO_WOC_A-DIR'
--ORDER BY F.ITEM, F.ITEM_SEQ_NUM
;