--PS_LI_PER_ARPMT_VW_
USE SCHEMA ODSMGR;

--CREATE OR REPLACE VIEW PS_LI_PER_ARPMT_VW("DEPOSIT_BU", "PYMNT_REF_ID", "DRAWER_ID", "STEP_STATUS", "FILENAME", "CUST_ID", "INVOICE", "RECEIPT_NBR", "PAYMENT_METHOD_CDR", "DEPOSIT_ID", "PAYMENT_SEQ_NUM", "PAYMENT_ID", "PAYMENT_STATUS", "WO_ADJ_USED_SW", "ENTRY_DT", "ACCOUNTING_DT", "CREATEDTTM", "ENTERED_DTTM") AS
SELECT TBL.DEPOSIT_BU , TBL.PYMNT_REF_ID , TBL.DRAWER_ID , TBL.LOCKBOX_RUN_STATUS ,
          TBL.FILENAME , TBL.BILL_TO_CUST_ID , REF.INVOICE , TBL.RECEIPT_NBR ,
          DTL.PAYMENT_METHOD_CDR , PAY.DEPOSIT_ID , PAY.PAYMENT_SEQ_NUM , PAY.PAYMENT_ID ,
          PAY.PAYMENT_STATUS , PAY.WO_ADJ_USED_SW , PAY.ENTRY_DT , PAY.ACCOUNTING_DT ,
          TBL.CREATEDTTM , PAY.ENTERED_DTTM
    FROM PS_LI_GBL_ARPY_TBL TBL ,
         PS_LI_GBL_ARPY_REF REF ,
         (PS_LI_GBL_ARPY_DTL DTL LEFT OUTER JOIN PS_PAYMENT PAY ON
           (DTL.DEPOSIT_BU = PAY.DEPOSIT_BU AND DTL.REFERENCE = PAY.PAYMENT_ID)
           LEFT OUTER JOIN PS_PAYMENT_ID_ITEM IDPY ON
           (PAY.DEPOSIT_BU = IDPY.DEPOSIT_BU AND PAY.DEPOSIT_ID = IDPY.DEPOSIT_ID AND PAY.PAYMENT_SEQ_NUM = IDPY.PAYMENT_SEQ_NUM))
    WHERE TBL.DEPOSIT_BU = REF.DEPOSIT_BU
      AND TBL.PYMNT_REF_ID = REF.PYMNT_REF_ID
      AND DTL.DEPOSIT_BU = REF.DEPOSIT_BU
      AND DTL.PYMNT_REF_ID = REF.PYMNT_REF_ID
      AND TBL.SOURCE IN ('BNK','POR') 
UNION SELECT POS.DEPOSIT_BU , POS.PYMNT_REF_ID , POS.DRAWER_ID , CDR.RECEIPT_STATUS ,
             POS.FILENAME , POS.BILL_TO_CUST_ID , REF.INVOICE , CDR.RECEIPT_NBR ,
             PMT.PAYMENT_METHOD_CDR , PMT.DEPOSIT_ID , PMT.PAYMENT_SEQ_NUM ,
             PAY.PAYMENT_ID , PAY.PAYMENT_STATUS , PAY.WO_ADJ_USED_SW , PAY.ENTRY_DT ,
             PAY.ACCOUNTING_DT , POS.CREATEDTTM , PAY.ENTERED_DTTM
       FROM PS_LI_GBL_ARPY_REF REF , PS_LI_GBL_ARPY_TBL POS
       LEFT OUTER JOIN PS_CDR_RECEIPT CDR ON
              (CDR.DEPOSIT_BU=POS.DEPOSIT_BU AND CDR.RECEIPT_NBR=POS.RECEIPT_NBR)
       LEFT OUTER JOIN PS_CDR_RECEIPT_PMT PMT ON (CDR.DEPOSIT_BU = PMT.DEPOSIT_BU
                       AND CDR.RECEIPT_NBR = PMT.RECEIPT_NBR)
       LEFT OUTER JOIN PS_PAYMENT PAY ON (PMT.DEPOSIT_BU = PAY.DEPOSIT_BU
                       AND PMT.DEPOSIT_ID = PAY.DEPOSIT_ID
                       AND PMT.PAYMENT_SEQ_NUM = PAY.PAYMENT_SEQ_NUM)
     WHERE POS.SOURCE = 'POS'
       AND POS.DEPOSIT_BU = REF.DEPOSIT_BU
       AND POS.PYMNT_REF_ID = REF.PYMNT_REF_ID
UNION SELECT CDR.DEPOSIT_BU , NULL , CDR.DRAWER_ID , CDR.RECEIPT_STATUS , NULL ,
             CDR.BILL_TO_CUST_ID , REF.REF_VALUE , CDR.RECEIPT_NBR , PMT.PAYMENT_METHOD_CDR ,
             PMT.DEPOSIT_ID , PMT.PAYMENT_SEQ_NUM , PAY.PAYMENT_ID , PAY.PAYMENT_STATUS ,
             PAY.WO_ADJ_USED_SW , PAY.ENTRY_DT , PAY.ACCOUNTING_DT , CDR.ADD_DTTM ,
             PAY.ENTERED_DTTM
       FROM PS_CDR_RECEIPT_REF REF ,
            PS_CDR_RECEIPT CDR
      LEFT OUTER JOIN PS_CDR_RECEIPT_PMT PMT ON (CDR.DEPOSIT_BU = PMT.DEPOSIT_BU AND CDR.RECEIPT_NBR = PMT.RECEIPT_NBR)
      LEFT OUTER JOIN PS_PAYMENT PAY ON (PMT.DEPOSIT_BU = PAY.DEPOSIT_BU AND PMT.DEPOSIT_ID = PAY.DEPOSIT_ID AND PMT.PAYMENT_SEQ_NUM = PAY.PAYMENT_SEQ_NUM)
WHERE CDR.DEPOSIT_BU = REF.DEPOSIT_BU
  AND CDR.RECEIPT_NBR = REF.RECEIPT_NBR
  AND REF.REF_QUALIFIER_CODE = 'I'
  AND NOT EXISTS( SELECT 'X'
                   FROM PS_LI_GBL_ARPY_TBL POS
                   WHERE CDR.DEPOSIT_BU=POS.DEPOSIT_BU
                     AND CDR.RECEIPT_NBR=POS.RECEIPT_NBR)
 UNION SELECT PAY.DEPOSIT_BU , NULL , NULL , NULL , NULL , ITM.CUST_ID , ITM.REF_VALUE ,
              NULL , PAY.PAYMENT_METHOD , PAY.DEPOSIT_ID , PAY.PAYMENT_SEQ_NUM ,
              PAY.PAYMENT_ID , PAY.PAYMENT_STATUS , PAY.WO_ADJ_USED_SW , PAY.ENTRY_DT ,
              PAY.ACCOUNTING_DT , PAY.ENTERED_DTTM , PAY.ENTERED_DTTM
         FROM PS_PAYMENT_ID_ITEM ITM , PS_PAYMENT PAY
       WHERE ITM.DEPOSIT_BU = PAY.DEPOSIT_BU
         AND ITM.DEPOSIT_ID = PAY.DEPOSIT_ID
         AND ITM.PAYMENT_SEQ_NUM = PAY.PAYMENT_SEQ_NUM
         AND ITM.REF_QUALIFIER_CODE = 'I'
         AND NOT EXISTS ( SELECT 'X'
                            FROM PS_CDR_RECEIPT_PMT PMT
                            WHERE PMT.DEPOSIT_BU = PAY.DEPOSIT_BU
                              AND PMT.DEPOSIT_ID = PAY.DEPOSIT_ID
                              AND PMT.PAYMENT_SEQ_NUM = PAY.PAYMENT_SEQ_NUM)
                              AND NOT EXISTS ( SELECT 'X'
                                                  FROM PS_LI_GBL_ARPY_TBL TBL ,
                                                       PS_LI_GBL_ARPY_REF REF ,
                                                       PS_LI_GBL_ARPY_DTL DTL
                                                 WHERE TBL.DEPOSIT_BU = DTL.DEPOSIT_BU
                                                   AND TBL.PYMNT_REF_ID = DTL.PYMNT_REF_ID
                                                   AND DTL.DEPOSIT_BU = REF.DEPOSIT_BU
                                                   AND DTL.PYMNT_REF_ID = REF.PYMNT_REF_ID
                                                   AND TBL.SOURCE IN ('BNK','POR')
                                                   AND REF.DEPOSIT_BU = ITM.DEPOSIT_BU
                                                   AND REF.INVOICE = ITM.REF_VALUE
                                                   AND DTL.DEPOSIT_BU = PAY.DEPOSIT_BU
                                                   AND DTL.REFERENCE = PAY.PAYMENT_ID)
;