-- UPN_RPT_DM_PROD.ODSMGR.PS_PORTAL_VISA_HEADER_PRC source

CREATE OR REPLACE VIEW PS_PORTAL_VISA_HEADER_PRC AS
SELECT DISTINCT
	A.BILL_TO_CUST_ID  CodigoEstudiante ,
	A.INVOICE Invoice ,
	A.BILL_TYPE_ID TipoDocumento ,
	B.INVOICE2 NumeroDocumento ,
	--(  nvl(A.INVOICE_AMOUNT, 0)  + nvl(E.FC_AMT, 0 ) )as MontoTotal ,
	( nvl(A.INVOICE_AMOUNT,0) + nvl(C.USER_AMT3,0) + nvl(C.USER_AMT4,0) ) as MontoTotal ,
	nvl(C.PAYMENT_AMT,0) as MontoPagado ,
	--  E.INVOICE_AMOUNT ,  E.FC_AMT ,
	CASE WHEN D.BAL_AMT IS NULL THEN nvl(A.INVOICE_AMOUNT,0) + nvl(C.USER_AMT3,0) + nvl(C.USER_AMT4,0) + nvl(C.PAYMENT_AMT,0) ELSE nvl(D.BAL_AMT,0) + nvl(C.USER_AMT3,0) + nvl(C.USER_AMT4,0) END MontoSaldo,
	A.PO_REF Semestre ,
	D.invoice_DT fecha_de_emision ,
	NVL(TO_DATE( TO_CHAR(D.DUE_DT,'YYYY-MM-DD'),'YYYY-MM-DD'), TRMS_TIME.DUE_DT) fecha_de_vencimiento ,
	TO_DATE(CURRENT_DATE) - TO_DATE( TO_CHAR(D.DUE_DT,'YYYY-MM-DD'),'YYYY-MM-DD') DiasMora ,
	--E.FC_AMT MontoMora ,
	C.USER_AMT3 MontoMora,
	C.USER_AMT4 MontoGastoAdministrativo,
	A.BILL_STATUS Estado_Facturacion ,
	D.ITEM_STATUS Estado_Item  ,
	F.OPERATING_UNIT OperatingUnit /*,
	G.USER_AMT1 ,
	G.USER_AMT2*/
FROM (((((ODSMGR.PS_BI_HDR A LEFT OUTER JOIN ODSMGR.PS_LI_GBL_BI_INV B ON A.BUSINESS_UNIT = B.BUSINESS_UNIT AND A.INVOICE = B.INVOICE )
                              LEFT OUTER JOIN ODSMGR.PS_ITEM D ON A.BUSINESS_UNIT = D.BUSINESS_UNIT AND A.INVOICE = D.INVOICE )
                              LEFT OUTER JOIN ODSMGR.PS_ITEM_ACTIVITY C ON D.BUSINESS_UNIT = C.BUSINESS_UNIT AND D.CUST_ID = C.CUST_ID
                                                                       AND D.ITEM = C.ITEM AND D.ITEM_LINE = C.ITEM_LINE AND C.ITEM_SEQ_NUM = D.ITEM_SEQ_NUM )
                              LEFT OUTER JOIN ODSMGR.PS_LI_GBL_PYCRT_VW E ON A.BUSINESS_UNIT = E.BUSINESS_UNIT AND A.INVOICE = E.INVOICE )
                              LEFT OUTER JOIN ODSMGR.PS_BI_LINE G ON  A.BUSINESS_UNIT = G.BUSINESS_UNIT AND A.INVOICE = G.INVOICE)
           LEFT OUTER JOIN ODSMGR.PS_PAY_TRMS_NET TRMS_NET ON TRMS_NET.PYMNT_TERMS_CD = A.PYMNT_TERMS_CD
           LEFT OUTER JOIN ODSMGR.PS_PAY_TRMS_TIME TRMS_TIME ON TRMS_TIME.SETID = TRMS_NET.SETID AND TRMS_TIME.PAY_TRMS_TIME_ID = TRMS_NET.PAY_TRMS_TIME_ID
           , ODSMGR.PS_BI_LINE_DST F
WHERE A.BUSINESS_UNIT = F.BUSINESS_UNIT
	AND A.TEMPLATE_IVC_FLG <> 'I'
	AND ((A.BILLING_FREQUENCY = 'INS' AND A.TEMPLATE_INVOICE <> '') OR A.BILLING_FREQUENCY <> 'INS')
	AND A.INVOICE = f.invoice
;
