SELECT A.SFRSTCR_TERM_CODE, A.SFRSTCR_PIDM, SPRIDEN_ID, A.SFRSTCR_CRN, B.SSBSECT_SUBJ_CODE, B.SSBSECT_CRSE_NUMB, A.SFRSTCR_RSTS_CODE, A.SFRSTCR_RSTS_DATE, B.SSBSECT_SCHD_CODE, B.SSBSECT_CAMP_CODE
FROM SFRSTCR A, SSBSECT B, SPRIDEN, 
	(SELECT SFRSTCR_TERM_CODE, SFRSTCR_PIDM, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB, COUNT (SFRSTCR_PIDM)
		FROM SFRSTCR, SSBSECT
		WHERE SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
			AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA')
			AND SFRSTCR_TERM_CODE IN ('220413','220513')    --INGRESAR PERIODO
		HAVING COUNT (SFRSTCR_PIDM) > 1
		GROUP BY SFRSTCR_TERM_CODE, SFRSTCR_PIDM, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB) C
WHERE A.SFRSTCR_TERM_CODE = B.SSBSECT_TERM_CODE AND A.SFRSTCR_CRN = B.SSBSECT_CRN
	AND A.SFRSTCR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
	AND A.SFRSTCR_TERM_CODE = C.SFRSTCR_TERM_CODE AND A.SFRSTCR_PIDM = C.SFRSTCR_PIDM
	AND B.SSBSECT_SUBJ_CODE = C.SSBSECT_SUBJ_CODE AND B.SSBSECT_CRSE_NUMB = C.SSBSECT_CRSE_NUMB
	AND A.SFRSTCR_TERM_CODE IN ('220413','220513');     --INGRESAR PERIODO
