SELECT DISTINCT
    b.PERSON_UID AS PIDM, 
    d.SPRIDEN_ID AS CODBANNER, 
    MAX(e.ALTERNATIVE_ID)
        OVER (PARTITION BY
            e.ENTITY_UID) AS CODSPRING, 
    d.SPRIDEN_FIRST_NAME AS NOMBRES, 
    d.SPRIDEN_LAST_NAME AS APELLIDOS, 
    f.EMAIL_ADDRESS AS EMAIL, 
    a.ACADEMIC_PERIOD PERIODO, 
    c.CAMPUS_DESC AS CAMPUS, 
    a.SUBJECT AS MATER, 
    a.COURSE_NUMBER AS CURSO, 
    a.COURSE_REFERENCE_NUMBER AS NRC, 
    NVL(a.TITLE_LONG_DESC,a.TITLE_SHORT_DESC) AS NOMBRE_CURSO
FROM 
    ((((MEETING_TIME a
        INNER JOIN INSTRUCTIONAL_ASSIGNMENT b ON
            a.ACADEMIC_PERIOD = b.ACADEMIC_PERIOD AND
            a.COURSE_REFERENCE_NUMBER = b.COURSE_REFERENCE_NUMBER AND
            a.CATEGORY = b.CATEGORY)
        INNER JOIN SCHEDULE_OFFERING c ON
            a.ACADEMIC_PERIOD = c.ACADEMIC_PERIOD AND
            a.COURSE_REFERENCE_NUMBER = c.COURSE_REFERENCE_NUMBER)
        LEFT JOIN LOE_SPRIDEN d ON
            b.PERSON_UID = d.SPRIDEN_PIDM AND
            d.SPRIDEN_CHANGE_IND IS NULL)
        LEFT JOIN ALTERNATIVE_ID e ON
            b.PERSON_UID = e.ENTITY_UID AND
            e.ATERNATIVE_ID_TYPE = 'SPID')
        LEFT JOIN LOE_EMAIL f ON
            b.PERSON_UID = f.PERSON_UID AND
            f.STATUS_IND = 'A' AND
            f.EMAIL_TYPE = 'UNIV'
WHERE 
    a.SCHEDULE = 'VIR' AND
    c.STATUS = 'A'
    AND a.ACADEMIC_PERIOD IN ('218413','218512') --INGRESAR PERIODO
ORDER BY a.ACADEMIC_PERIOD DESC, b.PERSON_UID;