--SIU_Matriculados_
/*CODIGO_LOCAL, PERIODO_LECTIVO, TIPO_PERIODO, PERIODO_ACADEMICO, CODIGO_FACULTAD_UNIDAD, CODIGO_PROGRAMA, CAMBIO_PROGRAMA
	, CODIGO_PROGRAMA_ANTERIOR, FECHA_CAMBIO_PROGRAMA, TIPO_DOCUMENTO, NRO_DOCUMENTO, CODIGO_ESTUDIANTE, CICLO_ACADEMICO
	, MODALIDAD_ESTUDIO, FECHA_MATRICULA, CODIGO_ESCALA_PAGO, PORCENTAJE_DESCUENTO, TIENE_BECA, TIPO_BECA, OTRA_BECA, PORCENTAJE_CUBIERTO
*/
WITH PROGRAMA_ANTERIOR AS (
	SELECT *
	FROM (
		SELECT DISTINCT A.SOVLCUR_PIDM, A.SOVLCUR_SEQNO, A.SOVLCUR_TERM_CODE, A.SOVLCUR_LEVL_CODE, A.SOVLCUR_USER_ID, A.SOVLCUR_ACTIVITY_DATE
		    , A.SOVLCUR_PROGRAM AS PROGRAMA_DESTINO, B.SOVLCUR_TERM_CODE AS PERIODO_ORIGEN, B.SOVLCUR_PROGRAM AS PROGRAMA_ORIGEN
		FROM ODSMGR.LOE_SOVLCUR A, ODSMGR.LOE_SOVLCUR B
		WHERE A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_LEVL_CODE = 'UG'
		    AND A.SOVLCUR_PIDM = B.SOVLCUR_PIDM
		    AND B.SOVLCUR_SEQNO = ( SELECT MAX(B1.SOVLCUR_SEQNO) FROM ODSMGR.LOE_SOVLCUR B1
		                            WHERE B1.SOVLCUR_PIDM = B.SOVLCUR_PIDM AND SUBSTR(B1.SOVLCUR_PROGRAM,1,3) <> SUBSTR(A.SOVLCUR_PROGRAM,1,3)
		                                AND B1.SOVLCUR_SEQNO < A.SOVLCUR_SEQNO AND B1.SOVLCUR_TERM_CODE_END = A.SOVLCUR_TERM_CODE
		                                AND B1.SOVLCUR_LMOD_CODE = 'LEARNER'
		                                AND B1.SOVLCUR_CACT_CODE = 'ACTIVE'
		                                AND B1.SOVLCUR_LEVL_CODE = 'UG'
		                                AND B1.SOVLCUR_PROGRAM NOT LIKE '%PDN%' )
		) C
	WHERE (SUBSTR(C.PERIODO_ORIGEN,4,1) <> '3' OR C.PERIODO_ORIGEN < '217300')
)
, DOCUMENTO_IDENTIDAD AS (
	SELECT ENTITY_UID, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'DNI' THEN ALTERNATIVE_ID END) AS DNI
		, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'PASS' THEN ALTERNATIVE_ID END) AS PASS
		, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'CNEX' THEN ALTERNATIVE_ID END) AS CNEX
	FROM ODSMGR.ALTERNATIVE_ID I
	WHERE ATERNATIVE_ID_TYPE IN ('DNI','PASS','CNEX')
		AND I.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(I1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ODSMGR.ALTERNATIVE_ID I1
												WHERE I1.ENTITY_UID = I.ENTITY_UID AND I1.ATERNATIVE_ID_TYPE IN ('DNI','PASS','CNEX'))
	GROUP BY ENTITY_UID
)
, MAESTRIA_MOINTL AS (
	SELECT STUD.SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, REGLA.MAESTRIA
	FROM ( SELECT DISTINCT SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, SOVLCUR_PROGRAM
			FROM ODSMGR.LOE_SOVLCUR 
			WHERE SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE'
				AND SOVLCUR_LEVL_CODE = 'EC'/* AND SOVLCUR_CURRENT_IND = 'N'*/ ) STUD
		, ( SELECT N.MAESTRIA, N.TERM_CODE_EFF, SUBSTR(O.AREA,1,6) AS DIPLOMADO
			FROM ( SELECT PROGRAM AS MAESTRIA, TERM_CODE_EFF
					FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY M
					WHERE PROGRAM <> SUBSTR(AREA,1,6) AND SUBSTR(PROGRAM,1,5) <> 'ING-C'
						AND M.TERM_CODE_EFF = (SELECT MAX(M1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY M1
												WHERE M1.PROGRAM = M.PROGRAM)
					GROUP BY PROGRAM, TERM_CODE_EFF
					HAVING COUNT(SUBSTR(AREA,1,6)) = 2 ) N
				, ODSMGR.LOE_PROGRAM_AREA_PRIORITY O
			WHERE N.MAESTRIA = O.PROGRAM AND N.TERM_CODE_EFF = O.TERM_CODE_EFF AND N.MAESTRIA <> SUBSTR(O.AREA,1,6) ) REGLA
	WHERE STUD.SOVLCUR_PROGRAM = REGLA.DIPLOMADO
	GROUP BY STUD.SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, REGLA.MAESTRIA
	HAVING COUNT(STUD.SOVLCUR_PROGRAM) = 2
)
SELECT DISTINCT A.PERSON_UID, A.ID, A.STUDENT_LEVEL, CASE WHEN O.MAESTRIA IS NOT NULL THEN A.PROGRAM ||' - '|| O.MAESTRIA ELSE A.PROGRAM END AS PROGRAMA
	, CASE
		WHEN N.DNI IS NOT NULL THEN 'DNI - ' || N.DNI
		WHEN N.PASS IS NOT NULL THEN 'PASS - ' || N.PASS
		WHEN N.CNEX IS NOT NULL THEN 'CNEX - ' || N.CNEX
		ELSE NULL END AS DOCUMENTO_IDENTIDAD
	, CASE A.STUDENT_POPULATION
		WHEN 'N' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				ELSE 'Nuevo' END
		WHEN 'C' THEN 
			CASE 
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'NEW_REING' THEN 'Nuevo Reingreso'
				WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT = 'REINGRESO' THEN 'Reingreso'
				WHEN A.ADMISSIONS_POPULATION = 'II' THEN 'Intercambio IN'
				WHEN A.ADMISSIONS_POPULATION <> 'RE' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				WHEN E.ACTIVITY = 'DTO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Doble Titulacion OUT'
				WHEN E.ACTIVITY = 'ITO' AND D.STUDENT_ATTRIBUTE = 'TINT' THEN 'Intercambio OUT'
				ELSE 'Continuo' END
		ELSE A.STUDENT_POPULATION END AS TIPO_ESTUDIANTE
	, CASE
		WHEN Q.STUDENT_ATTRIBUTE = 'BK18' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		WHEN R.TBBESTU_PIDM IS NOT NULL AND S.EXEMPTION_CODE IS NOT NULL THEN S.EXEMPTION_CODE ||' - '|| T.TBBEXPT_DESC
		WHEN Q.STUDENT_ATTRIBUTE = 'FSMI' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		WHEN Q.STUDENT_ATTRIBUTE = 'CONT' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		ELSE NULL END AS BECA, 
	CASE A.CAMPUS
		WHEN 'TML' THEN (CASE
				WHEN A.STUDENT_LEVEL IN ('EC','MA') OR A.PROGRAM IN ('ABF-UG','ABF-WA','ENI-UG','ENI-WA')
					THEN 'SL02'
				ELSE 'SL01' END)
		WHEN 'TSI' THEN 'SL03'
		WHEN 'CAJ' THEN 'F01L01'
		WHEN 'LN0' THEN (CASE
				WHEN (CASE WHEN A.PROGRAM = 'MOINTL' THEN O.MAESTRIA ELSE A.PROGRAM END)
						IN ('MIAEMI','DGTHMI','ENF-UG','ENF-WA','NUT-UG','NUT-WA','OBS-UG','OBS-WA','PSI-UG','PSI-WA','TFI-UG','TFI-WA')
					THEN 'F02L03'
				ELSE 'F02L01' END)
		WHEN 'LC0' THEN 'F02L02'
		WHEN 'LE0' THEN 'F02L04'
		WHEN 'LN1' THEN 'F02L05'
		WHEN 'LS0' THEN 'F02L06'
		ELSE NULL END AS CODIGO_LOCAL
	, CASE
		WHEN G0.STVTERM_TRMT_CODE = 'S' THEN 1
		WHEN G0.STVTERM_TRMT_CODE = 'A' THEN 2
		WHEN G0.STVTERM_TRMT_CODE = 'D' THEN 4
		END AS PERIODO_LECTIVO
	, CASE
		WHEN A.STUDENT_LEVEL IN ('UG','MA') THEN 1
		WHEN A.STUDENT_LEVEL = 'EC' THEN 12
		END AS TIPO_PERIODO
	, SUBSTR(G0.STVTERM_DESC,1,6) AS PERIODO_ACADEMICO
	--, '2021-1' AS PERIODO_ACADEMICO
	, CASE (CASE WHEN A.PROGRAM = 'MOINTL' THEN O.MAESTRIA ELSE A.PROGRAM END)
		WHEN 'ADM-EA' THEN 3
		WHEN 'ADM-FS' THEN 3
		WHEN 'ADM-UG' THEN 3
		WHEN 'ADM-WA' THEN 3
		WHEN 'ABF-UG' THEN 3
		WHEN 'ABF-WA' THEN 3
		WHEN 'AGC-UG' THEN 3
		WHEN 'AGC-WA' THEN 3
		WHEN 'AGT-WA' THEN 3
		WHEN 'AGT-UG' THEN 3
		WHEN 'GPU-WA' THEN 3
		WHEN 'GPU-UG' THEN 3
		WHEN 'AMK-UG' THEN 3
		WHEN 'AMK-WA' THEN 3
		WHEN 'AST-UG' THEN 3
		WHEN 'AST-WA' THEN 3
		WHEN 'ADI-UG' THEN 15
		WHEN 'ADI-WA' THEN 15
		WHEN 'AUR-UG' THEN 15
		WHEN 'AUR-WA' THEN 15
		WHEN 'COM-UG' THEN 9
		WHEN 'COM-WA' THEN 9
		WHEN 'CAM-UG' THEN 9
		WHEN 'CAM-WA' THEN 9
		WHEN 'CCR-UG' THEN 9
		WHEN 'CCR-WA' THEN 9
		WHEN 'CDG-UG' THEN 9
		WHEN 'CDG-WA' THEN 9
		WHEN 'CPE-UG' THEN 9
		WHEN 'CPE-WA' THEN 9
		WHEN 'CPU-UG' THEN 9
		WHEN 'CPU-WA' THEN 9
		WHEN 'CON-UG' THEN 3
		WHEN 'CON-WA' THEN 3
		WHEN 'DEH-WA' THEN 8
		WHEN 'DEH-UG' THEN 8
		WHEN 'DIN-UG' THEN 15
		WHEN 'DIN-WA' THEN 15
		WHEN 'ECO-UG' THEN 3
		WHEN 'ECO-WA' THEN 3
		WHEN 'ENI-UG' THEN 3
		WHEN 'ENI-WA' THEN 3
		WHEN 'EDG-UG' THEN 9
		WHEN 'EDG-WA' THEN 9
		WHEN 'ENF-UG' THEN 11
		WHEN 'ENF-WA' THEN 11
		WHEN 'GGR-UG' THEN 3
		WHEN 'GGR-WA' THEN 3
		WHEN 'AGR-UG' THEN 5
		WHEN 'AGR-WA' THEN 5
		WHEN 'AMB-UG' THEN 5
		WHEN 'AMB-WA' THEN 5
		WHEN 'MIN-UG' THEN 5
		WHEN 'MIN-WA' THEN 5
		WHEN 'SIC-WA' THEN 5
		WHEN 'SIC-UG' THEN 5
		WHEN 'ELE-UG' THEN 5
		WHEN 'ELE-WA' THEN 5
		WHEN 'EMP-UG' THEN 5
		WHEN 'EMP-WA' THEN 5
		WHEN 'GEO-UG' THEN 5
		WHEN 'GEO-WA' THEN 5
		WHEN 'IND-FS' THEN 5
		WHEN 'IND-EA' THEN 5
		WHEN 'IND-UG' THEN 5
		WHEN 'IND-WA' THEN 5
		WHEN 'ILT-UG' THEN 5
		WHEN 'ILT-WA' THEN 5
		WHEN 'MCT-UG' THEN 5
		WHEN 'MCT-WA' THEN 5
		WHEN 'MEAEPM' THEN 18
		WHEN 'DEREPM' THEN 18
		WHEN 'DCGEPM' THEN 18
		WHEN 'DOCAPM' THEN 18
		WHEN 'DGIEPM' THEN 18
		WHEN 'DGTHPM' THEN 18
		WHEN 'FICOPM' THEN 18
		WHEN 'GMGCPM' THEN 18
		WHEN 'GARCPM' THEN 18
		WHEN 'GEPUPM' THEN 18
		WHEN 'INSIPM' THEN 18
		WHEN 'MKNIPM' THEN 18
		WHEN 'MIAEMI' THEN 18
		WHEN 'LMBAPM' THEN 18
		WHEN 'NUT-WA' THEN 11
		WHEN 'NUT-UG' THEN 11
		WHEN 'OBS-UG' THEN 11
		WHEN 'OBS-WA' THEN 11
		WHEN 'PSI-UG' THEN 11
		WHEN 'PSI-WA' THEN 11
		WHEN 'TFI-UG' THEN 11
		WHEN 'TFI-WA' THEN 11
		ELSE 1 END AS CODIGO_FACULTAD_UNIDAD
	, CASE (CASE WHEN A.PROGRAM = 'MOINTL' THEN O.MAESTRIA ELSE A.PROGRAM END)
		WHEN 'ADM-EA' THEN 1
		WHEN 'ADM-FS' THEN 1
		WHEN 'ADM-UG' THEN 1
		WHEN 'ADM-WA' THEN 1
		WHEN 'ABF-UG' THEN 20
		WHEN 'ABF-WA' THEN 20
		WHEN 'AGC-UG' THEN 2
		WHEN 'AGC-WA' THEN 2
		WHEN 'AGT-WA' THEN 21
		WHEN 'AGT-UG' THEN 21
		WHEN 'GPU-WA' THEN 22
		WHEN 'GPU-UG' THEN 22
		WHEN 'AMK-UG' THEN 3
		WHEN 'AMK-WA' THEN 3
		WHEN 'ANI-UG' THEN 4
		WHEN 'ANI-WA' THEN 4
		WHEN 'AST-UG' THEN 5
		WHEN 'AST-WA' THEN 5
		WHEN 'ARQ-UG' THEN 58
		WHEN 'ARQ-WA' THEN 58
		WHEN 'ADI-UG' THEN 6
		WHEN 'ADI-WA' THEN 6
		WHEN 'AGP-UG' THEN 59
		WHEN 'AGP-WA' THEN 59
		WHEN 'AUR-UG' THEN 7
		WHEN 'AUR-WA' THEN 7
		WHEN 'CCO-UG' THEN 60
		WHEN 'CCO-WA' THEN 60
		WHEN 'COM-UG' THEN 23
		WHEN 'COM-WA' THEN 23
		WHEN 'CAM-UG' THEN 8
		WHEN 'CAM-WA' THEN 8
		WHEN 'CCR-UG' THEN 24
		WHEN 'CCR-WA' THEN 24
		WHEN 'CDG-UG' THEN 25
		WHEN 'CDG-WA' THEN 25
		WHEN 'CPE-UG' THEN 9
		WHEN 'CPE-WA' THEN 9
		WHEN 'CPU-UG' THEN 10
		WHEN 'CPU-WA' THEN 10
		WHEN 'CON-UG' THEN 11
		WHEN 'CON-WA' THEN 11
		WHEN 'DEH-WA' THEN 12
		WHEN 'DEH-UG' THEN 12
		WHEN 'DER-WA' THEN 62
		WHEN 'DER-UG' THEN 62
		WHEN 'DIN-UG' THEN 26
		WHEN 'DIN-WA' THEN 26
		WHEN 'DEREPD' THEN 28
		WHEN 'ECO-UG' THEN 29
		WHEN 'ECO-WA' THEN 29
		WHEN 'ENI-UG' THEN 30
		WHEN 'ENI-WA' THEN 30
		WHEN 'EDG-UG' THEN 31
		WHEN 'EDG-WA' THEN 31
		WHEN 'ENF-UG' THEN 32
		WHEN 'ENF-WA' THEN 32
		WHEN 'GGR-UG' THEN 33
		WHEN 'GGR-WA' THEN 33
		WHEN 'AGR-UG' THEN 34
		WHEN 'AGR-WA' THEN 34
		WHEN 'AMB-UG' THEN 13
		WHEN 'AMB-WA' THEN 13
		WHEN 'CIV-UG' THEN 14
		WHEN 'CIV-WA' THEN 14
		WHEN 'MIN-UG' THEN 35
		WHEN 'MIN-WA' THEN 35
		WHEN 'SIS-EA' THEN 63
		WHEN 'SIS-FS' THEN 63
		WHEN 'SIS-UG' THEN 63
		WHEN 'SIS-WA' THEN 63
		WHEN 'SIC-WA' THEN 15
		WHEN 'SIC-UG' THEN 15
		WHEN 'ELE-UG' THEN 36
		WHEN 'ELE-WA' THEN 36
		WHEN 'EMP-UG' THEN 16
		WHEN 'EMP-WA' THEN 16
		WHEN 'GEO-UG' THEN 38
		WHEN 'GEO-WA' THEN 38
		WHEN 'IND-FS' THEN 17
		WHEN 'IND-EA' THEN 17
		WHEN 'IND-UG' THEN 17
		WHEN 'IND-WA' THEN 17
		WHEN 'ILT-UG' THEN 37
		WHEN 'ILT-WA' THEN 37
		WHEN 'MCT-UG' THEN 39
		WHEN 'MCT-WA' THEN 39
		WHEN 'MEAEPM' THEN 40
		WHEN 'DEREPM' THEN 43
		WHEN 'DCGEPM' THEN 43
		WHEN 'DOCAPM' THEN 44
		WHEN 'DGIEPM' THEN 45
		WHEN 'DGTHPM' THEN 46
		WHEN 'FICOPM' THEN 49
		WHEN 'GMGCPM' THEN 50
		WHEN 'GARCPM' THEN 51
		WHEN 'GEPUPM' THEN 53
		WHEN 'INSIPM' THEN 54
		WHEN 'MKNIPM' THEN 55
		WHEN 'MIAEMI' THEN 42
		WHEN 'LMBAPM' THEN 41
		WHEN 'NUT-WA' THEN 18
		WHEN 'NUT-UG' THEN 18
		WHEN 'OBS-UG' THEN 56
		WHEN 'OBS-WA' THEN 56
		WHEN 'PSI-UG' THEN 19
		WHEN 'PSI-WA' THEN 19
		WHEN 'TFI-UG' THEN 57
		WHEN 'TFI-WA' THEN 57
		WHEN 'MKT-UG' THEN 64
		WHEN 'MKT-WA' THEN 64
		ELSE 999999 END AS CODIGO_PROGRAMA
	, CASE WHEN SUBSTR(A.PROGRAM,1,3) <> SUBSTR(L.SOVLCUR_PROGRAM,1,3) AND K.SOVLCUR_PIDM IS NOT NULL THEN 1 ELSE 0 END AS CAMBIO_PROGRAMA
	, CASE WHEN SUBSTR(A.PROGRAM,1,3) <> SUBSTR(L.SOVLCUR_PROGRAM,1,3) AND K.SOVLCUR_PIDM IS NOT NULL THEN (
		CASE L.SOVLCUR_PROGRAM
			WHEN 'ADM-EA' THEN 1
			WHEN 'ADM-FS' THEN 1
			WHEN 'ADM-UG' THEN 1
			WHEN 'ADM-WA' THEN 1
			WHEN 'ABF-UG' THEN 20
			WHEN 'ABF-WA' THEN 20
			WHEN 'AGC-UG' THEN 2
			WHEN 'AGC-WA' THEN 2
			WHEN 'AGT-WA' THEN 21
			WHEN 'AGT-UG' THEN 21
			WHEN 'GPU-WA' THEN 22
			WHEN 'GPU-UG' THEN 22
			WHEN 'AMK-UG' THEN 3
			WHEN 'AMK-WA' THEN 3
			WHEN 'ANI-UG' THEN 4
			WHEN 'ANI-WA' THEN 4
			WHEN 'AST-UG' THEN 5
			WHEN 'AST-WA' THEN 5
			WHEN 'ARQ-UG' THEN 58
			WHEN 'ARQ-WA' THEN 58
			WHEN 'ADI-UG' THEN 6
			WHEN 'ADI-WA' THEN 6
			WHEN 'AGP-UG' THEN 59
			WHEN 'AGP-WA' THEN 59
			WHEN 'AUR-UG' THEN 7
			WHEN 'AUR-WA' THEN 7
			WHEN 'CCO-UG' THEN 60
			WHEN 'CCO-WA' THEN 60
			WHEN 'COM-UG' THEN 23
			WHEN 'COM-WA' THEN 23
			WHEN 'CAM-UG' THEN 8
			WHEN 'CAM-WA' THEN 8
			WHEN 'CCR-UG' THEN 24
			WHEN 'CCR-WA' THEN 24
			WHEN 'CDG-UG' THEN 25
			WHEN 'CDG-WA' THEN 25
			WHEN 'CPE-UG' THEN 9
			WHEN 'CPE-WA' THEN 9
			WHEN 'CPU-UG' THEN 10
			WHEN 'CPU-WA' THEN 10
			WHEN 'CON-UG' THEN 11
			WHEN 'CON-WA' THEN 11
			WHEN 'DEH-WA' THEN 12
			WHEN 'DEH-UG' THEN 12
			WHEN 'DER-WA' THEN 62
			WHEN 'DER-UG' THEN 62
			WHEN 'DIN-UG' THEN 26
			WHEN 'DIN-WA' THEN 26
			WHEN 'DEREPD' THEN 28
			WHEN 'ECO-UG' THEN 29
			WHEN 'ECO-WA' THEN 29
			WHEN 'ENI-UG' THEN 30
			WHEN 'ENI-WA' THEN 30
			WHEN 'EDG-UG' THEN 31
			WHEN 'EDG-WA' THEN 31
			WHEN 'ENF-UG' THEN 32
			WHEN 'ENF-WA' THEN 32
			WHEN 'GGR-UG' THEN 33
			WHEN 'GGR-WA' THEN 33
			WHEN 'AGR-UG' THEN 34
			WHEN 'AGR-WA' THEN 34
			WHEN 'AMB-UG' THEN 13
			WHEN 'AMB-WA' THEN 13
			WHEN 'CIV-UG' THEN 14
			WHEN 'CIV-WA' THEN 14
			WHEN 'MIN-UG' THEN 35
			WHEN 'MIN-WA' THEN 35
			WHEN 'SIS-EA' THEN 63
			WHEN 'SIS-FS' THEN 63
			WHEN 'SIS-UG' THEN 63
			WHEN 'SIS-WA' THEN 63
			WHEN 'SIC-WA' THEN 15
			WHEN 'SIC-UG' THEN 15
			WHEN 'ELE-UG' THEN 36
			WHEN 'ELE-WA' THEN 36
			WHEN 'EMP-UG' THEN 16
			WHEN 'EMP-WA' THEN 16
			WHEN 'GEO-UG' THEN 38
			WHEN 'GEO-WA' THEN 38
			WHEN 'IND-FS' THEN 17
			WHEN 'IND-EA' THEN 17
			WHEN 'IND-UG' THEN 17
			WHEN 'IND-WA' THEN 17
			WHEN 'ILT-UG' THEN 37
			WHEN 'ILT-WA' THEN 37
			WHEN 'MCT-UG' THEN 39
			WHEN 'MCT-WA' THEN 39
			WHEN 'MEAEPM' THEN 40
			WHEN 'DEREPM' THEN 43
			WHEN 'DCGEPM' THEN 43
			WHEN 'DOCAPM' THEN 44
			WHEN 'DGIEPM' THEN 45
			WHEN 'DGTHPM' THEN 46
			WHEN 'FICOPM' THEN 49
			WHEN 'GMGCPM' THEN 50
			WHEN 'GARCPM' THEN 51
			WHEN 'GEPUPM' THEN 53
			WHEN 'INSIPM' THEN 54
			WHEN 'MKNIPM' THEN 55
			WHEN 'MIAEMI' THEN 42
			WHEN 'LMBAPM' THEN 41
			WHEN 'NUT-WA' THEN 18
			WHEN 'NUT-UG' THEN 18
			WHEN 'OBS-UG' THEN 56
			WHEN 'OBS-WA' THEN 56
			WHEN 'PSI-UG' THEN 19
			WHEN 'PSI-WA' THEN 19
			WHEN 'TFI-UG' THEN 57
			WHEN 'TFI-WA' THEN 57
			WHEN 'MKT-UG' THEN 64
			WHEN 'MKT-WA' THEN 64
			ELSE 999999 END
		) ELSE NULL END AS CODIGO_PROGRAMA_ANTERIOR
	, TO_CHAR(CASE WHEN SUBSTR(A.PROGRAM,1,3) <> SUBSTR(L.SOVLCUR_PROGRAM,1,3) THEN COALESCE(M.START_DATE,M0.STVTERM_START_DATE) END,'DD/MM/YYYY') AS FECHA_CAMBIO_PROGRAMA
	, CASE
		WHEN N.DNI IS NOT NULL AND LENGTH(N.DNI) < 9 THEN 1
		WHEN N.PASS IS NOT NULL AND LENGTH(N.PASS) < 19 THEN 2
		WHEN N.CNEX IS NOT NULL AND LENGTH(N.CNEX) < 19 THEN 3
		ELSE NULL END AS TIPO_DOCUMENTO
	, CASE
		WHEN N.DNI IS NOT NULL AND LENGTH(N.DNI) < 9 THEN N.DNI
		WHEN N.PASS IS NOT NULL AND LENGTH(N.PASS) < 19 THEN N.PASS
		WHEN N.CNEX IS NOT NULL AND LENGTH(N.CNEX) < 19 THEN N.CNEX
		ELSE NULL END AS NRO_DOCUMENTO
	, A.ID AS CODIGO_ESTUDIANTE
	--, NVL(ROUND(P.ACT_CREDITS_OVERALL/20,0),0) AS CICLO_ACADEMICO
	, NVL(CASE
			WHEN CAST(P.ACT_CREDITS_OVERALL/20 AS INT) = 0 THEN 1
			WHEN CAST(P.ACT_CREDITS_OVERALL/20 AS INT) = 13 THEN 12
			ELSE CAST(P.ACT_CREDITS_OVERALL/20 AS INT) END
			,0) AS CICLO_ACADEMICO
	, CASE WHEN A.PROGRAM IN ('GPU-UG','GPU-WA') THEN 2 ELSE 1 END AS MODALIDAD_ESTUDIO
	, TO_CHAR(CASE WHEN A.STUDENT_LEVEL IN ('EC','MA') AND SUBSTR(J.STVTERM_DESC,1,6) <> '2021-1'
			THEN MIN(B0.SECTION_ADD_DATE) OVER(PARTITION BY B0.PERSON_UID, B0.ACADEMIC_PERIOD) ELSE G.START_DATE END,'DD/MM/YYYY') AS FECHA_MATRICULA
	, NULL AS CODIGO_ESCALA_PAGO, NULL AS PORCENTAJE_DESCUENTO
	, CASE WHEN (Q.PERSON_UID IS NOT NULL AND U.TBBCSTU_STU_PIDM IS NOT NULL) OR (R.TBBESTU_PIDM IS NOT NULL AND S.EXEMPTION_CODE IS NOT NULL) THEN 1 ELSE 0 END AS TIENE_BECA
	, CASE
		WHEN Q.STUDENT_ATTRIBUTE = 'BK18' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN 1
		WHEN R.TBBESTU_PIDM IS NOT NULL AND S.EXEMPTION_CODE IS NOT NULL THEN 2
		WHEN Q.STUDENT_ATTRIBUTE IN ('FSMI','CONT') AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN 3
		ELSE NULL END AS TIPO_BECA
	, CASE
		WHEN (Q.STUDENT_ATTRIBUTE = 'BK18' AND U.TBBCSTU_STU_PIDM IS NOT NULL) OR R.TBBESTU_PIDM IS NOT NULL THEN NULL
		WHEN Q.STUDENT_ATTRIBUTE = 'FSMI' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN 'FONDO SOCIAL MICHIQUILLAY'
		WHEN Q.STUDENT_ATTRIBUTE = 'CONT' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN 'CONTRATOS EMPRESAS'
		ELSE NULL END AS OTRA_BECA
	, CASE
		WHEN Q.STUDENT_ATTRIBUTE = 'BK18' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN U.TBRCDET_PERCENT
		WHEN R.TBBESTU_PIDM IS NOT NULL AND S.EXEMPTION_CODE IS NOT NULL THEN S.CHARGE_PERCENTAGE
		WHEN Q.STUDENT_ATTRIBUTE = 'FSMI' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN U.TBRCDET_PERCENT
		WHEN Q.STUDENT_ATTRIBUTE = 'CONT' AND U.TBBCSTU_STU_PIDM IS NOT NULL THEN U.TBRCDET_PERCENT
		ELSE NULL END AS PORCENTAJE_CUBIERTO
FROM ODSMGR.ACADEMIC_STUDY A
		INNER JOIN ODSMGR.STUDENT_COURSE B ON A.PERSON_UID = B.PERSON_UID AND A.ACADEMIC_PERIOD = B.ACADEMIC_PERIOD
												AND B.TRANSFER_COURSE_IND = 'N' AND B.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF','RO','SC')
		LEFT JOIN ODSMGR.STUDENT_COURSE_REG_AUDIT B0 ON A.PERSON_UID = B0.PERSON_UID AND A.ACADEMIC_PERIOD = B0.ACADEMIC_PERIOD AND B0.REGISTRATION_SOURCE = 'BASE'
		LEFT JOIN ODSMGR.STUDENT_COHORT C ON A.PERSON_UID = C.PERSON_UID AND A.ACADEMIC_PERIOD = C.ACADEMIC_PERIOD AND C.COHORT IN ('REINGRESO','NEW_REING')
		LEFT JOIN ODSMGR.STUDENT_ATTRIBUTE D ON A.PERSON_UID = D.PERSON_UID AND A.ACADEMIC_PERIOD = D.ACADEMIC_PERIOD AND D.STUDENT_ATTRIBUTE = 'TINT'
		LEFT JOIN ODSMGR.STUDENT_ACTIVITY E ON A.PERSON_UID = E.PERSON_UID AND A.ACADEMIC_PERIOD = E.ACADEMIC_PERIOD AND E.ACTIVITY IN ('DTO','ITO')
		LEFT JOIN ( SELECT DISTINCT PERSON_UID, ID, NAME, CURRICULUM_CHANGE_REASON FROM ODSMGR.FIELD_OF_STUDY
					WHERE SOURCE = 'OUTCOME' AND CURRICULUM_CHANGE_REASON = 'EGRESADO' AND STUDENT_LEVEL = 'UG'
					) F ON A.PERSON_UID = F.PERSON_UID
		LEFT JOIN ODSMGR.LOE_SECTION_PART_OF_TERM G ON A.ACADEMIC_PERIOD = G.TERM_CODE
		LEFT JOIN ODSMGR.STVTERM G0 ON A.ACADEMIC_PERIOD = G0.STVTERM_CODE
		LEFT JOIN ODSMGR.LOE_SOVLCUR H ON A.PERSON_UID = H.SOVLCUR_PIDM AND A.STUDENT_LEVEL = H.SOVLCUR_LEVL_CODE AND H.SOVLCUR_PROGRAM <> 'PDN-UG'
											AND H.SOVLCUR_TERM_CODE_ADMIT = (SELECT MIN(H1.SOVLCUR_TERM_CODE_ADMIT) FROM ODSMGR.LOE_SOVLCUR H1
																			WHERE H1.SOVLCUR_PIDM = H.SOVLCUR_PIDM AND H1.SOVLCUR_LEVL_CODE = H.SOVLCUR_LEVL_CODE AND H1.SOVLCUR_TERM_CODE_ADMIT IS NOT NULL
																				AND (SUBSTR(H1.SOVLCUR_TERM_CODE_ADMIT,4,1) <> '3' OR H1.SOVLCUR_TERM_CODE_ADMIT < '217300') AND H1.SOVLCUR_PROGRAM <> 'PDN-UG'
																				AND H1.SOVLCUR_LMOD_CODE = 'LEARNER' AND H1.SOVLCUR_CACT_CODE = 'ACTIVE')
		LEFT JOIN ODSMGR.LOE_SOVLCUR I ON A.PERSON_UID = I.SOVLCUR_PIDM AND A.STUDENT_LEVEL = I.SOVLCUR_LEVL_CODE AND A.PROGRAM = I.SOVLCUR_PROGRAM
											AND I.SOVLCUR_TERM_CODE_ADMIT = (SELECT MIN(I1.SOVLCUR_TERM_CODE_ADMIT) FROM ODSMGR.LOE_SOVLCUR I1
																			WHERE I1.SOVLCUR_PIDM = I.SOVLCUR_PIDM AND I1.SOVLCUR_LEVL_CODE = I.SOVLCUR_LEVL_CODE
																				AND I1.SOVLCUR_PROGRAM = I.SOVLCUR_PROGRAM AND I1.SOVLCUR_TERM_CODE_ADMIT IS NOT NULL
																				AND (SUBSTR(I1.SOVLCUR_TERM_CODE_ADMIT,4,1) <> '3' OR I1.SOVLCUR_TERM_CODE_ADMIT < '217300') AND I1.SOVLCUR_PROGRAM <> 'PDN-UG'
																				AND I1.SOVLCUR_LMOD_CODE = 'LEARNER' AND I1.SOVLCUR_CACT_CODE = 'ACTIVE')
		LEFT JOIN ODSMGR.STVTERM J ON CASE
										WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT IN ('REINGRESO','NEW_REING') AND F.PERSON_UID IS NULL THEN H.SOVLCUR_TERM_CODE_ADMIT
										WHEN A.STUDENT_LEVEL = 'UG' AND C.COHORT IN ('REINGRESO','NEW_REING') AND F.PERSON_UID IS NOT NULL THEN I.SOVLCUR_TERM_CODE_ADMIT
										WHEN A.STUDENT_POPULATION = 'N' OR A.ADMISSIONS_POPULATION = 'II' OR D.STUDENT_ATTRIBUTE = 'TINT' THEN A.ACADEMIC_PERIOD_ADMITTED
										WHEN A.STUDENT_LEVEL = 'UG' AND A.STUDENT_POPULATION = 'C' AND F.PERSON_UID IS NULL THEN H.SOVLCUR_TERM_CODE_ADMIT
										WHEN A.STUDENT_LEVEL = 'UG' AND A.STUDENT_POPULATION = 'C' AND F.PERSON_UID IS NOT NULL THEN I.SOVLCUR_TERM_CODE_ADMIT
										ELSE A.ACADEMIC_PERIOD_ADMITTED END = J.STVTERM_CODE
		LEFT JOIN PROGRAMA_ANTERIOR K ON A.PERSON_UID = K.SOVLCUR_PIDM AND A.STUDENT_LEVEL = K.SOVLCUR_LEVL_CODE AND A.PROGRAM = K.PROGRAMA_DESTINO
											AND K.SOVLCUR_SEQNO = (SELECT MAX(K1.SOVLCUR_SEQNO) FROM PROGRAMA_ANTERIOR K1
																	WHERE K1.SOVLCUR_PIDM = K.SOVLCUR_PIDM AND K1.SOVLCUR_LEVL_CODE = K.SOVLCUR_LEVL_CODE
																		AND ((SUBSTR(K1.PROGRAMA_DESTINO,4,3) = '-UG' AND K1.SOVLCUR_TERM_CODE <= '221413')
																				OR (SUBSTR(K1.PROGRAMA_DESTINO,4,3) = '-WA' AND K1.SOVLCUR_TERM_CODE <= '221513'))
																		AND K1.PROGRAMA_DESTINO = K.PROGRAMA_DESTINO)
		LEFT JOIN ODSMGR.LOE_SOVLCUR L ON K.SOVLCUR_PIDM = L.SOVLCUR_PIDM AND K.SOVLCUR_LEVL_CODE = L.SOVLCUR_LEVL_CODE AND J.STVTERM_CODE = L.SOVLCUR_TERM_CODE_ADMIT
											AND L.SOVLCUR_SEQNO = (SELECT MIN(L1.SOVLCUR_SEQNO) FROM ODSMGR.LOE_SOVLCUR L1
																			WHERE L1.SOVLCUR_PIDM = L.SOVLCUR_PIDM AND L1.SOVLCUR_LEVL_CODE = L.SOVLCUR_LEVL_CODE
																				AND L1.SOVLCUR_TERM_CODE_ADMIT = L.SOVLCUR_TERM_CODE_ADMIT AND L1.SOVLCUR_PROGRAM <> 'PDN-UG'
																				AND L1.SOVLCUR_LMOD_CODE = 'LEARNER' AND L1.SOVLCUR_CACT_CODE = 'ACTIVE')
		LEFT JOIN ODSMGR.LOE_SECTION_PART_OF_TERM M ON K.SOVLCUR_TERM_CODE = M.TERM_CODE
		LEFT JOIN ODSMGR.STVTERM M0 ON K.SOVLCUR_TERM_CODE = M0.STVTERM_CODE
		LEFT JOIN DOCUMENTO_IDENTIDAD N ON A.PERSON_UID = N.ENTITY_UID
		LEFT JOIN MAESTRIA_MOINTL O ON A.PERSON_UID = O.SOVLCUR_PIDM AND A.STUDENT_LEVEL = O.SOVLCUR_LEVL_CODE
		LEFT JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS P ON A.PERSON_UID = P.PERSON_UID AND A.PROGRAM = P.PROGRAM AND A.STUDENT_LEVEL = P.LEVL_CODE
															AND P.SEQUENCE_NUMBER = (SELECT MAX(P1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS P1
																						WHERE P1.PERSON_UID = P.PERSON_UID AND P1.PROGRAM = P.PROGRAM AND P1.LEVL_CODE = P.LEVL_CODE)
		LEFT JOIN ODSMGR.STUDENT_ATTRIBUTE Q ON A.PERSON_UID = Q.PERSON_UID AND A.ACADEMIC_PERIOD = Q.ACADEMIC_PERIOD AND Q.STUDENT_ATTRIBUTE IN ('BK18','FSMI','CONT')
		LEFT JOIN ODSMGR.LOE_EXEMPTION_STU_AUTHOR R ON A.PERSON_UID = R.TBBESTU_PIDM AND A.ACADEMIC_PERIOD = R.TBBESTU_TERM_CODE
														AND R.TBBESTU_SURROGATE_ID = (SELECT MAX(R1.TBBESTU_SURROGATE_ID) FROM ODSMGR.LOE_EXEMPTION_STU_AUTHOR R1
																						WHERE R1.TBBESTU_PIDM = R.TBBESTU_PIDM AND R1.TBBESTU_TERM_CODE = R.TBBESTU_TERM_CODE
																							AND SUBSTR(R1.TBBESTU_EXEMPTION_CODE,5,1) = '1' AND R1.TBBESTU_DEL_IND IS NULL)
		LEFT JOIN ODSMGR.LOE_EXEMPTION_DETAIL_LEVEL S ON R.TBBESTU_TERM_CODE = S.EXEMPTION_TERM AND R.TBBESTU_EXEMPTION_CODE = S.EXEMPTION_CODE AND SUBSTR(S.REGISTRATION_DETAIL_CODE,1,2) LIKE '%A'
		LEFT JOIN ODSMGR.LOE_TBBEXPT T ON R.TBBESTU_TERM_CODE = T.TBBEXPT_TERM_CODE AND R.TBBESTU_EXEMPTION_CODE = T.TBBEXPT_EXEMPTION_CODE
		LEFT JOIN ( SELECT DISTINCT TBBCSTU_STU_PIDM, TBBCSTU_CONTRACT_PIDM, TBBCSTU_CONTRACT_NUMBER, TBBCSTU_TERM_CODE, TBRCDET_PERCENT
					FROM ODSMGR.LOE_TBBCSTU, ODSMGR.TBRCDET
					WHERE TBBCSTU_CONTRACT_PIDM = TBRCDET_PIDM AND TBBCSTU_CONTRACT_NUMBER = TBRCDET_CONTRACT_NUMBER AND TBBCSTU_TERM_CODE = TBRCDET_TERM_CODE
						AND SUBSTR(TBRCDET_DETAIL_CODE,1,2) LIKE '%A' AND TBBCSTU_DEL_IND IS NULL
															) U ON Q.PERSON_UID = U.TBBCSTU_STU_PIDM AND Q.ACADEMIC_PERIOD = U.TBBCSTU_TERM_CODE
WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE')
	AND ((A.STUDENT_LEVEL ='UG' AND A.ACADEMIC_PERIOD IN ('221413','221513'))
		OR (A.STUDENT_LEVEL = 'EC' AND A.ACADEMIC_PERIOD = '221953' AND A.PROGRAM = 'MOINTL')/*
		OR (A.STUDENT_LEVEL = 'MA' AND A.ACADEMIC_PERIOD IN ('221813') AND (A.ACADEMIC_PERIOD = A.ACADEMIC_PERIOD_ADMITTED OR A.ACADEMIC_PERIOD_ADMITTED IS NULL))*/)
;
