
/*CODIGO_LOCAL, PERIODO_LECTIVO, TIPO_PERIODO, PERIODO_ACADEMICO, CODIGO_FACULTAD_UNIDAD, CODIGO_PROGRAMA, CAMBIO_PROGRAMA
	, CODIGO_PROGRAMA_ANTERIOR, FECHA_CAMBIO_PROGRAMA, TIPO_DOCUMENTO, NRO_DOCUMENTO, CODIGO_ESTUDIANTE, CICLO_ACADEMICO
	, MODALIDAD_ESTUDIO, FECHA_MATRICULA, CODIGO_ESCALA_PAGO, PORCENTAJE_DESCUENTO, TIENE_BECA, TIPO_BECA, OTRA_BECA, PORCENTAJE_CUBIERTO
*/

WITH PROGRAMA_ANTERIOR AS (
	SELECT DISTINCT A.SOVLCUR_PIDM, A.SOVLCUR_SEQNO, A.SOVLCUR_TERM_CODE, A.SOVLCUR_LEVL_CODE, A.SOVLCUR_USER_ID, A.SOVLCUR_ACTIVITY_DATE
	    , A.SOVLCUR_PROGRAM AS PROGRAMA_DESTINO, B.SOVLCUR_TERM_CODE AS PERIODO_ORIGEN, B.SOVLCUR_PROGRAM AS PROGRAMA_ORIGEN
	FROM ODSMGR.LOE_SOVLCUR A, ODSMGR.LOE_SOVLCUR B
	WHERE A.SOVLCUR_LMOD_CODE = 'LEARNER' AND A.SOVLCUR_CACT_CODE = 'ACTIVE' AND A.SOVLCUR_LEVL_CODE = 'UG'
	    AND A.SOVLCUR_PIDM = B.SOVLCUR_PIDM
	    AND B.SOVLCUR_SEQNO = ( SELECT MAX(B1.SOVLCUR_SEQNO) FROM ODSMGR.LOE_SOVLCUR B1
	                            WHERE B1.SOVLCUR_PIDM = B.SOVLCUR_PIDM AND SUBSTR(B1.SOVLCUR_PROGRAM,1,3) <> SUBSTR(A.SOVLCUR_PROGRAM,1,3)
	                                AND B1.SOVLCUR_SEQNO < A.SOVLCUR_SEQNO AND B1.SOVLCUR_TERM_CODE_END = A.SOVLCUR_TERM_CODE
	                                AND B1.SOVLCUR_LMOD_CODE = 'LEARNER'
	                                AND B1.SOVLCUR_CACT_CODE = 'ACTIVE'
	                                AND B1.SOVLCUR_LEVL_CODE = 'UG'
	                                AND B1.SOVLCUR_PROGRAM NOT LIKE '%PDN%' )
)
, DOCUMENTO_IDENTIDAD AS (
	SELECT ENTITY_UID, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'DNI' THEN ALTERNATIVE_ID END) AS DNI
		, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'PASS' THEN ALTERNATIVE_ID END) AS PASS
		, MAX(CASE WHEN ATERNATIVE_ID_TYPE = 'CNEX' THEN ALTERNATIVE_ID END) AS CNEX
	FROM ODSMGR.ALTERNATIVE_ID I
	WHERE ATERNATIVE_ID_TYPE IN ('DNI','PASS','CNEX')
		AND I.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(I1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ODSMGR.ALTERNATIVE_ID I1
												WHERE I1.ENTITY_UID = I.ENTITY_UID AND I1.ATERNATIVE_ID_TYPE IN ('DNI','PASS','CNEX'))
	GROUP BY ENTITY_UID
)
, MAESTRIA_MOINTL AS (
	SELECT STUD.SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, REGLA.MAESTRIA
	FROM ( SELECT DISTINCT SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, SOVLCUR_PROGRAM
			FROM ODSMGR.LOE_SOVLCUR 
			WHERE SOVLCUR_LMOD_CODE = 'LEARNER' AND SOVLCUR_CACT_CODE = 'ACTIVE'
				AND SOVLCUR_LEVL_CODE = 'EC'/* AND SOVLCUR_CURRENT_IND = 'N'*/ ) STUD
		, ( SELECT N.MAESTRIA, N.TERM_CODE_EFF, SUBSTR(O.AREA,1,6) AS DIPLOMADO
			FROM ( SELECT PROGRAM AS MAESTRIA, TERM_CODE_EFF
					FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY M
					WHERE PROGRAM <> SUBSTR(AREA,1,6) AND SUBSTR(PROGRAM,1,5) <> 'ING-C'
						AND M.TERM_CODE_EFF = (SELECT MAX(M1.TERM_CODE_EFF) FROM ODSMGR.LOE_PROGRAM_AREA_PRIORITY M1
												WHERE M1.PROGRAM = M.PROGRAM)
					GROUP BY PROGRAM, TERM_CODE_EFF
					HAVING COUNT(SUBSTR(AREA,1,6)) = 2 ) N
				, ODSMGR.LOE_PROGRAM_AREA_PRIORITY O
			WHERE N.MAESTRIA = O.PROGRAM AND N.TERM_CODE_EFF = O.TERM_CODE_EFF AND N.MAESTRIA <> SUBSTR(O.AREA,1,6) ) REGLA
	WHERE STUD.SOVLCUR_PROGRAM = REGLA.DIPLOMADO
	GROUP BY STUD.SOVLCUR_PIDM, SOVLCUR_LEVL_CODE, REGLA.MAESTRIA
	HAVING COUNT(STUD.SOVLCUR_PROGRAM) = 2
)
SELECT DISTINCT A.PERSON_UID, A.ID, A.STUDENT_LEVEL, CASE WHEN H.MAESTRIA IS NOT NULL THEN A.PROGRAM ||' - '|| H.MAESTRIA ELSE A.PROGRAM END AS PROGRAMA
	, CASE
		WHEN G.DNI IS NOT NULL THEN 'DNI - ' || G.DNI
		WHEN G.PASS IS NOT NULL THEN 'PASS - ' || G.PASS
		WHEN G.CNEX IS NOT NULL THEN 'CNEX - ' || G.CNEX
		ELSE NULL END AS DOCUMENTO_IDENTIDAD
	, CASE
		WHEN J.STUDENT_ATTRIBUTE = 'BK18' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		WHEN K.TBBESTU_PIDM IS NOT NULL AND L.EXEMPTION_CODE IS NOT NULL THEN L.EXEMPTION_CODE ||' - '|| M.TBBEXPT_DESC
		WHEN J.STUDENT_ATTRIBUTE = 'FSMI' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		WHEN J.STUDENT_ATTRIBUTE = 'CONT' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN NULL
		ELSE NULL END AS BECA, 
	CASE A.CAMPUS
		WHEN 'TML' THEN (CASE
				WHEN A.STUDENT_LEVEL IN ('EC','MA') OR A.PROGRAM IN ('ABF-UG','ABF-WA','ENI-UG','ENI-WA')
					THEN 'SL02'
				ELSE 'SL01' END)
		WHEN 'TSI' THEN 'SL03'
		WHEN 'CAJ' THEN 'F01L01'
		WHEN 'LN0' THEN (CASE
				WHEN (CASE WHEN A.PROGRAM = 'MOINTL' THEN H.MAESTRIA ELSE A.PROGRAM END)
						IN ('MIAEMI','DGTHMI','ENF-UG','ENF-WA','NUT-UG','NUT-WA','OBS-UG','OBS-WA','PSI-UG','PSI-WA','TFI-UG','TFI-WA')
					THEN 'F02L03'
				ELSE 'F02L01' END)
		WHEN 'LC0' THEN 'F02L02'
		WHEN 'LE0' THEN 'F02L04'
		WHEN 'LN1' THEN 'F02L05'
		WHEN 'LS0' THEN 'F02L06'
		ELSE NULL END AS CODIGO_LOCAL
	, 1 AS PERIODO_LECTIVO, 1 AS TIPO_PERIODO
	, CASE
		WHEN A.STUDENT_LEVEL IN ('EC','MA') THEN SUBSTR(D.STVTERM_DESC,1,4)
		ELSE SUBSTR(D.STVTERM_DESC,1,6) END AS PERIODO_ACADEMICO
	, CASE A.COLLEGE
		WHEN 'AR' THEN 15
		WHEN 'SA' THEN 11
		WHEN 'CO' THEN 9
		WHEN 'DE' THEN 8
		WHEN 'IN' THEN 5
		WHEN 'NE' THEN 3
		WHEN 'GR' THEN 18
		ELSE 1 END AS CODIGO_FACULTAD_UNIDAD
	, CASE (CASE WHEN A.PROGRAM = 'MOINTL' THEN H.MAESTRIA ELSE A.PROGRAM END)
		WHEN 'ADM-EA' THEN 1
		WHEN 'ADM-FS' THEN 1
		WHEN 'ADM-UG' THEN 1
		WHEN 'ADM-WA' THEN 1
		WHEN 'ABF-UG' THEN 20
		WHEN 'ABF-WA' THEN 20
		WHEN 'AGC-UG' THEN 2
		WHEN 'AGC-WA' THEN 2
		WHEN 'AGT-WA' THEN 21
		WHEN 'AGT-UG' THEN 21
		WHEN 'GPU-WA' THEN 22
		WHEN 'GPU-UG' THEN 22
		WHEN 'AMK-UG' THEN 3
		WHEN 'AMK-WA' THEN 3
		WHEN 'ANI-UG' THEN 4
		WHEN 'ANI-WA' THEN 4
		WHEN 'AST-UG' THEN 5
		WHEN 'AST-WA' THEN 5
		WHEN 'ARQ-UG' THEN 58
		WHEN 'ARQ-WA' THEN 58
		WHEN 'ADI-UG' THEN 6
		WHEN 'ADI-WA' THEN 6
		WHEN 'AGP-UG' THEN 59
		WHEN 'AGP-WA' THEN 59
		WHEN 'AUR-UG' THEN 7
		WHEN 'AUR-WA' THEN 7
		WHEN 'CCO-UG' THEN 60
		WHEN 'CCO-WA' THEN 60
		WHEN 'COM-UG' THEN 23
		WHEN 'COM-WA' THEN 23
		WHEN 'CAM-UG' THEN 8
		WHEN 'CAM-WA' THEN 8
		WHEN 'CCR-UG' THEN 24
		WHEN 'CCR-WA' THEN 24
		WHEN 'CDG-UG' THEN 25
		WHEN 'CDG-WA' THEN 25
		WHEN 'CPE-UG' THEN 9
		WHEN 'CPE-WA' THEN 9
		WHEN 'CPU-UG' THEN 10
		WHEN 'CPU-WA' THEN 10
		WHEN 'CON-UG' THEN 11
		WHEN 'CON-WA' THEN 11
		WHEN 'DEH-WA' THEN 12
		WHEN 'DEH-UG' THEN 12
		WHEN 'DER-WA' THEN 62
		WHEN 'DER-UG' THEN 62
		WHEN 'DIN-UG' THEN 26
		WHEN 'DIN-WA' THEN 26
		WHEN 'DEREPD' THEN 28
		WHEN 'ECO-UG' THEN 29
		WHEN 'ECO-WA' THEN 29
		WHEN 'ENI-UG' THEN 30
		WHEN 'ENI-WA' THEN 30
		WHEN 'EDG-UG' THEN 31
		WHEN 'EDG-WA' THEN 31
		WHEN 'ENF-UG' THEN 32
		WHEN 'ENF-WA' THEN 32
		WHEN 'GGR-UG' THEN 33
		WHEN 'GGR-WA' THEN 33
		WHEN 'AGR-UG' THEN 34
		WHEN 'AGR-WA' THEN 34
		WHEN 'AMB-UG' THEN 13
		WHEN 'AMB-WA' THEN 13
		WHEN 'CIV-UG' THEN 14
		WHEN 'CIV-WA' THEN 14
		WHEN 'MIN-UG' THEN 35
		WHEN 'MIN-WA' THEN 35
		WHEN 'SIS-EA' THEN 63
		WHEN 'SIS-FS' THEN 63
		WHEN 'SIS-UG' THEN 63
		WHEN 'SIS-WA' THEN 63
		WHEN 'SIC-WA' THEN 15
		WHEN 'SIC-UG' THEN 15
		WHEN 'ELE-UG' THEN 36
		WHEN 'ELE-WA' THEN 36
		WHEN 'EMP-UG' THEN 16
		WHEN 'EMP-WA' THEN 16
		WHEN 'GEO-UG' THEN 38
		WHEN 'GEO-WA' THEN 38
		WHEN 'IND-FS' THEN 17
		WHEN 'IND-EA' THEN 17
		WHEN 'IND-UG' THEN 17
		WHEN 'IND-WA' THEN 17
		WHEN 'ILT-UG' THEN 37
		WHEN 'ILT-WA' THEN 37
		WHEN 'MCT-UG' THEN 39
		WHEN 'MCT-WA' THEN 39
		WHEN 'MEAEPM' THEN 40
		WHEN 'DEREPM' THEN 43
		WHEN 'DCGEPM' THEN 43
		WHEN 'DOCAPM' THEN 44
		WHEN 'DGIEPM' THEN 45
		WHEN 'DGTHPM' THEN 46
		WHEN 'FICOPM' THEN 49
		WHEN 'GMGCPM' THEN 50
		WHEN 'GARCPM' THEN 51
		WHEN 'GEPUPM' THEN 53
		WHEN 'INSIPM' THEN 54
		WHEN 'MKNIPM' THEN 55
		WHEN 'MIAEMI' THEN 42
		WHEN 'LMBAPM' THEN 41
		WHEN 'NUT-WA' THEN 18
		WHEN 'NUT-UG' THEN 18
		WHEN 'OBS-UG' THEN 56
		WHEN 'OBS-WA' THEN 56
		WHEN 'PSI-UG' THEN 19
		WHEN 'PSI-WA' THEN 19
		WHEN 'TFI-UG' THEN 57
		WHEN 'TFI-WA' THEN 57
		WHEN 'MKT-UG' THEN 64
		WHEN 'MKT-WA' THEN 64
		ELSE 999999 END AS CODIGO_PROGRAMA
	, CASE WHEN E.SOVLCUR_PIDM IS NOT NULL THEN 1 ELSE 0 END AS CAMBIO_PROGRAMA
	, CASE WHEN E.SOVLCUR_PIDM IS NOT NULL THEN (
		CASE E.PROGRAMA_ORIGEN
			WHEN 'ADM-EA' THEN 1
			WHEN 'ADM-FS' THEN 1
			WHEN 'ADM-UG' THEN 1
			WHEN 'ADM-WA' THEN 1
			WHEN 'ABF-UG' THEN 20
			WHEN 'ABF-WA' THEN 20
			WHEN 'AGC-UG' THEN 2
			WHEN 'AGC-WA' THEN 2
			WHEN 'AGT-WA' THEN 21
			WHEN 'AGT-UG' THEN 21
			WHEN 'GPU-WA' THEN 22
			WHEN 'GPU-UG' THEN 22
			WHEN 'AMK-UG' THEN 3
			WHEN 'AMK-WA' THEN 3
			WHEN 'ANI-UG' THEN 4
			WHEN 'ANI-WA' THEN 4
			WHEN 'AST-UG' THEN 5
			WHEN 'AST-WA' THEN 5
			WHEN 'ARQ-UG' THEN 58
			WHEN 'ARQ-WA' THEN 58
			WHEN 'ADI-UG' THEN 6
			WHEN 'ADI-WA' THEN 6
			WHEN 'AGP-UG' THEN 59
			WHEN 'AGP-WA' THEN 59
			WHEN 'AUR-UG' THEN 7
			WHEN 'AUR-WA' THEN 7
			WHEN 'CCO-UG' THEN 60
			WHEN 'CCO-WA' THEN 60
			WHEN 'COM-UG' THEN 23
			WHEN 'COM-WA' THEN 23
			WHEN 'CAM-UG' THEN 8
			WHEN 'CAM-WA' THEN 8
			WHEN 'CCR-UG' THEN 24
			WHEN 'CCR-WA' THEN 24
			WHEN 'CDG-UG' THEN 25
			WHEN 'CDG-WA' THEN 25
			WHEN 'CPE-UG' THEN 9
			WHEN 'CPE-WA' THEN 9
			WHEN 'CPU-UG' THEN 10
			WHEN 'CPU-WA' THEN 10
			WHEN 'CON-UG' THEN 11
			WHEN 'CON-WA' THEN 11
			WHEN 'DEH-WA' THEN 12
			WHEN 'DEH-UG' THEN 12
			WHEN 'DER-WA' THEN 62
			WHEN 'DER-UG' THEN 62
			WHEN 'DIN-UG' THEN 26
			WHEN 'DIN-WA' THEN 26
			WHEN 'DEREPD' THEN 28
			WHEN 'ECO-UG' THEN 29
			WHEN 'ECO-WA' THEN 29
			WHEN 'ENI-UG' THEN 30
			WHEN 'ENI-WA' THEN 30
			WHEN 'EDG-UG' THEN 31
			WHEN 'EDG-WA' THEN 31
			WHEN 'ENF-UG' THEN 32
			WHEN 'ENF-WA' THEN 32
			WHEN 'GGR-UG' THEN 33
			WHEN 'GGR-WA' THEN 33
			WHEN 'AGR-UG' THEN 34
			WHEN 'AGR-WA' THEN 34
			WHEN 'AMB-UG' THEN 13
			WHEN 'AMB-WA' THEN 13
			WHEN 'CIV-UG' THEN 14
			WHEN 'CIV-WA' THEN 14
			WHEN 'MIN-UG' THEN 35
			WHEN 'MIN-WA' THEN 35
			WHEN 'SIS-EA' THEN 63
			WHEN 'SIS-FS' THEN 63
			WHEN 'SIS-UG' THEN 63
			WHEN 'SIS-WA' THEN 63
			WHEN 'SIC-WA' THEN 15
			WHEN 'SIC-UG' THEN 15
			WHEN 'ELE-UG' THEN 36
			WHEN 'ELE-WA' THEN 36
			WHEN 'EMP-UG' THEN 16
			WHEN 'EMP-WA' THEN 16
			WHEN 'GEO-UG' THEN 38
			WHEN 'GEO-WA' THEN 38
			WHEN 'IND-FS' THEN 17
			WHEN 'IND-EA' THEN 17
			WHEN 'IND-UG' THEN 17
			WHEN 'IND-WA' THEN 17
			WHEN 'ILT-UG' THEN 37
			WHEN 'ILT-WA' THEN 37
			WHEN 'MCT-UG' THEN 39
			WHEN 'MCT-WA' THEN 39
			WHEN 'MEAEPM' THEN 40
			WHEN 'DEREPM' THEN 43
			WHEN 'DCGEPM' THEN 43
			WHEN 'DOCAPM' THEN 44
			WHEN 'DGIEPM' THEN 45
			WHEN 'DGTHPM' THEN 46
			WHEN 'FICOPM' THEN 49
			WHEN 'GMGCPM' THEN 50
			WHEN 'GARCPM' THEN 51
			WHEN 'GEPUPM' THEN 53
			WHEN 'INSIPM' THEN 54
			WHEN 'MKNIPM' THEN 55
			WHEN 'MIAEMI' THEN 42
			WHEN 'LMBAPM' THEN 41
			WHEN 'NUT-WA' THEN 18
			WHEN 'NUT-UG' THEN 18
			WHEN 'OBS-UG' THEN 56
			WHEN 'OBS-WA' THEN 56
			WHEN 'PSI-UG' THEN 19
			WHEN 'PSI-WA' THEN 19
			WHEN 'TFI-UG' THEN 57
			WHEN 'TFI-WA' THEN 57
			WHEN 'MKT-UG' THEN 64
			WHEN 'MKT-WA' THEN 64
			ELSE 999999 END
		) ELSE NULL END AS CODIGO_PROGRAMA_ANTERIOR
	, TO_CHAR(COALESCE(F.START_DATE,F0.STVTERM_START_DATE),'DD/MM/YYYY') AS FECHA_CAMBIO_PROGRAMA
	, CASE
		WHEN G.DNI IS NOT NULL AND LENGTH(G.DNI) < 9 THEN 1
		WHEN G.PASS IS NOT NULL AND LENGTH(G.PASS) < 19 THEN 2
		WHEN G.CNEX IS NOT NULL AND LENGTH(G.CNEX) < 19 THEN 3
		ELSE NULL END AS TIPO_DOCUMENTO
	, CASE
		WHEN G.DNI IS NOT NULL AND LENGTH(G.DNI) < 9 THEN G.DNI
		WHEN G.PASS IS NOT NULL AND LENGTH(G.PASS) < 19 THEN G.PASS
		WHEN G.CNEX IS NOT NULL AND LENGTH(G.CNEX) < 19 THEN G.CNEX
		ELSE NULL END AS NRO_DOCUMENTO
	, A.ID AS CODIGO_ESTUDIANTE
	, NVL(ROUND(I.ACT_CREDITS_OVERALL/20,0),0) +1 AS CICLO_ACADEMICO
	, 1 AS MODALIDAD_ESTUDIO
	, TO_CHAR(MIN(B0.SECTION_ADD_DATE) OVER(PARTITION BY B0.PERSON_UID, B0.ACADEMIC_PERIOD),'DD/MM/YYYY') AS FECHA_MATRICULA
	, NULL AS CODIGO_ESCALA_PAGO, NULL AS PORCENTAJE_DESCUENTO
	, CASE WHEN (J.PERSON_UID IS NOT NULL AND N.TBBCSTU_STU_PIDM IS NOT NULL) OR (K.TBBESTU_PIDM IS NOT NULL AND L.EXEMPTION_CODE IS NOT NULL) THEN 1 ELSE 0 END AS TIENE_BECA
	, CASE
		WHEN J.STUDENT_ATTRIBUTE = 'BK18' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN 1
		WHEN K.TBBESTU_PIDM IS NOT NULL AND L.EXEMPTION_CODE IS NOT NULL THEN 2
		WHEN J.STUDENT_ATTRIBUTE IN ('FSMI','CONT') AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN 3
		ELSE NULL END AS TIPO_BECA
	, CASE
		WHEN (J.STUDENT_ATTRIBUTE = 'BK18' AND N.TBBCSTU_STU_PIDM IS NOT NULL) OR K.TBBESTU_PIDM IS NOT NULL THEN NULL
		WHEN J.STUDENT_ATTRIBUTE = 'FSMI' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN 'FONDO SOCIAL MICHIQUILLAY'
		WHEN J.STUDENT_ATTRIBUTE = 'CONT' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN 'CONTRATOS EMPRESAS'
		ELSE NULL END AS OTRA_BECA
	, CASE
		WHEN J.STUDENT_ATTRIBUTE = 'BK18' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN N.TBRCDET_PERCENT
		WHEN K.TBBESTU_PIDM IS NOT NULL AND L.EXEMPTION_CODE IS NOT NULL THEN L.CHARGE_PERCENTAGE
		WHEN J.STUDENT_ATTRIBUTE = 'FSMI' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN N.TBRCDET_PERCENT
		WHEN J.STUDENT_ATTRIBUTE = 'CONT' AND N.TBBCSTU_STU_PIDM IS NOT NULL THEN N.TBRCDET_PERCENT
		ELSE NULL END AS PORCENTAJE_CUBIERTO
FROM ODSMGR.ACADEMIC_STUDY A
		INNER JOIN ODSMGR.STUDENT_COURSE B ON A.PERSON_UID = B.PERSON_UID AND A.ACADEMIC_PERIOD = B.ACADEMIC_PERIOD
												AND B.TRANSFER_COURSE_IND = 'N' AND B.REGISTRATION_STATUS IN ('RE','RW','RA','WC','RF','RO')
		LEFT JOIN ODSMGR.STUDENT_COURSE_REG_AUDIT B0 ON A.PERSON_UID = B0.PERSON_UID AND A.ACADEMIC_PERIOD = B0.ACADEMIC_PERIOD AND B0.REGISTRATION_SOURCE = 'BASE'
		LEFT JOIN ODSMGR.LOE_SOVLCUR C ON A.PERSON_UID = C.SOVLCUR_PIDM AND A.STUDENT_LEVEL = C.SOVLCUR_LEVL_CODE --AND C.SOVLCUR_TERM_CODE_ADMIT IS NOT NULL
											AND C.SOVLCUR_TERM_CODE_ADMIT = (SELECT MIN(C1.SOVLCUR_TERM_CODE_ADMIT) FROM ODSMGR.LOE_SOVLCUR C1
																			WHERE C1.SOVLCUR_PIDM = C.SOVLCUR_PIDM AND C1.SOVLCUR_LEVL_CODE = C.SOVLCUR_LEVL_CODE
																				AND C1.SOVLCUR_TERM_CODE_ADMIT IS NOT NULL AND C1.SOVLCUR_LMOD_CODE = 'LEARNER' AND C1.SOVLCUR_CACT_CODE = 'ACTIVE')
		LEFT JOIN ODSMGR.STVTERM D ON A.ACADEMIC_PERIOD = D.STVTERM_CODE
		LEFT JOIN PROGRAMA_ANTERIOR E ON A.PERSON_UID = E.SOVLCUR_PIDM AND A.STUDENT_LEVEL = E.SOVLCUR_LEVL_CODE AND A.PROGRAM = E.PROGRAMA_DESTINO
											AND E.SOVLCUR_SEQNO = (SELECT MAX(E1.SOVLCUR_SEQNO) FROM PROGRAMA_ANTERIOR E1
																	WHERE E1.SOVLCUR_PIDM = E.SOVLCUR_PIDM AND E1.SOVLCUR_LEVL_CODE = E.SOVLCUR_LEVL_CODE
																		AND ((SUBSTR(E1.PROGRAMA_DESTINO,4,3) = '-UG' AND E1.SOVLCUR_TERM_CODE <= '220413')
																				OR (SUBSTR(E1.PROGRAMA_DESTINO,4,3) = '-WA' AND E1.SOVLCUR_TERM_CODE <= '220513'))
																		AND E1.PROGRAMA_DESTINO = E.PROGRAMA_DESTINO)
		LEFT JOIN ODSMGR.LOE_SECTION_PART_OF_TERM F ON E.SOVLCUR_TERM_CODE = F.TERM_CODE
		LEFT JOIN ODSMGR.STVTERM F0 ON E.SOVLCUR_TERM_CODE = F0.STVTERM_CODE
		LEFT JOIN DOCUMENTO_IDENTIDAD G ON A.PERSON_UID = G.ENTITY_UID
		LEFT JOIN MAESTRIA_MOINTL H ON A.PERSON_UID = H.SOVLCUR_PIDM AND A.STUDENT_LEVEL = H.SOVLCUR_LEVL_CODE		
		LEFT JOIN ODSMGR.LOE_PROGRAM_OVERALL_RESULTS I ON A.PERSON_UID = I.PERSON_UID AND A.PROGRAM = I.PROGRAM AND A.STUDENT_LEVEL = I.LEVL_CODE
															AND I.SEQUENCE_NUMBER = (SELECT MAX(G1.SEQUENCE_NUMBER) FROM ODSMGR.LOE_PROGRAM_OVERALL_RESULTS G1
																						WHERE G1.PERSON_UID = I.PERSON_UID AND G1.PROGRAM = I.PROGRAM AND G1.LEVL_CODE = I.LEVL_CODE)
		LEFT JOIN ODSMGR.STUDENT_ATTRIBUTE J ON A.PERSON_UID = J.PERSON_UID AND A.ACADEMIC_PERIOD = J.ACADEMIC_PERIOD AND J.STUDENT_ATTRIBUTE IN ('BK18','FSMI','CONT')
		LEFT JOIN ODSMGR.LOE_EXEMPTION_STU_AUTHOR K ON A.PERSON_UID = K.TBBESTU_PIDM AND A.ACADEMIC_PERIOD = K.TBBESTU_TERM_CODE --AND SUBSTR(K.TBBESTU_EXEMPTION_CODE,5,1) = '1' AND K.TBBESTU_DEL_IND IS NULL
														AND K.TBBESTU_SURROGATE_ID = (SELECT MAX(K1.TBBESTU_SURROGATE_ID) FROM ODSMGR.LOE_EXEMPTION_STU_AUTHOR K1
																						WHERE K1.TBBESTU_PIDM = K.TBBESTU_PIDM AND K1.TBBESTU_TERM_CODE = K.TBBESTU_TERM_CODE
																							AND SUBSTR(K1.TBBESTU_EXEMPTION_CODE,5,1) = '1' AND K1.TBBESTU_DEL_IND IS NULL)
		LEFT JOIN ODSMGR.LOE_EXEMPTION_DETAIL_LEVEL L ON K.TBBESTU_TERM_CODE = L.EXEMPTION_TERM AND K.TBBESTU_EXEMPTION_CODE = L.EXEMPTION_CODE AND SUBSTR(L.REGISTRATION_DETAIL_CODE,1,2) LIKE '%A'
		LEFT JOIN ODSMGR.LOE_TBBEXPT M ON K.TBBESTU_TERM_CODE = M.TBBEXPT_TERM_CODE AND K.TBBESTU_EXEMPTION_CODE = M.TBBEXPT_EXEMPTION_CODE
		LEFT JOIN ( SELECT DISTINCT TBBCSTU_STU_PIDM, TBBCSTU_CONTRACT_PIDM, TBBCSTU_CONTRACT_NUMBER, TBBCSTU_TERM_CODE, TBRCDET_PERCENT
					FROM ODSMGR.LOE_TBBCSTU, ODSMGR.TBRCDET
					WHERE TBBCSTU_CONTRACT_PIDM = TBRCDET_PIDM AND TBBCSTU_CONTRACT_NUMBER = TBRCDET_CONTRACT_NUMBER AND TBBCSTU_TERM_CODE = TBRCDET_TERM_CODE
						AND SUBSTR(TBRCDET_DETAIL_CODE,1,2) LIKE '%A' AND TBBCSTU_DEL_IND IS NULL 
															) N ON J.PERSON_UID = N.TBBCSTU_STU_PIDM AND J.ACADEMIC_PERIOD = N.TBBCSTU_TERM_CODE
WHERE A.ENROLLMENT_STATUS IN ('EL','RF','RO','SE')
	AND ((A.STUDENT_LEVEL ='UG' AND A.ACADEMIC_PERIOD IN ('220413','220513'))
		OR (A.STUDENT_LEVEL = 'EC' AND A.ACADEMIC_PERIOD = '220953' AND A.PROGRAM = 'MOINTL')
		OR (A.STUDENT_LEVEL = 'MA' AND A.ACADEMIC_PERIOD IN ('218816','219813','219839','220813') AND (A.ACADEMIC_PERIOD = A.ACADEMIC_PERIOD_ADMITTED OR A.ACADEMIC_PERIOD_ADMITTED IS NULL)))
;
