SELECT DISTINCT h.* FROM
(SELECT DISTINCT
    g.PERSON_UID, g.ID, g.NAME, g.HOLD, g.HOLD_DESC, g.HOLD_USER_CREATOR, g.HOLD_FROM_DATE, g.HOLD_TO_DATE, g.ACTIVE_HOLD_IND
    , g.PO_REF, g.INVOICE, g.BILL_STATUS, g.ITEM_STATUS, g.BILL_TYPE_ID, g.INVOICE_AMOUNT, g.INVOICE_DT--, g.LINE_SEQ_NUM, g.DESCR, g.NET_EXTENDED_AMT
FROM
    (SELECT DISTINCT
        a.PERSON_UID, a.ID, a.NAME, a.HOLD, a.HOLD_DESC, a.HOLD_USER_CREATOR, a.HOLD_FROM_DATE, a.HOLD_TO_DATE, a.ACTIVE_HOLD_IND
        , f.PO_REF, f.INVOICE, f.BILL_STATUS, f.ITEM_STATUS, f.BILL_TYPE_ID, f.INVOICE_AMOUNT, f.INVOICE_DT, f.LINE_SEQ_NUM, f.DESCR, f.NET_EXTENDED_AMT, f.CARGO, f.ADD_DTTM
        , MAX(f.ADD_DTTM) OVER (PARTITION BY f.PO_REF, f.CARGO) AS MAX_ADD_DTTM
    FROM HOLD a
        ,(SELECT 
          b.BUSINESS_UNIT, 
          b.INVOICE, 
          b.BILL_TO_CUST_ID, 
          b.BILL_STATUS, 
          d.ITEM_STATUS, 
          b.BILL_TYPE_ID, 
          b.NAME1, 
          b.INVOICE_AMOUNT, 
          b.INVOICE_DT, 
          b.PO_REF, 
          b.ADD_DTTM, 
          c.LINE_SEQ_NUM, 
          c.DESCR, 
          c.NET_EXTENDED_AMT, 
          NVL(
          MAX(CASE 
                  WHEN UPPER(c.DESCR) LIKE '%CUOTA%INI%' OR UPPER(c.DESCR) LIKE '%CUOTA 0%' OR UPPER(c.DESCR) LIKE '%CUOTA 1%' THEN 'T1'
              ELSE NULL END) OVER (PARTITION BY b.INVOICE) --AS TIPO_CARGO,
          ,MAX(CASE (CASE WHEN e.TEXT254 like '%EXEMPTION/CROSS_REF:%' THEN SUBSTR(e.TEXT254,LENGTH(e.TEXT254)-3,2) ELSE NULL END) 
                  WHEN 'X1' THEN 'T1' 
                  WHEN 'Y1' THEN 'T1' 
                  WHEN 'Z1' THEN 'T1' 
                  ELSE (CASE WHEN e.TEXT254 like '%EXEMPTION/CROSS_REF:%' THEN SUBSTR(e.TEXT254,LENGTH(e.TEXT254)-3,2) ELSE NULL END) 
              END) OVER (PARTITION BY b.INVOICE) --AS CARGO_ORIGEN
          ) AS CARGO
          FROM 
          ((PS_BI_HDR b
              INNER JOIN PS_BI_LINE c ON
                  b.BUSINESS_UNIT = c.BUSINESS_UNIT AND
                  b.INVOICE = c.INVOICE)
              LEFT JOIN PS_ITEM d ON
                  b.BUSINESS_UNIT = d.BUSINESS_UNIT AND
                  b.INVOICE = d.ITEM)
              LEFT JOIN PS_BI_LINE_NOTE e ON
                  b.BUSINESS_UNIT = e.BUSINESS_UNIT AND
                  b.INVOICE = e.INVOICE AND
                  c.LINE_SEQ_NUM = e.LINE_SEQ_NUM AND
                  CASE WHEN e.TEXT254 like '%EXEMPTION/CROSS_REF:%' THEN SUBSTR(e.TEXT254,LENGTH(e.TEXT254)-3,2) ELSE NULL END IN ('T1','X1','Y1','Z1')
          WHERE 
          b.BUSINESS_UNIT = 'PER03' 
          AND b.BILL_STATUS IN ('INV','NEW')
          AND b.BILLING_FREQUENCY = 'ONC') f
    WHERE a.HOLD = 'C1' AND a.ACTIVE_HOLD_IND = 'Y'
        AND a.ID = f.BILL_TO_CUST_ID AND SUBSTR(a.HOLD_EXPLANATION,1,6) = f.PO_REF AND f.CARGO IS NOT NULL
        AND SUBSTR(a.HOLD_EXPLANATION,1,6) IN ('218533','218434','219413','219513')) g --INGRESAR PERIODO
WHERE g.ADD_DTTM = g.MAX_ADD_DTTM) h
WHERE h.BILL_TYPE_ID IN ('B1','F1') AND h.ITEM_STATUS = 'C';
