SELECT DISTINCT A.ADMISSIONS_POPULATION, A.ADMISSIONS_POPULATION_DESC, A.PERSON_UID, A.ID, A.NAME
    , CASE 
        WHEN A.STUDENT_POPULATION = 'N' THEN 'NUEVO' 
        WHEN A.STUDENT_POPULATION = 'C' AND D.COHORT = 'REINGRESO' THEN 'REINGRESO'
        WHEN A.STUDENT_POPULATION = 'C' AND D.COHORT = 'NEW_REING' THEN 'NUEVO REINGRESO'
        ELSE 'CONTINUO' END AS TIPO_ESTUDIANTE
    , ATERNATIVE_ID_TYPE AS TIPO_DOCUMENTO, ALTERNATIVE_ID AS NRO_DOCUMENTO, CASE SPBPERS_SEX WHEN 'M' THEN 'Masculino' WHEN 'F' THEN 'Femenino' ELSE NULL END AS GENERO
	, NULL AS MOTIVO_TRASLADO, SHRTRIT_SBGI_CODE AS COD_INSTITUCION_ORIGEN, STVSBGI_DESC AS INSTITUCION_ORIGEN
	, CASE STVSBGI_TYPE_IND WHEN 'C' THEN 'UNIVERSIDAD' WHEN 'H' THEN 'INSTITUTO' ELSE STVSBGI_TYPE_IND END AS TIPO_INSTITUCION, SHRTRAM_ATTN_PERIOD AS PERIODO_MATRICULA_ORIGEN
	, A.ACADEMIC_PERIOD_ADMITTED AS PERIODO_MATRICULA_UPN, A.CAMPUS_DESC AS SEDE, TRIM(CONCAT(CONCAT(STVSITE_STREET_ADDR1,' '),STVSITE_STREET_ADDR2)) AS DIRECCION
	, SUBSTR(STVSITE_CITY,INSTR(STVSITE_CITY,'/',1,1)+1,INSTR(STVSITE_CITY,'/',1,2)-INSTR(STVSITE_CITY,'/',1,1)-1) AS REGION, A.COLLEGE_DESC AS FACULTAD
	, A.PROGRAM_DESC AS PROGRAMA, 'Pregrado' AS NIVEL, 'Presencial' AS MODALIDAD
FROM ACADEMIC_STUDY A
        INNER JOIN STUDENT_COURSE C ON A.PERSON_UID = C.PERSON_UID AND A.ACADEMIC_PERIOD = C.ACADEMIC_PERIOD
        LEFT JOIN STUDENT_COHORT D ON A.PERSON_UID = D.PERSON_UID AND A.ACADEMIC_PERIOD = D.ACADEMIC_PERIOD AND D.COHORT IN ('REINGRESO','NEW_REING')
		LEFT JOIN STVSITE ON A.CAMPUS = STVSITE_CODE
		LEFT JOIN ALTERNATIVE_ID B ON A.PERSON_UID = B.ENTITY_UID AND B.ATERNATIVE_ID_TYPE = 'DNI'
				AND B.ALTERNATIVE_ID_ACTIVITY_DATE = (SELECT MAX(B1.ALTERNATIVE_ID_ACTIVITY_DATE) FROM ALTERNATIVE_ID B1
													WHERE B1.ENTITY_UID = A.PERSON_UID AND B1.ATERNATIVE_ID_TYPE = 'DNI')
		LEFT JOIN SPBPERS ON A.PERSON_UID = SPBPERS_PIDM
		LEFT JOIN SHRTRIT ON A.PERSON_UID = SHRTRIT_PIDM
		LEFT JOIN STVSBGI ON SHRTRIT_SBGI_CODE = STVSBGI_CODE
		LEFT JOIN SHRTRAM ON SHRTRIT_PIDM = SHRTRAM_PIDM AND SHRTRIT_SEQ_NO = SHRTRAM_TRIT_SEQ_NO
WHERE A.ADMISSIONS_POPULATION = 'TE' AND A.STUDENT_LEVEL = 'UG' AND A.ACADEMIC_PERIOD IN ('220413','220513');