--BASADO EN LA QUERY PS: PER_AR_CTA_CORRIENTE_CAJA_V14
SELECT TO_CHAR(ADD_DTTM,'DD/MM/YYYY') AS FECHA, DRAWER_ID AS CAJA, MAX(RECON_ID) AS CONCILIACION/*, MEDIO_PAGO, TIPO_TARJETA*/, CURRENCY_CD, SUM(IMPORTE) AS MONTO
FROM (

--QUERY01
SELECT 
    A.DEPOSIT_BU, A.RECEIPT_NBR, A.DRAWER_ID, A.RECON_ID, A.ADD_DTTM, A.BILL_TO_CUST_ID
    , CASE WHEN G.PAYMENT_METHOD_CDR = 'CC' THEN G.PAYMENT_METHOD_CDR || ' - CREDIT CARD'            
            WHEN G.PAYMENT_METHOD_CDR = 'CSH' THEN G.PAYMENT_METHOD_CDR || ' - CASH'
            WHEN G.PAYMENT_METHOD_CDR = 'CV' THEN G.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
            WHEN G.PAYMENT_METHOD_CDR = 'DC' THEN G.PAYMENT_METHOD_CDR || ' - DEBIT CARD'
            WHEN G.PAYMENT_METHOD_CDR = 'PC' THEN G.PAYMENT_METHOD_CDR || ' - PROCURENMENT CARD'
        ELSE G.PAYMENT_METHOD_CDR END AS MEDIO_PAGO
    , CASE WHEN G.CR_CARD_TYPE = '01' OR G.CR_CARD_TYPE = 'V' THEN 'VISA'
            WHEN G.CR_CARD_TYPE = '02' OR G.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
            WHEN G.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
            WHEN G.CR_CARD_TYPE = '04' OR G.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
            WHEN G.CR_CARD_TYPE = ' ' AND G.PAYMENT_METHOD_CDR = 'CSH' THEN G.PAYMENT_METHOD_CDR || ' - CASH'
            WHEN G.CR_CARD_TYPE = ' ' AND G.PAYMENT_METHOD_CDR = 'CV' THEN G.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
        ELSE G.CR_CARD_TYPE END AS TIPO_TARJETA
    , CASE WHEN G.CR_CARD_TYPE = '01' OR G.CR_CARD_TYPE = 'V' THEN 'VISA'
            WHEN G.CR_CARD_TYPE = '02' OR G.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
            WHEN G.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
            WHEN G.CR_CARD_TYPE = '04' OR G.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
        ELSE G.CR_CARD_TYPE END AS NRO_TARJETA
    , A.CURRENCY_CD
    , CASE WHEN U.PAYMENT_METHOD_CDR = 'CV' THEN U.BNK_ID_NBR ELSE V.BNK_ID_NBR END AS BANCO
    , J.PYMNT_REF_ID
    , CASE WHEN ROW_NUMBER () OVER (PARTITION BY A.DRAWER_ID,J.PYMNT_REF_ID,A.BILL_TO_CUST_ID,A.RECEIPT_NBR
                ORDER BY TO_CHAR(CAST((A.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') DESC) = 1
        THEN (CASE WHEN J.TOTAL_TEND_AMT IS NULL THEN A.TOTAL_TEND_AMT ELSE J.TOTAL_TEND_AMT END) ELSE 0 END AS IMPORTE
FROM ((  PS_CDR_RECEIPT A
            LEFT JOIN PS_LI_GBL_ARPY_TBL J ON A.DEPOSIT_BU = J.DEPOSIT_BU AND A.RECEIPT_NBR = J.RECEIPT_NBR )
            LEFT JOIN PS_LI_GBL_ARPY_DTL U ON J.DEPOSIT_BU = U.DEPOSIT_BU AND J.PYMNT_REF_ID = U.PYMNT_REF_ID )
     , ( PS_CDR_RECEIPT_PMT G
            LEFT JOIN PS_PAYMENT V ON G.DEPOSIT_BU = V.DEPOSIT_BU AND V.DEPOSIT_ID = G.DEPOSIT_ID AND V.PAYMENT_SEQ_NUM = G.PAYMENT_SEQ_NUM )
WHERE A.DEPOSIT_BU = G.DEPOSIT_BU AND A.RECEIPT_NBR = G.RECEIPT_NBR
    AND A.DEPOSIT_BU = 'PER03'
    AND A.ADD_DTTM > TO_CHAR(CAST((TO_DATE(:3,'YYYY-MM-DD')) AS TIMESTAMP))
    AND A.ADD_DTTM < TO_CHAR(CAST((TO_DATE(:4,'YYYY-MM-DD')) AS TIMESTAMP) + 1)
    AND A.DRAWER_ID = :5
    AND CASE WHEN (G.PAYMENT_METHOD_CDR = 'CC' OR G.PAYMENT_METHOD_CDR = 'DD') AND G.CR_CARD_AUTH_STAT = 'U' THEN 0 ELSE 1 END = 1
    AND G.PAYMENT_METHOD_CDR <> 'CV'
    
UNION
--QUERY02
SELECT 
    K.DEPOSIT_BU, M.RECEIPT_NBR, L.DRAWER_ID, AG.RECON_ID, P.CREATEDTTM, K.CUSTOMER_ID
    , CASE WHEN P.PAYMENT_METHOD_CDR = 'CC' THEN P.PAYMENT_METHOD_CDR || ' - CREDIT CARD'            
            WHEN P.PAYMENT_METHOD_CDR = 'CSH' THEN P.PAYMENT_METHOD_CDR || ' - CASH'
            WHEN P.PAYMENT_METHOD_CDR = 'CV' THEN P.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
            WHEN P.PAYMENT_METHOD_CDR = 'DC' THEN P.PAYMENT_METHOD_CDR || ' - DEBIT CARD'
            WHEN P.PAYMENT_METHOD_CDR = 'PC' THEN P.PAYMENT_METHOD_CDR || ' - PROCURENMENT CARD'
        ELSE P.PAYMENT_METHOD_CDR END AS MEDIO_PAGO
    , CASE WHEN P.CR_CARD_TYPE = '01' OR P.CR_CARD_TYPE = 'V' THEN 'VISA'
            WHEN P.CR_CARD_TYPE = '02' OR P.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
            WHEN P.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
            WHEN P.CR_CARD_TYPE = '04' OR P.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
            WHEN P.CR_CARD_TYPE = ' ' AND P.PAYMENT_METHOD_CDR = 'CSH' THEN P.PAYMENT_METHOD_CDR || ' - CASH'
            WHEN P.CR_CARD_TYPE = ' ' AND P.PAYMENT_METHOD_CDR = 'CV' THEN P.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
        ELSE P.CR_CARD_TYPE END AS TIPO_TARJETA
    , CASE WHEN P.CR_CARD_TYPE = '01' OR P.CR_CARD_TYPE = 'V' THEN 'VISA'
            WHEN P.CR_CARD_TYPE = '02' OR P.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
            WHEN P.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
            WHEN P.CR_CARD_TYPE = '04' OR P.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
        ELSE P.CR_CARD_TYPE END AS NRO_TARJETA
    , P.PAYMENT_CURRENCY, CASE WHEN P.PAYMENT_METHOD_CDR = 'CV' THEN P.BNK_ID_NBR ELSE Q.BNK_ID_NBR END AS BANCO
    , K.PYMNT_REF_ID
    , CASE WHEN ROW_NUMBER () OVER (PARTITION BY L.DRAWER_ID,K.PYMNT_REF_ID,K.CUSTOMER_ID,M.RECEIPT_NBR
            ORDER BY TO_CHAR(CAST((P.CREATEDTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') DESC, K.INVOICE DESC) = 1
        THEN  L.PAYMENT_TOTAL ELSE 0 END AS IMPORTE
FROM PS_LI_GBL_ARPY_REF K, 
    (((PS_LI_GBL_ARPY_TBL L
            LEFT JOIN  PS_CDR_RECEIPT_PMT M ON  L.DEPOSIT_BU = M.DEPOSIT_BU AND M.RECEIPT_NBR = L.RECEIPT_NBR ) 
            LEFT JOIN  PS_PAYMENT Q ON  M.DEPOSIT_BU = Q.DEPOSIT_BU AND Q.DEPOSIT_ID = M.DEPOSIT_ID AND Q.PAYMENT_SEQ_NUM = M.PAYMENT_SEQ_NUM ) 
            LEFT JOIN  PS_CDR_RECEIPT AG ON L.DEPOSIT_BU = AG.DEPOSIT_BU AND AG.RECEIPT_NBR = L.RECEIPT_NBR )
    , PS_LI_GBL_ARPY_DTL P
WHERE K.DEPOSIT_BU = L.DEPOSIT_BU AND K.PYMNT_REF_ID = L.PYMNT_REF_ID
    AND L.DEPOSIT_BU = P.DEPOSIT_BU AND L.PYMNT_REF_ID = P.PYMNT_REF_ID
    AND K.DEPOSIT_BU = 'PER03'
    AND P.PAYMENT_DT BETWEEN TO_DATE(:3,'YYYY-MM-DD') AND TO_DATE(:4,'YYYY-MM-DD')
    AND L.DRAWER_ID = :5
    AND ( P.PAYMENT_METHOD_CDR = 'CV'
    OR L.RECEIPT_NBR NOT IN (SELECT H.RECEIPT_NBR
        FROM PS_CDR_RECEIPT H
        WHERE H.DEPOSIT_BU = 'PER03'
            AND H.DRAWER_ID = :5
            AND H.ADD_DTTM > TO_CHAR(CAST((TO_DATE(:3,'YYYY-MM-DD')) AS TIMESTAMP))
            AND H.ADD_DTTM < TO_CHAR(CAST((TO_DATE(:4,'YYYY-MM-DD')) AS TIMESTAMP) +1)) )
            
)
GROUP BY TO_CHAR(ADD_DTTM,'DD/MM/YYYY'), DRAWER_ID/*, MEDIO_PAGO, TIPO_TARJETA*/,CURRENCY_CD
ORDER BY 1,2,3;