
SELECT TO_CHAR(ADD_DTTM,'DD/MM/YYYY') AS FECHA, DRAWER_ID, RECON_ID, MEDIO_PAGO/*, TIPO_TARJETA*/, SUM(IMPORTE)
FROM (
SELECT 
    a.DEPOSIT_BU, a.RECEIPT_NBR, a.DRAWER_ID, a.BILL_TO_CUST_ID, a.TOTAL_TEND_AMT, a.RECON_ID, a.ADD_DTTM
    , CASE            
            WHEN c.PAYMENT_METHOD_CDR = 'CC' THEN 'CC - CREDIT CARD'
            WHEN c.PAYMENT_METHOD_CDR = 'CV' THEN 'CV - CORPORATE VOUCHER'
            WHEN c.PAYMENT_METHOD_CDR = 'CSH' THEN 'CSH - CASH'
            WHEN c.PAYMENT_METHOD_CDR = 'DC' THEN 'DC - DEBIT CARD'
            WHEN c.PAYMENT_METHOD_CDR = 'PC' THEN 'PC - PROCURENMENT CARD'
        ELSE c.PAYMENT_METHOD_CDR END AS MEDIO_PAGO
    , CASE WHEN c.CR_CARD_TYPE = '01' OR c.CR_CARD_TYPE = 'V' THEN 'VISA'
            WHEN c.CR_CARD_TYPE = '02' OR c.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
            WHEN c.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
            WHEN c.CR_CARD_TYPE = '04' OR c.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
            WHEN c.CR_CARD_TYPE = ' ' AND c.PAYMENT_METHOD_CDR = 'CSH' THEN 'CSH - CASH'
            WHEN c.CR_CARD_TYPE = ' ' AND c.PAYMENT_METHOD_CDR = 'CV' THEN 'CV - CORPORATE VOUCHER'
        ELSE c.CR_CARD_TYPE END AS TIPO_TARJETA
    , CASE WHEN ROW_NUMBER () OVER (PARTITION BY a.DRAWER_ID,b.PYMNT_REF_ID,a.BILL_TO_CUST_ID,a.RECEIPT_NBR
                ORDER BY TO_CHAR(CAST((A.ADD_DTTM) AS TIMESTAMP),'YYYY-MM-DD-HH24.MI.SS.FF') DESC) = 1
        THEN (CASE WHEN b.TOTAL_TEND_AMT IS NULL THEN a.TOTAL_TEND_AMT ELSE b.TOTAL_TEND_AMT END) ELSE 0 END AS IMPORTE    
FROM (  PS_CDR_RECEIPT a
            LEFT JOIN  PS_LI_GBL_ARPY_TBL b ON
                a.DEPOSIT_BU = b.DEPOSIT_BU
                AND a.RECEIPT_NBR = b.RECEIPT_NBR )
     , (PS_CDR_RECEIPT_PMT c
            LEFT JOIN  PS_PAYMENT d ON
                c.DEPOSIT_BU = d.DEPOSIT_BU
                AND c.DEPOSIT_ID = d.DEPOSIT_ID
                AND c.PAYMENT_SEQ_NUM = d.PAYMENT_SEQ_NUM )
WHERE a.DEPOSIT_BU = c.DEPOSIT_BU AND a.RECEIPT_NBR = c.RECEIPT_NBR
    AND a.ADD_DTTM > TO_CHAR(CAST((TO_DATE('2019-03-18','YYYY-MM-DD')) AS TIMESTAMP))
    AND a.ADD_DTTM < TO_CHAR(CAST((TO_DATE('2019-03-18','YYYY-MM-DD')) AS TIMESTAMP) + 1)
    AND a.DRAWER_ID = 'C13'
    )
GROUP BY TO_CHAR(ADD_DTTM,'DD/MM/YYYY'), DRAWER_ID, RECON_ID, MEDIO_PAGO/*, TIPO_TARJETA*/;

