
SELECT --LOCATION, CAJERO, RECON_ID, CREATEDTTM, TIPO_TARJETA, MEDIO_PAGO, NRO_TARJETA, MONEDA, BANCO, AUTORIZACION
    SUM(IMPORTE_PAGO)
FROM (
    SELECT B.DEPOSIT_BU, B.PYMNT_REF_ID, A.CREATEDTTM, B.DRAWER_ID || ' - ' || H.DESCR AS CAJERO, H.LOCATION, C.RECON_ID
        , CASE WHEN C.RECEIPT_NBR IS NULL THEN B.PAYMENT_TOTAL
                WHEN B.TOTAL_TEND_AMT IS NULL THEN C.TOTAL_TEND_AMT
            ELSE B.TOTAL_TEND_AMT END AS IMPORTE_PAGO
        , ROW_NUMBER () OVER (PARTITION BY B.DRAWER_ID,B.PYMNT_REF_ID,B.RECEIPT_NBR
            ORDER BY A.CREATEDTTM DESC) AS ORDEN
        , CASE WHEN G.PAYMENT_METHOD_CDR = 'CC' THEN G.PAYMENT_METHOD_CDR || ' - CREDIT CARD'            
                WHEN G.PAYMENT_METHOD_CDR = 'CSH' THEN G.PAYMENT_METHOD_CDR || ' - CASH'
                WHEN G.PAYMENT_METHOD_CDR = 'CV' THEN G.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
                WHEN G.PAYMENT_METHOD_CDR = 'DC' THEN G.PAYMENT_METHOD_CDR || ' - DEBIT CARD'
                WHEN G.PAYMENT_METHOD_CDR = 'PC' THEN G.PAYMENT_METHOD_CDR || ' - PROCURENMENT CARD'
            ELSE G.PAYMENT_METHOD_CDR END AS MEDIO_PAGO
        , CASE WHEN G.CR_CARD_TYPE = '01' OR G.CR_CARD_TYPE = 'V' THEN 'VISA'
                WHEN G.CR_CARD_TYPE = '02' OR G.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
                WHEN G.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
                WHEN G.CR_CARD_TYPE = '04' OR G.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
                WHEN G.CR_CARD_TYPE = ' ' AND G.PAYMENT_METHOD_CDR = 'CSH' THEN G.PAYMENT_METHOD_CDR || ' - CASH'
                WHEN G.CR_CARD_TYPE = ' ' AND G.PAYMENT_METHOD_CDR = 'CV' THEN G.PAYMENT_METHOD_CDR || ' - CORPORATE VOUCHER'
            ELSE G.CR_CARD_TYPE END AS TIPO_TARJETA
        , CASE WHEN G.CR_CARD_TYPE = '01' OR G.CR_CARD_TYPE = 'V' THEN 'VISA'
                WHEN G.CR_CARD_TYPE = '02' OR G.CR_CARD_TYPE = 'M' THEN 'MASTERCARD'
                WHEN G.CR_CARD_TYPE = '03' THEN 'DINERS CLUB'
                WHEN G.CR_CARD_TYPE = '04' OR G.CR_CARD_TYPE = 'A' THEN 'AMERICAN EXPRESS'
            ELSE G.CR_CARD_TYPE END AS NRO_TARJETA
        , B.PAYMENT_CURRENCY AS MONEDA, H.BANK_CD AS BANCO
        , CASE 
                WHEN G.PAYMENT_METHOD_CDR = 'CV' THEN G.TRANSACTION_REF
                WHEN G.PAYMENT_METHOD_CDR = 'CSH' THEN B.PYMNT_REF_ID
                WHEN G.CR_CARD_AUTH_CD IS NOT NULL THEN G.CR_CARD_AUTH_CD
            ELSE NULL END AS AUTORIZACION
    FROM PS_LI_GBL_ARPY_REF A, PS_LI_GBL_ARPY_TBL B, PS_CDR_RECEIPT C, PS_LI_GBL_ARPY_DTL G, PS_CASH_DRAWER_TBL H
    WHERE A.DEPOSIT_BU = B.DEPOSIT_BU AND A.PYMNT_REF_ID = B.PYMNT_REF_ID AND B.DRAWER_ID IS NOT NULL
        AND B.DEPOSIT_BU = C.DEPOSIT_BU(+) AND B.RECEIPT_NBR = C.RECEIPT_NBR(+)
        AND B.DEPOSIT_BU = G.DEPOSIT_BU AND B.PYMNT_REF_ID = G.PYMNT_REF_ID
        AND B.DEPOSIT_BU = H.BUSINESS_UNIT(+) AND B.DRAWER_ID = H.DRAWER_ID(+)
        AND A.DEPOSIT_BU = 'PER03'
        AND G.PAYMENT_DT BETWEEN TO_DATE(:1,'YYYY-MM-DD') AND TO_DATE(:2,'YYYY-MM-DD')
        AND B.DRAWER_ID = :3
)
WHERE ORDEN = 1;
