--Validar_SHRQPNM_DS_
SELECT A.DECODE_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME ||' '|| REPLACE(SPRIDEN_LAST_NAME,'/',' ') AS NOMBRE_ESTUDIANTE, A.DECODE_SEQ, B.QUALIFYING_PAPER_TYPE_CODE
	, B.ACCEPTANCE_DATE AS FECHA_CONVOCATORIA, B.FIRST_TITLE_LINE, B.SECOND_TITLE_LINE, A.GORSDAV_PK_PARENTTAB, A.GORSDAV_USER_ID
	, MAX(A.GORSDAV_ACTIVITY_DATE) AS FECHA_CARGA
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'TESIS' THEN A.DECODE_VALUE END) AS TESIS
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'URL_TESIS' THEN A.DECODE_VALUE END) AS URL_TESIS
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'ACTO_TIP' THEN A.DECODE_VALUE END) AS ACTO_TIP
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'MODALIDAD' THEN A.DECODE_VALUE END) AS MODALIDAD
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'RESO_NUM' THEN A.DECODE_VALUE END) AS RESO_NUM
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'RESO_FEC' THEN A.DECODE_VALUE END) AS RESO_FEC
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'DIPL_NUM' THEN A.DECODE_VALUE END) AS DIPL_NUM
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'DIPL_FEC' THEN A.DECODE_VALUE END) AS DIPL_FEC
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'DIPL_TIP_EMI' THEN A.DECODE_VALUE END) AS DIPL_TIP_EMI
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'REG_LIBRO' THEN A.DECODE_VALUE END) AS REG_LIBRO
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'REG_FOLIO' THEN A.DECODE_VALUE END) AS REG_FOLIO
	, MAX(CASE WHEN A.GORSDAV_ATTR_NAME = 'REG_REGISTRO' THEN A.DECODE_VALUE END) AS REG_REGISTRO
FROM ODSMGR.LOE_SUPPLEMENTAL_ATTRI_VALUES A
		LEFT JOIN ODSMGR.LOE_SPRIDEN ON A.DECODE_PIDM = SPRIDEN_PIDM||'' AND SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN ODSMGR.LOE_QUALIFYING_PAPER_TYPE_CODE B ON A.DECODE_PIDM || A.DECODE_SEQ = B.PERSON_UID ||''|| B.SEQUENCE_NUMBER
WHERE A.GORSDAV_ATTR_NAME IN ('TESIS','URL_TESIS','ACTO_TIP','MODALIDAD','RESO_NUM','RESO_FEC','DIPL_NUM','DIPL_FEC','DIPL_TIP_EMI','REG_LIBRO','REG_FOLIO','REG_REGISTRO')
	AND A.GORSDAV_TABLE_NAME = 'SHRQPNM' AND A.GORSDAV_USER_ID = 'S200014252' --USUARIO_CARGA
	AND A.GORSDAV_ACTIVITY_DATE BETWEEN TO_DATE('10/09/2020','DD/MM/YYYY') AND TO_DATE('10/09/2020','DD/MM/YYYY') --FECHA_CARGA
	--AND B.ACCEPTANCE_DATE BETWEEN TO_DATE('22/06/2020','DD/MM/YYYY') AND TO_DATE('10/07/2020','DD/MM/YYYY') --FECHA_CONVOCATORIA
	--AND A.DECODE_PIDM IN (31654)
GROUP BY A.DECODE_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME ||' '|| REPLACE(SPRIDEN_LAST_NAME,'/',' '), A.DECODE_SEQ, B.QUALIFYING_PAPER_TYPE_CODE, B.ACCEPTANCE_DATE, B.FIRST_TITLE_LINE
	, B.SECOND_TITLE_LINE, A.GORSDAV_PK_PARENTTAB, A.GORSDAV_USER_ID
;

SELECT * FROM ODSMGR.LOE_SUPPLEMENTAL_ATTRI_VALUES WHERE SUBSTR(DECODE_VALUE,1,1) LIKE '%'||CHR(10)||'%';
