SELECT DISTINCT CODE, PROGRAM
FROM (SELECT CODE, PROGRAM, COUNT(PROGRAM) OVER(PARTITION BY CODE) AS COUNT
        FROM (SELECT DISTINCT SUBSTR(DETAIL_CODE,3,2) AS CODE , PROGRAM FROM LOE_REGISTRATION_FEES))
WHERE COUNT > 1
ORDER BY 1;

SELECT DISTINCT REGISTRATION_TERM, SUBSTR(DETAIL_CODE,3,2), PROGRAM 
FROM LOE_REGISTRATION_FEES
WHERE SUBSTR(DETAIL_CODE,3,2) IN (SELECT DISTINCT CODE
                                  FROM (SELECT CODE, PROGRAM, COUNT(PROGRAM) OVER(PARTITION BY CODE) AS COUNT
                                          FROM (SELECT DISTINCT SUBSTR(DETAIL_CODE,3,2) AS CODE , PROGRAM FROM LOE_REGISTRATION_FEES))
                                  WHERE COUNT > 1)
ORDER BY 2,1;

SELECT * FROM LOE_REGISTRATION_FEES
WHERE SUBSTR(DETAIL_CODE,3,2) IN (SELECT DISTINCT CODE
                                  FROM (SELECT CODE, PROGRAM, COUNT(PROGRAM) OVER(PARTITION BY CODE) AS COUNT
                                          FROM (SELECT DISTINCT SUBSTR(DETAIL_CODE,3,2) AS CODE , PROGRAM FROM LOE_REGISTRATION_FEES))
                                  WHERE COUNT > 1);
